force-app/main/default/objects/clcommon__Address__c/clcommon__Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

elixir/force-app/main/default/objects/clcommon__Address__c/fields/clcommon__Contact__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

elixir/force-app/main/default/objects/clcommon__Address__c/fields/Mail_At__c.field-meta.xml
<CustomField>
    <fullName>Mail_At__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mail At</label>
    <type>Checkbox</type>
</CustomField>

elixir/force-app/main/default/objects/clcommon__Address__c/fields/Other_At__c.field-meta.xml
<CustomField>
    <fullName>Other_At__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Other At</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/clcommon__Address__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NSW</fullName>
            </value>
            <value>
                <fullName>NT</fullName>
            </value>
            <value>
                <fullName>QLD</fullName>
            </value>
            <value>
                <fullName>SA</fullName>
            </value>
            <value>
                <fullName>TAS</fullName>
            </value>
            <value>
                <fullName>VIC</fullName>
            </value>
            <value>
                <fullName>WA</fullName>
            </value>
            <value>
                <fullName>ACT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

elixir/force-app/main/default/objects/clcommon__Address__c/fields/Street_No__c.field-meta.xml
<CustomField>
    <fullName>Street_No__c</fullName>
    <label>Street No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

elixir/force-app/main/default/objects/clcommon__Address__c/fields/Street_Type__c.field-meta.xml
<CustomField>
    <fullName>Street_Type__c</fullName>
    <label>Street Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Access</fullName>
            </value>
            <value>
                <fullName>Alley</fullName>
            </value>
            <value>
                <fullName>Alleyway</fullName>
            </value>
            <value>
                <fullName>Amble</fullName>
            </value>
            <value>
                <fullName>Anchorage</fullName>
            </value>
            <value>
                <fullName>Approach</fullName>
            </value>
            <value>
                <fullName>Arcade</fullName>
            </value>
            <value>
                <fullName>Arterial</fullName>
            </value>
            <value>
                <fullName>Artery</fullName>
            </value>
            <value>
                <fullName>Avenue</fullName>
            </value>
            <value>
                <fullName>Banan</fullName>
            </value>
            <value>
                <fullName>Bank</fullName>
            </value>
            <value>
                <fullName>Basin</fullName>
            </value>
            <value>
                <fullName>Bay</fullName>
            </value>
            <value>
                <fullName>Beach</fullName>
            </value>
            <value>
                <fullName>Bend</fullName>
            </value>
            <value>
                <fullName>Block</fullName>
            </value>
            <value>
                <fullName>Boardwalk</fullName>
            </value>
            <value>
                <fullName>Boulevard</fullName>
            </value>
            <value>
                <fullName>Boulevarde</fullName>
            </value>
            <value>
                <fullName>Bowl</fullName>
            </value>
            <value>
                <fullName>Brace</fullName>
            </value>
            <value>
                <fullName>Brae</fullName>
            </value>
            <value>
                <fullName>Break</fullName>
            </value>
            <value>
                <fullName>Bridge</fullName>
            </value>
            <value>
                <fullName>Broadway</fullName>
            </value>
            <value>
                <fullName>Brow</fullName>
            </value>
            <value>
                <fullName>Bypass</fullName>
            </value>
            <value>
                <fullName>Byway</fullName>
            </value>
            <value>
                <fullName>Canal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/clcommon__Party__c.object-meta.xml
<CustomObject>
    <label>Party</label>
    <nameField>
        <displayFormat>PAR-{00000000}</displayFormat>
        <label>Party Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

elixir/force-app/main/default/objects/clcommon__Party__c/fields/Allow_Direct_Marketing__c.field-meta.xml
<CustomField>
    <fullName>Allow_Direct_Marketing__c</fullName>
    <label>Allow Direct Marketing</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>YesNo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/clcommon__Contact__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Parties</relationshipLabel>
    <relationshipName>Parties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/genesis__Application__c.field-meta.xml
<CustomField>
    <fullName>genesis__Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Parties</relationshipLabel>
    <relationshipName>Parties</relationshipName>
    <type>Lookup</type>
</CustomField>

elixir/force-app/main/default/objects/clcommon__Party__c/fields/Politically_Exposed_Person__c.field-meta.xml
<CustomField>
    <fullName>Politically_Exposed_Person__c</fullName>
    <label>Politically Exposed Person</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>YesNo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Is_this_the_Postal_Address__c.field-meta.xml
<CustomField>
    <fullName>Is_this_the_Postal_Address__c</fullName>
    <label>Is this the Postal Address</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>YesNo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/PEP__c.field-meta.xml
<CustomField>
    <fullName>PEP__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Politically Exposed Person</description>
    <inlineHelpText>Politically Exposed Person</inlineHelpText>
    <label>PEP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Applications__c/fields/Allow_Direct_Marketing__c.field-meta.xml
<CustomField>
    <fullName>Allow_Direct_Marketing__c</fullName>
    <label>Allow Direct Marketing</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Telephone_Contact_Number__c/Telephone_Contact_Number__c.object-meta.xml
<CustomObject>
    <label>Telephone Contact Number</label>
    <nameField>
        <label>Phone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Telephone Contact Number</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

elixir/force-app/main/default/objects/Telephone_Contact_Number__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Telephone Contact Number</relationshipLabel>
    <relationshipName>Telephone_Contact_Number</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

elixir/force-app/main/default/objects/Telephone_Contact_Number__c/fields/Phone_Type__c.field-meta.xml
<CustomField>
    <fullName>Phone_Type__c</fullName>
    <label>Phone Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home Phone</fullName>
            </value>
            <value>
                <fullName>Work Phone</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContactDetailUpdateBatch.cls
/****************************************************************************************************
Company: Cloudkaptan Consultancy Services Pvt. Ltd.
Author: Ariz Mazhary
Description : This class helps in updatting Contact detail on existing apps according to defined rules/scenarios
Development Date : 01/06/2021
Last Modified Date : 01/06/2021
****************************************************************************************************/
public class ContactDetailUpdateBatch implements DataBase.StateFul,DataBase.Batchable<sObject> {
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([SELECT id,
                                               MobilePhone,
                                               Phone,
                                               Is_this_the_Postal_Address__c,
                                               OtherStreet,
                                               OtherState,
                                               OtherCity,
                                               OtherPostalCode,
                                               OtherCountry,
                                               MailingStreet,
                                               MailingState,
                                               MailingCity,
                                               MailingPostalCode,
                                               MailingCountry,
                                               Opt_Out_of_Marketing__c,
                                               PEP__c
                                           FROM Contact]);
    }
    public void execute(Database.BatchableContext bc, List<Contact> objContactList) {
        try{
            List<Telephone_Contact_Number__c> objTelephoneList1=new List<Telephone_Contact_Number__c>();
            List<clcommon__Address__c> objAddressList1=new List<clcommon__Address__c>();
            List<Telephone_Contact_Number__c> objTelephoneList2=new List<Telephone_Contact_Number__c>();
            List<clcommon__Address__c> objAddressList2=new List<clcommon__Address__c>();
            List<clcommon__Party__c> objPartiesList=new List<clcommon__Party__c>();
            if(objContactList.size()>0){
                objTelephoneList1=[SELECT Id,
                                        Contact__c,
                                        Phone_Type__c,
                                        Phone_Number__c 
                                    FROM Telephone_Contact_Number__c 
                                    WHERE Contact__c IN: objContactList  
                                    AND Phone_Type__c =: ConstantValues.MOBILE_TAG
                                    AND Phone_Number__c != NULL
                                    ORDER BY CreatedDate];
                
                objTelephoneList2=[SELECT Id,
                                        Contact__c,
                                        Phone_Type__c,
                                        Phone_Number__c 
                                    FROM Telephone_Contact_Number__c 
                                    WHERE Contact__c IN: objContactList  
                                    AND Phone_Type__c =: ConstantValues.Home_Phone
                                    AND Phone_Number__c != NULL
                                    ORDER BY CreatedDate];

                objAddressList1=[SELECT Id,
                                      clcommon__County__c,
                                      Street_No__c,
                                      Street_Name__c,
                                      Street_Type__c,
                                      clcommon__City__c,
                                      State__c,
                                      clcommon__Zip_Code__c,
                                      clcommon__Contact__c,
                                      clcommon__Country__c
                                  FROM clcommon__Address__c 
                                  WHERE clcommon__Contact__c IN:objContactList  
                                  AND Mail_At__c = True];

                objAddressList2=[SELECT Id,
                                       clcommon__County__c,
                                       Street_No__c,
                                       Street_Name__c,
                                       Street_Type__c,
                                       clcommon__City__c,
                                       State__c,
                                       clcommon__Zip_Code__c,
                                       clcommon__Contact__c,
                                       clcommon__Country__c 
                                 FROM clcommon__Address__c 
                                 WHERE clcommon__Contact__c IN:objContactList  
                                 AND Other_At__c = True];

                objPartiesList=[SELECT id,
                                      Politically_Exposed_Person__c,
                                      genesis__Application__c,
                                      genesis__Application__r.Allow_Direct_Marketing__c,
                                      clcommon__Contact__c
                                  FROM clcommon__Party__c 
                                  WHERE clcommon__Contact__c IN: objContactList];
            }
            for(Contact objContact:objContactList){
                for(Telephone_Contact_Number__c objtelephone1:objTelephoneList1){
                    if(objtelephone1.Contact__c==objContact.Id){
                        objContact.MobilePhone=objtelephone1.Phone_Number__c;
                    }
                }
                for(Telephone_Contact_Number__c objtelephone2:objTelephoneList2){
                    if(objtelephone2.Contact__c==objContact.Id){
                        objContact.Phone=objtelephone2.Phone_Number__c;
                    }
                }
                objContact.OtherStreet = null;
                objContact.OtherState = null;
                objContact.OtherCity = null;
                objContact.OtherPostalCode = null;
                objContact.OtherCountry = null;
                for(clcommon__Address__c objAddress1:objAddressList1){
                    if(objAddress1.clcommon__Contact__c==objContact.Id){
                        if(objAddress1.clcommon__County__c!=null)
                            objContact.OtherStreet = ''+objAddress1.clcommon__County__c;
                        if(objAddress1.Street_No__c!=null){
                            if(objContact.OtherStreet!=null){
                                objContact.OtherStreet =objContact.OtherStreet+' '+objAddress1.Street_No__c;
                            }else{
                                objContact.OtherStreet =objAddress1.Street_No__c;
                            }
                        }
                        if(objAddress1.Street_Name__c!=null){
                            if(objContact.OtherStreet!=null){
                                objContact.OtherStreet =objContact.OtherStreet+' '+objAddress1.Street_Name__c;
                            }else{
                                objContact.OtherStreet =objAddress1.Street_Name__c;
                            }
                        }
                        if(objAddress1.Street_Type__c!=null){
                            if(objContact.OtherStreet!=null){
                                objContact.OtherStreet =objContact.OtherStreet+' '+objAddress1.Street_Type__c;
                            }else{
                                objContact.OtherStreet =objAddress1.Street_Type__c;
                            }
                        }
                        if(objAddress1.State__c != null && objAddress1.State__c != ''){
                            objContact.OtherState = objAddress1.State__c;
                        }
                        if(objAddress1.clcommon__City__c != null && objAddress1.clcommon__City__c != ''){
                            objContact.OtherCity = objAddress1.clcommon__City__c;
                        }
                        if(objAddress1.clcommon__Zip_Code__c != null && objAddress1.clcommon__Zip_Code__c != ''){
                            objContact.OtherPostalCode = objAddress1.clcommon__Zip_Code__c;
                        }
                        if( objAddress1.clcommon__Country__c != null && objAddress1.clcommon__Country__c != ''){
                            objContact.OtherCountry = objAddress1.clcommon__Country__c;
                        }
                    }
                }
                if(objContact.Is_this_the_Postal_Address__c== ConstantValues.YES_TAG || objContact.Is_this_the_Postal_Address__c ==ConstantValues.None_Tag){
                    objContact.MailingStreet = null;
                    objContact.MailingState = null;
                    objContact.MailingCity = null;
                    objContact.MailingPostalCode = null;
                    objContact.MailingCountry = null;
                }else{
                    for(clcommon__Address__c objAddress2:objAddressList2){
                        if(objAddress2.clcommon__Contact__c==objContact.Id){
                            objContact.MailingStreet = '';
                            objContact.MailingState = '';
                            objContact.MailingCity = '';
                            objContact.MailingPostalCode = '';
                            objContact.MailingCountry = '';
                            if(objAddress2.clcommon__County__c != null && objAddress2.clcommon__County__c != ''){
                                objContact.MailingStreet = objAddress2.clcommon__County__c;
                            }
                            if(objAddress2.Street_No__c != null && objAddress2.Street_No__c != ''){
                                if(objContact.MailingStreet != null && objContact.MailingStreet != ''){
                                    objContact.MailingStreet = objContact.MailingStreet+' '+objAddress2.Street_No__c;
                                }
                                else{
                                    objContact.MailingStreet = objAddress2.Street_No__c;
                                }
                            }
                            if(objAddress2.Street_Name__c != null && objAddress2.Street_Name__c != ''){
                                if(objContact.MailingStreet != null && objContact.MailingStreet != ''){
                                    objContact.MailingStreet = objContact.MailingStreet+' '+objAddress2.Street_Name__c;
                                }
                                else{
                                    objContact.MailingStreet = objAddress2.Street_Name__c;
                                }
                            }
                            if(objAddress2.Street_Type__c != null && objAddress2.Street_Type__c != ''){
                                if(objContact.MailingStreet != null && objContact.MailingStreet != ''){
                                    objContact.MailingStreet = objContact.MailingStreet+' '+objAddress2.Street_Type__c;
                                }
                                else{
                                    objContact.MailingStreet = objAddress2.Street_Type__c;
                                }
                            }
                            if(objAddress2.State__c != null && objAddress2.State__c != ''){
                                objContact.MailingState = objAddress2.State__c;
                            }
                            if(objAddress2.clcommon__City__c != null && objAddress2.clcommon__City__c != ''){
                                objContact.MailingCity = objAddress2.clcommon__City__c;
                            }
                            if(objAddress2.clcommon__Zip_Code__c != null && objAddress2.clcommon__Zip_Code__c != ''){
                                objContact.MailingPostalCode = objAddress2.clcommon__Zip_Code__c;
                            }
                            if(objAddress2.clcommon__Country__c != null && objAddress2.clcommon__Country__c != ''){
                                objContact.MailingCountry = objAddress2.clcommon__Country__c;
                            }
                        }
                    }
                }
                for(clcommon__Party__c party:objPartiesList){
                    if(party.clcommon__Contact__c==objContact.Id){
                        if(party.Politically_Exposed_Person__c == ConstantValues.YES_TAG){
                            objContact.PEP__c = true;
                        }else{
                            objContact.PEP__c = false;
                        }
                        if(party.genesis__Application__r.Allow_Direct_Marketing__c== ConstantValues.NO_TAG){
                            objContact.Opt_Out_of_Marketing__c = true;
                        }else{
                            objContact.Opt_Out_of_Marketing__c = false;
                        }
                    }
                }
            }
            if(objContactList.size()>0){
                Database.update(objContactList,false);
            }

        }catch(Exception exe){
            insert new clcommon__Batch_Process_Log__c(
                clcommon__Message__c = 'ContactDetailUpdateBatch :Exception: '+exe.getStackTraceString()
                                        +'error='+exe.getMessage()+' at Line Number '+exe.getLineNumber(),
                clcommon__Timestamp__c = System.Now());
        }
    }
    public void finish(Database.BatchableContext bc){
    }
}