force-app/main/default/objects/clcommon__Party__c/clcommon__Party__c.object-meta.xml
<CustomObject>
    <label>Party</label>
    <nameField>
        <displayFormat>PAR-{00000000}</displayFormat>
        <label>Party Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/clcommon__Party__c/fields/Date_of_Most_Recent_Credit_Event__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Most_Recent_Credit_Event__c</fullName>
    <label>Date of Most Recent Credit Event</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/genesis__Application__c.field-meta.xml
<CustomField>
    <fullName>genesis__Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Parties</relationshipLabel>
    <relationshipName>Parties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Applications__c/fields/Date_Of_Most_Recent_Credit_Event__c.field-meta.xml
<CustomField>
    <fullName>Date_Of_Most_Recent_Credit_Event__c</fullName>
    <label>Date Of Most Recent Credit Event</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/UpdateMostRecentCreditEventInApplication.cls
/****************************************************************************************************
Company: Cloudkaptan Consultancy Services Pvt. Ltd.
Author: Ariz Mazhary
Description : This class checks across all parties' Most Recent Credit Event Date 
                and updates the Most Recent Credit Event date in application
Development Date : 13/05/2021
Last Modified Date : 13/05/2021
****************************************************************************************************/
global with sharing  class UpdateMostRecentCreditEventInApplication {
    //Method used for updating the most recent conduct issue date in applications
    Webservice static String updateMostRecentCreditEvent(Id appId){
        try{
            List <genesis__Applications__c> appList = [SELECT Id,
                                                            Date_Of_Most_Recent_Credit_Event__c
                                                        FROM genesis__Applications__c
                                                        WHERE Id = : appId];
            
            List <clcommon__Party__c> partyList = [SELECT Id,
                                                        Date_of_Most_Recent_Credit_Event__c,
                                                        genesis__Application__c
                                                    FROM clcommon__Party__c
                                                    WHERE genesis__Application__c = : appId
                                                    ORDER BY Date_of_Most_Recent_Credit_Event__c ASC NULLS FIRST];
            if(appList.size() > 0){
                for(genesis__Applications__c eachApp : appList){
                    eachApp.Date_Of_Most_Recent_Credit_Event__c = NULL;
                    for(clcommon__Party__c eachParty : partyList){
                        if(eachParty.genesis__Application__c == eachApp.id){
                            if(eachParty.Date_of_Most_Recent_Credit_Event__c != NULL){
                                eachApp.Date_Of_Most_Recent_Credit_Event__c = eachParty.Date_of_Most_Recent_Credit_Event__c;
                            }
                        }
                    }
                }
                Database.update(appList,false);
            }
            
        }catch(Exception exe){
            GenericUtility.insertLog('UpdateApplicationCreditValues.updateApplicationCreditEvent', exe);
            return ConstantValues.GENERAL_ERROR;

        }
        return ConstantValues.SUCCESS;
    }
}