force-app/main/default/objects/clcommon__Party__c/clcommon__Party__c.object-meta.xml
<CustomObject>
    <label>Party</label>
    <nameField>
        <displayFormat>PAR-{00000000}</displayFormat>
        <label>Party Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/clcommon__Party__c/fields/genesis__Application__c.field-meta.xml
<CustomField>
    <fullName>genesis__Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Parties</relationshipLabel>
    <relationshipName>Parties</relationshipName>
    <type>Lookup</type>
</CustomField>

elixir/force-app/main/default/objects/clcommon__Party__c/fields/Total_HEM_Monthly_Living_Expenses__c.field-meta.xml
<CustomField>
    <fullName>Total_HEM_Monthly_Living_Expenses__c</fullName>
    <formula>Primary_Residence_Property_Costs__c+Groceries__c+Clothing_Personal_Care__c+Transport_Monthly_Amount__c+Medical_Health__c+Education_excluding_Private_School_Fees__c+Childcare_Monthly_Income__c+Insurance__c+Telephone_Media_Streaming_Amount__c+Recreation_Entertainment__c+Memberships_gym_sporting_clubs_etc__c+Description_for_Other_Discretionary_exp__c+Other_Expenses__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total HEM Monthly Living Expenses</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Elixir_Prod/force-app/main/default/objects/clcommon__Party__c/fields/Total_Non_HEM_Living_Expenses__c.field-meta.xml
<CustomField>
    <fullName>Total_Non_HEM_Living_Expenses__c</fullName>
    <formula>Investment_Property_Costs__c+Education_Private_School_Fees__c+Private_Health_Life_and_IP_Insurance__c+Non_Compulsory_Superannuation__c+Maintenance_Alimony__c+Rent_Board_Monthly_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Non-HEM Living Expenses</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Applications__c/fields/Total_Monthly_Living_Expenses_Declared__c.field-meta.xml
<CustomField>
    <fullName>Total_Monthly_Living_Expenses_Declared__c</fullName>
    <label>Total Monthly Living Expenses Declared</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/InvokeOnPartyUpdate.cls
/****************************************************************************************************/
/* Company              : Cloudkaptan Consultancy Services Pvt. Ltd. */
/* Class Name           : InvokeOnPartyUpdate */
/* Created Date         : 15/10/2020 */
/* Developed By         : Souvik */
/* Description          : This class is used to update total monthly expenses declared value on
application. */
/* Last Modified Date   : 15/10/2020 */
/* Last Modified By     : Souvik */
/****************************************************************************************************/

public with sharing class InvokeOnPartyUpdate {
    @InvocableMethod(
        label='Update Living Expense'
        description='Updates Total Monthly Living Expenses Declared value on Application'
    )
    public static void updateLivingExpense(List<Id> appIdList){
        Decimal sumOfAllLivingExpenses = 0;
        Id appId;
        List<clcommon__Party__c> parties;
        genesis__Applications__c appObj;
        try{
            if(appIdList.isEmpty()){
                GenericUtility.insertLog('InvokeOnPartyUpdate.updateLivingExpense', new CustomException(ConstantValues.NO_PARTY));
                return;
            }
            appId = appIdList[0];
            parties = [SELECT Id,
                        Total_HEM_Monthly_Living_Expenses__c,
                        Total_Non_HEM_Living_Expenses__c
                        FROM clcommon__Party__c
                        WHERE genesis__Application__c =:appId];
            for(clcommon__Party__c eachParty : parties) {
                sumOfAllLivingExpenses += eachParty.Total_HEM_Monthly_Living_Expenses__c;
                sumOfAllLivingExpenses += eachParty.Total_Non_HEM_Living_Expenses__c;
            }
            appObj = new genesis__Applications__c(Id = appId);
            appObj.Total_Monthly_Living_Expenses_Declared__c = sumOfAllLivingExpenses;
            Database.update(appObj);
        }
        catch(Exception ex){
            GenericUtility.insertLog('InvokeOnPartyUpdate.updateLivingExpense', ex);
        }
    }
}