force-app/main/default/objects/clcommon__Party__c/clcommon__Party__c.object-meta.xml
<CustomObject>
    <label>Party</label>
    <nameField>
        <displayFormat>PAR-{00000000}</displayFormat>
        <label>Party Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

elixir/force-app/main/default/objects/clcommon__Party__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full</fullName>
            </value>
            <value>
                <fullName>Alt</fullName>
            </value>
            <value>
                <fullName>Lease</fullName>
                <isActive>false</isActive>
                <label>Lease</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/Employment_Type__c.field-meta.xml
<CustomField>
    <fullName>Employment_Type__c</fullName>
    <label>Employment Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PAYG</fullName>
            </value>
            <value>
                <fullName>Self Employed</fullName>
            </value>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Home Duties</fullName>
            </value>
            <value>
                <fullName>Retired</fullName>
            </value>
            <value>
                <fullName>Unemployed</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
                <isActive>false</isActive>
                <label>Contractor</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/genesis__Application__c.field-meta.xml
<CustomField>
    <fullName>genesis__Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Parties</relationshipLabel>
    <relationshipName>Parties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/Income_for_servicing_purposes__c.field-meta.xml
<CustomField>
    <fullName>Income_for_servicing_purposes__c</fullName>
    <formula>IF(OR(AND( Total_Current_Income_Period__c &gt; Total_Previous_Income_Period__c ,Total_Current_Income_Period__c &lt;(Total_Previous_Income_Period__c*1.2)),Total_Current_Income_Period__c&lt;Total_Previous_Income_Period__c), Total_Current_Income_Period__c, if(Total_Current_Income_Period__c &gt; (1.2*Total_Previous_Income_Period__c),Total_Previous_Income_Period__c*1.2, null))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Income for servicing purposes</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/Legal_Entity_Type__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Type__c</fullName>
    <formula>clcommon__Account__r.clcommon__Legal_Entity_Type__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Legal Entity Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/Override_Amount__c.field-meta.xml
<CustomField>
    <fullName>Override_Amount__c</fullName>
    <label>Override Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/Total_Other_Income__c.field-meta.xml
<CustomField>
    <fullName>Total_Other_Income__c</fullName>
    <label>Total Other Income</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/Total_PAYG_Income__c.field-meta.xml
<CustomField>
    <fullName>Total_PAYG_Income__c</fullName>
    <label>Total PAYG Income</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/Total_Self_Employed_Income__c.field-meta.xml
<CustomField>
    <fullName>Total_Self_Employed_Income__c</fullName>
    <label>Total Self Employed Income</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/Total_Unemployment_Income__c.field-meta.xml
<CustomField>
    <fullName>Total_Unemployment_Income__c</fullName>
    <label>Total Unemployment Income</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Applications__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full Doc</fullName>
            </value>
            <value>
                <fullName>Alt Doc</fullName>
            </value>
            <value>
                <fullName>Lease Doc</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/Employment_Type__c.field-meta.xml
<CustomField>
    <fullName>Employment_Type__c</fullName>
    <label>Employment Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

elixir/force-app/main/default/objects/genesis__Applications__c/fields/Income_for_servicing_purposes__c.field-meta.xml
<CustomField>
    <fullName>Income_for_servicing_purposes__c</fullName>
    <formula>if(OR(AND( Total_Current_Income_Period__c  &gt; Total_Previous_Income_Period__c ,Total_Current_Income_Period__c  &lt;(Total_Previous_Income_Period__c*1.2)),Total_Current_Income_Period__c&lt;Total_Previous_Income_Period__c), Total_Current_Income_Period__c, if(Total_Current_Income_Period__c &gt; (1.2*Total_Previous_Income_Period__c),Total_Previous_Income_Period__c*1.2, null))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Income for servicing purposes</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/Months_Self_Employed__c.field-meta.xml
<CustomField>
    <fullName>Months_Self_Employed__c</fullName>
    <label>Months Self Employed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

elixir/force-app/main/default/objects/genesis__Applications__c/fields/Override_Amount__c.field-meta.xml
<CustomField>
    <fullName>Override_Amount__c</fullName>
    <label>Override Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/Total_Other_Income__c.field-meta.xml
<CustomField>
    <fullName>Total_Other_Income__c</fullName>
    <label>Total Other Income</label>
    <summarizedField>genesis__Income__c.genesis__Amount__c</summarizedField>
    <summaryFilterItems>
        <field>genesis__Income__c.Other_Income__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>genesis__Income__c.genesis__Application__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/Total_PAYG_Income__c.field-meta.xml
<CustomField>
    <fullName>Total_PAYG_Income__c</fullName>
    <label>Total PAYG Income</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/Total_Self_Employed_Alt_Doc_Income__c.field-meta.xml
<CustomField>
    <fullName>Total_Self_Employed_Alt_Doc_Income__c</fullName>
    <label>Total Self Employed Alt Doc Income</label>
    <summarizedField>genesis__Income__c.genesis__Amount__c</summarizedField>
    <summaryFilterItems>
        <field>genesis__Income__c.Document_Type__c</field>
        <operation>equals</operation>
        <value>Alt</value>
    </summaryFilterItems>
    <summaryForeignKey>genesis__Income__c.genesis__Application__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/Total_Self_Employed_Full_Doc_Income__c.field-meta.xml
<CustomField>
    <fullName>Total_Self_Employed_Full_Doc_Income__c</fullName>
    <label>Total Self Employed Full Doc Income</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/Total_Self_Employed_Income__c.field-meta.xml
<CustomField>
    <fullName>Total_Self_Employed_Income__c</fullName>
    <label>Total Self Employed Income</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/Total_Unemployment_Income__c.field-meta.xml
<CustomField>
    <fullName>Total_Unemployment_Income__c</fullName>
    <label>Total Unemployment Income</label>
    <summarizedField>genesis__Income__c.genesis__Amount__c</summarizedField>
    <summaryFilterItems>
        <field>genesis__Income__c.Unemployed_Income__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>genesis__Income__c.genesis__Application__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/genesis__Employment_Information__c/genesis__Employment_Information__c.object-meta.xml
<CustomObject>
    <label>Employment Information</label>
    <nameField>
        <label>Employment Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employment Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

elixir/force-app/main/default/objects/genesis__Employment_Information__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Document_Type_Set</valueSetName>
    </valueSet>
</CustomField>

elixir/force-app/main/default/objects/genesis__Employment_Information__c/fields/genesis__Application__c.field-meta.xml
<CustomField>
    <fullName>genesis__Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Employment Information</relationshipLabel>
    <relationshipName>Employment_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

Elixir_Prod/force-app/main/default/objects/genesis__Employment_Information__c/fields/Income_for_servicing_purposes__c.field-meta.xml
<CustomField>
    <fullName>Income_for_servicing_purposes__c</fullName>
    <formula>if(OR(AND( Total_Current_Income_Period__c  &gt; Total_Previous_Income_Period__c ,Total_Current_Income_Period__c  &lt;(Total_Previous_Income_Period__c*1.2)),Total_Current_Income_Period__c&lt;Total_Previous_Income_Period__c), Total_Current_Income_Period__c, if(Total_Current_Income_Period__c &gt; (1.2*Total_Previous_Income_Period__c),Total_Previous_Income_Period__c*1.2, null))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Income for servicing purposes</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

elixir/force-app/main/default/objects/genesis__Employment_Information__c/fields/Months_Self_Employed__c.field-meta.xml
<CustomField>
    <fullName>Months_Self_Employed__c</fullName>
    <label>Months Self Employed</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/genesis__Employment_Information__c/fields/Override_Amount__c.field-meta.xml
<CustomField>
    <fullName>Override_Amount__c</fullName>
    <label>Override Amount</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

elixir/force-app/main/default/objects/genesis__Employment_Information__c/fields/PAYG_Income__c.field-meta.xml
<CustomField>
    <fullName>PAYG_Income__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PAYG Income</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/genesis__Employment_Information__c/recordTypes/PAYG.recordType-meta.xml
<RecordType>
    <fullName>PAYG</fullName>
    <active>true</active>
    <label>PAYG</label>
</RecordType>

force-app/main/default/objects/genesis__Employment_Information__c/recordTypes/Self_Employed.recordType-meta.xml
<RecordType>
    <fullName>Self_Employed</fullName>
    <active>true</active>
    <label>Self Employed</label>
</RecordType>

force-app/main/default/objects/genesis__Income__c/genesis__Income__c.object-meta.xml
<CustomObject>
    <description>This object will track the other income</description>
    <label>Income</label>
    <nameField>
        <label>Income Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incomes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Income__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full</fullName>
            </value>
            <value>
                <fullName>Alt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

elixir/force-app/main/default/objects/genesis__Income__c/fields/Employment_Information__c.field-meta.xml
<CustomField>
    <fullName>Employment_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employment Information</label>
    <referenceTo>genesis__Employment_Information__c</referenceTo>
    <relationshipLabel>Incomes</relationshipLabel>
    <relationshipName>Incomes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Income__c/fields/genesis__Application__c.field-meta.xml
<CustomField>
    <fullName>genesis__Application__c</fullName>
    <description>Master-Detail relationship for income</description>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Incomes</relationshipLabel>
    <relationshipName>Incomes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

elixir/force-app/main/default/globalValueSets/Document_Type_Set.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Full</fullName>
    </customValue>
    <customValue>
        <fullName>Alt</fullName>
    </customValue>
    <masterLabel>Document Type Set</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/UpdateEmpTypeBatch.cls
/****************************************************************************************************
Company              : Cloudkaptan Consultancy Services Pvt. Ltd. 
Class Name           : UpdateEmploymentTypeOnApplication 
Created Date         : 04/07/2022 
Developed By         : Sayak Mukhopadhyay 
Description          : This is used to Migrate all existing data(regarding the development of 
                       UpdateEmploymentTypeOnApplication Class)
****************************************************************************************************/

public class UpdateEmpTypeBatch implements DataBase.StateFul,DataBase.Batchable<sObject> {
    public Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator([SELECT id,
                                            Total_Self_Employed_Full_Doc_Income__c,
                                            Total_Self_Employed_Income__c,
                                            Total_Self_Employed_Alt_Doc_Income__c,
                                            Total_PAYG_Income__c,
                                            Total_Other_Income__c,
                                            Total_Unemployment_Income__c,
                                            Employment_Type__c,
                                            Months_Self_Employed__c,
                                            Document_Type__c,
                                            (
                                                SELECT id,
                                                Employment_Type__c
                                                FROM genesis__Parties__r
                                                WHERE Legal_Entity_Type__c =: ConstantValues.indType
                                            )
                                            FROM genesis__Applications__c]);
                                            // FROM genesis__Applications__c
                                            // WHERE id = 'a5m9p000000202L']);
    }
    public void execute(Database.BatchableContext bc, List<genesis__Applications__c>objAppList){
        try{
            Double totalAmount,maxOne,maxTwo,maxIncome,totalPaygIncome,ammount;
            String empType,frequency;
            List<String> docTypeList = new String[]{ConstantValues.FullDocType,ConstantValues.ALT};
            List<String> legalEntityList = new String[]{ConstantValues.indType,ConstantValues.JOINT};
            List<String> partyTypeList = new String[]{ConstantValues.HOUSEHOLD_PARTY_TYPE,ConstantValues.SOLICITOR_PARTY_TYPE};
            List<genesis__Employment_Information__c> objEmpInfoList = [SELECT id,
                                                                            Override_Amount__c,
                                                                            Income_for_servicing_purposes__c,
                                                                            genesis__Application__c,
                                                                            Party__c,
                                                                            Months_Self_Employed__c,
                                                                            Document_Type__c,
                                                                            ( SELECT id,
                                                                                genesis__Amount__c,
                                                                                Document_Type__c
                                                                                FROM Incomes__r
                                                                                WHERE Document_Type__c in: docTypeList
                                                                            )
                                                                            FROM genesis__Employment_Information__c
                                                                            WHERE Document_Type__c in: docTypeList
                                                                            AND genesis__Application__c in: objAppList
                                                                            AND Party__r.Party_Type_Name__c NOT IN: partyTypeList
                                                                            AND Party__r.Legal_Entity_Type__c IN: legalEntityList];
            List<genesis__Income__c> objIncomeList = [SELECT id,
                                                        genesis__Amount__c,
                                                        genesis__Application__r.id,
                                                        genesis__Frequency__c
                                                        FROM genesis__Income__c
                                                        WHERE genesis__Application__c in: objAppList
                                                        AND PAYG_Income__c = true];                                                                
            for(genesis__Applications__c objApp : objAppList){
                Integer count = 0;
                Integer flag = 1;
                for(clcommon__Party__c objParty : objApp.genesis__Parties__r){
                    if(objParty.Employment_Type__c == null){
                        count += 1;
                    }
                }
                if(objApp.genesis__Parties__r.size() > 0 && count == objApp.genesis__Parties__r.size()){
                    objApp.Employment_Type__c = ConstantValues.SELF_EMPLOYED;
                    flag = 0;
                }
                totalAmount = 0;
                totalPaygIncome = 0;
                for(genesis__Income__c objIncome : objIncomeList){
                    ammount = 0;
                    if(objIncome.genesis__Application__r.id == objApp.id){
                        if(objIncome.genesis__Amount__c != null){
                            ammount = objIncome.genesis__Amount__c;
                        }
                        if(objIncome.genesis__Frequency__c != null){
                            frequency = objIncome.genesis__Frequency__c;
                            if(frequency == ConstantValues.weekly){
                                ammount *= 52;
                            }else if(frequency == ConstantValues.FORTNIGHTLY){
                                ammount *= 26;
                            }else if(frequency == ConstantValues.monthly){
                                ammount *= 12;
                            }else if(frequency == ConstantValues.YEARLY){
                                ammount *= 1;
                            }
                        }
                    }
                    totalPaygIncome += ammount;
                }
                objApp.Total_PAYG_Income__c = totalPaygIncome;
                for(genesis__Employment_Information__c objEmpInfo : objEmpInfoList){
                    if(objEmpInfo.Document_Type__c == ConstantValues.FullDocType && objEmpInfo.Incomes__r.size()>0 && objEmpInfo.genesis__Application__c == objApp.id){
                        if(objEmpInfo.Override_Amount__c != null){
                            totalAmount += decimal.valueOf(objEmpInfo.Override_Amount__c);
                        }else if(objEmpInfo.Income_for_servicing_purposes__c != null){
                            totalAmount += objEmpInfo.Income_for_servicing_purposes__c;
                        }
                    }
                }
                    // System.debug('totalAmount(Full) ' + totalAmount);
                if(!String.isBlank(objApp.Document_Type__c) && objApp.Document_Type__c == ConstantValues.LEASE_DOC && flag == 1){
                    objApp.Employment_Type__c = ConstantValues.LEASE_DOC;
                }
                else{
                    maxOne = Math.max(objApp.Total_PAYG_Income__c,objApp.Total_Self_Employed_Alt_Doc_Income__c + totalAmount);
                    maxTwo = Math.max(objApp.Total_Unemployment_Income__c,objApp.Total_Other_Income__c);
                    maxIncome = Math.max(maxOne,maxTwo);
                    empType = (maxIncome == objApp.Total_PAYG_Income__c ? ConstantValues.PAYG
                            : maxIncome == objApp.Total_Self_Employed_Alt_Doc_Income__c + totalAmount ? ConstantValues.SELF_EMPLOYED
                            : maxIncome == objApp.Total_Unemployment_Income__c ? ConstantValues.UNEMPLOYMENT_STUDENT_HOME_DUTIES_RETIREMENT
                            : ConstantValues.OTHER);
                    if(flag == 1){
                        objApp.Employment_Type__c = empType;
                    }
                    System.debug(empType);
                    if(empType == ConstantValues.SELF_EMPLOYED){
                        objApp.Months_Self_Employed__c = UpdateEmploymentTypeOnApplication.getMonthsSelfEmpIncome(objApp.id,objEmpInfoList);
                    }
                }
                objApp.Total_Self_Employed_Full_Doc_Income__c = totalAmount;
                objApp.Total_Self_Employed_Income__c = objApp.Total_Self_Employed_Alt_Doc_Income__c + totalAmount;
            }
            if(objAppList.size() > 0){
                Database.update(objAppList,false);
            }
        }catch(Exception exe){
            insert new clcommon__Batch_Process_Log__c(
                clcommon__Message__c = 'UpdateEmpTypeBatch :Exception: '+exe.getStackTraceString()
                                        +'error='+exe.getMessage()+' at Line Number '+exe.getLineNumber(),
                clcommon__Timestamp__c = System.Now());
        }
    }
    public void finish(Database.BatchableContext bc){
    }
}



// UpdateEmpTypeBatch obj = new UpdateEmpTypeBatch();
// database.executebatch(obj,100);