force-app/main/default/objects/clcommon__Party__c/clcommon__Party__c.object-meta.xml
<CustomObject>
    <label>Party</label>
    <nameField>
        <displayFormat>PAR-{00000000}</displayFormat>
        <label>Party Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/clcommon__Party__c/fields/Date_of_most_recent_conduct_issue__c.field-meta.xml
<CustomField>
    <fullName>Date_of_most_recent_conduct_issue__c</fullName>
    <label>Date of most recent conduct issue</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/genesis__Application__c.field-meta.xml
<CustomField>
    <fullName>genesis__Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Parties</relationshipLabel>
    <relationshipName>Parties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Applications__c/fields/Date_Of_Most_Recent_Conduct_Issue__c.field-meta.xml
<CustomField>
    <fullName>Date_Of_Most_Recent_Conduct_Issue__c</fullName>
    <description>RJohnston 17/5/21 - for reporting purposes on the latest conduct issue
 https://wingategroup.atlassian.net/secure/RapidBoard.jspa?rapidView=8&amp;projectKey=AMS&amp;modal=detail&amp;selectedIssue=AMS-826</description>
    <label>Date Of Most Recent Conduct Issue</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/UpdateMostRecentConductInApplication.cls
/****************************************************************************************************
Company: Cloudkaptan Consultancy Services Pvt. Ltd.
Author: Ariz Mazhary
Description : This class checks across party's Most Recent Coduct Date 
                and updates the most recent conduct issue date in application
Development Date : 13/05/2021
Last Modified Date : 13/05/2021
****************************************************************************************************/
global with sharing class UpdateMostRecentConductInApplication {
    //Method used for updating the most recent conduct issue date in applications
    Webservice static String updateMostRecentConductIssueDate(Id appId){
        try{
            List <genesis__Applications__c> appList = [SELECT Id,
                                                            Date_Of_Most_Recent_Conduct_Issue__c
                                                        FROM genesis__Applications__c
                                                        WHERE Id  =: appId];
            
            List <clcommon__Party__c> partyList = [SELECT Id,
                                                        Date_of_most_recent_conduct_issue__c,
                                                        genesis__Application__c
                                                    FROM clcommon__Party__c
                                                    WHERE genesis__Application__c = : appId
                                                    ORDER BY Date_of_most_recent_conduct_issue__c ASC NULLS FIRST];
            if(appList.size() > 0){
                for(genesis__Applications__c eachApp : appList){
                    eachApp.Date_Of_Most_Recent_Conduct_Issue__c = NULL;
                    for(clcommon__Party__c eachParty : partyList){
                        if(eachParty.genesis__Application__c == eachApp.id){
                            if(eachParty.Date_of_most_recent_conduct_issue__c != NULL){
                                eachApp.Date_Of_Most_Recent_Conduct_Issue__c = eachParty.Date_of_most_recent_conduct_issue__c;
                            }
                        }
                    }
                }
                Database.update(appList,false);
            }
            
        }catch(Exception exe){
            GenericUtility.insertLog('UpdateApplicationDateValue.updateApplication', exe);
             return ConstantValues.GENERAL_ERROR;

        }
        return ConstantValues.SUCCESS;
    }
}