force-app/main/default/objects/clcommon__Party__c/clcommon__Party__c.object-meta.xml
<CustomObject>
    <label>Party</label>
    <nameField>
        <displayFormat>PAR-{00000000}</displayFormat>
        <label>Party Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/clcommon__Party__c/fields/Date_of_Most_Recent_Credit_Event__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Most_Recent_Credit_Event__c</fullName>
    <label>Date of Most Recent Credit Event</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/Legal_Entity_Type__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Type__c</fullName>
    <formula>clcommon__Account__r.clcommon__Legal_Entity_Type__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Legal Entity Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CalculateCreditHistoryBatch.cls
/**************************************************************************
Company : CloudKaptan Consultancy Services Pvt. Ltd.
Developer : Rameswari Barman
Development Date : 13/05/2021
Last Modified By : Rameswari Barman
Last Modified Date : 13/05/2021
Description : This class is used to update existing parties' Date of most credit event value in prod
***************************************************************************/
global class CalculateCreditHistoryBatch implements Database.Batchable<sObject> {
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
          [
            SELECT Id,
            Legal_Entity_Type__c,
            Date_of_Most_Recent_Credit_Event__c 
            FROM clcommon__Party__c 
          ]
        );
    }
    global void execute(Database.BatchableContext bc, List<clcommon__Party__c> scope) {
      try{
            if (scope != null && !scope.isEmpty()) {
                for(clcommon__Party__c eachParty : scope){
                    CalculateCreditHistoryValues.calculateValues(eachParty.Id);
                }
            }
      }
      catch(Exception ex){
        GenericUtility.insertLog('CreditHistoryUpdateBatch', ex);
      }
    }
    global void finish(Database.BatchableContext bc) {
    }
}