force-app/main/default/objects/clcommon__Party__c/clcommon__Party__c.object-meta.xml
<CustomObject>
    <label>Party</label>
    <nameField>
        <displayFormat>PAR-{00000000}</displayFormat>
        <label>Party Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/clcommon__Party__c/fields/Applicant_ever_declared_banckrupt__c.field-meta.xml
<CustomField>
    <fullName>Applicant_ever_declared_banckrupt__c</fullName>
    <label>Applicant ever declared banckrupt</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

elixir/force-app/main/default/objects/clcommon__Party__c/fields/Bankrupt_Date__c.field-meta.xml
<CustomField>
    <fullName>Bankrupt_Date__c</fullName>
    <label>Bankrupt Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/genesis__Application__c.field-meta.xml
<CustomField>
    <fullName>genesis__Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Parties</relationshipLabel>
    <relationshipName>Parties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Collateral__c/genesis__Application_Collateral__c.object-meta.xml
<CustomObject>
    <label>Application Collateral</label>
    <nameField>
        <displayFormat>ACD-{00000000}</displayFormat>
        <label>Application Collateral Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Collateral</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Applications__c/fields/Bankrupt_Date__c.field-meta.xml
<CustomField>
    <fullName>Bankrupt_Date__c</fullName>
    <label>Bankrupt Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/Previously_Bankrupt__c.field-meta.xml
<CustomField>
    <fullName>Previously_Bankrupt__c</fullName>
    <label>Previously Bankrupt</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/Total_Number_of_Securities__c.field-meta.xml
<CustomField>
    <fullName>Total_Number_of_Securities__c</fullName>
    <defaultValue>0</defaultValue>
    <description>https://wingategroup.atlassian.net/secure/RapidBoard.jspa?rapidView=8&amp;projectKey=AMS&amp;modal=detail&amp;selectedIssue=AMS-683
RJohnston - 14/4/2021
For reporting purposes, to have the number of securities per loan</description>
    <label>Total Number of Securities</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/UpdateApplicationValues.cls
/*
Company: Cloudkaptan Consultancy Services Pvt. Ltd.
Author: Rameswari Barman
Description: 
Development Date: 30/03/2021
Last Modified Date - 05/04/2021
*/
global with sharing class UpdateApplicationValues {
    webService static String updateNoOfSecurities(Id applicationId){
        try{
            
            if (String.isBlank(applicationId)) {
                throw new CustomException(ConstantValues.APPLICATION_ID_NULL);
            }
            genesis__Applications__c application = new genesis__Applications__c(Id = applicationId);
            List <genesis__Application_Collateral__c> applicationCollateralList = [SELECT Id
                                                                                    FROM genesis__Application_Collateral__c
                                                                                    WHERE genesis__Application__c =: applicationId
                                                                                    AND genesis__Collateral__c != NULL];
            if(applicationCollateralList.size() > 0){
               application.Total_Number_of_Securities__c = applicationCollateralList.size();
            }
            else{
                application.Total_Number_of_Securities__c = 0;
            }
            update application;
            return ConstantValues.SUCCESS_STATUS;
        }
        catch (Exception e) {
            GenericUtility.insertLog('UpdateApplicationValues.updateNoOfSecurities', e);
        }
        return ConstantValues.GENERAL_ERROR;
    }
    @InvocableMethod(
        label='Update Bankrupt Values'
        description='Updates Previously Bankrupt and Bankrupt discharged date value on Application'
    )
    public static void updateBankruptInfo(List<Id> appIdList){
        try{
            if (appIdList.size() > 0 == false) {
                throw new CustomException(ConstantValues.NO_APPLICATION);
            }
            List <genesis__Applications__c> appList = [SELECT Id,
                                                            Previously_Bankrupt__c,
                                                            Bankrupt_Date__c
                                                        FROM genesis__Applications__c
                                                        WHERE Id IN : appIdList];
            
            List <clcommon__Party__c> partyList = [SELECT Id,
                                                        Bankrupt_Date__c,
                                                        Applicant_ever_declared_banckrupt__c
                                                        FROM clcommon__Party__c
                                                        WHERE genesis__Application__c IN : appIdList
                                                        AND Applicant_ever_declared_banckrupt__c != NULL
                                                        ORDER BY Bankrupt_Date__c ASC NULLS FIRST];
            if(partyList.size() > 0){
                for(genesis__Applications__c eachApp : appList){
                    eachApp.Previously_Bankrupt__c = ConstantValues.NO_TAG;
                    eachApp.Bankrupt_Date__c = NULL;
                    for(clcommon__Party__c eachParty : partyList){
                        if(eachParty.Applicant_ever_declared_banckrupt__c == ConstantValues.YES_TAG){
                            eachApp.Previously_Bankrupt__c = ConstantValues.YES_TAG;
                            if(eachParty.Bankrupt_Date__c != NULL){
                                eachApp.Bankrupt_Date__c = eachParty.Bankrupt_Date__c;
                            }
                        }
                    }
                }
                update appList;
            }
        }
        catch (Exception e) {
            GenericUtility.insertLog('UpdateApplicationValues.updateBankruptInfo', e);
        }
    }
}