force-app/main/default/objects/clcommon__Party__c/clcommon__Party__c.object-meta.xml
<CustomObject>
    <label>Party</label>
    <nameField>
        <displayFormat>PAR-{00000000}</displayFormat>
        <label>Party Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

elixir/force-app/main/default/objects/clcommon__Party__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full</fullName>
            </value>
            <value>
                <fullName>Alt</fullName>
            </value>
            <value>
                <fullName>Lease</fullName>
                <isActive>false</isActive>
                <label>Lease</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/genesis__Application__c.field-meta.xml
<CustomField>
    <fullName>genesis__Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Parties</relationshipLabel>
    <relationshipName>Parties</relationshipName>
    <type>Lookup</type>
</CustomField>

elixir/force-app/main/default/objects/clcommon__Party__c/fields/Gross_Taxable_Income__c.field-meta.xml
<CustomField>
    <fullName>Gross_Taxable_Income__c</fullName>
    <label>Gross Taxable Income</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

elixir/force-app/main/default/objects/clcommon__Party__c/fields/Other_Income__c.field-meta.xml
<CustomField>
    <fullName>Other_Income__c</fullName>
    <label>Other Income</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/Total_Current_Income_Period__c.field-meta.xml
<CustomField>
    <fullName>Total_Current_Income_Period__c</fullName>
    <label>Total Current Income Period</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/Total_Other_Income__c.field-meta.xml
<CustomField>
    <fullName>Total_Other_Income__c</fullName>
    <label>Total Other Income</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/Total_PAYG_Income__c.field-meta.xml
<CustomField>
    <fullName>Total_PAYG_Income__c</fullName>
    <label>Total PAYG Income</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/Total_Self_Employed_Income__c.field-meta.xml
<CustomField>
    <fullName>Total_Self_Employed_Income__c</fullName>
    <label>Total Self Employed Income</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/Total_Unemployment_Income__c.field-meta.xml
<CustomField>
    <fullName>Total_Unemployment_Income__c</fullName>
    <label>Total Unemployment Income</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/genesis__Employment_Information__c/genesis__Employment_Information__c.object-meta.xml
<CustomObject>
    <label>Employment Information</label>
    <nameField>
        <label>Employment Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employment Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

elixir/force-app/main/default/objects/genesis__Employment_Information__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Document_Type_Set</valueSetName>
    </valueSet>
</CustomField>

elixir/force-app/main/default/objects/genesis__Employment_Information__c/fields/genesis__Application__c.field-meta.xml
<CustomField>
    <fullName>genesis__Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Employment Information</relationshipLabel>
    <relationshipName>Employment_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

elixir/force-app/main/default/objects/genesis__Employment_Information__c/fields/Party__c.field-meta.xml
<CustomField>
    <fullName>Party__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Party</label>
    <referenceTo>clcommon__Party__c</referenceTo>
    <relationshipLabel>Employment Information</relationshipLabel>
    <relationshipName>Employment_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

elixir/force-app/main/default/objects/genesis__Employment_Information__c/fields/PAYG_Income__c.field-meta.xml
<CustomField>
    <fullName>PAYG_Income__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PAYG Income</label>
    <type>Checkbox</type>
</CustomField>

elixir/force-app/main/default/objects/genesis__Employment_Information__c/fields/Total_Current_Income_Period__c.field-meta.xml
<CustomField>
    <fullName>Total_Current_Income_Period__c</fullName>
    <label>Total Current Income Period</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/genesis__Income__c/genesis__Income__c.object-meta.xml
<CustomObject>
    <description>This object will track the other income</description>
    <label>Income</label>
    <nameField>
        <label>Income Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incomes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Income__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full</fullName>
            </value>
            <value>
                <fullName>Alt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

elixir/force-app/main/default/objects/genesis__Income__c/fields/Employment_Information__c.field-meta.xml
<CustomField>
    <fullName>Employment_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employment Information</label>
    <referenceTo>genesis__Employment_Information__c</referenceTo>
    <relationshipLabel>Incomes</relationshipLabel>
    <relationshipName>Incomes</relationshipName>
    <type>Lookup</type>
</CustomField>

elixir/force-app/main/default/objects/genesis__Income__c/fields/genesis__Amount__c.field-meta.xml
<CustomField>
    <fullName>genesis__Amount__c</fullName>
    <description>The amount of other income</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/genesis__Income__c/fields/genesis__Application__c.field-meta.xml
<CustomField>
    <fullName>genesis__Application__c</fullName>
    <description>Master-Detail relationship for income</description>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Incomes</relationshipLabel>
    <relationshipName>Incomes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Elixir_Prod/force-app/main/default/objects/genesis__Income__c/fields/genesis__Frequency__c.field-meta.xml
<CustomField>
    <fullName>genesis__Frequency__c</fullName>
    <description>Period of income</description>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Fortnightly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
                <isActive>false</isActive>
                <label>Annual</label>
            </value>
            <value>
                <fullName>Bi-Weekly</fullName>
                <isActive>false</isActive>
                <label>Bi-Weekly</label>
            </value>
            <value>
                <fullName>Quarterly</fullName>
                <isActive>false</isActive>
                <label>Quarterly</label>
            </value>
            <value>
                <fullName>Semi Monthly</fullName>
                <isActive>false</isActive>
                <label>Semi Monthly</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

elixir/force-app/main/default/objects/genesis__Income__c/fields/Other_Income__c.field-meta.xml
<CustomField>
    <fullName>Other_Income__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Other Income</label>
    <type>Checkbox</type>
</CustomField>

Elixir_Prod/force-app/main/default/objects/genesis__Income__c/fields/Party__c.field-meta.xml
<CustomField>
    <fullName>Party__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Party</label>
    <referenceTo>clcommon__Party__c</referenceTo>
    <relationshipLabel>Incomes</relationshipLabel>
    <relationshipName>Incomes</relationshipName>
    <type>Lookup</type>
</CustomField>

elixir/force-app/main/default/objects/genesis__Income__c/fields/Unemployed_Income__c.field-meta.xml
<CustomField>
    <fullName>Unemployed_Income__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Unemployed Income</label>
    <type>Checkbox</type>
</CustomField>

elixir/force-app/main/default/globalValueSets/Document_Type_Set.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Full</fullName>
    </customValue>
    <customValue>
        <fullName>Alt</fullName>
    </customValue>
    <masterLabel>Document Type Set</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/UpdateTotalIncomesOnParty.cls
global with sharing class UpdateTotalIncomesOnParty {
    webService static void updateIncomesWS(Id partyId) {
        try{
            Double totalUnEmpIncome = 0;
            Double totalPaygIncome = 0;
            Double totalOtherIncome = 0;
            Double totalCurrentIncome = 0;
            String frequency;
            Double ammount = 0;
            Double totalSelfEmpAltDocIncome = 0;
            clcommon__Party__c objParty = [SELECT id,
                                                Name,
                                                Total_Unemployment_Income__c,
                                                Total_Other_Income__c,
                                                Total_PAYG_Income__c,
                                                Total_Self_Employed_Income__c,
                                                Gross_Taxable_Income__c,
                                                (
                                                    SELECT id,
                                                    genesis__Application__c,
                                                    Unemployed_Income__c,
                                                    Document_Type__c,
                                                    Other_Income__c,
                                                    PAYG_Income__c,
                                                    genesis__Amount__c,
                                                    genesis__Frequency__c
                                                    FROM Incomes__r
                                                ),
                                                (
                                                    SELECT Id,
                                                    Party__c,
                                                    genesis__Application__c,
                                                    Total_Current_Income_Period__c
                                                    FROM Employment_Information__r
                                                ) 
                                                FROM clcommon__Party__c 
                                                WHERE id =: partyId];
            for(genesis__Income__c objIncome : objParty.Incomes__r){
                if(objIncome.Unemployed_Income__c == true  && objIncome.genesis__Amount__c != null){
                    frequency = objIncome.genesis__Frequency__c;
                    ammount = objIncome.genesis__Amount__c;
                    if(frequency != null){
                        if(frequency == ConstantValues.weekly){
                            ammount *= 52;
                        }else if(frequency == ConstantValues.FORTNIGHTLY){
                            ammount *= 26;
                        }else if(frequency == ConstantValues.monthly){
                            ammount *= 12;
                        }else if(frequency == ConstantValues.YEARLY){
                            ammount *= 1;
                        }
                    }
                    totalUnEmpIncome += ammount;
                }
                if(objIncome.Other_Income__c == true  && objIncome.genesis__Amount__c != null){
                    frequency = objIncome.genesis__Frequency__c;
                    ammount = objIncome.genesis__Amount__c;
                    if(frequency != null){
                        if(frequency == ConstantValues.weekly){
                            ammount *= 52;
                        }else if(frequency == ConstantValues.FORTNIGHTLY){
                            ammount *= 26;
                        }else if(frequency == ConstantValues.monthly){
                            ammount *= 12;
                        }else if(frequency == ConstantValues.YEARLY){
                            ammount *= 1;
                        }
                    }
                    totalOtherIncome += ammount;
                }
                if(objIncome.PAYG_Income__c == true  && objIncome.genesis__Amount__c != null){
                    frequency = objIncome.genesis__Frequency__c;
                    ammount = objIncome.genesis__Amount__c;
                    System.debug('amount -> ' + ammount);
                    if(frequency != null){
                        if(frequency == ConstantValues.weekly){
                            ammount *= 52;
                        }else if(frequency == ConstantValues.FORTNIGHTLY){
                            ammount *= 26;
                        }else if(frequency == ConstantValues.monthly){
                            ammount *= 12;
                        }else if(frequency == ConstantValues.YEARLY){
                            ammount *= 1;
                        }
                    }
                    totalPaygIncome += ammount;
                }
                if(objIncome.Document_Type__c != null && objIncome.Document_Type__c == ConstantValues.ALT && objIncome.genesis__Amount__c != null){
                    totalSelfEmpAltDocIncome += objIncome.genesis__Amount__c; 
                }
            }
            for(genesis__Employment_Information__c objEmpInfo : objParty.Employment_Information__r){
                if(objEmpInfo.Total_Current_Income_Period__c != null){
                    totalCurrentIncome += objEmpInfo.Total_Current_Income_Period__c; 
                }
            }
            objParty.Total_Self_Employed_Income__c = totalCurrentIncome + totalSelfEmpAltDocIncome;
            objParty.Total_Unemployment_Income__c = totalUnEmpIncome;
            objParty.Total_PAYG_Income__c = totalPaygIncome;
            objParty.Total_Other_Income__c = totalOtherIncome;
            objParty.Gross_Taxable_Income__c = totalCurrentIncome + totalSelfEmpAltDocIncome + totalUnEmpIncome + totalPaygIncome + totalOtherIncome;
            update objParty;
        }
        catch(Exception e){
            GenericUtility.insertLog('UpdateTotalIncomesOnParty', e);
        }
    }
}