Elixir_Prod/force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Applications__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full Doc</fullName>
            </value>
            <value>
                <fullName>Alt Doc</fullName>
            </value>
            <value>
                <fullName>Lease Doc</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Elixir_Prod/force-app/main/default/objects/genesis__Employment_Information__c/genesis__Employment_Information__c.object-meta.xml
<CustomObject>
    <label>Employment Information</label>
    <nameField>
        <label>Employment Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employment Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

elixir/force-app/main/default/objects/genesis__Employment_Information__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Document_Type_Set</valueSetName>
    </valueSet>
</CustomField>

elixir/force-app/main/default/objects/genesis__Employment_Information__c/fields/genesis__Application__c.field-meta.xml
<CustomField>
    <fullName>genesis__Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Employment Information</relationshipLabel>
    <relationshipName>Employment_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Employment_Information__c/recordTypes/Self_Employed.recordType-meta.xml
<RecordType>
    <fullName>Self_Employed</fullName>
    <active>true</active>
    <label>Self Employed</label>
</RecordType>

force-app/main/default/objects/genesis__Income__c/genesis__Income__c.object-meta.xml
<CustomObject>
    <description>This object will track the other income</description>
    <label>Income</label>
    <nameField>
        <label>Income Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incomes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Income__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full</fullName>
            </value>
            <value>
                <fullName>Alt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

elixir/force-app/main/default/objects/genesis__Income__c/fields/Employment_Information__c.field-meta.xml
<CustomField>
    <fullName>Employment_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employment Information</label>
    <referenceTo>genesis__Employment_Information__c</referenceTo>
    <relationshipLabel>Incomes</relationshipLabel>
    <relationshipName>Incomes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Income__c/fields/genesis__Application__c.field-meta.xml
<CustomField>
    <fullName>genesis__Application__c</fullName>
    <description>Master-Detail relationship for income</description>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Incomes</relationshipLabel>
    <relationshipName>Incomes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

elixir/force-app/main/default/globalValueSets/Document_Type_Set.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Full</fullName>
    </customValue>
    <customValue>
        <fullName>Alt</fullName>
    </customValue>
    <masterLabel>Document Type Set</masterLabel>
</GlobalValueSet>

Elixir_Prod/force-app/main/default/classes/IncomeSummaryTest.cls
@isTest
public with sharing class IncomeSummaryTest{
        static testMethod void test1() {
                Test.startTest();
                genesis__applications__c appObj = new genesis__applications__c();
                insert appObj;

                RecordType rec = [Select id, name,sobjectType,
                                                        DeveloperName 
                                                        from RecordType 
                                                        Where sobjectType = 'genesis__Employment_Information__c' 
                                                        AND DeveloperName='Self_Employed'];

                genesis__Employment_Information__c empObj = new genesis__Employment_Information__c();
                empObj.Document_Type__c= 'Full';
                empObj.RecordTypeId = rec.id;
                Insert empobj;

                genesis__Income__c incomeobj = new genesis__Income__c();
                incomeobj.genesis__Application__c =appObj.id;
                incomeobj.Employment_Information__c= empobj.id;
                Insert incomeobj;             

                IncomeSummary.summaryValue(appObj.id);
                Test.stopTest(); 
        }

        static testMethod void test2() {
                Test.startTest();
                genesis__applications__c appObj = new genesis__applications__c();
                insert appObj;

                RecordType rec = [Select id, name,sobjectType,
                                                        DeveloperName 
                                                        from RecordType 
                                                        Where sobjectType = 'genesis__Employment_Information__c' 
                                                        AND DeveloperName='Self_Employed'];

                genesis__Employment_Information__c empObj = new genesis__Employment_Information__c();
                empObj.Document_Type__c= 'Full';
                empObj.RecordTypeId = rec.id;
                Insert empobj;

                genesis__Income__c incomeobj = new genesis__Income__c();
                incomeobj.genesis__Application__c =appObj.id;
                incomeobj.Employment_Information__c= empobj.id;
                Insert incomeobj;             

                IncomeSummary.IncomeSummarySkuidCallout(appObj.id);
                Test.stopTest(); 
        }
         static testMethod void test3() {
                Test.startTest();
                genesis__applications__c appObj = new genesis__applications__c();
                insert appObj;

                RecordType rec = [Select id, name,sobjectType,
                                                        DeveloperName 
                                                        from RecordType 
                                                        Where sobjectType = 'genesis__Employment_Information__c' 
                                                        AND DeveloperName='Self_Employed'];

                genesis__Employment_Information__c empObj = new genesis__Employment_Information__c();
                empObj.Document_Type__c= 'Full';
                empObj.RecordTypeId = rec.id;
                Insert empobj;

                genesis__Income__c incomeobj = new genesis__Income__c();
                incomeobj.genesis__Application__c =appObj.id;
                incomeobj.Employment_Information__c= empobj.id;           

                IncomeSummary.summaryValue(appObj.id);
                Test.stopTest(); 
        }
}