Elixir_Prod/force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <customHelpPage>loan__CLContractHelp</customHelpPage>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Elixir_Prod/force-app/main/default/objects/loan__Loan_Account__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>CL Contracts</relationshipLabel>
    <relationshipName>CL_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

Elixir_Prod/force-app/main/default/objects/loan__Loan_Account__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>CL Contracts</relationshipLabel>
    <relationshipName>CL_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

Elixir_Prod/force-app/main/default/objects/Loan_Warehouse__c/Loan_Warehouse__c.object-meta.xml
<CustomObject>
    <label>Loan Warehouse</label>
    <nameField>
        <label>Loan Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Warehouse</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

elixir/force-app/main/default/objects/Loan_Warehouse__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Loan Warehouse</relationshipLabel>
    <relationshipName>Loan_Warehouse</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Warehouse__c/fields/CL_Contract__c.field-meta.xml
<CustomField>
    <fullName>CL_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CL Contract</label>
    <referenceTo>loan__Loan_Account__c</referenceTo>
    <relationshipLabel>Loan Warehouse</relationshipLabel>
    <relationshipName>Loan_Warehouse</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Warehouse__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Settled in &amp; Transferred in</relationshipLabel>
    <relationshipName>Loan_Warehouse</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Elixir_Prod/force-app/main/default/classes/WarehouseController.cls
/*************************************
Description : Controller class for warehouse tagging - used to tag a warehouse when 'Add Warehouse' button is clicked in CL contract.
Developer : Deep Bhattacharjee
Date : 01/01/20
***************************************/

public class WarehouseController{
    public loan__Loan_Account__c acct {get;set;}
    public class MyException extends Exception {}
    public WarehouseController(){
        acct = [SELECT id,name, Warehouse__c, Application__r.Name FROM loan__Loan_Account__c WHERE id = :ApexPages.currentPage().getParameters().get('loanId')];
    }
    public PageReference Save() {
        try {
            Loan_Warehouse__c obj = new Loan_Warehouse__c();
            obj.Warehouse__c = acct.Warehouse__c;
            obj.Application__c = acct.Application__c;
            obj.CL_Contract__c = acct.id;
            if(obj!=Null){
                insert obj;
            }
            return new Pagereference('/'+ApexPages.currentPage().getParameters().get('loanId'));
        }
        catch(Exception e){
            insert new clcommon__Log__c(
                clcommon__Message__c = 'WarehouseController :Exception: '+e.getStackTraceString()+'error='+e.getMessage()+' at Line Number '+e.getLineNumber(),
                clcommon__Time__c = System.Now());
            return null;
        }
    }
    public PageReference Cancel() {
        return new Pagereference('/'+ApexPages.currentPage().getParameters().get('loanId')); 
    }
}