elixir/force-app/main/default/objects/ABN_Company_Information__c/ABN_Company_Information__c.object-meta.xml
<CustomObject>
    <label>ABN Company Information</label>
    <nameField>
        <displayFormat>ABNCOMINFO-{000000}</displayFormat>
        <label>ABN Company Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ABN Company Informations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ABN_Company_Information__c/fields/Employment_Information__c.field-meta.xml
<CustomField>
    <fullName>Employment_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employment Information</label>
    <referenceTo>genesis__Employment_Information__c</referenceTo>
    <relationshipLabel>ABN Company Informations</relationshipLabel>
    <relationshipName>ABN_Company_Informations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ABN_Company_Information__c/fields/Party__c.field-meta.xml
<CustomField>
    <fullName>Party__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Party</label>
    <referenceTo>clcommon__Party__c</referenceTo>
    <relationshipLabel>ABN Company Informations</relationshipLabel>
    <relationshipName>ABN_Company_Informations</relationshipName>
    <type>Lookup</type>
</CustomField>

elixir/force-app/main/default/objects/ABN_Company_List__c/ABN_Company_List__c.object-meta.xml
<CustomObject>
    <label>ABN Company List</label>
    <nameField>
        <displayFormat>ABNCOM-{000000000}</displayFormat>
        <label>ABN Company List Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ABN Company Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ABN_Company_List__c/fields/ABN_Company_Information__c.field-meta.xml
<CustomField>
    <fullName>ABN_Company_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ABN Company Information</label>
    <referenceTo>ABN_Company_Information__c</referenceTo>
    <relationshipLabel>ABN Company Lists</relationshipLabel>
    <relationshipName>ABN_Company_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

Elixir_Prod/force-app/main/default/objects/ABN_Company_List__c/fields/ABN_Information__c.field-meta.xml
<CustomField>
    <fullName>ABN_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ABN Information</label>
    <referenceTo>ABN_Information__c</referenceTo>
    <relationshipLabel>ABN Company Lists</relationshipLabel>
    <relationshipName>ABN_Company_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

Elixir_Prod/force-app/main/default/objects/ABN_Company_List__c/fields/Employment_Information__c.field-meta.xml
<CustomField>
    <fullName>Employment_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employment Information</label>
    <referenceTo>genesis__Employment_Information__c</referenceTo>
    <relationshipLabel>ABN Company Lists</relationshipLabel>
    <relationshipName>ABN_Company_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

elixir/force-app/main/default/objects/ABN_Company_List__c/fields/Entity_Description__c.field-meta.xml
<CustomField>
    <fullName>Entity_Description__c</fullName>
    <label>Entity Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

elixir/force-app/main/default/objects/ABN_Company_List__c/fields/Entity_Status_Code__c.field-meta.xml
<CustomField>
    <fullName>Entity_Status_Code__c</fullName>
    <label>Entity Status Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ABN_Company_List__c/fields/Party__c.field-meta.xml
<CustomField>
    <fullName>Party__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Party</label>
    <referenceTo>clcommon__Party__c</referenceTo>
    <relationshipLabel>ABN Company Lists</relationshipLabel>
    <relationshipName>ABN_Company_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ABN_Company_List__c/fields/Selected_for_ABN_Search__c.field-meta.xml
<CustomField>
    <fullName>Selected_for_ABN_Search__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Selected for ABN Search</label>
    <type>Checkbox</type>
</CustomField>

elixir/force-app/main/default/objects/ABN_Information__c/ABN_Information__c.object-meta.xml
<CustomObject>
    <label>ABN Information</label>
    <nameField>
        <label>ABN Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ABN Informations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Elixir_Prod/force-app/main/default/objects/ABN_Information__c/fields/Effective_From__c.field-meta.xml
<CustomField>
    <fullName>Effective_From__c</fullName>
    <label>Effective From</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

elixir/force-app/main/default/objects/ABN_Information__c/fields/Employment_Information__c.field-meta.xml
<CustomField>
    <fullName>Employment_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employment Information</label>
    <referenceTo>genesis__Employment_Information__c</referenceTo>
    <relationshipLabel>ABN Informations</relationshipLabel>
    <relationshipName>ABN_Informations</relationshipName>
    <type>Lookup</type>
</CustomField>

Elixir_Prod/force-app/main/default/objects/ABN_Information__c/fields/Entity_description__c.field-meta.xml
<CustomField>
    <fullName>Entity_description__c</fullName>
    <label>Entity description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

elixir/force-app/main/default/objects/ABN_Information__c/fields/Entity_status_code__c.field-meta.xml
<CustomField>
    <fullName>Entity_status_code__c</fullName>
    <label>Entity status code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ABN_Information__c/fields/GST_EffectiveFrom__c.field-meta.xml
<CustomField>
    <fullName>GST_EffectiveFrom__c</fullName>
    <inlineHelpText>A business  is registered for Goods &amp; Services Tax (G.S.T) if annual income is greater than $75,000.  [7.6]</inlineHelpText>
    <label>GST EffectiveFrom</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

elixir/force-app/main/default/objects/ABN_Information__c/fields/Identifier_value__c.field-meta.xml
<CustomField>
    <fullName>Identifier_value__c</fullName>
    <label>Identifier value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

elixir/force-app/main/default/objects/ABN_Information__c/fields/Party__c.field-meta.xml
<CustomField>
    <fullName>Party__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Party</label>
    <referenceTo>clcommon__Party__c</referenceTo>
    <relationshipLabel>ABN Informations</relationshipLabel>
    <relationshipName>ABN_Informations</relationshipName>
    <type>Lookup</type>
</CustomField>

elixir/force-app/main/default/objects/clcommon__Party__c/clcommon__Party__c.object-meta.xml
<CustomObject>
    <label>Party</label>
    <nameField>
        <displayFormat>PAR-{00000000}</displayFormat>
        <label>Party Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

elixir/force-app/main/default/objects/clcommon__Party__c/fields/ABN_Effective_From__c.field-meta.xml
<CustomField>
    <fullName>ABN_Effective_From__c</fullName>
    <label>ABN Effective From</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

elixir/force-app/main/default/objects/clcommon__Party__c/fields/Company_ABN__c.field-meta.xml
<CustomField>
    <fullName>Company_ABN__c</fullName>
    <label>Company ABN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

elixir/force-app/main/default/objects/clcommon__Party__c/fields/Company_ABN_Status__c.field-meta.xml
<CustomField>
    <fullName>Company_ABN_Status__c</fullName>
    <label>Company ABN Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

elixir/force-app/main/default/objects/clcommon__Party__c/fields/Company_ACN__c.field-meta.xml
<CustomField>
    <fullName>Company_ACN__c</fullName>
    <label>Company ACN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

elixir/force-app/main/default/objects/clcommon__Party__c/fields/Entity_Type__c.field-meta.xml
<CustomField>
    <fullName>Entity_Type__c</fullName>
    <label>Entity Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

elixir/force-app/main/default/objects/clcommon__Party__c/fields/Goods_Services_Tax__c.field-meta.xml
<CustomField>
    <fullName>Goods_Services_Tax__c</fullName>
    <label>Goods &amp; Services Tax</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

elixir/force-app/main/default/objects/clcommon__Party__c/fields/Record_Extract_Date__c.field-meta.xml
<CustomField>
    <fullName>Record_Extract_Date__c</fullName>
    <label>Record Extract Date</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

elixir/force-app/main/default/objects/genesis__Employment_Information__c/genesis__Employment_Information__c.object-meta.xml
<CustomObject>
    <label>Employment Information</label>
    <nameField>
        <label>Employment Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employment Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

elixir/force-app/main/default/objects/genesis__Employment_Information__c/fields/ABN_Effective_From__c.field-meta.xml
<CustomField>
    <fullName>ABN_Effective_From__c</fullName>
    <label>ABN Effective From</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

elixir/force-app/main/default/objects/genesis__Employment_Information__c/fields/Company_ABN__c.field-meta.xml
<CustomField>
    <fullName>Company_ABN__c</fullName>
    <label>Company ABN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

elixir/force-app/main/default/objects/genesis__Employment_Information__c/fields/Company_ACN__c.field-meta.xml
<CustomField>
    <fullName>Company_ACN__c</fullName>
    <label>Company ACN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

elixir/force-app/main/default/objects/genesis__Employment_Information__c/fields/Goods_Services_Tax__c.field-meta.xml
<CustomField>
    <fullName>Goods_Services_Tax__c</fullName>
    <label>Goods &amp; Services Tax</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

elixir/force-app/main/default/objects/genesis__Employment_Information__c/fields/Party__c.field-meta.xml
<CustomField>
    <fullName>Party__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Party</label>
    <referenceTo>clcommon__Party__c</referenceTo>
    <relationshipLabel>Employment Information</relationshipLabel>
    <relationshipName>Employment_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Employment_Information__c/fields/Record_Extract_Date__c.field-meta.xml
<CustomField>
    <fullName>Record_Extract_Date__c</fullName>
    <label>Record Extract Date</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

elixir/force-app/main/default/classes/ABNAPICallout.cls
/******************************************
* Descrption : This is the callout class for ABN Integration. 
*              This class called the adapter class.
*              And also responsible for store the response of ABN.
*
* Developer : Soumik Sarkar
*************************************************/

global class ABNAPICallout{
    
    public static List<ABN_Company_List__c> companyList = new List<ABN_Company_List__c>();
    public static List<ABN_Company_List__c> updatedCompanyList = new List<ABN_Company_List__c>();
    
    global static void makeABNCallout(Id companyListId){
        try{
            companyList = [SELECT Id,
                                  Name, 
                                  Selected_for_ABN_Search__c,
                                  ABN_Company_Information__r.Employment_Information__c,
                                  ABN_Company_Information__r.Party__c
                                  FROM ABN_Company_List__c
                                  WHERE Id=:companyListId];

            if(companyList.isEmpty() == true){
                throw new CustomException(ConstantValues.companyNotFound);
            }
            
            Map<String,Object> compInfo = new Map<String,Object>();
            Map<String,Object> companyMap = new Map<String,Object>();
            compInfo.put('abnCompanyId',companyList.get(0).id);
            companyMap.put('companyInfo',compInfo);
            companyMap.put('ExecutionPriority', 1);

            ints.AbstractMockService   mc  = ints.APIFactory.getPassthroughService();
            ints.IntegrationResponseObject responseObject = mc.runPassthroughService(companyMap,ConstantValues.serviceName,'');
            
            ABN_Information__c abnObj = new ABN_Information__c();
            abnObj = ABNResponse.saveResponse(responseObject);
            insert abnObj;
            updateParentRecord(abnObj);
            
            //return ConstantValues.ABN_GENERATED;
            
        }
        catch(Exception e){
            insert new clcommon__Log__c(
                        clcommon__Message__c = 'ABN_API :Exception:: '+e.getStackTraceString()+'error='+e.getMessage()+' at Line Number '+e.getLineNumber(),
                        clcommon__Time__c = System.Now());
            //return ConstantValues.EXCEPTION_OCCURED;
        }
        
    }
    
    //******* Update ABN values to Party Object & Employment Information Object. *******//

    private static void updateParentRecord(ABN_Information__c abnObj){
        try{
            //CHECK IF NEWLY CREATED ABN INFORMATION OBJECT IS BLANK OR NOT
            if(abnObj == NULL){
                throw new CustomException(ConstantValues.abnInfoException);
            }
            
            if(String.isNotBlank(companyList.get(0).ABN_Company_Information__r.Employment_Information__c) && String.isBlank(companyList.get(0).ABN_Company_Information__r.Party__c)){
                List<genesis__Employment_Information__c > empInfoList = [SELECT Id, Name FROM genesis__Employment_Information__c WHERE Id =:companyList.get(0).ABN_Company_Information__r.Employment_Information__c LIMIT 1];
                if(empInfoList.isEmpty() == false){
                    //UPDATE ELEMENTS FROM ABN INFORMATION OBJ TO EMPLOYMENT INFORMATION OBJ
                    empInfoList.get(0).Company_ABN__c = String.isNotBlank(abnObj.Identifier_value__c) ? abnObj.Identifier_value__c : '';
                    empInfoList.get(0).Company_ACN__c = String.isNotBlank(abnObj.ASICNumber__c) ? abnObj.ASICNumber__c : '';
                    empInfoList.get(0).Record_Extract_Date__c = String.isNotBlank(abnObj.DateTimeRetrieved__c) ? abnObj.DateTimeRetrieved__c : '';
                    empInfoList.get(0).Entity_Type__c = String.isNotBlank(abnObj.Entity_description__c) ? abnObj.Entity_description__c : '';
                    empInfoList.get(0).ABN_Status__c = String.isNotBlank(abnObj.Entity_status_code__c) ? abnObj.Entity_status_code__c : '';
                    empInfoList.get(0).Goods_Services_Tax__c = String.isNotBlank(abnObj.GST_EffectiveFrom__c) ? abnObj.GST_EffectiveFrom__c : 'Not currently registered for GST';
                    empInfoList.get(0).ABN_Effective_From__c = String.isNotBlank(abnObj.Effective_From__c) ? abnObj.Effective_From__c : '';
                    UPDATE empInfoList.get(0);
                    deleteUnwantedCompanyRecords(companyList.get(0).id);
                    
                }
            }else if(String.isNotBlank(companyList.get(0).ABN_Company_Information__r.Party__c) && String.isBlank(companyList.get(0).ABN_Company_Information__r.Employment_Information__c)){
                List<clcommon__Party__c> partyList = [SELECT Id, Name FROM clcommon__Party__c WHERE Id =: companyList.get(0).ABN_Company_Information__r.Party__c LIMIT 1];
                if(partyList.isEmpty() == false){
                    //UPDATE ELEMENTS FROM ABN INFORMATION OBJ TO PARTY OBJ
                    partyList.get(0).Company_ACN__c = String.isNotBlank(abnObj.ASICNumber__c) ? abnObj.ASICNumber__c : '';
                    partyList.get(0).Company_ABN_Status__c = String.isNotBlank(abnObj.Entity_status_code__c) ? abnObj.Entity_status_code__c : '';
                    partyList.get(0).Record_Extract_Date__c = String.isNotBlank(abnObj.DateTimeRetrieved__c) ? abnObj.DateTimeRetrieved__c : '';
                    partyList.get(0).Goods_Services_Tax__c = String.isNotBlank(abnObj.GST_EffectiveFrom__c) ? abnObj.GST_EffectiveFrom__c : 'Not currently registered for GST';
                    partyList.get(0).Entity_Type__c = String.isNotBlank(abnObj.Entity_description__c) ? abnObj.Entity_description__c : '';
                    partyList.get(0).Company_ABN__c = String.isNotBlank(abnObj.Identifier_value__c) ? abnObj.Identifier_value__c : '';
                    partyList.get(0).ABN_Effective_From__c = String.isNotBlank(abnObj.Effective_From__c) ? abnObj.Effective_From__c : '';
                    UPDATE partyList.get(0); 
                    deleteUnwantedCompanyRecords(companyList.get(0).id);                   
                    
                }
            }else if(String.isNotBlank(companyList.get(0).ABN_Company_Information__r.Party__c) && String.isNotBlank(companyList.get(0).ABN_Company_Information__r.Employment_Information__c)){
                throw new CustomException(ConstantValues.lookupConflict);
            }else{
                 throw new CustomException(ConstantValues.parentRecordLookupException);   
            }
        }catch(Exception e){
            throw new CustomException(e.getMessage());
        }
        
        
    }
    
    // ***** Delete Unwanted Company Record from ABN Company Search ******//
    
    private static void deleteUnwantedCompanyRecords(Id companyListId){
        updatedCompanyList = [SELECT Id, 
                                     Name, 
                                     Selected_for_ABN_Search__c 
                                     FROM  ABN_Company_List__c 
                                     WHERE Id !=: companyListId
                                     AND Selected_for_ABN_Search__c = false];
        
        companyList.get(0).Selected_for_ABN_Search__c = true;
        UPDATE companyList.get(0);        
        DELETE updatedCompanyList;
        
        
    }
    
    // Webservice method for calling this ABNAPICallout class &  makeABNCallout() method for ABN COmpany Search Integration. ******//

    Webservice static String makeABNCompanySkuidCallout(Id companyId){
        try{
            makeABNCallout(companyId);
            return ConstantValues.msg;    
        }catch(Exception e){
            throw new CustomException(e.getMessage());
        }
    }
    
}