force-app/main/default/objects/Batch_Job_Size__c/Batch_Job_Size__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Batch Job Size</label>
</CustomObject>

force-app/main/default/objects/Batch_Job_Size__c/fields/UpdateFirstSecondPmntDateBatch__c.field-meta.xml
<CustomField>
    <fullName>UpdateFirstSecondPmntDateBatch__c</fullName>
    <label>UpdateFirstSecondPmntDateBatch</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <customHelpPage>loan__CLContractHelp</customHelpPage>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Account__c/fields/First_Repayment_Date_After_IR_Change__c.field-meta.xml
<CustomField>
    <fullName>First_Repayment_Date_After_IR_Change__c</fullName>
    <label>First Repayment Date After IR Change</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Invalid_Data__c.field-meta.xml
<CustomField>
    <fullName>loan__Invalid_Data__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If system identify any data issues with this lending account, the reasons will be displayed on the top of lending account and this flag will be checked.
Once the issues are fixed, this flag will be unchecked by system.
User should not modify this flag.</inlineHelpText>
    <label>Invalid Data</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Loan Amount</description>
    <inlineHelpText>This is the financed amount on the contract which will be disbursed to the customer.</inlineHelpText>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Loan_Status__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Status__c</fullName>
    <inlineHelpText>Status of the Account expected values are :
Pending Approval
Active - Good Standing
Active - Bad Standing
Active - Matured
Approved
Canceled
Closed - Obligations met
Closed- Written Off
Closed - Refinanced
Partial Application
Closed - Premature</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active - Bad Standing</fullName>
            </value>
            <value>
                <fullName>Active - Good Standing</fullName>
            </value>
            <value>
                <fullName>Active - Marked for Closure</fullName>
            </value>
            <value>
                <fullName>Active - Matured</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Closed - Obligations met</fullName>
            </value>
            <value>
                <fullName>Closed - Premature</fullName>
            </value>
            <value>
                <fullName>Closed - Refinanced</fullName>
            </value>
            <value>
                <fullName>Closed- Written Off</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>Partial Application</fullName>
                <default>true</default>
                <label>Partial Application</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Premature Closure Initiated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/New_Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>New_Interest_Rate__c</fullName>
    <label>New Interest Rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/New_Interest_Rate_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>New_Interest_Rate_Effective_Date__c</fullName>
    <label>New Interest Rate Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Scheduled_Balance_As_at_IR_change_date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Balance_As_at_IR_change_date__c</fullName>
    <label>Scheduled Balance As at IR change date</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Second_Repayment_Date_After_IR_Change__c.field-meta.xml
<CustomField>
    <fullName>Second_Repayment_Date_After_IR_Change__c</fullName>
    <label>Second Repayment Date After IR Change</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/UpdateFirstSecondPmntDateBatch.cls
/**********************************************************************************************************************************************************
Company : CloudKaptan Consultancy Services Pvt. Ltd.
Developer : Rameswari Barman
Development Date : 12/04/2022
Last Modified By : Rameswari Barman
Last Modified Date : 12/04/2022
Description : This class is used to update first,second payments dates along with schedule balance at the rate change date
 
***********************************************************************************************************************************************************/


global class UpdateFirstSecondPmntDateBatch extends clcommon.DynamicJob{

    global UpdateFirstSecondPmntDateBatch(){
        //BLANK CONSTRUCTOR
    } 
    
    global override String getRuntimeQuery() {
        return                        'SELECT Id, '+
                                            'Name, '+
                                            'First_Repayment_Date_After_IR_Change__c, '+
                                            'Second_Repayment_Date_After_IR_Change__c, '+
                                            'New_Interest_Rate_Effective_Date__c,'+
                                            'New_Interest_Rate__c, '+
                                            'Scheduled_Balance_As_at_IR_change_date__c, '+
                                            'loan__Loan_Amount__c '+
                                        'FROM loan__Loan_Account__c '+
                                        'WHERE loan__Invalid_Data__c = FALSE '+
                                        'AND loan__Loan_Status__c IN (\'Active - Good Standing\',\'Active - Bad Standing\',\'Active - Matured\',\'Active - Marked for Closure\') '+
                                        'AND New_Interest_Rate_Effective_Date__c != NULL '+
                                        'AND New_Interest_Rate__c != NULL '+
                                        'ORDER BY Id';
    }
    
    global override void doStart(Database.BatchableContext bc) {}

    global override void doExecute(System.SchedulableContext sc) {
        UpdateFirstSecondPmntDateBatch obj = new UpdateFirstSecondPmntDateBatch();
        Batch_Job_Size__c batch=Batch_Job_Size__c.getInstance();
        Integer size = batch.UpdateFirstSecondPmntDateBatch__c != NULL ? Integer.valueOf(batch.UpdateFirstSecondPmntDateBatch__c) : 200;  
        database.executebatch(obj,size);
    }
    public override void doexecute(Database.BatchableContext bc, List<sobject> objLoanList) {
        try{
            if(objLoanList.isEmpty() == FALSE){
                Integer count = 0;
                List <loan__Loan_Account__c> loanList = objLoanList;
                List <loan__Repayment_Schedule__c> repaymentList = [SELECT Id,
                                                                        loan__Due_Date__c,
                                                                        loan__Loan_Account__c,
                                                                        loan__Balance__c
                                                                        FROM loan__Repayment_Schedule__c
                                                                        WHERE loan__Loan_Account__c IN : objLoanList
                                                                    AND loan__Is_Archived__c = FALSE
                                                                    AND loan__Due_Date__c != NULL
                                                                    AND loan__Balance__c != NULL
                                                                    ORDER BY loan__Loan_Account__c, loan__Due_Date__c ASC];
                Map <Id,List<loan__Repayment_Schedule__c>> loanScheduleMap = new Map <Id,List<loan__Repayment_Schedule__c>>();
                for(loan__Loan_Account__c eachLoan : loanList){
                    count = 0;
                    eachLoan.First_Repayment_Date_After_IR_Change__c = NULL;
                    eachLoan.Second_Repayment_Date_After_IR_Change__c = NULL;
                    eachLoan.Scheduled_Balance_As_at_IR_change_date__c = eachLoan.loan__Loan_Amount__c;
                    for(loan__Repayment_Schedule__c eachSchedule : repaymentList){
                        if(eachSchedule.loan__Loan_Account__c == eachLoan.Id && eachSchedule.loan__Due_Date__c <= eachLoan.New_Interest_Rate_Effective_Date__c){
                            eachLoan.Scheduled_Balance_As_at_IR_change_date__c = eachSchedule.loan__Balance__c;
                        }
                        else if(eachSchedule.loan__Loan_Account__c == eachLoan.Id && eachSchedule.loan__Due_Date__c > eachLoan.New_Interest_Rate_Effective_Date__c){
                            if(count == 0){
                                eachLoan.First_Repayment_Date_After_IR_Change__c = eachSchedule.loan__Due_Date__c;
                                count ++;
                            }
                            else if(count == 1){
                                eachLoan.Second_Repayment_Date_After_IR_Change__c = eachSchedule.loan__Due_Date__c;
                                break;
                            }
                        }
                    }
                }
                update objLoanList;
            }
        }catch(Exception exe){
            GenericUtility.insertBatchProcessLog('UpdateFirstSecondPmntDateBatch',exe);
        }
    }
    
    global override void doInitialize() {}
  
    global override void doFinish(Database.BatchableContext bc) {}
}