force-app/main/default/objects/Batch_Job_Size__c/Batch_Job_Size__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Batch Job Size</label>
</CustomObject>

force-app/main/default/objects/Batch_Job_Size__c/fields/ChecklistDetailDeletionBatch_Job_Size__c.field-meta.xml
<CustomField>
    <fullName>ChecklistDetailDeletionBatch_Job_Size__c</fullName>
    <label>ChecklistDetailDeletionBatch Job Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Checklist_Detail__c/Checklist_Detail__c.object-meta.xml
<CustomObject>
    <label>Checklist Detail</label>
    <nameField>
        <label>Checklist Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Checklist Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Checklist_Detail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NOT EVALUATED</fullName>
                <default>true</default>
                <label>NOT EVALUATED</label>
            </value>
            <value>
                <fullName>SUCCESS</fullName>
            </value>
            <value>
                <fullName>FAIL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CheckListDetailDeletionBatch.cls
/****************************************************************************************************
Company : CloudKaptan Consultancy Services Pvt. Ltd.
Developer : Rameswari Barman
Development Date : 2/09/2022
Last Modified By : Rameswari Barman
Last Modified Date : 2/09/2022
Description : This batch deletes ChecklistDetail records that have SUCCESS at status
****************************************************************************************************/

global class CheckListDetailDeletionBatch extends clcommon.DynamicJob {

    global CheckListDetailDeletionBatch(){
        //BLANK CONSTRUCTOR
    } 
    
    global override String getRuntimeQuery() {
        String queryString = '';
        try{
            //Not doing null check for Days_consideration_for_deleting_loan_repayment_schedule_records
            //as its in a custom label and its required to save a value for saving the label
            queryString = 'SELECT Id '+
                          'FROM Checklist_Detail__c '+
                          'WHERE Status__c = \'SUCCESS\'';
        }catch(Exception exe){
            GenericUtility.insertBatchProcessLog('CheckListDetailDeletionBatch',exe);
        }
        return queryString;
    }
    
    global override void doStart(Database.BatchableContext bc) {}

    global override void doExecute(System.SchedulableContext sc) {
        CheckListDetailDeletionBatch obj = new CheckListDetailDeletionBatch();
        Batch_Job_Size__c batch=Batch_Job_Size__c.getInstance();
        Integer size = batch.ChecklistDetailDeletionBatch_Job_Size__c != NULL ? Integer.valueOf(batch.ChecklistDetailDeletionBatch_Job_Size__c) : 200;  
        database.executebatch(obj,size);
    }
    public override void doexecute(Database.BatchableContext bc, List<Sobject> objChecklistDetailList) {
        try{
            if(objChecklistDetailList.isEmpty() == FALSE){
                Database.delete(objChecklistDetailList,false);
            }
        }catch(Exception exe){
            GenericUtility.insertBatchProcessLog('CheckListDetailDeletionBatch',exe);
        }
    }
    global override void doInitialize() {}
  
    global override void doFinish(Database.BatchableContext bc) {}
}