force-app/main/default/objects/Batch_Job_Size__c/Batch_Job_Size__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Batch Job Size</label>
</CustomObject>

force-app/main/default/objects/Batch_Job_Size__c/fields/LoanCollateralUpdateBatch_Size__c.field-meta.xml
<CustomField>
    <fullName>LoanCollateralUpdateBatch_Size__c</fullName>
    <label>LoanCollateralUpdateBatch_Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <customHelpPage>loan__CLContractHelp</customHelpPage>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Account__c/fields/Actual_Security_Value__c.field-meta.xml
<CustomField>
    <fullName>Actual_Security_Value__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Actual Security Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Current_Loan_Balance_Excluding_Deposit__c.field-meta.xml
<CustomField>
    <fullName>Current_Loan_Balance_Excluding_Deposit__c</fullName>
    <formula>loan__Loan_Balance__c- Deposit_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Current Loan Balance Excluding Deposit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Current_Total_of_Discharged_Securities__c.field-meta.xml
<CustomField>
    <fullName>Current_Total_of_Discharged_Securities__c</fullName>
    <label>Current Total # of Discharged Securities</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Current_Total_of_Securities__c.field-meta.xml
<CustomField>
    <fullName>Current_Total_of_Securities__c</fullName>
    <label>Current Total # of Securities</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

elixir/force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Approval_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Approval_Date__c</fullName>
    <inlineHelpText>The date on which the loan is approved.</inlineHelpText>
    <label>Approval Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/MIP_LVR__c.field-meta.xml
<CustomField>
    <fullName>MIP_LVR__c</fullName>
    <label>MIP LVR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Original_Total_of_Securities__c.field-meta.xml
<CustomField>
    <fullName>Original_Total_of_Securities__c</fullName>
    <label>Original Total # of Securities</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Risk_LVR__c.field-meta.xml
<CustomField>
    <fullName>Risk_LVR__c</fullName>
    <label>Risk LVR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Collateral__c/fields/MIP_Value__c.field-meta.xml
<CustomField>
    <fullName>MIP_Value__c</fullName>
    <label>MIP Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Collateral__c/fields/Risk_Value__c.field-meta.xml
<CustomField>
    <fullName>Risk_Value__c</fullName>
    <label>Risk Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Collateral__c/fields/Security_Status__c.field-meta.xml
<CustomField>
    <fullName>Security_Status__c</fullName>
    <label>Security Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Discharged</fullName>
            </value>
            <value>
                <fullName>Mortgagee in Possession</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LoanCollateralUpdateBatch.cls
/****************************************************************************************************
Company: Cloudkaptan Consultancy Services Pvt. Ltd.
Author: Ariz Mazhary
Description : This class update Cl Contract Fields.
Development Date : 14/02/2022
Last Modified Date : 24/02/2022
****************************************************************************************************/

public class LoanCollateralUpdateBatch implements DataBase.StateFul,DataBase.Batchable<sObject>,Schedulable {
    //Query all Loan Collateral  
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([SELECT id,
                                                 loan__Loan__c,
                                                 loan__Loan__r.id,
                                                 Original_Value__c,
                                                 MIP_Value__c,
                                                 Risk_Value__c,
                                         		 CreatedDate,
                                         		 LastModifiedDate,
                                                 Security_Status__c
                                             FROM loan__Loan_Collateral__c]);
    }
    public void execute(Database.BatchableContext bc, List<loan__Loan_Collateral__c> objLoanCollList) {
        try{
            List<loan__Loan_Account__c> loanAccountList=new List<loan__Loan_Account__c>();
            List<Id> loanIdList=new List<Id>();
            for(loan__Loan_Collateral__c objLoanColl:objLoanCollList){
                if(objLoanColl.CreatedDate != objLoanColl.LastModifiedDate && objLoanColl.loan__Loan__c!=NULL){
                    loanIdList.add(objLoanColl.loan__Loan__c);
                }
            }
            loanAccountList= [SELECT id,
                                    Current_Loan_Balance_Excluding_Deposit__c,
                                    loan__Payment_Mode__c,
                                    loan__Loan_Purpose__c,
                                    loan__Approval_Date__c,
                                    Original_Total_of_Securities__c,
                                    Actual_Security_Value__c,
                                    Current_Total_of_Securities__c,
                                    Current_Total_of_Discharged_Securities__c,
                                    Risk_LVR__c,
                                    MIP_LVR__c
                                FROM loan__Loan_Account__c 
                                WHERE id IN: loanIdList];
            if(loanAccountList.size()>0){
				ConvertToContract.updateClContract(loanAccountList);               
            }
            if(test.isRunningTest()){
                Integer a = 4/0;
            }
        }catch(Exception exe){
            GenericUtility.insertBatchProcessLog('LoanCollateralUpdateBatch',exe);
        } 
    }
	public void execute(SchedulableContext sc) {
        Batch_Job_Size__c batch=Batch_Job_Size__c.getInstance();
        LoanCollateralUpdateBatch obj = new LoanCollateralUpdateBatch();
        Integer size = batch.LoanCollateralUpdateBatch_Size__c != NULL ? Integer.valueOf(batch.LoanCollateralUpdateBatch_Size__c) : 10;  
        database.executebatch(obj,size);
    }
    public void finish(Database.BatchableContext bc){
    }

}