force-app/main/default/objects/Batch_Job_Size__c/Batch_Job_Size__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Batch Job Size</label>
</CustomObject>

force-app/main/default/objects/Batch_Job_Size__c/fields/LTSRedrawUpdateBatch_Size__c.field-meta.xml
<CustomField>
    <fullName>LTSRedrawUpdateBatch_Size__c</fullName>
    <label>LTSRedrawUpdateBatch_Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LTSRedrawUpdateBatchExecution.cls
/****************************************************************************************************
Company: Cloudkaptan Consultancy Services Pvt. Ltd.
Author: Ariz Mazhary
Description : This class is to run the LTSRedrawUpdateBatch batch job 
                from 'Update LTS Redraw ' custom button.
Development Date : 14/06/2021
Last Modified Date : 14/06/2021
****************************************************************************************************/

global with sharing class LTSRedrawUpdateBatchExecution {
    
    Webservice static string executeLTSRedrawUpdateBatchWS(){

        Batch_Job_Size__c batch=Batch_Job_Size__c.getInstance();
        LTSRedrawUpdateBatch obj = new LTSRedrawUpdateBatch();
        Integer size = batch.LTSRedrawUpdateBatch_Size__c != NULL ? Integer.valueOf(batch.LTSRedrawUpdateBatch_Size__c) : 10;  
		Id batchprocessid = Database.executebatch(obj,size);
        return batchprocessid;
        
    }

}