force-app/main/default/objects/Batch_Job_Size__c/Batch_Job_Size__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Batch Job Size</label>
</CustomObject>

force-app/main/default/objects/Batch_Job_Size__c/fields/LTSChargeUpdateBatch__c.field-meta.xml
<CustomField>
    <fullName>LTSChargeUpdateBatch__c</fullName>
    <label>LTSChargeUpdateBatch</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LTSChargeUpdateBatchExecution.cls
/****************************************************************************************************
Company: Cloudkaptan Consultancy Services Pvt. Ltd.
Author: Ariz Mazhary
Description : This class is to run the LTSChargeUpdateBatch batch job 
                from 'Update LTS Charge ' custom button.
Development Date : 30/12/2021
Last Modified Date : 30/12/2021
****************************************************************************************************/

global with sharing class LTSChargeUpdateBatchExecution {
    Webservice static string executeLTSRedrawUpdateBatchWS(){

        Batch_Job_Size__c batch=Batch_Job_Size__c.getInstance();
        LTSChargeUpdateBatch obj = new LTSChargeUpdateBatch();
        Integer size = batch.LTSChargeUpdateBatch__c != NULL ? Integer.valueOf(batch.LTSChargeUpdateBatch__c) : 10;  
        Id batchprocessid = Database.executebatch(obj,size);
        return batchprocessid;
        
    }
}