force-app/main/default/objects/Batch_Job_Size__c/Batch_Job_Size__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Batch Job Size</label>
</CustomObject>

force-app/main/default/objects/Batch_Job_Size__c/fields/LoanCollateralUpdateBatch_Size__c.field-meta.xml
<CustomField>
    <fullName>LoanCollateralUpdateBatch_Size__c</fullName>
    <label>LoanCollateralUpdateBatch_Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LoanCollateralUpdateBatchExecution.cls
/****************************************************************************************************
Company: Cloudkaptan Consultancy Services Pvt. Ltd.
Author: Ariz Mazhary
Description : This class is to run the LoanCollateralUpdateBatch batch job 
                from 'Update Securities Detail' custom button.
Development Date : 14/02/2022
Last Modified Date : 24/02/2022
****************************************************************************************************/

global with sharing class LoanCollateralUpdateBatchExecution {
	Webservice static string executeLoanCollateralUpdateBatchWS(){

        Batch_Job_Size__c batchJobSize=Batch_Job_Size__c.getInstance();
        LoanCollateralUpdateBatch objLoanCollateral = new LoanCollateralUpdateBatch();
        Integer size = batchJobSize.LoanCollateralUpdateBatch_Size__c != NULL ? Integer.valueOf(batchJobSize.LoanCollateralUpdateBatch_Size__c) : 10;
		Id batchprocessid = Database.executebatch(objLoanCollateral,size);
        return batchprocessid;
        
    }
}