force-app/main/default/objects/Batch_Job_Size__c/Batch_Job_Size__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Batch Job Size</label>
</CustomObject>

force-app/main/default/objects/Batch_Job_Size__c/fields/ContentDocumentLinkVisibility_Size__c.field-meta.xml
<CustomField>
    <fullName>ContentDocumentLinkVisibility_Size__c</fullName>
    <label>ContentDocumentLinkVisibility_Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <customHelpPage>loan__CLContractHelp</customHelpPage>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Account__c/fields/Conga_Batch_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Conga_Batch_End_Date__c</fullName>
    <formula>IF($User.loan__Current_Branch_s_System_Date__c &gt; loan__Disbursal_Date__c , IF((MONTH($User.loan__Current_Branch_s_System_Date__c)&gt;=1 &amp;&amp; MONTH($User.loan__Current_Branch_s_System_Date__c)&lt;=6) &amp;&amp; YEAR($User.loan__Current_Branch_s_System_Date__c) &gt; YEAR(loan__Disbursal_Date__c ) , DATE( YEAR($User.loan__Current_Branch_s_System_Date__c)-1 ,12,31) , IF((MONTH($User.loan__Current_Branch_s_System_Date__c)&gt;=7 &amp;&amp; MONTH($User.loan__Current_Branch_s_System_Date__c)&lt;=12), DATE( YEAR($User.loan__Current_Branch_s_System_Date__c) ,6,30), $User.loan__Current_Branch_s_System_Date__c)),$User.loan__Current_Branch_s_System_Date__c)</formula>
    <label>Conga Batch End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Conga_Batch_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Conga_Batch_Start_Date__c</fullName>
    <formula>IF($User.loan__Current_Branch_s_System_Date__c &gt;  loan__Disbursal_Date__c , IF((MONTH($User.loan__Current_Branch_s_System_Date__c)&gt;=1  &amp;&amp; MONTH($User.loan__Current_Branch_s_System_Date__c)&lt;=6)  &amp;&amp;  YEAR($User.loan__Current_Branch_s_System_Date__c)  &gt;  YEAR(loan__Disbursal_Date__c ) ,  IF((MONTH(loan__Disbursal_Date__c )&gt;=7  &amp;&amp; MONTH(loan__Disbursal_Date__c )&lt;=12  &amp;&amp; YEAR($User.loan__Current_Branch_s_System_Date__c)   =   YEAR(loan__Disbursal_Date__c )+1),loan__Disbursal_Date__c, DATE( YEAR($User.loan__Current_Branch_s_System_Date__c)-1 ,7,1)) ,  IF((MONTH($User.loan__Current_Branch_s_System_Date__c)&gt;=7  &amp;&amp; MONTH($User.loan__Current_Branch_s_System_Date__c)&lt;=12),  IF((MONTH(loan__Disbursal_Date__c )&gt;=1  &amp;&amp; MONTH(loan__Disbursal_Date__c )&lt;=6  &amp;&amp; YEAR($User.loan__Current_Branch_s_System_Date__c)   =   YEAR(loan__Disbursal_Date__c )),loan__Disbursal_Date__c , DATE( YEAR($User.loan__Current_Branch_s_System_Date__c) ,1,1)) , $User.loan__Current_Branch_s_System_Date__c)),$User.loan__Current_Branch_s_System_Date__c)</formula>
    <label>Conga Batch Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Loan_Status__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Status__c</fullName>
    <inlineHelpText>Status of the Account expected values are :
Pending Approval
Active - Good Standing
Active - Bad Standing
Active - Matured
Approved
Canceled
Closed - Obligations met
Closed- Written Off
Closed - Refinanced
Partial Application
Closed - Premature</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active - Bad Standing</fullName>
            </value>
            <value>
                <fullName>Active - Good Standing</fullName>
            </value>
            <value>
                <fullName>Active - Marked for Closure</fullName>
            </value>
            <value>
                <fullName>Active - Matured</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Closed - Obligations met</fullName>
            </value>
            <value>
                <fullName>Closed - Premature</fullName>
            </value>
            <value>
                <fullName>Closed - Refinanced</fullName>
            </value>
            <value>
                <fullName>Closed- Written Off</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>Partial Application</fullName>
                <default>true</default>
                <label>Partial Application</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Premature Closure Initiated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Statement_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Statement_End_Date__c</fullName>
    <label>Statement End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Statement_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Statement_Start_Date__c</fullName>
    <label>Statement Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ContentDocumentLinkVisibilityUpdateBatch.cls
/****************************************************************************************************
Company: Cloudkaptan Consultancy Services Pvt. Ltd.
Author: Ariz Mazhary
Description : This batch class query all Active Loans and update the document visibility to AllUsers.
Development Date : 01/12/2021
Last Modified Date : 09/12/2021
****************************************************************************************************/

public class ContentDocumentLinkVisibilityUpdateBatch implements DataBase.StateFul,DataBase.Batchable<sObject>,Schedulable{
    List<String> loanStatusList=System.label.Active_CL_Contract_Status.split(',');
	//Query all Active Cl Contract  
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([SELECT Id,
                                                 Name, 
                                                 Statement_Start_Date__c,
                                                 Statement_End_Date__c,
                                                 Conga_Batch_Start_Date__c,
                                                 Conga_Batch_End_Date__c
                                         FROM loan__Loan_Account__c 
                                         WHERE loan__Loan_Status__c in: loanStatusList]);
    }
    
    public void execute(Database.BatchableContext bc, List<loan__Loan_Account__c> objLoanList) {
        try{
            Set<Id> newSet = new Set<Id>();
            for(loan__Loan_Account__c loanAccount:objLoanList){
                newSet.add(loanAccount.id);
            }
            List <ContentDocumentLink> contentDocumentLinkList = [SELECT Id,
                                                                        ContentDocument.Title,
                                                                        ContentDocumentId,
                                                                        ContentDocument.CreatedDate,
                                                                  		Visibility,
                                                                  		shareType
                                                                  FROM ContentDocumentLink
                                                                  WHERE LinkedEntityId IN: newSet
                                                                  AND (Visibility !=: ConstantValues.ALLUSERS
                                                                  OR shareType!=:ConstantValues.SHARE_TYPE_V)];
            for(ContentDocumentLink objcontentDocument:contentDocumentLinkList){
                if((objcontentDocument.ContentDocument.Title).startsWith(ConstantValues.HALF_YEARLY_STATEMENT)){
					objcontentDocument.Visibility =ConstantValues.ALLUSERS;
					objcontentDocument.shareType = ConstantValues.SHARE_TYPE_V;                    
                }
            }
            if(contentDocumentLinkList.size()>0){
                update contentDocumentLinkList;
            }           
        }catch(Exception exe){
            insert new clcommon__Batch_Process_Log__c(
                clcommon__Message__c = 'ContentDocumentLinkVisibilityUpdateBatch :Exception: '+exe.getStackTraceString()
                                        +'error='+exe.getMessage()+' at Line Number '+exe.getLineNumber(),
                clcommon__Timestamp__c = System.Now());
        }
    }
    public void execute(SchedulableContext sc) {
        Batch_Job_Size__c batch=Batch_Job_Size__c.getInstance();
        ContentDocumentLinkVisibilityUpdateBatch obj = new ContentDocumentLinkVisibilityUpdateBatch();
        Integer size = batch.ContentDocumentLinkVisibility_Size__c != NULL ? Integer.valueOf(batch.ContentDocumentLinkVisibility_Size__c) : 10;  
        database.executebatch(obj,size);
    }
    public void finish(Database.BatchableContext bc){
        
        AsyncApexJob a = [SELECT Id, 
                                Status,
                                ExtendedStatus,
                                NumberOfErrors,
                                JobItemsProcessed,
                                TotalJobItems, 
                                CreatedBy.Email
                            FROM AsyncApexJob 
                            WHERE Id =:bc.getJobId()];
        if(a!=null){

            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            String[] toAddresses = new String[] {a.CreatedBy.Email};
            mail.setToAddresses(toAddresses);
            mail.setSubject(ConstantValues.MAIL_SUBJECT + a.Status);
            if(a.Status == ConstantValues.COMPLETED){
                mail.setPlainTextBody(ConstantValues.MAIL_BODY_COMPLETED);
            }else{
                mail.setPlainTextBody(ConstantValues.MAIL_BODY + a.TotalJobItems +'with '+ a.NumberOfErrors + ' failures.');
            }
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
            
        }
    }
}