force-app/main/default/objects/Batch_Job_Size__c/Batch_Job_Size__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Batch Job Size</label>
</CustomObject>

force-app/main/default/objects/Batch_Job_Size__c/fields/InterestRateChangeBatch_Job_Size__c.field-meta.xml
<CustomField>
    <fullName>InterestRateChangeBatch_Job_Size__c</fullName>
    <label>InterestRateChangeBatch Job Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <customHelpPage>loan__CLContractHelp</customHelpPage>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Account__c/fields/Calculated_Upcoming_Repayment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Calculated_Upcoming_Repayment_Amount__c</fullName>
    <formula>IF( !ISBLANK(New_Interest_Rate__c) &amp;&amp; !ISBLANK( New_Interest_Rate_Effective_Date__c) &amp;&amp; ISPICKVAL(Repayment_Type__c , &apos;Principal and Interest&apos;),((New_Interest_Rate__c /12)*((1+( New_Interest_Rate__c /12))^ Remaining_Loan_Term__c ))/((1+(New_Interest_Rate__c/12))^ Remaining_Loan_Term__c -1)* loan__Loan_Balance__c,0.0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Calculated Upcoming Repayment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/First_Repayment_Date_After_IR_Change__c.field-meta.xml
<CustomField>
    <fullName>First_Repayment_Date_After_IR_Change__c</fullName>
    <label>First Repayment Date After IR Change</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Interest_Rate_Change_Notification_Date__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate_Change_Notification_Date__c</fullName>
    <label>Interest Rate Change Notification Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Delinquent_Amount__c.field-meta.xml
<CustomField>
    <fullName>loan__Delinquent_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Total Unpaid bills/invoices amount on this account.</inlineHelpText>
    <label>Delinquent Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Due_Day__c.field-meta.xml
<CustomField>
    <fullName>loan__Due_Day__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Due Day for the loan account.</description>
    <inlineHelpText>The day on which the loan payment is due.</inlineHelpText>
    <label>Current Due Day</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Frequency_of_Loan_Payment__c.field-meta.xml
<CustomField>
    <fullName>loan__Frequency_of_Loan_Payment__c</fullName>
    <inlineHelpText>This decides the Payment Frequency, below are the supported ones:
Daily
Weekly
Bi-weekly
Semi-Monthly
Monthly
Bi-Monthly
Quarterly
Semi-Annual
Annual
Single-Payment</inlineHelpText>
    <label>Payment Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Bi-weekly</fullName>
            </value>
            <value>
                <fullName>Semi-Monthly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
                <default>true</default>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Semi-Annual</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Single-Payment</fullName>
            </value>
            <value>
                <fullName>Semi-Monthly-PD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

elixir/force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>loan__Interest_Rate__c</fullName>
    <description>Interest Rate</description>
    <inlineHelpText>Rate of Interest for the loan.</inlineHelpText>
    <label>Current Interest Rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Invalid_Data__c.field-meta.xml
<CustomField>
    <fullName>loan__Invalid_Data__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If system identify any data issues with this lending account, the reasons will be displayed on the top of lending account and this flag will be checked.
Once the issues are fixed, this flag will be unchecked by system.
User should not modify this flag.</inlineHelpText>
    <label>Invalid Data</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Loan_Status__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Status__c</fullName>
    <inlineHelpText>Status of the Account expected values are :
Pending Approval
Active - Good Standing
Active - Bad Standing
Active - Matured
Approved
Canceled
Closed - Obligations met
Closed- Written Off
Closed - Refinanced
Partial Application
Closed - Premature</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active - Bad Standing</fullName>
            </value>
            <value>
                <fullName>Active - Good Standing</fullName>
            </value>
            <value>
                <fullName>Active - Marked for Closure</fullName>
            </value>
            <value>
                <fullName>Active - Matured</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Closed - Obligations met</fullName>
            </value>
            <value>
                <fullName>Closed - Premature</fullName>
            </value>
            <value>
                <fullName>Closed - Refinanced</fullName>
            </value>
            <value>
                <fullName>Closed- Written Off</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>Partial Application</fullName>
                <default>true</default>
                <label>Partial Application</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Premature Closure Initiated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

elixir/force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Maturity_Date_Current__c.field-meta.xml
<CustomField>
    <fullName>loan__Maturity_Date_Current__c</fullName>
    <inlineHelpText>This is the date on which the the loan matures</inlineHelpText>
    <label>Current Maturity Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Pmt_Amt_Cur__c.field-meta.xml
<CustomField>
    <fullName>loan__Pmt_Amt_Cur__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Current Payment Amount</description>
    <inlineHelpText>This is the current installment amount that needs to be paid.</inlineHelpText>
    <label>Current Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

elixir/force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Uncleared_Repayment_Amount__c.field-meta.xml
<CustomField>
    <fullName>loan__Uncleared_Repayment_Amount__c</fullName>
    <description>The repaid amount, which has not yet been supervised.</description>
    <inlineHelpText>The reapaid amount, which has not yet been supervised.</inlineHelpText>
    <label>Uncleared Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/New_Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>New_Interest_Rate__c</fullName>
    <label>New Interest Rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/New_Interest_Rate_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>New_Interest_Rate_Effective_Date__c</fullName>
    <label>New Interest Rate Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Remaining_IO_Period__c.field-meta.xml
<CustomField>
    <fullName>Remaining_IO_Period__c</fullName>
    <label>Remaining IO Period</label>
    <summaryFilterItems>
        <field>loan__Repayment_Schedule__c.loan__Is_Archived__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>loan__Repayment_Schedule__c.loan__Due_Principal__c</field>
        <operation>equals</operation>
        <value>0</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>loan__Repayment_Schedule__c.loan__Is_Billed__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryForeignKey>loan__Repayment_Schedule__c.loan__Loan_Account__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Remaining_Loan_Term__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Loan_Term__c</fullName>
    <formula>MONTH(loan__Maturity_Date_Current__c) + 12 - MONTH($User.loan__Current_Branch_s_System_Date__c)+12*(YEAR(loan__Maturity_Date_Current__c)-YEAR($User.loan__Current_Branch_s_System_Date__c)-1)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remaining Loan Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Remaining_Term_from_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Term_from_Schedule__c</fullName>
    <label>Remaining Term from Schedule</label>
    <summaryFilterItems>
        <field>loan__Repayment_Schedule__c.loan__Is_Billed__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>loan__Repayment_Schedule__c.loan__Is_Archived__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryForeignKey>loan__Repayment_Schedule__c.loan__Loan_Account__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Repayment_Type__c.field-meta.xml
<CustomField>
    <fullName>Repayment_Type__c</fullName>
    <label>Repayment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Principal and Interest</fullName>
            </value>
            <value>
                <fullName>Interest Only reverting to Principal and Interest</fullName>
            </value>
            <value>
                <fullName>Interest Only</fullName>
            </value>
            <value>
                <fullName>Prepaid Interest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Second_Repayment_Date_After_IR_Change__c.field-meta.xml
<CustomField>
    <fullName>Second_Repayment_Date_After_IR_Change__c</fullName>
    <label>Second Repayment Date After IR Change</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/InterestRateChangeBatch.cls
/****************************************************************************************************
Company : CloudKaptan Consultancy Services Pvt. Ltd.
Developer : Rameswari Barman
Development Date : 18/04/2022
Last Modified By : Rameswari Barman
Last Modified Date : 18/04/2022
Description : This batch calls and is used to update interest rates of LAIs at bulk 
                where new interest rate vaue is present in LAIs and the interest effective rate 
                is equal to current system date
****************************************************************************************************/

global class InterestRateChangeBatch extends clcommon.DynamicJob {

    global InterestRateChangeBatch(){
        //BLANK CONSTRUCTOR
    } 
    
    global override String getRuntimeQuery() {
        String currentSystemDate = ((DateTime) (!Test.isRunningTest()?(new loan.GlobalLoanUtilFacade()).getCurrentSystemDate().addDays(0): Date.Today())).format('yyyy-MM-dd');
        List<String> params = new List<String>{
            currentSystemDate
        };
        String queryString =                   'SELECT Id, '+
                                               'Name, '+
                                               'New_Interest_Rate__c, '+
                                               'New_Interest_Rate_Effective_Date__c, '+
                                               'loan__Next_Installment_Date__c, '+
                                               'Calculated_Upcoming_Repayment_Amount__c, '+
                                               'loan__Interest_Rate__c, '+
                                               'Repayment_Type__c, '+
                                               'Remaining_Loan_Term__c, '+
                                               'Remaining_Term_from_Schedule__c, '+
                                               'Remaining_IO_Period__c, '+
                                               'loan__Due_Day__c, '+
                                               'loan__Frequency_of_Loan_Payment__c, '+
                                               'Interest_Rate_Change_Notification_Date__c, '+
                                               'First_Repayment_Date_After_IR_Change__c, '+
                                               'Second_Repayment_Date_After_IR_Change__c, '+
                                               'loan__Pmt_Amt_Cur__c, '+
                                               'loan__Uncleared_Repayment_Amount__c, '+
                                               'loan__Loan_Status__c, '+
                                               'loan__Delinquent_Amount__c, '+
                                               'loan__Maturity_Date_Current__c, '+
                                               'loan__Previous_Installment_Date__c '+
                                           'FROM loan__Loan_Account__c '+
                                           'WHERE New_Interest_Rate__c != NULL '+
                                           'AND New_Interest_Rate_Effective_Date__c <= {0}'+
                                           'AND loan__Interest_Type__c = \'FIXED\' '+
                                           'AND loan__Invalid_Data__c = FALSE '+
                                           'AND loan__Loan_Status__c IN (\'Active - Good Standing\',\'Active - Bad Standing\',\'Active - Marked for Closure\') '+
                                           'AND (loan__Uncleared_Repayment_Amount__c = 0 '+
                                           'OR loan__Uncleared_Repayment_Amount__c = NULL)'+
                                           'AND loan__Floating_Rate_Index__c = NULL '+
                                           'AND First_Repayment_Date_After_IR_Change__c != NULL '+
                                           'AND Interest_Rate_Change_Notification_Date__c != NULL '+
                                           'AND Remaining_Term_from_Schedule__c > 0';
        String formattedString = String.format(queryString, params);
        return formattedString;
    }
    
    global override void doStart(Database.BatchableContext bc) {}

    global override void doExecute(System.SchedulableContext sc) {
        InterestRateChangeBatch obj = new InterestRateChangeBatch();
        Batch_Job_Size__c batch=Batch_Job_Size__c.getInstance();
        Integer size = batch.InterestRateChangeBatch_Job_Size__c != NULL ? Integer.valueOf(batch.InterestRateChangeBatch_Job_Size__c) : 1;  
        database.executebatch(obj,size);
    }
    public override void doexecute(Database.BatchableContext bc, List<Sobject> loanList) {
        try{
            List <loan__Loan_Account__c> objLoanList = loanList;
            InterestRateChangeHandler.updateRate(objLoanList);
        }catch(Exception exe){
            GenericUtility.insertBatchProcessLog('InterestRateChangeBatch',exe);
        }
    }
    global override void doInitialize() {}
  
    global override void doFinish(Database.BatchableContext bc) {}
}