force-app/main/default/objects/Application_Platform_Event__e/Application_Platform_Event__e.object-meta.xml
<CustomObject>
    <label>Application Platform Event</label>
    <pluralLabel>Application Platform Event</pluralLabel>
</CustomObject>

force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Applications__c/fields/Check_Status_Change__c.field-meta.xml
<CustomField>
    <fullName>Check_Status_Change__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Check Status  Change</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Status__c.field-meta.xml
<CustomField>
    <fullName>genesis__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>App Received</fullName>
                <default>true</default>
                <label>App Received</label>
            </value>
            <value>
                <fullName>App Processed</fullName>
            </value>
            <value>
                <fullName>Conditional Assessed</fullName>
            </value>
            <value>
                <fullName>Conditionally Approved</fullName>
            </value>
            <value>
                <fullName>Conditional Accepted</fullName>
            </value>
            <value>
                <fullName>Assessment in Progress</fullName>
            </value>
            <value>
                <fullName>Recommended</fullName>
            </value>
            <value>
                <fullName>Formally Approved</fullName>
            </value>
            <value>
                <fullName>Solicitor Instructed</fullName>
            </value>
            <value>
                <fullName>LOO Issued</fullName>
            </value>
            <value>
                <fullName>LOO Accepted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Approved - Converted to Contract</fullName>
            </value>
            <value>
                <fullName>Loan Settled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NextGenApplicationPlatformEvent.cls
/****************************************************************************************************
Company: Cloudkaptan Consultancy Services Pvt. Ltd.
Author: Ariz Mazhary
Description : This class publish platform event when Application status changes.
Development Date : 09/05/2022
Last Modified Date : 18/05/2022

****************************************************************************************************/

public class NextGenApplicationPlatformEvent {
@InvocableMethod(
    label='Publish Platform Event'
    description='Publish Application Platform Event'
    )
    public static void publishApplicationPlatformEvent(List<Id> appIdList){
        try{
            List<genesis__Applications__c> applicationList=[SELECT id,
                                                                genesis__Status__c,
                                                                Check_Status_Change__c 
                                                            FROM genesis__Applications__c 
                                                            WHERE id in: appIdList];
            List<Application_Platform_Event__e> applicationEventList=new List<Application_Platform_Event__e>();
            for(genesis__Applications__c application : applicationList){
                applicationEventList.add(new Application_Platform_Event__e(Application_Id__c=application.id,Status__c=application.genesis__Status__c));
                application.Check_Status_Change__c=false; 
                
            }
            if(applicationList.size()>0){
                Database.update(applicationList,false);
            }
            List<Database.SaveResult> results = EventBus.publish(applicationEventList);
        }catch(Exception exe){
            GenericUtility.insertLog('NextGenApplicationPlatformEvent', exe);
        }
    }

}