force-app/main/default/objects/Application_Platform_Event__e/Application_Platform_Event__e.object-meta.xml
<CustomObject>
    <label>Application Platform Event</label>
    <pluralLabel>Application Platform Event</pluralLabel>
</CustomObject>

force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Applications__c/fields/Check_Status_Change__c.field-meta.xml
<CustomField>
    <fullName>Check_Status_Change__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Check Status  Change</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/Solicitor_Status__c.field-meta.xml
<CustomField>
    <fullName>Solicitor_Status__c</fullName>
    <description>RJohnston 23/5/22 - https://wingategroup.atlassian.net/jira/software/c/projects/AMS/boards/8?modal=detail&amp;selectedIssue=AMS-1237
For recording where the settlement process is with the solicitor</description>
    <label>Solicitor Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Instructions Received</fullName>
            </value>
            <value>
                <fullName>Matter On Hold</fullName>
            </value>
            <value>
                <fullName>File in Doc Prep QA</fullName>
            </value>
            <value>
                <fullName>Docs Sent</fullName>
            </value>
            <value>
                <fullName>Docs Returned</fullName>
            </value>
            <value>
                <fullName>Outstanding Requirements</fullName>
            </value>
            <value>
                <fullName>Docs Verified</fullName>
            </value>
            <value>
                <fullName>File in Settlement QA</fullName>
            </value>
            <value>
                <fullName>Ready to Book</fullName>
            </value>
            <value>
                <fullName>Settlement Booked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NextGenApplicationSolicitorStatusChange.cls
/****************************************************************************************************
Company: Cloudkaptan Consultancy Services Pvt. Ltd.
Author: Ariz Mazhary
Description : This class publish platform event when Application Solicitor Status changes.
Development Date : 09/05/2022
Last Modified Date : 18/05/2022

****************************************************************************************************/
public class NextGenApplicationSolicitorStatusChange {
@InvocableMethod(
    label='Publish Platform Event When Solicitor Status Change'
    description='Publish Application Platform Event When Solicitor Status Change'
    )
    public static void publishApplicationPlatformEvent(List<Id> appIdList){
        try{
            List<genesis__Applications__c> applicationList=[SELECT id,
                                                                Solicitor_Status__c,
                                                                Check_Status_Change__c 
                                                                FROM genesis__Applications__c 
                                                                WHERE id in: appIdList];
            List<Application_Platform_Event__e> applicationEventList=new List<Application_Platform_Event__e>();
            for(genesis__Applications__c application : applicationList){
                applicationEventList.add(new Application_Platform_Event__e(Application_Id__c=application.id,
                                            Status__c=application.Solicitor_Status__c));
                application.Check_Status_Change__c=true; 
            }
            if(applicationList.size()>0){
                Database.update(applicationList,false);
            }
            List<Database.SaveResult> results = EventBus.publish(applicationEventList);
            System.debug(results);
        }catch(Exception objException){
            GenericUtility.insertLog('NextGenApplicationPlatformEvent', objException);
        }
    }
}