force-app/main/default/objects/Checklist_Detail__c/Checklist_Detail__c.object-meta.xml
<CustomObject>
    <label>Checklist Detail</label>
    <nameField>
        <label>Checklist Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Checklist Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Checklist_Detail__c/fields/Checklist__c.field-meta.xml
<CustomField>
    <fullName>Checklist__c</fullName>
    <label>Checklist</label>
    <referenceTo>genesis__Checklist__c</referenceTo>
    <relationshipLabel>Checklist Details</relationshipLabel>
    <relationshipName>Checklist_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Checklist_Detail__c/fields/Employment_Information__c.field-meta.xml
<CustomField>
    <fullName>Employment_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employment Information</label>
    <referenceTo>genesis__Employment_Information__c</referenceTo>
    <relationshipLabel>Checklist Details</relationshipLabel>
    <relationshipName>Checklist_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Checklist_Detail__c/fields/Income__c.field-meta.xml
<CustomField>
    <fullName>Income__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Income</label>
    <referenceTo>genesis__Income__c</referenceTo>
    <relationshipLabel>Checklist Details</relationshipLabel>
    <relationshipName>Checklist_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Exit_Strategy_Provided__c.field-meta.xml
<CustomField>
    <fullName>Exit_Strategy_Provided__c</fullName>
    <label>Exit Strategy Provided</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>YesNo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Exit_Strategy_Suitable__c.field-meta.xml
<CustomField>
    <fullName>Exit_Strategy_Suitable__c</fullName>
    <label>Exit Strategy Suitable</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>YesNo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Exit_Strategy_Suitable_Rule_Check__c.field-meta.xml
<CustomField>
    <fullName>Exit_Strategy_Suitable_Rule_Check__c</fullName>
    <description>Exit Strategy Suitable Rule Check</description>
    <formula>IF(IF(ISNULL(Birthdate),true,IF(ISPICKVAL(Exit_Strategy_Suitable__c,&apos;&apos;),true,false)),true,false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Exit Strategy Suitable Rule Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

elixir/force-app/main/default/objects/genesis__Applications__c/fields/Actual_LVR__c.field-meta.xml
<CustomField>
    <fullName>Actual_LVR__c</fullName>
    <formula>genesis__Loan_Amount__c /  Actual_Security_Value__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Actual_LVR</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/Cash_Out_Purpose_Suitable__c.field-meta.xml
<CustomField>
    <fullName>Cash_Out_Purpose_Suitable__c</fullName>
    <label>Cash Out Purpose Suitable</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>YesNo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/Cash_Out_Purpose_Suitable_Rule_Check__c.field-meta.xml
<CustomField>
    <fullName>Cash_Out_Purpose_Suitable_Rule_Check__c</fullName>
    <description>Cash Out Purpose Suitable Rule Check</description>
    <formula>IF(IF(NOT(INCLUDES(Refinance_purpose_list__c,&apos;Refinance - Cash Out&apos;)),true,IF(ISPICKVAL(Cash_Out_Purpose_Suitable__c,&apos;&apos;),true,false)),true,false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cash Out Purpose Suitable Rule Check</label>
    <type>Checkbox</type>
</CustomField>

elixir/force-app/main/default/objects/genesis__Applications__c/fields/Commission_Mandate__c.field-meta.xml
<CustomField>
    <fullName>Commission_Mandate__c</fullName>
    <label>Commission Mandate</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/Commission_Mandate_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Commission_Mandate_Percentage__c</fullName>
    <formula>(Commission_Mandate_Amount__c/genesis__Loan_Amount__c)*100</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Commission Mandate Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/Commission_Mandate_Percentage_Rule_Check__c.field-meta.xml
<CustomField>
    <fullName>Commission_Mandate_Percentage_Rule_Check__c</fullName>
    <description>Commission Mandate Percentage Rule Check</description>
    <formula>IF(IF(OR((ISPICKVAL(Commission_Mandate__c,&apos;&apos;)),(ISPICKVAL(Commission_Mandate__c,&apos;No&apos;))),true,false),true,false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Commission Mandate Percentage Rule Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/Customer_Interview_completed__c.field-meta.xml
<CustomField>
    <fullName>Customer_Interview_completed__c</fullName>
    <label>Customer Interview completed</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>YesNo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/Customer_Interview_Completed_Rule_Check__c.field-meta.xml
<CustomField>
    <fullName>Customer_Interview_Completed_Rule_Check__c</fullName>
    <formula>IF(NOT(genesis__CL_Product_Name__c == &apos;SMSF Residential&apos; || genesis__CL_Product_Name__c == &apos;SMSF Commercial&apos; || ISPICKVAL(NCCP_status_list__c,&apos;Regulated&apos;)),&apos;Not Render&apos;,&apos;Render&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Interview Completed Rule Check</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full Doc</fullName>
            </value>
            <value>
                <fullName>Alt Doc</fullName>
            </value>
            <value>
                <fullName>Lease Doc</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/Exit_Strategy_Provided__c.field-meta.xml
<CustomField>
    <fullName>Exit_Strategy_Provided__c</fullName>
    <label>Exit Strategy Provided</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>YesNo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/Exit_Strategy_Suitable__c.field-meta.xml
<CustomField>
    <fullName>Exit_Strategy_Suitable__c</fullName>
    <label>Exit Strategy Suitable</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>YesNo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/Exit_Strategy_Suitable_Rule_Check__c.field-meta.xml
<CustomField>
    <fullName>Exit_Strategy_Suitable_Rule_Check__c</fullName>
    <description>Exit Strategy Suitable Rule Check</description>
    <formula>IF(NOT(ISPICKVAL(Repayment_Type__c,&apos;Interest Only&apos;)),true,false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Exit Strategy Suitable Rule Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/Lenders_Mortgage_Insurance__c.field-meta.xml
<CustomField>
    <fullName>Lenders_Mortgage_Insurance__c</fullName>
    <label>Lenders Mortgage Insurance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Elixir_Prod/force-app/main/default/objects/genesis__Applications__c/fields/NCCP_status_list__c.field-meta.xml
<CustomField>
    <fullName>NCCP_status_list__c</fullName>
    <label>NCCP status list</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Regulated</fullName>
            </value>
            <value>
                <fullName>Unregulated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/Repayment_Type__c.field-meta.xml
<CustomField>
    <fullName>Repayment_Type__c</fullName>
    <label>Repayment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Principal and Interest</fullName>
            </value>
            <value>
                <fullName>Interest Only reverting to Principal and Interest</fullName>
            </value>
            <value>
                <fullName>Interest Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Checklist__c/genesis__Checklist__c.object-meta.xml
<CustomObject>
    <label>Checklist</label>
    <nameField>
        <displayFormat>CLID-{0000000000}</displayFormat>
        <label>CheckList ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checklist</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Checklist__c/fields/genesis__Type__c.field-meta.xml
<CustomField>
    <fullName>genesis__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Business Rule</fullName>
            </value>
            <value>
                <fullName>Document</fullName>
            </value>
            <value>
                <fullName>Validation Rule</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Employment_Information__c/genesis__Employment_Information__c.object-meta.xml
<CustomObject>
    <label>Employment Information</label>
    <nameField>
        <label>Employment Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employment Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

elixir/force-app/main/default/objects/genesis__Employment_Information__c/fields/genesis__Application__c.field-meta.xml
<CustomField>
    <fullName>genesis__Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Employment Information</relationshipLabel>
    <relationshipName>Employment_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

elixir/force-app/main/default/objects/genesis__Employment_Information__c/fields/genesis__Contact__c.field-meta.xml
<CustomField>
    <fullName>genesis__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If this is null, it is for contact (borrower) of an application</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Employment Information</relationshipLabel>
    <relationshipName>Employment_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

elixir/force-app/main/default/objects/genesis__Employment_Information__c/fields/Previous_Employment__c.field-meta.xml
<CustomField>
    <fullName>Previous_Employment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Previous Employment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/genesis__Income__c/genesis__Income__c.object-meta.xml
<CustomObject>
    <description>This object will track the other income</description>
    <label>Income</label>
    <nameField>
        <label>Income Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incomes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

elixir/force-app/main/default/objects/genesis__Income__c/fields/Employment_Information__c.field-meta.xml
<CustomField>
    <fullName>Employment_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employment Information</label>
    <referenceTo>genesis__Employment_Information__c</referenceTo>
    <relationshipLabel>Incomes</relationshipLabel>
    <relationshipName>Incomes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Income__c/fields/genesis__Application__c.field-meta.xml
<CustomField>
    <fullName>genesis__Application__c</fullName>
    <description>Master-Detail relationship for income</description>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Incomes</relationshipLabel>
    <relationshipName>Incomes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CheckRules.cls
/**********************************************************************************************************************************************************
Company : CloudKaptan Consultancy Services Pvt. Ltd.
Developer : Koushik Mondal
Development Date : 29/07/2020
Last Modified By : Koushik Mondal
Last Modified Date : 29/07/2020
Description : This class query all the Rules and check the Rule Criteria for the Loan Application.
***********************************************************************************************************************************************************/

global with sharing class CheckRules {
    webService static String callCheckRulesWS(String applicationId, String tabName) {
        String returnValue = '';
        String applicationRecordId;
        List <String> rulesNameList = new List<String>();
        Savepoint sp = Database.setSavepoint();
        List<genesis__Checklist__c> checkList = new List<genesis__Checklist__c>();
        try {
            if (applicationId == null) {
                return (ConstantValues.CHECKRULES_APPLICATION_ID_NULL);
            }

            applicationRecordId = applicationId.substring(0,applicationId.length()-3);

            if(tabName == 'Loan Details'){
                rulesNameList.add('Cash Out Purpose Suitable Rule');
                rulesNameList.add('Commission Mandate Percentage Rule');
                rulesNameList.add('Interest Only Suitable Rule');
                rulesNameList.add('Exit Strategy Suitable Rule');
                rulesNameList.add('Lenders Mortgage Insurance Rule');
            }
            else if(tabName == 'Settlement'){
                rulesNameList.add('Customer Interview completed Rule');
            }
            else if(tabName == 'Securities'){
                rulesNameList.add('Distressed Asset Rule');
                rulesNameList.add('Check Val Value Rule');
            }
            else if(tabName == 'Individual Contact Details'){
                rulesNameList.add('Temporary Visa Suitability Rule');
                rulesNameList.add('ABN Status Explanation Suitable Rule');
                rulesNameList.add('Exit Strategy Suitable Rule (Contact)');
                rulesNameList.add('Borrower is a Staff Member Rule');
            }
            else if(tabName == 'Non Individual Contact Details'){
                rulesNameList.add('GST Suitable Rule');
            }
            else if(tabName == 'Credit History'){
                rulesNameList.add('Explanation of Credit Events Suitable Rule');
                rulesNameList.add('Explanation of Credit Enquiries Suitable Rule');
                rulesNameList.add('Explanation of Bankruptcy Suitable Rule');
                rulesNameList.add('Explanation of Age of Credit File Suitable Rule');
            }
            else if(tabName == 'Individual Employment Information'){
                rulesNameList.add('Confirm letter prepared by accountant Rule');
                rulesNameList.add('Confirm stated annual income Rule');
                rulesNameList.add('Accountant aware of any circumstances Rule');
                rulesNameList.add('Accountant Call Suitable Rule');
                rulesNameList.add('Employment Call Suitable Rule');
                rulesNameList.add('Income Consistent with Declaration Rule');
            }
            else if(tabName == 'Living Expense'){
                rulesNameList.add('Living Expense Explanation Suitable Rule');
                rulesNameList.add('Bank Statements Reviewed Rule');
            }
            else if(tabName == 'Company Income'){
                rulesNameList.add('Income Consistent with Declaration Rule');
                rulesNameList.add('Satisfactory Explanation Provided Rule');
                rulesNameList.add('Confirm letter prepared by accountant Rule');
                rulesNameList.add('Confirm stated annual income Rule');
                rulesNameList.add('Accountant aware of any circumstances Rule');
                rulesNameList.add('Accountant Call Suitable Rule');
            }
            Map<Id,genesis__Rule__c> mapRules = new Map<Id,genesis__Rule__c>([SELECT Id,
                                                                            Name
                                                                            FROM genesis__Rule__c
                                                                            WHERE genesis__Enabled__c = true
                                                                            AND Name =: rulesNameList]);


            genesis__Applications__c application = [SELECT  Id, 
                                                    Lenders_Mortgage_Insurance__c,
                                                    Actual_LVR__c,
                                                    Exit_Strategy_Suitable__c,
                                                    Exit_Strategy_Suitable_Rule_Check__c,
                                                    Exit_Strategy_Provided__c,
                                                    Repayment_Type__c,
                                                    Customer_Interview_Completed_Rule_Check__c,
                                                    Customer_Interview_completed__c,
                                                    genesis__CL_Product_Name__c,
                                                    NCCP_status_list__c,
                                                    Commission_Mandate_Percentage__c,
                                                    Commission_Mandate__c,
                                                    Commission_Mandate_Percentage_Rule_Check__c,
                                                    Cash_Out_Purpose_Suitable__c,
                                                    Cash_Out_Purpose_Suitable_Rule_Check__c
                                                    FROM genesis__Applications__c 
                                                    WHERE id = :applicationRecordId
                                                    LIMIT 1];                                                               
            If (application != null && mapRules != null) {                              
                if(Test.isRunningTest() == false){
                checkList = genesis.RulesAPI.evaluateRules(application, mapRules.values(), true, true);
                /*List<genesis__Checklist__c> archivedChecklistList = [SELECT Id 
                                                                  FROM genesis__Checklist__c 
                                                                  WHERE genesis__Application__c  =: applicationRecordId
                                                                  AND genesis__Is_Archived__c = TRUE];
                delete archivedChecklistList;*/
                }
                else{
                    
                    checkList = [Select Id,
                                        genesis__Application__c,
                                        genesis__Assessed_Record_Id__c,
                                        genesis__Is_Archived__c ,
                                        genesis__Level__c,
                                        genesis__Message__c,
                                        genesis__Rule__c,
                                        genesis__Rule__r.Name,
                                        genesis__Type__c
                                        From genesis__Checklist__c];
                }
                if(tabName != 'Loan Details' && tabName != 'Settlement'){
                    ChildChecklistAPI api = new ChildChecklistAPI();
                    List<Checklist_Detail__c> listOfDetail = api.processListOfChecklist(checkList, applicationRecordId);
                    
                    /*if(tabName == 'Individual Employment Information'){
                        for(Checklist_Detail__c eachCheckListDet : listOfDetail){
                            if((eachCheckListDet.Employment_Information__c != NULL
                            && 
                            && eachCheckListDet.Employment_Information__r.Previous_Employment__c == true
                            && (eachCheckListDet.Checklist__r.genesis__Rule__r.Name == 'Employment Call Suitable Rule')){
                                finalSet.add(eachCheckListDet);
                            }
                            if((eachCheckListDet.Income__c != NULL
                            && eachCheckListDet.Income__r.Document_Type__c == 'Alt')
                            && (eachCheckListDet.Checklist__r.genesis__Rule__r.Name == 'Confirm letter prepared by accountant Rule'
                            || eachCheckListDet.Checklist__r.genesis__Rule__r.Name == 'Confirm stated annual income Rule'
                            || eachCheckListDet.Checklist__r.genesis__Rule__r.Name == 'Accountant aware of any circumstances Rule'
                            || eachCheckListDet.Checklist__r.genesis__Rule__r.Name == 'Employment Call Suitable Rule')){
                                finalSet.add(eachCheckListDet);
                            }
                        }
                    }
                    if(tabName == 'Company Income'){
                        for(Checklist_Detail__c eachCheckListDet : listOfDetail){
                            if((eachCheckListDet.Income__c != NULL)
                            && eachCheckListDet.Income__r.Document_Type__c == 'Alt')
                            && (eachCheckListDet.Checklist__r.genesis__Rule__r.Name == 'Confirm letter prepared by accountant Rule'
                            || eachCheckListDet.Checklist__r.genesis__Rule__r.Name == 'Confirm stated annual income Rule'
                            || eachCheckListDet.Checklist__r.genesis__Rule__r.Name == 'Accountant aware of any circumstances Rule'
                            || eachCheckListDet.Checklist__r.genesis__Rule__r.Name == 'Employment Call Suitable Rule')){
                                finalSet.add(eachCheckListDet);
                            }
                        }
                    }
                    else{*/
                        Database.insert(listOfDetail);
                    //}
                }
            }

            returnValue = ConstantValues.Success;

        } 
        catch (Exception e) {
            Database.rollback(sp);
            returnValue = e.getMessage();
        }
      return returnValue;
    }
}