force-app/main/default/objects/Account/recordTypes/Borrower.recordType-meta.xml
<RecordType>
    <fullName>Borrower</fullName>
    <active>true</active>
    <label>Borrower</label>
</RecordType>

force-app/main/default/objects/clcommon__Party__c/clcommon__Party__c.object-meta.xml
<CustomObject>
    <label>Party</label>
    <nameField>
        <displayFormat>PAR-{00000000}</displayFormat>
        <label>Party Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/clcommon__Party__c/fields/clcommon__Account__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Parties</relationshipLabel>
    <relationshipName>Parties</relationshipName>
    <type>Lookup</type>
</CustomField>

elixir/force-app/main/default/objects/clcommon__Party__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full</fullName>
            </value>
            <value>
                <fullName>Alt</fullName>
            </value>
            <value>
                <fullName>Lease</fullName>
                <isActive>false</isActive>
                <label>Lease</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/genesis__Application__c.field-meta.xml
<CustomField>
    <fullName>genesis__Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Parties</relationshipLabel>
    <relationshipName>Parties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/LAS_Utility_Show_in_Capacity_Section__c.field-meta.xml
<CustomField>
    <fullName>LAS_Utility_Show_in_Capacity_Section__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LAS Utility Show in Capacity Section</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/Legal_Entity_Type__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Type__c</fullName>
    <formula>clcommon__Account__r.clcommon__Legal_Entity_Type__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Legal Entity Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/NewExisting__c.field-meta.xml
<CustomField>
    <fullName>NewExisting__c</fullName>
    <label>NewExisting</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Existing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/Override__c.field-meta.xml
<CustomField>
    <fullName>Override__c</fullName>
    <label>Override</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>YesNo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/Override_Amount__c.field-meta.xml
<CustomField>
    <fullName>Override_Amount__c</fullName>
    <label>Override Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/Party_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Party_Type_Name__c</fullName>
    <formula>clcommon__Type__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Party Type Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/genesis__Employment_Information__c/genesis__Employment_Information__c.object-meta.xml
<CustomObject>
    <label>Employment Information</label>
    <nameField>
        <label>Employment Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employment Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

elixir/force-app/main/default/objects/genesis__Employment_Information__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Document_Type_Set</valueSetName>
    </valueSet>
</CustomField>

elixir/force-app/main/default/objects/genesis__Employment_Information__c/fields/genesis__Application__c.field-meta.xml
<CustomField>
    <fullName>genesis__Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Employment Information</relationshipLabel>
    <relationshipName>Employment_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Employment_Information__c/fields/LAS_Utility_Override_Amt__c.field-meta.xml
<CustomField>
    <fullName>LAS_Utility_Override_Amt__c</fullName>
    <defaultValue>0</defaultValue>
    <label>LAS Utility Override Amt</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/genesis__Employment_Information__c/fields/LAS_Utility_Override_Amt_Rendered__c.field-meta.xml
<CustomField>
    <fullName>LAS_Utility_Override_Amt_Rendered__c</fullName>
    <defaultValue>&quot;No&quot;</defaultValue>
    <label>LAS Utility Override Amt Rendered</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/genesis__Employment_Information__c/fields/Override__c.field-meta.xml
<CustomField>
    <fullName>Override__c</fullName>
    <label>Override</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Employment_Information__c/fields/Override_Amount__c.field-meta.xml
<CustomField>
    <fullName>Override_Amount__c</fullName>
    <label>Override Amount</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

elixir/force-app/main/default/objects/genesis__Employment_Information__c/fields/Party__c.field-meta.xml
<CustomField>
    <fullName>Party__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Party</label>
    <referenceTo>clcommon__Party__c</referenceTo>
    <relationshipLabel>Employment Information</relationshipLabel>
    <relationshipName>Employment_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

elixir/force-app/main/default/objects/genesis__Employment_Information__c/fields/PAYG_Income__c.field-meta.xml
<CustomField>
    <fullName>PAYG_Income__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PAYG Income</label>
    <type>Checkbox</type>
</CustomField>

elixir/force-app/main/default/objects/genesis__Employment_Information__c/fields/Previous_Employment__c.field-meta.xml
<CustomField>
    <fullName>Previous_Employment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Previous Employment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/genesis__Employment_Information__c/recordTypes/Self_Employed.recordType-meta.xml
<RecordType>
    <fullName>Self_Employed</fullName>
    <active>true</active>
    <label>Self Employed</label>
</RecordType>

force-app/main/default/objects/genesis__Income__c/genesis__Income__c.object-meta.xml
<CustomObject>
    <description>This object will track the other income</description>
    <label>Income</label>
    <nameField>
        <label>Income Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incomes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Income__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full</fullName>
            </value>
            <value>
                <fullName>Alt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

elixir/force-app/main/default/objects/genesis__Income__c/fields/Employment_Information__c.field-meta.xml
<CustomField>
    <fullName>Employment_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employment Information</label>
    <referenceTo>genesis__Employment_Information__c</referenceTo>
    <relationshipLabel>Incomes</relationshipLabel>
    <relationshipName>Incomes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Income__c/fields/genesis__Application__c.field-meta.xml
<CustomField>
    <fullName>genesis__Application__c</fullName>
    <description>Master-Detail relationship for income</description>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Incomes</relationshipLabel>
    <relationshipName>Incomes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

elixir/force-app/main/default/objects/genesis__Income__c/fields/Income_Alt__c.field-meta.xml
<CustomField>
    <fullName>Income_Alt__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Income Alt</label>
    <type>Checkbox</type>
</CustomField>

Elixir_Prod/force-app/main/default/objects/genesis__Income__c/fields/Party__c.field-meta.xml
<CustomField>
    <fullName>Party__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Party</label>
    <referenceTo>clcommon__Party__c</referenceTo>
    <relationshipLabel>Incomes</relationshipLabel>
    <relationshipName>Incomes</relationshipName>
    <type>Lookup</type>
</CustomField>

elixir/force-app/main/default/globalValueSets/Document_Type_Set.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Full</fullName>
    </customValue>
    <customValue>
        <fullName>Alt</fullName>
    </customValue>
    <masterLabel>Document Type Set</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LASDocumentHelper.cls
/****************************************************************************************************/
/* Company              : Cloudkaptan Consultancy Services Pvt. Ltd. */
/* Class Name           : LASDocumentHelper */
/* Created Date         : 15/03/2021 */
/* Developed By         : Rameswari Barman */
/* Description          : */
/* Last Modified Date   : 25/03/2021 */
/* Last Modified By     : Rameswari Barman */
/****************************************************************************************************/

global with sharing class LASDocumentHelper{
    Webservice static String updateValues(Id appId){
        try{
            if(String.isBlank(appId)){
                return null;
            }
            List <clcommon__Party__c> borrowerPartyList = [SELECT Id,
                                                            clcommon__Account__c,
                                                            clcommon__Account__r.Name,
                                                            NewExisting__c
                                                            FROM clcommon__Party__c 
                                                            WHERE genesis__Application__c =: appId
                                                            AND Party_Type_Name__c in (:ConstantValues.GUARANTOR,:ConstantValues.CO_APPLICANT,:ConstantValues.BORROWER)
                                                          ];
            if(borrowerPartyList.size() > 0 == false){
                return null;
            }
            List <Id> accountIds = new List<Id>();
            for(clcommon__Party__c eachParty : borrowerPartyList){
                accountIds.add(eachParty.clcommon__Account__c);
            }
            List <clcommon__Party__c> allBorrowerPartyList = [SELECT Id,
                                                                clcommon__Account__c,
                                                                clcommon__Account__r.Name
                                                                FROM clcommon__Party__c 
                                                                WHERE Party_Type_Name__c in (:ConstantValues.GUARANTOR,:ConstantValues.CO_APPLICANT,:ConstantValues.BORROWER)
                                                                AND genesis__Application__c NOT IN (:appId)
                                                                AND genesis__Application__c != NULL
                                                                AND clcommon__Account__c =: accountIds
                                                            ];
            for(clcommon__Party__c eachParty : borrowerPartyList){
                eachParty.NewExisting__c = ConstantValues.NEW_TAG;
                for(clcommon__Party__c eachRemainingParty : allBorrowerPartyList){
                    if(eachParty.clcommon__Account__c == eachRemainingParty.clcommon__Account__c){
                        eachParty.NewExisting__c = ConstantValues.EXISTING_TAG;
                    }
                }
            }
            update borrowerPartyList;                               
        }
        catch (Exception ex) {
            GenericUtility.insertLog('LASDocumentHelper.updateValues', ex);
            return ConstantValues.GENERAL_ERROR;
        }
        return ConstantValues.SUCCESS;
    }
    Webservice static String updateOverrideValues(Id appId){
        try{
            if(String.isBlank(appId)){
                return null;
            }
            List <String> companyList = new List<String>();
            List <genesis__Employment_Information__c> empInfoList = [SELECT Id,
                                                                        Override_Amount__c,
                                                                        Company_Name__c
                                                                    FROM genesis__Employment_Information__c 
                                                                    WHERE Document_Type__c =: ConstantValues.FullDocType
                                                                    AND Party__r.genesis__Application__c =: appId 
                                                                    AND Override__c =: ConstantValues.YES
                                                                    AND Company_Name__c != NULL
                                                                    AND Override_Amount__c != NULL];  
            if(empInfoList.size() > 0){
                List <RecordType> selfEmployedRecordTypeList = [SELECT Id,
                                                                    Name 
                                                                    FROM RecordType 
                                                                    WHERE Name =: ConstantValues.SELF_EMPLOYED
                                                                    LIMIT 1]; 
                if(selfEmployedRecordTypeList.size() > 0){
                    for(genesis__Employment_Information__c eachEmp : empInfoList){
                        companyList.add(eachEmp.Company_Name__c);
                    }
                    //Developer comment - not checking the size of companyList
                    //as in the list query null check is provided in where clause 
                    List <genesis__Employment_Information__c> incomeList =  [SELECT Id,
                                                                                Company_Name__c,
                                                                                LAS_Utility_Override_Amt__c,
                                                                                LAS_Utility_Override_Amt_Rendered__c
                                                                                FROM genesis__Employment_Information__c 
                                                                                WHERE Previous_Employment__c = false 
                                                                                AND genesis__Application__c =: appId 
                                                                                AND Party__r.genesis__Application__c =: appId 
                                                                                AND RecordTypeId =: selfEmployedRecordTypeList[0].Id
                                                                                AND Company_Name__c =: companyList];
                    for(genesis__Employment_Information__c eachIncome : incomeList){
                        eachIncome.LAS_Utility_Override_Amt__c = 0;
                        eachIncome.LAS_Utility_Override_Amt_Rendered__c = ConstantValues.NO_TAG;
                        for(genesis__Employment_Information__c eachEmp : empInfoList){
                            if(eachEmp.Company_Name__c == eachIncome.Company_Name__c){
                                eachIncome.LAS_Utility_Override_Amt__c = Decimal.valueOf(eachEmp.Override_Amount__c);
                                eachIncome.LAS_Utility_Override_Amt_Rendered__c = ConstantValues.YES_TAG;
                            }
                        }
                    }
                    update incomeList;
                }
            }                         
        }
        catch (Exception ex) {
            GenericUtility.insertLog('LASDocumentHelper.updateOverriValues', ex);
            return ConstantValues.GENERAL_ERROR;
        }
        return ConstantValues.SUCCESS;
    }
    Webservice static String updateEmploymentValues(Id appId){
        try{
            Integer employmentDeclared = 0;
            if(String.isBlank(appId)){
                return null;
            }
            List <clcommon__Party__c> borrowerPartyList = [SELECT Id,
                                                            LAS_Utility_Show_in_Capacity_Section__c
                                                            FROM clcommon__Party__c 
                                                            WHERE genesis__Application__c =: appId
                                                            AND Party_Type_Name__c in (:ConstantValues.GUARANTOR,:ConstantValues.CO_APPLICANT,:ConstantValues.BORROWER)
                                                          ];
            if(borrowerPartyList.size() > 0 == false){
                return null;
            }
            List <RecordType> selfEmployedRecordTypeList = [SELECT Id 
                                                                FROM RecordType 
                                                                WHERE Name =: ConstantValues.SELF_EMPLOYED
                                                                LIMIT 1];
            if(selfEmployedRecordTypeList.size() > 0 == false){
                return null;
            }
            List <genesis__Income__c> altIncomeDetailsList = [SELECT Id,
                                                                Party__c
                                                                FROM genesis__Income__c 
                                                                WHERE Income_Alt__c = true and genesis__Application__c =: appId
                                                                AND Party__c != NULL
                                                                AND Party__r.genesis__Application__c =: appId 
                                                                AND Party__r.Document_Type__c =: ConstantValues.ALT];  
            List <clcommon__Party__c> nonIndividualBorrowerFullList = [SELECT Id 
                                                                        FROM clcommon__Party__c 
                                                                        WHERE genesis__Application__c =: appId 
                                                                        AND Party_Type_Name__c IN (:ConstantValues.BORROWER,:ConstantValues.CO_APPLICANT) 
                                                                        AND Legal_Entity_Type__c NOT IN (:ConstantValues.indType)
                                                                        AND Document_Type__c =: ConstantValues.FullDocType];
            List <genesis__Income__c> altSelEmployedList = [SELECT Id,
                                                                Employment_Information__r.Party__c
                                                                FROM genesis__Income__c 
                                                                WHERE genesis__Application__c =: appId 
                                                                AND Document_Type__c =: ConstantValues.ALT 
                                                                AND Employment_Information__r.RecordTypeId =: selfEmployedRecordTypeList[0].Id
                                                                AND Employment_Information__r.Party__c != NULL]; 
            List <genesis__Employment_Information__c> individualSelfEmployedDetailsList = [SELECT Id,
                                                                                                Party__c
                                                                                                FROM genesis__Employment_Information__c 
                                                                                                WHERE Previous_Employment__c = false
                                                                                                AND genesis__Application__c =: appId 
                                                                                                AND Party__c != NULL
                                                                                                AND Party__r.genesis__Application__c =: appId 
                                                                                                AND RecordTypeId =: selfEmployedRecordTypeList[0].Id];
            List <genesis__Income__c> individualPAYGList =[SELECT Id,
                                                                Employment_Information__r.Party__c
                                                                FROM genesis__Income__c
                                                                WHERE genesis__Application__c =: appId
                                                                AND PAYG_Income__c = true
                                                                AND Employment_Information__r.Party__c != NULL];                                                                               
            for(clcommon__Party__c eachBorrower : borrowerPartyList){
                employmentDeclared = 0;
                eachBorrower.LAS_Utility_Show_in_Capacity_Section__c = false;
                if(altIncomeDetailsList.size() > 0){
                    for(genesis__Income__c eachIncome : altIncomeDetailsList){
                        if(eachIncome.Party__c == eachBorrower.Id){
                            employmentDeclared++;
                        }
                    }
                }
                if(nonIndividualBorrowerFullList.size() > 0){
                    for(clcommon__Party__c nonIndividualParty : nonIndividualBorrowerFullList){
                        if(nonIndividualParty.Id == eachBorrower.Id){
                            employmentDeclared++;
                        }
                    }
                }
                if(altSelEmployedList.size() > 0){
                    for(genesis__Income__c eachIncome : altSelEmployedList){
                        if(eachIncome.Employment_Information__r.Party__c == eachBorrower.Id){
                            employmentDeclared++;
                        }
                    }
                }
                if(individualSelfEmployedDetailsList.size() > 0){
                    for(genesis__Employment_Information__c eachEmp : individualSelfEmployedDetailsList){
                        if(eachEmp.Party__c == eachBorrower.Id){
                            employmentDeclared++;
                        }
                    }
                }
                if(individualPAYGList.size() > 0){
                    for(genesis__Income__c eachIncome : individualPAYGList){
                        if(eachIncome.Employment_Information__r.Party__c == eachBorrower.Id){
                            employmentDeclared++;
                        }
                    }
                }
                if(employmentDeclared == 0){
                    eachBorrower.LAS_Utility_Show_in_Capacity_Section__c = true;
                }
                update borrowerPartyList;
            }                                                      
        }
        catch (Exception ex) {
            GenericUtility.insertLog('LASDocumentHelper.updateEmploymentValues', ex);
            return ConstantValues.GENERAL_ERROR;
        }
        return ConstantValues.SUCCESS;
    }
 }