force-app/main/default/objects/Account/recordTypes/Borrower.recordType-meta.xml
<RecordType>
    <fullName>Borrower</fullName>
    <active>true</active>
    <label>Borrower</label>
</RecordType>

force-app/main/default/objects/clcommon__Collateral__c/clcommon__Collateral__c.object-meta.xml
<CustomObject>
    <label>Collateral</label>
    <nameField>
        <displayFormat>COL-{00000000}</displayFormat>
        <label>Collateral ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collaterals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/clcommon__Collateral__c/fields/clcommon__Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Postal_Code__c</fullName>
    <label>Postal Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/clcommon__Collateral__c/fields/genesis__Application__c.field-meta.xml
<CustomField>
    <fullName>genesis__Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Collaterals</relationshipLabel>
    <relationshipName>Collaterals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/clcommon__Collateral__c/fields/Mortgagor__c.field-meta.xml
<CustomField>
    <fullName>Mortgagor__c</fullName>
    <label>Mortgagor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/clcommon__Collateral__c/fields/QBE_Location__c.field-meta.xml
<CustomField>
    <fullName>QBE_Location__c</fullName>
    <label>QBE Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/clcommon__Collateral__c/fields/S_P_Location__c.field-meta.xml
<CustomField>
    <fullName>S_P_Location__c</fullName>
    <label>S &amp; P Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/clcommon__Party__c.object-meta.xml
<CustomObject>
    <label>Party</label>
    <nameField>
        <displayFormat>PAR-{00000000}</displayFormat>
        <label>Party Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/clcommon__Party__c/fields/clcommon__Account__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Parties</relationshipLabel>
    <relationshipName>Parties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/Employment_Type__c.field-meta.xml
<CustomField>
    <fullName>Employment_Type__c</fullName>
    <label>Employment Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PAYG</fullName>
            </value>
            <value>
                <fullName>Self Employed</fullName>
            </value>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Home Duties</fullName>
            </value>
            <value>
                <fullName>Retired</fullName>
            </value>
            <value>
                <fullName>Unemployed</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
                <isActive>false</isActive>
                <label>Contractor</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/genesis__Application__c.field-meta.xml
<CustomField>
    <fullName>genesis__Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Parties</relationshipLabel>
    <relationshipName>Parties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/Legal_Entity_Type__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Type__c</fullName>
    <formula>clcommon__Account__r.clcommon__Legal_Entity_Type__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Legal Entity Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/Party_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Party_Type_Name__c</fullName>
    <formula>clcommon__Type__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Party Type Name</label>
    <type>Text</type>
</CustomField>

elixir/force-app/main/default/objects/clcommon__Party__c/fields/Trust_Structure__c.field-meta.xml
<CustomField>
    <fullName>Trust_Structure__c</fullName>
    <label>Trust Structure</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Discretionary</fullName>
            </value>
            <value>
                <fullName>Fixed</fullName>
            </value>
            <value>
                <fullName>Hybrid</fullName>
            </value>
            <value>
                <fullName>Unit</fullName>
            </value>
            <value>
                <fullName>SMSF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Application_Collateral__c/genesis__Application_Collateral__c.object-meta.xml
<CustomObject>
    <label>Application Collateral</label>
    <nameField>
        <displayFormat>ACD-{00000000}</displayFormat>
        <label>Application Collateral Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Collateral</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Applications__c/fields/Employment_Type__c.field-meta.xml
<CustomField>
    <fullName>Employment_Type__c</fullName>
    <label>Employment Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Due_Date__c.field-meta.xml
<CustomField>
    <fullName>genesis__Due_Date__c</fullName>
    <description>The date deadline to perform an action on the application.</description>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

elixir/force-app/main/default/objects/genesis__Applications__c/fields/Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Legal Entity</label>
    <referenceTo>clcommon__Legal_Entity__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/Months_Self_Employed__c.field-meta.xml
<CustomField>
    <fullName>Months_Self_Employed__c</fullName>
    <label>Months Self Employed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/genesis__Employment_Information__c/genesis__Employment_Information__c.object-meta.xml
<CustomObject>
    <label>Employment Information</label>
    <nameField>
        <label>Employment Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employment Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

elixir/force-app/main/default/objects/genesis__Employment_Information__c/fields/genesis__Application__c.field-meta.xml
<CustomField>
    <fullName>genesis__Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Employment Information</relationshipLabel>
    <relationshipName>Employment_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

elixir/force-app/main/default/objects/genesis__Employment_Information__c/fields/Months_Self_Employed__c.field-meta.xml
<CustomField>
    <fullName>Months_Self_Employed__c</fullName>
    <label>Months Self Employed</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

elixir/force-app/main/default/objects/genesis__Employment_Information__c/fields/Party__c.field-meta.xml
<CustomField>
    <fullName>Party__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Party</label>
    <referenceTo>clcommon__Party__c</referenceTo>
    <relationshipLabel>Employment Information</relationshipLabel>
    <relationshipName>Employment_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Employment_Information__c/fields/Primary_Employment__c.field-meta.xml
<CustomField>
    <fullName>Primary_Employment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Employment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/genesis__Employment_Information__c/recordTypes/Self_Employed.recordType-meta.xml
<RecordType>
    <fullName>Self_Employed</fullName>
    <active>true</active>
    <label>Self Employed</label>
</RecordType>

Elixir_Prod/force-app/main/default/objects/QBEpostCode__c/QBEpostCode__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>QBEpostCode</label>
</CustomObject>

elixir/force-app/main/default/objects/QBEpostCode__c/fields/PostCode_High_RangeNumber__c.field-meta.xml
<CustomField>
    <fullName>PostCode_High_RangeNumber__c</fullName>
    <label>PostCode High RangeNumber</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Elixir_Prod/force-app/main/default/objects/QBEpostCode__c/fields/PostCode_Low_RangeNumber__c.field-meta.xml
<CustomField>
    <fullName>PostCode_Low_RangeNumber__c</fullName>
    <label>PostCode Low RangeNumber</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

elixir/force-app/main/default/objects/S_P_Postcode__c/S_P_Postcode__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>S&amp;P Postcode</label>
</CustomObject>

force-app/main/default/classes/SkuidValuesUpdateHelper.cls
/****************************************************************************************************/
/* Company              : Cloudkaptan Consultancy Services Pvt. Ltd. */
/* Class Name           : SkuidValuesUpdateHelper */
/* Created Date         : 29/12/2020 */
/* Developed By         : Rameswari Barman */
/* Description          : This class is used to update values when called from skuid*/
/* Last Modified Date   : 03/02/2021 */
/* Last Modified By     : Rameswari Barman */
/****************************************************************************************************/

global with sharing class SkuidValuesUpdateHelper {
    //This method helps in update S&P and QBE location values
    //from custom settings to collateral-security records
    Webservice static String updateLocationValues(Id appId){
        try{
            if(String.isBlank(appId)){
                return null;
            }
            //sub-query is used to query out collateral with the help of application id
            List <clcommon__Collateral__c> collateralList = [select Id,
                                                            S_P_Location__c,
                                                            QBE_Location__c,
                                                            clcommon__Postal_Code__c
                                                            from clcommon__Collateral__c
                                                            where Id in (Select genesis__Collateral__c 
                                                                            from genesis__Application_Collateral__c 
                                                                            where genesis__Application__c =: appId)];
            //Querying out locations from Custom settings
            List <QBEpostCode__c> qbeList = [Select Id,
                                                PostCode_High_RangeNumber__c,
                                                PostCode_Low_RangeNumber__c,
                                                Location__c
                                                From QBEpostCode__c
                                                LIMIT 1000
                                            ];
            List <S_P_Postcode__c> sAndPList = [Select Id,
                                                PostCode_High_RangeNumber__c,
                                                PostCode_Low_RangeNumber__c,
                                                Location__c
                                                From S_P_Postcode__c
                                                LIMIT 1000
                                            ];
            if(collateralList.size() > 0 == false){
                return null;
            }
            for(clcommon__Collateral__c collateral : collateralList){
                if(collateral.clcommon__Postal_Code__c != NULL && collateral.clcommon__Postal_Code__c != ''){
                    collateral.QBE_Location__c = ConstantValues.CATEGORY_3_OR_4;
                    for(QBEpostCode__c qbe : qbeList){
                        //looping to find the correct match from QBE custom setting values
                        //NULL check is not done on Location__c,PostCode_High_RangeNumber__c and QBE_Location__c as the values are already updated in custom settings and are hardly changed
                        if(qbe.PostCode_High_RangeNumber__c >= Decimal.ValueOf(collateral.clcommon__Postal_Code__c)
                                && qbe.PostCode_Low_RangeNumber__c <= Decimal.ValueOf(collateral.clcommon__Postal_Code__c)){
                            collateral.QBE_Location__c = qbe.Location__c;
                            break;//as correct match is found it will break from the loop
                        }
                    }
                    collateral.S_P_Location__c = '';
                    for(S_P_Postcode__c sp : sAndPList){
                        //NULL check is not done on Location__c,PostCode_High_RangeNumber__c and QBE_Location__c as the values are already updated in custom settings and are hardly changed
                        if(sp.PostCode_High_RangeNumber__c >= Decimal.ValueOf(collateral.clcommon__Postal_Code__c)
                                && sp.PostCode_Low_RangeNumber__c <= Decimal.ValueOf(collateral.clcommon__Postal_Code__c)){
                            collateral.S_P_Location__c = sp.Location__c;
                            break;//as correct match is found it will break from the loop
                        }
                    }
                }
            }
            update collateralList;//updation of collaterals with the latest location values from custom settings
        }
        catch (Exception ex) {
            GenericUtility.insertLog('SkuidValuesUpdateHelper.updateLocationValues', ex);
            return ConstantValues.GENERAL_ERROR;
        }
        return ConstantValues.SUCCESS;
    }
    //This method updates the mortgagor field value in collateral object for its displayal in the credit contract
    Webservice static String updateMortgagorName(Id appId){
        try{
            String mortgagor = '';
            Integer k = 0 ;
            if(String.isBlank(appId)){
                return null;
            }
            //Querying the Borrower Party
            List <clcommon__Party__c> borrowerPartyList = [Select Id,
                                                            Trust_Structure__c,
                                                            Legal_Entity_Type__c,
                                                            clcommon__Account__c,
                                                            clcommon__Account__r.Name
                                                            from clcommon__Party__c 
                                                            where genesis__Application__c =: appId
                                                            and Party_Type_Name__c =: ConstantValues.BORROWER
                                                            limit 1];
            if(borrowerPartyList.size() > 0 == false){
                return null;
            }
            //Querying out the list of collaterals with the help of application Id
            List <clcommon__Collateral__c> collateralList = [select Id,
                                                                Mortgagor__c
                                                                from clcommon__Collateral__c
                                                                where Id in (Select genesis__Collateral__c 
                                                                                from genesis__Application_Collateral__c 
                                                                                where genesis__Application__c =: appId)];
            if(collateralList.size() > 0 == false){
                return null;
            }
            //Querying out the collateral owners of the collaterals of the application
            List <clcommon__Collateral_Owner__c> collaterOwnerList = [Select Id,
                                                                        clcommon__Account__c,
                                                                        clcommon__Account__r.Name,
                                                                        clcommon__Collateral__c
                                                                        From clcommon__Collateral_Owner__c
                                                                        where clcommon__Collateral__c in (Select genesis__Collateral__c 
                                                                                                                from genesis__Application_Collateral__c 
                                                                                                                where genesis__Application__c =: appId)];
            if(borrowerPartyList[0].Legal_Entity_Type__c == ConstantValues.ENQUIRY_SMSF || (String.isBlank(borrowerPartyList[0].Trust_Structure__c) == false && borrowerPartyList[0].Trust_Structure__c == ConstantValues.ENQUIRY_SMSF)){
                //When the borrower is SMSF, the borower account holder is always the mortgagor
                for(clcommon__Collateral__c collateral : collateralList)
                {
                    if(String.isBlank(borrowerPartyList[0].clcommon__Account__c) == false && String.isBlank(borrowerPartyList[0].clcommon__Account__r.Name) == false){
                        collateral.Mortgagor__c = borrowerPartyList[0].clcommon__Account__r.Name;
                    }
                }
            }
            else{
                for(clcommon__Collateral__c collateral : collateralList){
                    //When the borrower is non-SMSF, the collateral owners are always the mortgagor
                    if(collaterOwnerList.size() > 0){
                        mortgagor = '';
                        k=0;
                        for(clcommon__Collateral_Owner__c colOwner : collaterOwnerList){
                            if(colOwner.clcommon__Collateral__c != NULL && colOwner.clcommon__Collateral__c == collateral.Id){
                                if(colOwner.clcommon__Account__c != NULl && String.isBlank(colOwner.clcommon__Account__r.Name) == false){
                                    if(k == 0){
                                        mortgagor = colOwner.clcommon__Account__r.Name;
                                    }
                                    else{
                                        mortgagor += ' and ' + colOwner.clcommon__Account__r.Name;
                                    }
                                    k++;
                                }
                            }
                        }
                    }
                    collateral.Mortgagor__c = mortgagor;
                }
            }
            update collateralList;//updation of the mortgagors
        }
        catch (Exception ex) {
            GenericUtility.insertLog('SkuidValuesUpdateHelper.updateMortgagorName', ex);
            return ConstantValues.GENERAL_ERROR;
        }
        return ConstantValues.SUCCESS;
    }
    //Method to update first payment date and due date
    Webservice static String updateFirstPaymentDate(Id appId){
        Savepoint sp = Database.setSavepoint();
        try{
            List <genesis__Applications__c> appList = [SELECT Id,
                                                        genesis__Expected_Start_Date__c,
                                                        genesis__Expected_First_Payment_Date__c,
                                                        genesis__Due_Day__c
                                                        FROM genesis__Applications__c 
                                                        WHERE Id =: appId];
            if(appList.size() > 0 && appList[0].genesis__Expected_Start_Date__c != NULL){
                Date settlementDate = appList[0].genesis__Expected_Start_Date__c;
                String scheduleResult;
                appList[0].genesis__Expected_First_Payment_Date__c = settlementDate.addMonths(1);
                appList[0].genesis__Due_Day__c = (appList[0].genesis__Expected_First_Payment_Date__c).Day();
                //updated the values as without putting first payment date and due date the schedule cant be generated
                update appList;
                //calling the Schedule generation class to generate schedule whoch considers business days
                scheduleResult = genesis.SkuidNewApplication.generateSchedule(appId);
                if(scheduleResult == ConstantValues.SUCCESSFULLY_DONE){
                    List <genesis__Amortization_Schedule__c> scheduleList = [SELECT id,
                                                                            genesis__Due_Date__c
                                                                            FROM genesis__Amortization_Schedule__c 
                                                                            WHERE genesis__Application__c =: appId
                                                                            ORDER BY genesis__Due_Date__c ASC LIMIT 1 ];
                    if(scheduleList.size() > 0 && scheduleList[0].genesis__Due_Date__c != NULL){
                        appList[0].genesis__Expected_First_Payment_Date__c = scheduleList[0].genesis__Due_Date__c;
                        update appList;//updating the first payment date from Schedule
                        return ConstantValues.SUCCESS_STATUS;
                    }
                    else{
                        Database.rollback(sp);
                        return ConstantValues.GENERAL_EXCEPTION;
                    }
                    
                }
                else{
                    Database.rollback(sp);
                    return scheduleResult;
                }
            }
            else {
                return ConstantValues.START_DATE_MISSING;
            }                       
        }
        catch (Exception ex) {
            Database.rollback(sp);
            GenericUtility.insertLog('SkuidValuesUpdateHelper.updateFirstPaymentDate', ex);
            return ConstantValues.GENERAL_ERROR;
        }
    }
    //Method to update Employment Tyep and Months Self Employed in applivation
    Webservice static String updateEmploymentTypeMonthsSelfEmployed(Id appId){
        Decimal monthsSelfEmployed = 1000000000;
        Boolean selfEmployed = false;
        try{
            if(String.isBlank(appId)){
                return null;
            }
            List <genesis__Applications__c> appList = [SELECT Id,
                                                            Employment_Type__c,
                                                            Months_Self_Employed__c,
                                                            Legal_Entity__c,
                                                            Legal_Entity__r.Name,
                                                            genesis__Account__c
                                                        FROM genesis__Applications__c 
                                                        WHERE Id =: appId];
            if(appList.size() > 0 
                && appList[0].Legal_Entity__c != NULL
                && String.isBlank(appList[0].Legal_Entity__r.Name) == false
                && appList[0].genesis__Account__c != NULL
            ){  
                appList[0].Employment_Type__c = null;
                appList[0].Months_Self_Employed__c = null;
                if(appList[0].Legal_Entity__r.Name == ConstantValues.indType){
                    List<genesis__Employment_Information__c> employmentList = [SELECT Id,
                                                                                RecordTypeId,
                                                                                Months_Self_Employed__c
                                                                                FROM genesis__Employment_Information__c
                                                                                WHERE Primary_Employment__c = true
                                                                                AND Party__r.clcommon__Account__c =: appList[0].genesis__Account__c
                                                                                AND RecordTypeId != NULL
                                                                                limit 1];
                    if(employmentList.size() > 0 ){
                        List<RecordType> recordTypeList = [SELECT Id,
                                                                Name
                                                            FROM RecordType
                                                            WHERE Id =: employmentList[0].RecordTypeId
                                                            LIMIT 1];
                        if(recordTypeList.size() > 0){
                            appList[0].Employment_Type__c = recordTypeList[0].Name;
                        }
                        appList[0].Months_Self_Employed__c = employmentList[0].Months_Self_Employed__c;
                    }
                }
                else{
                    List<genesis__Employment_Information__c> employmentList = [SELECT Id,
                                                                                    RecordTypeId,
                                                                                    Months_Self_Employed__c
                                                                                FROM genesis__Employment_Information__c
                                                                                WHERE Party__c != NULL
                                                                                AND Party__r.Party_Type_Name__c =: ConstantValues.GUARANTOR
                                                                                AND Party__r.Legal_Entity_Type__c =: ConstantValues.indType
                                                                                AND Party__r.genesis__Application__c =: appId
                                                                                AND RecordTypeId != NULL];
                    if(employmentList.size() > 0 ){
                        Set<Id> recordIdList = new Set<Id>();
                        for(genesis__Employment_Information__c eachEmployment : employmentList){
                            recordIdList.add(eachEmployment.RecordTypeId);
                        }
                        List<RecordType> recordTypeList = [SELECT Id,
                                                            Name
                                                            FROM RecordType
                                                            WHERE ID =: recordIdList];
                        Map<Id,String> recordTypeMap = new Map<Id,String>();
                        for(RecordType eachRecordType : recordTypeList){
                            if(String.isBlank(eachRecordType.Name) == false && eachRecordType.Name == ConstantValues.SELF_EMPLOYED){
                                selfEmployed = true;
                            }
                            recordTypeMap.put(eachRecordType.Id,eachRecordType.Name);
                        }
                        for(genesis__Employment_Information__c eachEmployment : employmentList){
                            if(recordTypeMap.containsKey(eachEmployment.RecordTypeId)
                                && recordTypeMap.get(eachEmployment.RecordTypeId) == ConstantValues.SELF_EMPLOYED){
                                    if(eachEmployment.Months_Self_Employed__c < monthsSelfEmployed){
                                        monthsSelfEmployed = eachEmployment.Months_Self_Employed__c;
                                    }
                                    appList[0].Employment_Type__c = ConstantValues.SELF_EMPLOYED;
                            }
                        }
                        if(monthsSelfEmployed < 1000000000){
                            appList[0].Months_Self_Employed__c = monthsSelfEmployed;
                        }
                        else{
                            appList[0].Months_Self_Employed__c = null;
                        }
                        if(employmentList.size() > 0 && selfEmployed == false
                            && recordTypeMap.containsKey(employmentList[0].RecordTypeId)){
                            appList[0].Employment_Type__c = recordTypeMap.get(employmentList[0].RecordTypeId);
                        }
                    }
                    else{
                        List <clcommon__Party__c> guarantorPartyList = [SELECT Id,
                                                                            Employment_Type__c
                                                                        FROM clcommon__Party__c
                                                                        WHERE genesis__Application__c =: appId
                                                                        AND Party_Type_Name__c =: ConstantValues.GUARANTOR
                                                                        AND Legal_Entity_Type__c =: ConstantValues.indType
                                                                        AND Employment_Type__c != NULL
                                                                        ORDER BY CreatedDate];
                        if(guarantorPartyList.size() > 0){
                            appList[0].Employment_Type__c = guarantorPartyList[0].Employment_Type__c;
                        }
                    }
                } 
                update appList;
                return ConstantValues.SUCCESS_STATUS;           
            } 
            else {
                return null;
            }                                       
        }
        catch (Exception ex) {
            GenericUtility.insertLog('SkuidValuesUpdateHelper.updateEmploymentTypeMonthsSelfEmployed', ex);
            return ConstantValues.GENERAL_ERROR;
        }
    }
}