force-app/main/default/objects/Account/recordTypes/Borrower.recordType-meta.xml
<RecordType>
    <fullName>Borrower</fullName>
    <active>true</active>
    <label>Borrower</label>
</RecordType>

force-app/main/default/objects/clcommon__Party__c/clcommon__Party__c.object-meta.xml
<CustomObject>
    <label>Party</label>
    <nameField>
        <displayFormat>PAR-{00000000}</displayFormat>
        <label>Party Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/clcommon__Party__c/fields/clcommon__Account__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Parties</relationshipLabel>
    <relationshipName>Parties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/genesis__Application__c.field-meta.xml
<CustomField>
    <fullName>genesis__Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Parties</relationshipLabel>
    <relationshipName>Parties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/NewExisting__c.field-meta.xml
<CustomField>
    <fullName>NewExisting__c</fullName>
    <label>NewExisting</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Existing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/Party_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Party_Type_Name__c</fullName>
    <formula>clcommon__Type__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Party Type Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UpdateNewOrExistingBorrower.cls
/****************************************************************************************************/
/* Company              : Cloudkaptan Consultancy Services Pvt. Ltd. */
/* Class Name           : UpdateNewOrExistingBorrower */
/* Created Date         : 15/03/2021 */
/* Developed By         : Rameswari Barman */
/* Description          : */
/* Last Modified Date   : 15/03/2021 */
/* Last Modified By     : Rameswari Barman */
/****************************************************************************************************/

global with sharing class UpdateNewOrExistingBorrower{
    Webservice static String updateValues(Id appId){
        try{
            if(String.isBlank(appId)){
                return null;
            }
            List <clcommon__Party__c> borrowerPartyList = [SELECT Id,
                                                            clcommon__Account__c,
                                                            clcommon__Account__r.Name,
                                                            NewExisting__c
                                                            FROM clcommon__Party__c 
                                                            WHERE genesis__Application__c =: appId
                                                            AND Party_Type_Name__c in (:ConstantValues.GUARANTOR,:ConstantValues.CO_APPLICANT,:ConstantValues.BORROWER)
                                                          ];
            if(borrowerPartyList.size() > 0 == false){
                return null;
            }
            List <Id> accountIds = new List<Id>();
            for(clcommon__Party__c eachParty : borrowerPartyList){
                accountIds.add(eachParty.clcommon__Account__c);
            }
            List <clcommon__Party__c> allBorrowerPartyList = [SELECT Id,
                                                                clcommon__Account__c,
                                                                clcommon__Account__r.Name
                                                                FROM clcommon__Party__c 
                                                                WHERE Party_Type_Name__c in (:ConstantValues.GUARANTOR,:ConstantValues.CO_APPLICANT,:ConstantValues.BORROWER)
                                                                AND genesis__Application__c NOT IN (:appId)
                                                                AND genesis__Application__c != NULL
                                                                AND clcommon__Account__c =: accountIds
                                                            ];
            for(clcommon__Party__c eachParty : borrowerPartyList){
                eachParty.NewExisting__c = 'New';
                for(clcommon__Party__c eachRemainingParty : allBorrowerPartyList){
                    if(eachParty.clcommon__Account__c == eachRemainingParty.clcommon__Account__c){
                        eachParty.NewExisting__c = 'Existing';
                    }
                }
            }
            update borrowerPartyList;                               
        }
        catch (Exception ex) {
            GenericUtility.insertLog('UpdateNewOrExistingBorrower.updateValues', ex);
            return ConstantValues.GENERAL_ERROR;
        }
        return ConstantValues.SUCCESS;
    }
 }