force-app/main/default/objects/Account/recordTypes/Borrower.recordType-meta.xml
<RecordType>
    <fullName>Borrower</fullName>
    <active>true</active>
    <label>Borrower</label>
</RecordType>

force-app/main/default/objects/clcommon__CL_Product__c/clcommon__CL_Product__c.object-meta.xml
<CustomObject>
    <label>CL Product</label>
    <nameField>
        <displayFormat>PRO-{00000000}</displayFormat>
        <label>CL Product Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/clcommon__Party__c/clcommon__Party__c.object-meta.xml
<CustomObject>
    <label>Party</label>
    <nameField>
        <displayFormat>PAR-{00000000}</displayFormat>
        <label>Party Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/clcommon__Party__c/fields/clcommon__Type__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Party Type</label>
    <referenceTo>clcommon__Party_Type__c</referenceTo>
    <relationshipLabel>Parties</relationshipLabel>
    <relationshipName>Parties</relationshipName>
    <type>Lookup</type>
</CustomField>

elixir/force-app/main/default/objects/clcommon__Party__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full</fullName>
            </value>
            <value>
                <fullName>Alt</fullName>
            </value>
            <value>
                <fullName>Lease</fullName>
                <isActive>false</isActive>
                <label>Lease</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/genesis__Enabled__c.field-meta.xml
<CustomField>
    <fullName>genesis__Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to determine whether the employee is an active employee of the company or not.</description>
    <inlineHelpText>Flag to determine whether the employee is an active employee of the company or not.</inlineHelpText>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/Legal_Entity_Type__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Type__c</fullName>
    <formula>clcommon__Account__r.clcommon__Legal_Entity_Type__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Legal Entity Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/Risk_Grade__c.field-meta.xml
<CustomField>
    <fullName>Risk_Grade__c</fullName>
    <label>Risk Grade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prime</fullName>
            </value>
            <value>
                <fullName>Near Prime</fullName>
            </value>
            <value>
                <fullName>Near Prime +</fullName>
            </value>
            <value>
                <fullName>Specialist</fullName>
            </value>
            <value>
                <fullName>Specialist +</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Application_Collateral__c/genesis__Application_Collateral__c.object-meta.xml
<CustomObject>
    <label>Application Collateral</label>
    <nameField>
        <displayFormat>ACD-{00000000}</displayFormat>
        <label>Application Collateral Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Collateral</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Applications__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full Doc</fullName>
            </value>
            <value>
                <fullName>Alt Doc</fullName>
            </value>
            <value>
                <fullName>Lease Doc</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

elixir/force-app/main/default/objects/genesis__Applications__c/fields/genesis__Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>genesis__Loan_Amount__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/Risk_grade_list__c.field-meta.xml
<CustomField>
    <fullName>Risk_grade_list__c</fullName>
    <label>Risk grade list</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prime</fullName>
            </value>
            <value>
                <fullName>Near Prime</fullName>
            </value>
            <value>
                <fullName>Near Prime +</fullName>
            </value>
            <value>
                <fullName>Specialist</fullName>
            </value>
            <value>
                <fullName>Specialist +</fullName>
            </value>
            <value>
                <fullName>Advance</fullName>
                <isActive>false</isActive>
                <label>Advance</label>
            </value>
            <value>
                <fullName>Advance Max</fullName>
                <isActive>false</isActive>
                <label>Advance Max</label>
            </value>
            <value>
                <fullName>Platinum</fullName>
                <isActive>false</isActive>
                <label>Platinum</label>
            </value>
            <value>
                <fullName>Recovery</fullName>
                <isActive>false</isActive>
                <label>Recovery</label>
            </value>
            <value>
                <fullName>Recovery Max</fullName>
                <isActive>false</isActive>
                <label>Recovery Max</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Employment_Information__c/genesis__Employment_Information__c.object-meta.xml
<CustomObject>
    <label>Employment Information</label>
    <nameField>
        <label>Employment Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employment Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

elixir/force-app/main/default/objects/genesis__Employment_Information__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Document_Type_Set</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Income__c/genesis__Income__c.object-meta.xml
<CustomObject>
    <description>This object will track the other income</description>
    <label>Income</label>
    <nameField>
        <label>Income Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incomes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Income__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full</fullName>
            </value>
            <value>
                <fullName>Alt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Rule__c/genesis__Rule__c.object-meta.xml
<CustomObject>
    <description>Object to hold the basic information (header ) of the rule. It is related to Rule Actions and Criteria</description>
    <label>Rule</label>
    <nameField>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

elixir/force-app/main/default/globalValueSets/Document_Type_Set.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Full</fullName>
    </customValue>
    <customValue>
        <fullName>Alt</fullName>
    </customValue>
    <masterLabel>Document Type Set</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CheckRulesTest.cls
/**********************************************************************************************************************************************************
Description : This class the Test class for CheckRules Apex Class.
Scenarios Tested : 1) This method acts as unit testing when the application id is not equal to null and Loan Details tab rules are executed
                   2) This method acts as unit testing when the application id is equal to null
                   3) This method acts as unit testing when the application id is not equal to null and Credit History tab rules are executed 
                   4) This method acts as unit testing when the application id is not equal to null and Settlement tab rules are executed
                   5) This method acts as unit testing when the application id is not equal to null and Securities tab rules are executed
                   6) This method acts as unit testing when the application id is not equal to null and Individual Contact Details tab rules are executed
                   7) This method acts as unit testing when the application id is not equal to null and Non Individual Contact Details tab rules are executed
                   8) This method acts as unit testing when the application id is not equal to null and Individual Employment Information tab rules are executed
                   9) This method acts as unit testing when the application id is not equal to null and Living Expense tab rules are executed
                   10) This method acts as unit testing when the application id is not equal to null and Company Income tab rules are executed
                   11) This method acts as unit testing when the application id is not equal to null and Credit History tab rules are executed
***********************************************************************************************************************************************************/
@isTest
private class CheckRulesTest {
    @testSetup
    static void setup() {
        clcommon__Legal_Entity__c legalEntity = GenericUtilityTestHelper.returnLegalEntity();
        List<clcommon__Legal_Entity__c> legalEntityList = [SELECT Id, Name FROM clcommon__Legal_Entity__c WHERE Name = 'Individual' LIMIT 1];
        System.assert(legalEntityList[0].Name == 'Individual','Legal Entity was not inserted.');

        Account accountDetails = GenericUtilityTestHelper.returnBorrowerAccount(legalEntity.Id);
        List<Account> accountDetailsList = [SELECT Id, Name FROM Account WHERE Name = 'Dummy Account' LIMIT 1];
        System.assert(accountDetailsList[0].Name == 'Dummy Account','Borrower Account was not inserted.');

        clcommon__CL_Product__c clProduct = GenericUtilityTestHelper.returnClProduct();
        List<clcommon__CL_Product__c> clProductList = [SELECT Id, clcommon__Product_Name__c FROM clcommon__CL_Product__c WHERE clcommon__Product_Name__c = 'Residential' LIMIT 1];
        System.assert(clProductList[0].clcommon__Product_Name__c == 'Residential','CL Product was not inserted.');

        genesis__Applications__c applicationDetails = GenericUtilityTestHelper.insertApplication(accountDetails.Id,clProduct.Id);
        applicationDetails.Risk_grade_list__c = 'Near Prime';
        applicationDetails.Document_Type__c = 'Full Doc';
        update applicationDetails;
        List<genesis__Applications__c> applicationDetailsList = [SELECT Id, genesis__Loan_Amount__c FROM genesis__Applications__c WHERE genesis__Loan_Amount__c = 150000 LIMIT 1];
        System.assert(applicationDetailsList[0].genesis__Loan_Amount__c == 150000,'Application was not inserted.');
        
        List<genesis__Rule__c> ruleList = GenericUtilityTestHelper.returnRule(applicationDetailsList[0].Id);
        List<genesis__Rule__c> getRuleList = [SELECT Id, Name FROM genesis__Rule__c WHERE genesis__Enabled__c = true];
        System.assert(ruleList[0].Name == 'Cash Out Purpose Suitable Rule', 'Rule was not inserted.');
        
        genesis__Employment_Information__c employmentInfo = GenericUtilityTestHelper.returnEmploymentInformation(applicationDetailsList[0].Id);
        System.assertNotEquals(employmentInfo.Id, NULL, 'Employment Information has been inserted');
        
        genesis__Income__c income = GenericUtilityTestHelper.returnEmploymentInformation(applicationDetailsList[0].Id,employmentInfo.Id);
        genesis__Application_Collateral__c appCollateral = GenericUtilityTestHelper.returnAppCollateral(applicationDetailsList[0].Id,accountDetails.Id);
        System.AssertNotEquals(appCollateral.Id,NULL,'Collateral inserted successfully!');
        
        clcommon__Party__c returnParty = GenericUtilityTestHelper.returnParty(applicationDetailsList[0].Id,accountDetails.Id);
        returnParty.Risk_Grade__c = 'Near Prime';
        returnParty.Document_Type__c = 'Full';
        update returnParty;
    }
    
    //This method acts as unit testing when the application id is not equal to null and Loan Details tab rules are executed
    @isTest
    static void testMethod1() {
        List<genesis__Applications__c> applicationDetailsList = [SELECT Id, genesis__Loan_Amount__c FROM genesis__Applications__c LIMIT 1];
        System.assert(applicationDetailsList[0].genesis__Loan_Amount__c == 150000,'Application was not inserted.');

        Test.startTest();
        String returnValue = CheckRules.callCheckRulesWS(
        applicationDetailsList[0].Id,
        'Loan Details'
        );
        Test.stopTest();
    }
    
    //This method acts as unit testing when the application id is equal to null
    @isTest
    static void testMethod2() {
        
        Test.startTest();
        String returnValue = CheckRules.callCheckRulesWS(
        NULL,
        'Loan Details'
        );
        Test.stopTest();
    }
    @isTest
    //This method acts as unit testing when the application id is not equal to null and Credit History tab rules are executed 
    static void testMethod3() {
        List<genesis__Applications__c> applicationDetailsList = [SELECT Id, genesis__Loan_Amount__c FROM genesis__Applications__c LIMIT 1];
        System.assert(applicationDetailsList[0].genesis__Loan_Amount__c == 150000,'Application was not inserted.');

        Test.startTest();
        String returnValue = CheckRules.callCheckRulesWS(
        applicationDetailsList[0].Id,
        'Credit History'
        );
        Test.stopTest();
        //System.assertEquals(ConstantValues.Success,returnValue,'Success');
    }
    @isTest
    //This method acts as unit testing when the application id is not equal to null and Review tab rules are executed 
    static void testMethod4() {
        List<genesis__Applications__c> applicationDetailsList = [SELECT Id, genesis__Loan_Amount__c FROM genesis__Applications__c LIMIT 1];
        System.assert(applicationDetailsList[0].genesis__Loan_Amount__c == 150000,'Application was not inserted.');

        Test.startTest();
        String returnValue = CheckRules.callCheckRulesWS(
        applicationDetailsList[0].Id,
        ConstantValues.XCEPTION
        );
        Test.stopTest();
        System.assertEquals(ConstantValues.Success,returnValue,'Success');
    }
    @isTest
    //This method acts as unit testing when the application id is not equal to null and Securities tab rules are executed
    static void testMethod5() {
        List<genesis__Applications__c> applicationDetailsList = [SELECT Id, genesis__Loan_Amount__c FROM genesis__Applications__c LIMIT 1];
        System.assert(applicationDetailsList[0].genesis__Loan_Amount__c == 150000,'Application was not inserted.');

        Test.startTest();
        String returnValue = CheckRules.callCheckRulesWS(
        applicationDetailsList[0].Id,
        'Securities'
        );
        Test.stopTest();
        System.assertEquals(ConstantValues.Success,returnValue,'Success');
    }
    @isTest
    //This method acts as unit testing when the application id is not equal to null and Individual Contact Details tab rules are executed
    static void testMethod6() {
        List<genesis__Applications__c> applicationDetailsList = [SELECT Id, genesis__Loan_Amount__c FROM genesis__Applications__c LIMIT 1];
        System.assert(applicationDetailsList[0].genesis__Loan_Amount__c == 150000,'Application was not inserted.');

        Test.startTest();
        String returnValue = CheckRules.callCheckRulesWS(
        applicationDetailsList[0].Id,
        'Individual Contact Details'
        );
        Test.stopTest();
        System.assertEquals(ConstantValues.Success,returnValue,'Success');
    }
    @isTest
    //This method acts as unit testing when the application id is not equal to null and Non Individual Contact Details tab rules are executed
    static void testMethod7() {
        List<genesis__Applications__c> applicationDetailsList = [SELECT Id, genesis__Loan_Amount__c FROM genesis__Applications__c LIMIT 1];
        System.assert(applicationDetailsList[0].genesis__Loan_Amount__c == 150000,'Application was not inserted.');

        Test.startTest();
        String returnValue = CheckRules.callCheckRulesWS(
        applicationDetailsList[0].Id,
        'Non Individual Contact Details'
        );
        Test.stopTest();
        System.assertEquals(ConstantValues.Success,returnValue,'Success');
    }
    @isTest
    //This method acts as unit testing when the application id is not equal to null and Individual Employment Information tab rules are executed
    static void testMethod8() {
        List<genesis__Applications__c> applicationDetailsList = [SELECT Id, genesis__Loan_Amount__c FROM genesis__Applications__c LIMIT 1];
        System.assert(applicationDetailsList[0].genesis__Loan_Amount__c == 150000,'Application was not inserted.');

        Test.startTest();
        String returnValue = CheckRules.callCheckRulesWS(
        applicationDetailsList[0].Id,
        'Individual Employment Information'
        );
        Test.stopTest();
        System.assertEquals(ConstantValues.Success,returnValue,'Success');
    }
    @isTest
    //This method acts as unit testing when the application id is not equal to null and Living Expense tab rules are executed
    static void testMethod9() {
        List<genesis__Applications__c> applicationDetailsList = [SELECT Id, genesis__Loan_Amount__c FROM genesis__Applications__c LIMIT 1];
        System.assert(applicationDetailsList[0].genesis__Loan_Amount__c == 150000,'Application was not inserted.');

        Test.startTest();
        String returnValue = CheckRules.callCheckRulesWS(
        applicationDetailsList[0].Id,
        'Living Expense'
        );
        Test.stopTest();
        System.assertEquals(ConstantValues.Success,returnValue,'Success');
    }
    @isTest
    //This method acts as unit testing when the application id is not equal to null and Company Income tab rules are executed
    static void testMethod10() {
        List<genesis__Applications__c> applicationDetailsList = [SELECT Id, genesis__Loan_Amount__c FROM genesis__Applications__c LIMIT 1];
        System.assert(applicationDetailsList[0].genesis__Loan_Amount__c == 150000,'Application was not inserted.');

        Test.startTest();
        String returnValue = CheckRules.callCheckRulesWS(
        applicationDetailsList[0].Id,
        'Company Income'
        );
        Test.stopTest();
        System.assertEquals(ConstantValues.Success,returnValue,'Success');
    }
    @isTest
    //This method acts as unit testing when the application id is not equal to null and Review tab rules are executed 
    static void testMethod11() {
        List<genesis__Applications__c> applicationDetailsList = [SELECT Id, genesis__Loan_Amount__c FROM genesis__Applications__c LIMIT 1];
        System.assert(applicationDetailsList[0].genesis__Loan_Amount__c == 150000,'Application was not inserted.');

        Test.startTest();
        String returnValue = CheckRules.callCheckRulesWS(
        applicationDetailsList[0].Id,
        ConstantValues.WARNING
        );
        Test.stopTest();
        System.assertEquals(ConstantValues.Success,returnValue,'Success');
    }
    @isTest
    //This method acts as unit testing when the application id is not equal to null and Review tab rules are executed 
    static void testMethod12() {
        List<genesis__Applications__c> applicationDetailsList = [SELECT Id, genesis__Loan_Amount__c FROM genesis__Applications__c LIMIT 1];
        System.assert(applicationDetailsList[0].genesis__Loan_Amount__c == 150000,'Application was not inserted.');

        Test.startTest();
        String returnValue = CheckRules.callCheckRulesWS(
        applicationDetailsList[0].Id,
        ConstantValues.WARNING2
        );
        Test.stopTest();
        System.assertEquals(ConstantValues.Success,returnValue,'Success');
    }
    @isTest
    //This method acts as unit testing when the application id is not equal to null and Review tab rules are executed 
    static void testMethod13() {
        List<genesis__Applications__c> applicationDetailsList = [SELECT Id, genesis__Loan_Amount__c FROM genesis__Applications__c LIMIT 1];
        System.assert(applicationDetailsList[0].genesis__Loan_Amount__c == 150000,'Application was not inserted.');
        List<clcommon__Legal_Entity__c> legalEntityList = [SELECT Id FROM clcommon__Legal_Entity__c LIMIT 1];
        legalEntityList[0].Name = 'Company';
        update legalEntityList;
        List<clcommon__Party__c> partyList = [SELECT Id, Legal_Entity_Type__c FROM clcommon__Party__c LIMIT 1];
        partyList[0].clcommon__Type__c = GenericUtilityTestHelper.insertPartyType(ConstantValues.GUARANTOR).Id;
        update partyList;
        Test.startTest();
        String returnValue = CheckRules.callCheckRulesWS(
        applicationDetailsList[0].Id,
        ConstantValues.CONDITION
        );
        Test.stopTest();
        System.assertEquals(ConstantValues.Success,returnValue,'Success');
    }
    @isTest
    //This method acts as unit testing when the application id is not equal to null and Review tab rules are executed 
    static void testMethod14() {
        List<genesis__Applications__c> applicationDetailsList = [SELECT Id, genesis__Loan_Amount__c FROM genesis__Applications__c LIMIT 1];
        System.assert(applicationDetailsList[0].genesis__Loan_Amount__c == 150000,'Application was not inserted.');
        List<clcommon__Legal_Entity__c> legalEntityList = [SELECT Id FROM clcommon__Legal_Entity__c LIMIT 1];
        legalEntityList[0].Name = 'Company';
        update legalEntityList;
        List<clcommon__Party__c> partyList = [SELECT Id FROM clcommon__Party__c LIMIT 1];
        partyList[0].clcommon__Type__c = GenericUtilityTestHelper.insertPartyType(ConstantValues.CO_APPLICANT).Id;
        update partyList;
        Test.startTest();
        String returnValue = CheckRules.callCheckRulesWS(
            applicationDetailsList[0].Id,
            ConstantValues.APP_EXCEP
        );
        Test.stopTest();
        System.assertEquals(ConstantValues.Success,returnValue,'Success');
    }
    @isTest
    //This method acts as unit testing when the application id is not equal to null and Review tab rules are executed 
    static void testMethod15() {
        List<genesis__Applications__c> applicationDetailsList = [SELECT Id, genesis__Loan_Amount__c FROM genesis__Applications__c LIMIT 1];
        Test.startTest();
        String returnValue = CheckRules.callCheckRulesWS(
        applicationDetailsList[0].Id,
        ConstantValues.RECOMMENDED
        );
        Test.stopTest();
        System.assertEquals(ConstantValues.Success,returnValue,'Success');
    }
}