force-app/main/default/objects/Account/recordTypes/Borrower.recordType-meta.xml
<RecordType>
    <fullName>Borrower</fullName>
    <active>true</active>
    <label>Borrower</label>
</RecordType>

force-app/main/default/objects/clcommon__Party__c/clcommon__Party__c.object-meta.xml
<CustomObject>
    <label>Party</label>
    <nameField>
        <displayFormat>PAR-{00000000}</displayFormat>
        <label>Party Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/clcommon__Party__c/fields/clcommon__Account__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Parties</relationshipLabel>
    <relationshipName>Parties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/genesis__Application__c.field-meta.xml
<CustomField>
    <fullName>genesis__Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Parties</relationshipLabel>
    <relationshipName>Parties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/Legal_Entity_Type__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Type__c</fullName>
    <formula>clcommon__Account__r.clcommon__Legal_Entity_Type__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Legal Entity Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/Living_Expense_Used_for_Servicing_Purpos__c.field-meta.xml
<CustomField>
    <fullName>Living_Expense_Used_for_Servicing_Purpos__c</fullName>
    <label>Living Expense Used for Servicing Purpos</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/Party_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Party_Type_Name__c</fullName>
    <formula>clcommon__Type__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Party Type Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Applications__c/fields/Monthly_Living_Expenses_Used__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Living_Expenses_Used__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Monthly Living Expenses Used</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DataMigrationBatch.cls
/****************************************************************************************************
Company              : Cloudkaptan Consultancy Services Pvt. Ltd. 
Class Name           : UpdateEmploymentTypeOnApplication 
Created Date         : 19/08/2022 
Developed By         : Sayak Mukhopadhyay
Last Modified By     : Sayak Mukhopadhyay
Description          : This Batch Job is used for One time Data Migration
****************************************************************************************************/
public class DataMigrationBatch implements DataBase.StateFul,DataBase.Batchable<sObject>{
    public Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator([SELECT id,
                                            Monthly_Living_Expenses_Used__c
                                            FROM genesis__Applications__c]);
    }
    public void execute(Database.BatchableContext bc, List<genesis__Applications__c>objAppList){
        Double partyLivingExpense = 0;
        List<String> partyTypeList = new String[]{ConstantValues.BORROWER,ConstantValues.GUARANTOR,ConstantValues.CO_APPLICANT};
        List<clcommon__Party__c> objPartyList = [SELECT id,
                                                    Name,
                                                    genesis__Application__c,
                                                    Living_Expense_Used_for_Servicing_Purpos__c,
                                                    clcommon__Account__r.Name 
                                                    FROM clcommon__Party__c  
                                                    WHERE genesis__Application__c in: objAppList 
                                                    AND ((Party_Type_Name__c IN: partyTypeList
                                                    AND Legal_Entity_Type__c =: ConstantValues.indType) 
                                                    OR Party_Type_Name__c =: ConstantValues.HOUSEHOLD_PARTY_TYPE)];
        Map<Id,Double> totalLivingExpenseMap = new Map<Id,Double>();
        for(genesis__Applications__c objApp : objAppList){
            totalLivingExpenseMap.put(objApp.id,0.0);
        }
        for(clcommon__Party__c objParty : objPartyList){
            partyLivingExpense = objParty.Living_Expense_Used_for_Servicing_Purpos__c;
            if(partyLivingExpense != null && totalLivingExpenseMap.containsKey(objParty.genesis__Application__c)){
                totalLivingExpenseMap.put(objParty.genesis__Application__c,totalLivingExpenseMap.get(objParty.genesis__Application__c) + partyLivingExpense);
            }
        }
        for(genesis__Applications__c objApp : objAppList){
            if(totalLivingExpenseMap.containsKey(objApp.id)){
                objApp.Monthly_Living_Expenses_Used__c = totalLivingExpenseMap.get(objApp.id);
            }
        }
        if(objAppList.size()>0){
            Database.update(objAppList,false);
        }
    }
    public void finish(Database.BatchableContext bc){
    }
}