force-app/main/default/objects/clcommon__Collateral__c/clcommon__Collateral__c.object-meta.xml
<CustomObject>
    <label>Collateral</label>
    <nameField>
        <displayFormat>COL-{00000000}</displayFormat>
        <label>Collateral ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collaterals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/clcommon__Collateral__c/fields/Document_Enquiry_Id__c.field-meta.xml
<CustomField>
    <fullName>Document_Enquiry_Id__c</fullName>
    <label>Document Enquiry Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/clcommon__Collateral__c/fields/Document_Status__c.field-meta.xml
<CustomField>
    <fullName>Document_Status__c</fullName>
    <label>Document Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PENDING</fullName>
            </value>
            <value>
                <fullName>READY</fullName>
            </value>
            <value>
                <fullName>EXPIRED</fullName>
            </value>
            <value>
                <fullName>FAILURE</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LandTitleDocumentStatusTest.cls
/****************************************************************************************************/
/* Class Name: LandTitleDocumentStatusTest */
/* Developed By: Souvik Dey */
/* Description : This is the Test class for LandTitleDocumentStatus */
/* Testing Scenario 1   : (testRest) tests with Apex rest API request */
/****************************************************************************************************/

@isTest
private with sharing class LandTitleDocumentStatusTest {
    @TestSetup
    static void initialize(){
        GenericUtilityTestHelper.getCollateral('', '155A', 'CRANEBROOK', 'ROAD', 'NORTH SYDNEY', 'NSW', '2060');
        List<clcommon__Collateral__c> collList = [SELECT Id FROM clcommon__Collateral__c];
        System.assertEquals(collList.size(), 1, 'Collateral not inserted');
    }
    @isTest
    static void testRest() {
        List<clcommon__Collateral__c> collList = [SELECT Id, Name
            FROM clcommon__Collateral__c];
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.addHeader('httpMethod', 'POST');
        req.requestUri = '/services/apexrest/DocumentStatus/';
        List <StaticResource> srList = [SELECT Id, Name, Body
            FROM StaticResource WHERE Name = 'Land_Title_Document_Status'];
        System.assertEquals(srList.size() > 0, true, 'Static Resource is present!');
        String postData = srList[0].Body.toString();
        postData = postData.replace('Collateral_Ref', collList[0].Name);
        req.requestBody = Blob.valueof(postData);
        RestContext.request = req;
        RestContext.response = res;
        Test.startTest();
        LandTitleDocumentStatus.createRecord();
        Test.stopTest();
        collList = [SELECT Id, Document_Status__c, Document_Enquiry_Id__c
            FROM clcommon__Collateral__c];
        System.assertEquals(collList[0].Document_Status__c, 'READY', 'Collateral status is not as Expected');
        System.assertEquals(collList[0].Document_Enquiry_Id__c, '140805-MFDUX-0000Q', 'Document Enquiry Id is not as Expected');
    }
}