force-app/main/default/objects/clcommon__Collateral__c/clcommon__Collateral__c.object-meta.xml
<CustomObject>
    <label>Collateral</label>
    <nameField>
        <displayFormat>COL-{00000000}</displayFormat>
        <label>Collateral ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collaterals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/clcommon__Collateral__c/fields/genesis__Application__c.field-meta.xml
<CustomField>
    <fullName>genesis__Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Collaterals</relationshipLabel>
    <relationshipName>Collaterals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/clcommon__Party__c.object-meta.xml
<CustomObject>
    <label>Party</label>
    <nameField>
        <displayFormat>PAR-{00000000}</displayFormat>
        <label>Party Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/clcommon__Party__c/fields/clcommon__Account__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Parties</relationshipLabel>
    <relationshipName>Parties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/genesis__Application__c.field-meta.xml
<CustomField>
    <fullName>genesis__Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Parties</relationshipLabel>
    <relationshipName>Parties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Collateral__c/genesis__Application_Collateral__c.object-meta.xml
<CustomObject>
    <label>Application Collateral</label>
    <nameField>
        <displayFormat>ACD-{00000000}</displayFormat>
        <label>Application Collateral Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Collateral</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CollateralOwnerTriggerHandler.cls
/**********************************************************************************************************************************************************
Company : CloudKaptan Consultancy Services Pvt. Ltd.
Developer : Rameswari Barman
Development Date : 03/05/2021
Last Modified By : Rameswari Barman
Last Modified Date : 03/05/2021
Description : This Handler class is called from before update trigger called from CollateralOwnerTrigger
Helps in checking whether the account owner belong to the application attached with the collateral
***********************************************************************************************************************************************************/
public with sharing class CollateralOwnerTriggerHandler {
    public static void collateralCheck(List<clcommon__Collateral_Owner__c> newList) {
        Set <Id> collateralList = new Set<Id>();
        Set <Id> accountIdList = new Set<Id>();
        try{
            for(clcommon__Collateral_Owner__c eachColOwner : newList){
                collateralList.add(eachColOwner.clcommon__Collateral__c);
            }
            List <clcommon__Party__c> partyList = [SELECT Id,
                                                        clcommon__Account__c
                                                        FROM clcommon__Party__c 
                                                        WHERE genesis__Application__c IN (SELECT genesis__Application__c
                                                                                            FROM genesis__Application_Collateral__c
                                                                                            WHERE genesis__Collateral__c =: collateralList)
                                                        ORDER BY genesis__Application__c];
            for(clcommon__Party__c eachParty : partyList){
                accountIdList.add(eachParty.clcommon__Account__c);
            }
            for(clcommon__Collateral_Owner__c eachColOwner : newList){
                if(accountIdList.contains(eachColOwner.clcommon__Account__c) == false){
                    eachColOwner.clcommon__Account__c.addError('Only accounts from the same application can be added as Collateral Owners.');
                }
            }
        }
        catch(Exception e){
            GenericUtility.insertLog('CollateralOwnerTriggerHandler', e);
        }
    }
}