force-app/main/default/objects/clcommon__Collateral__c/clcommon__Collateral__c.object-meta.xml
<CustomObject>
    <label>Collateral</label>
    <nameField>
        <displayFormat>COL-{00000000}</displayFormat>
        <label>Collateral ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collaterals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/clcommon__Collateral__c/fields/Document_Enquiry_Id__c.field-meta.xml
<CustomField>
    <fullName>Document_Enquiry_Id__c</fullName>
    <label>Document Enquiry Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/clcommon__Collateral__c/fields/Document_Retrived__c.field-meta.xml
<CustomField>
    <fullName>Document_Retrived__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Document Retrived</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/clcommon__Collateral__c/fields/Document_Status__c.field-meta.xml
<CustomField>
    <fullName>Document_Status__c</fullName>
    <label>Document Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PENDING</fullName>
            </value>
            <value>
                <fullName>READY</fullName>
            </value>
            <value>
                <fullName>EXPIRED</fullName>
            </value>
            <value>
                <fullName>FAILURE</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DocumentDeliveryCheckBatch.cls
/****************************************************************************************************/
/* Company              : Cloudkaptan Consultancy Services Pvt. Ltd. */
/* Class Name           : DocumentDeliveryCheckBatch */
/* Created Date         : 01/08/2020 */
/* Developed By         : Souvik */
/* Description          : This batch class does query on the collaterals for which order document
has been done previously and do callout with the enquiry Id for delivery document. This batch class
should be executed passing 1 in the batchSize parameter. */
/* Last Modified Date   : 01/08/2020 */
/* Last Modified By     : Souvik */
/****************************************************************************************************/

public class DocumentDeliveryCheckBatch implements Database.Batchable<sObject>, Database.AllowsCallouts{
    public Database.QueryLocator start(Database.BatchableContext bc)
    {
        String query = 'Select Id, Document_Enquiry_Id__c, Document_Status__c, Document_Retrived__c '
        + 'FROM clcommon__Collateral__c WHERE Document_Enquiry_Id__c != null AND Document_Status__c != \'FAILURE\' AND Document_Retrived__c = false AND Document_Status__c != \'EXPIRED\'';
        return Database.getQueryLocator(query);
    }
    public void execute(Database.BatchableContext bc, List<SObject> scope) {
        try{
            if(scope == null || scope.isEmpty()){
                return;
            }
            EquifaxCallout.equifaxDeliverDocument((Id)scope[0].get('Id'));
        }
        catch(Exception ex){
            GenericUtility.insertLog('DocumentDeliveryCheckBatch', ex);
        }
    }
    public void finish(Database.BatchableContext bc){}
}