force-app/main/default/objects/clcommon__Collateral__c/clcommon__Collateral__c.object-meta.xml
<CustomObject>
    <label>Collateral</label>
    <nameField>
        <displayFormat>COL-{00000000}</displayFormat>
        <label>Collateral ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collaterals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/clcommon__Collateral__c/fields/Document_Enquiry_Id__c.field-meta.xml
<CustomField>
    <fullName>Document_Enquiry_Id__c</fullName>
    <label>Document Enquiry Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/clcommon__Collateral__c/fields/Document_Status__c.field-meta.xml
<CustomField>
    <fullName>Document_Status__c</fullName>
    <label>Document Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PENDING</fullName>
            </value>
            <value>
                <fullName>READY</fullName>
            </value>
            <value>
                <fullName>EXPIRED</fullName>
            </value>
            <value>
                <fullName>FAILURE</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LandTitleDocumentStatus.cls
/****************************************************************************************************/
/* Company              : Cloudkaptan Consultancy Services Pvt. Ltd. */
/* Class Name           : LandTitleDocumentStatus */
/* Created Date         : 04/08/2020 */
/* Developed By         : Souvik */
/* Description          : This class is used to handle the notification request from Equifax. This
class gets called when post request on the mentioned url gets called. */
/* Last Modified Date   : 04/08/2020 */
/* Last Modified By     : Souvik */
/****************************************************************************************************/

@RestResource(urlMapping='/DocumentStatus/*')
global without sharing class LandTitleDocumentStatus {
    @HttpPost
    global static void createRecord() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        String enquiryId;
        String status;
        String dateTimeValue;
        String clientReference;
        try {
            Blob blb = req.requestBody;
            String requestBody = blb.toString();
            dom.Document doc = new dom.Document();
            doc.load(requestBody);
            Map<String, Object> responseMap = intframework.XmlToJson.parseDocumentToMap(doc);
            if(responseMap.containsKey('Envelope') && responseMap.get('Envelope') != null){
                responseMap = (Map<String, Object>) responseMap.get('Envelope');
                if(responseMap.containsKey('Body') && responseMap.get('Body') != null){
                    responseMap = (Map<String, Object>) responseMap.get('Body');
                    if(responseMap.containsKey('notify-event-request') && responseMap.get('notify-event-request') != null){
                        responseMap = (Map<String, Object>) responseMap.get('notify-event-request');
                        if(responseMap.containsKey('request-header') && responseMap.get('request-header') != null){
                            Map<String, Object> tempResponseMap = (Map<String, Object>) responseMap.get('request-header');
                            if(tempResponseMap.containsKey('client-reference') && tempResponseMap.get('client-reference') != null){
                                tempResponseMap = (Map<String, Object>) tempResponseMap.get('client-reference');
                                if(tempResponseMap.containsKey('NodeValue') && tempResponseMap.get('NodeValue') != null){
                                    clientReference = (String) tempResponseMap.get('NodeValue');
                                }
                            }
                        }
                        if(responseMap.containsKey('notify-event-data') && responseMap.get('notify-event-data') != null){
                            responseMap = (Map<String, Object>) responseMap.get('notify-event-data');
                            if(responseMap.containsKey('enquiry-id') && responseMap.get('enquiry-id') != null){
                                Map<String, Object> tempResponseMap = (Map<String, Object>) responseMap.get('enquiry-id');
                                if(tempResponseMap.containsKey('NodeValue') && tempResponseMap.get('NodeValue') != null){
                                    enquiryId = (String) tempResponseMap.get('NodeValue');
                                }
                            }
                            if(responseMap.containsKey('status') && responseMap.get('status') != null){
                                Map<String, Object> tempResponseMap = (Map<String, Object>) responseMap.get('status');
                                if(tempResponseMap.containsKey('NodeValue') && tempResponseMap.get('NodeValue') != null){
                                    status = (String) tempResponseMap.get('NodeValue');
                                }
                            }
                            if(responseMap.containsKey('date-time') && responseMap.get('date-time') != null){
                                Map<String, Object> tempResponseMap = (Map<String, Object>) responseMap.get('date-time');
                                if(tempResponseMap.containsKey('NodeValue') && tempResponseMap.get('NodeValue') != null){
                                    dateTimeValue = (String) tempResponseMap.get('NodeValue');
                                }
                            }
                        }
                    }
                }
            }
            clcommon__Collateral__c collateralObj = [
                SELECT Id, Name, Document_Enquiry_Id__c
                FROM clcommon__Collateral__c
                WHERE Name =:clientReference LIMIT 1
            ];
            collateralObj.Document_Status__c = status;
            collateralObj.Document_Enquiry_Id__c = enquiryId;
            Database.update(collateralObj);
            res.statusCode = 200;
            res.addHeader('Content-Type', 'application/soap+xml');
            res.responseBody = Blob.valueOf(ConstantValues.RES_HEADER + '<enquiry-id>' + enquiryId + '</enquiry-id>\n'
            + '<status>' + status + '</status>\n' + '<date-time>' + dateTimeValue + '</date-time>\n' + ConstantValues.RES_FOOTER);
        } catch (Exception ex) {
            res.statusCode = 500;
            res.addHeader('Content-Type', 'application/soap+xml');
            res.responseBody = Blob.valueOf(ConstantValues.RES_HEADER + '<errors><error><error-detail>'
            + ex.getMessage() + '</error-detail></error></errors>' + ConstantValues.RES_FOOTER);
        }
    }
}