elixir/force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

elixir/force-app/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <customHelpPage>loan__CLContractHelp</customHelpPage>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Elixir_Prod/force-app/main/default/objects/loan__Loan_Account__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>CL Contracts</relationshipLabel>
    <relationshipName>CL_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Interest_Accrued_Not_Due__c.field-meta.xml
<CustomField>
    <fullName>loan__Interest_Accrued_Not_Due__c</fullName>
    <defaultValue>0.0</defaultValue>
    <description>This field gets updated on Payment Date. It is the accrued interest that is posted on the account.</description>
    <inlineHelpText>Interest balance as of last accrual date.</inlineHelpText>
    <label>Interest Accrued</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Loan Amount</description>
    <inlineHelpText>This is the financed amount on the contract which will be disbursed to the customer.</inlineHelpText>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Loan_Balance__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Balance__c</fullName>
    <label>Loan Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Loan_Status__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Status__c</fullName>
    <inlineHelpText>Status of the Account expected values are :
Pending Approval
Active - Good Standing
Active - Bad Standing
Active - Matured
Approved
Canceled
Closed - Obligations met
Closed- Written Off
Closed - Refinanced
Partial Application
Closed - Premature</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active - Bad Standing</fullName>
            </value>
            <value>
                <fullName>Active - Good Standing</fullName>
            </value>
            <value>
                <fullName>Active - Marked for Closure</fullName>
            </value>
            <value>
                <fullName>Active - Matured</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Closed - Obligations met</fullName>
            </value>
            <value>
                <fullName>Closed - Premature</fullName>
            </value>
            <value>
                <fullName>Closed - Refinanced</fullName>
            </value>
            <value>
                <fullName>Closed- Written Off</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>Partial Application</fullName>
                <default>true</default>
                <label>Partial Application</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Premature Closure Initiated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

elixir/force-app/main/default/objects/loan__Loan_Account__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>CL Contracts</relationshipLabel>
    <relationshipName>CL_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

elixir/force-app/main/default/objects/Loan_Warehouse__c/Loan_Warehouse__c.object-meta.xml
<CustomObject>
    <label>Loan Warehouse</label>
    <nameField>
        <label>Loan Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Warehouse</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

elixir/force-app/main/default/objects/Loan_Warehouse__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Loan Warehouse</relationshipLabel>
    <relationshipName>Loan_Warehouse</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

elixir/force-app/main/default/objects/Loan_Warehouse__c/fields/Balance_Outstanding__c.field-meta.xml
<CustomField>
    <fullName>Balance_Outstanding__c</fullName>
    <label>Balance Outstanding</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan_Warehouse__c/fields/Changed_Time__c.field-meta.xml
<CustomField>
    <fullName>Changed_Time__c</fullName>
    <label>Changed Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Loan_Warehouse__c/fields/CL_Contract__c.field-meta.xml
<CustomField>
    <fullName>CL_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CL Contract</label>
    <referenceTo>loan__Loan_Account__c</referenceTo>
    <relationshipLabel>Loan Warehouse</relationshipLabel>
    <relationshipName>Loan_Warehouse</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Warehouse__c/fields/Loan_Warehouse_Number__c.field-meta.xml
<CustomField>
    <fullName>Loan_Warehouse_Number__c</fullName>
    <displayFormat>LWJunction-{0000}</displayFormat>
    <label>Loan Warehouse Number</label>
    <type>AutoNumber</type>
</CustomField>

elixir/force-app/main/default/objects/Loan_Warehouse__c/fields/Previous_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Previous_Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Previous Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Loan Warehouse (Previous Warehouse)</relationshipLabel>
    <relationshipName>Loan_Warehouse1</relationshipName>
    <type>Lookup</type>
</CustomField>

elixir/force-app/main/default/objects/Loan_Warehouse__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Loan Warehouse</relationshipLabel>
    <relationshipName>Loan_Warehouse</relationshipName>
    <type>Lookup</type>
</CustomField>

elixir/force-app/main/default/objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

elixir/force-app/main/default/classes/LoanWarehouseChangeHelper.cls
/***********************************************************************************************************************
Class Name - LoanWarehouseChangeHelper
Developer - Rameswari Barman
Purpose - When a record in Loan Warehouse junction is insserted through the object trigger this particular class is called.
          With the help of this class, values in the records of junction object is updated. 
          The newly inserted record value is changed to Active and all the existing application/contract loan warehouse record status is changed to Inactive.
          Also the warehouse atttached in CL Contract gets updated.
***********************************************************************************************************************/

global class LoanWarehouseChangeHelper{
    global static void changeActive(List <ID> exID, List <Id> loanWHList){
        //This method helps in changing the existing status of the loan warehouse records to inactive
        List<Loan_Warehouse__c> whList = new List<Loan_Warehouse__c> ();
        List<Loan_Warehouse__c> warehouseList = new List<Loan_Warehouse__c>();
        Savepoint sp=Database.setSavepoint();
        try{
            if(loanWHList != null && loanWHList.size() > 0 && exID != null && exID.size() > 0){
                whList = [SELECT Id,
                                 Active__c,
                                 Application__c 
                                 FROM Loan_Warehouse__c
                                 WHERE Id NOT IN : loanWHList 
                                 AND Application__c IN : exID
                                 AND Active__c = true
                           ];
                if(whList!=null && whList.size() > 0){
                    for(Loan_Warehouse__c eachWarehouse : whList){
                        eachWarehouse.Active__c = false;
                        warehouseList.add(eachWarehouse);
                    }
                    if(warehouseList != null && warehouseList.size() > 0){
                        update warehouseList;
                    }
                }
            }
        }
        catch(Exception e){
            insert new clcommon__Batch_Process_Log__c(clcommon__Message__c = 'LoanWarehouseChangeHelper :'+e.getStackTraceString()+':Error::'+e.getMessage(), clcommon__Timestamp__c = 
                                                  System.Now(),clcommon__Log_Level__c = 'ERROR'); 
            Database.rollback(sp);
        }
    }
    global static void loanWarehouse(List <Loan_Warehouse__c> newList){
        //This method helps in updating the loan record values and also updates the new warehouse funder in CL Contract when warehouse is changed
        System.debug('Test 1');
        List<Loan_Warehouse__c> listRecLoanWare = [select id,
                                                          Warehouse__c,
                                                          Application__c,
                                                          Balance_Outstanding__c,
                                                          Loan_Warehouse_Number__c,
                                                          Application__r.CL_Contract__c,
                                                          Application__r.CL_Contract__r.loan__Loan_Balance__c,
                                                          Application__r.CL_Contract__r.loan__Interest_Accrued_Not_Due__c,
                                                          Application__r.CL_Contract__r.loan__Loan_Status__c,
                                                          Application__r.CL_Contract__r.loan__Loan_Amount__c
                                                           
                                                          from Loan_Warehouse__c 
                                                          where id =: newList
                                                    ]; 
        List<Loan_Warehouse__c> listActiveWH = [select id,
                                                       Active__c,
                                                       Application__c,
                                                       Warehouse__c 
                                                       from Loan_Warehouse__c
                                                       where Active__c = true
                                                ];
        List<loan__Loan_Account__c> loanList = new List<loan__Loan_Account__c>();
        Map<Id,Id> prevId = new Map<Id,Id>();
        List<Id> appId = new List<Id>();
        List<Id> loanWarehouseIds = new List<Id>();
        List<Loan_Warehouse__c> newRecords = new List<Loan_Warehouse__c>();
        Savepoint sp=Database.setSavepoint();
        try{
            if(listActiveWH != null && listActiveWH.size() > 0){
                for(Loan_Warehouse__c lh : listActiveWH){
                    prevId.put(lh.Application__c,lh.Warehouse__c);
                    System.debug('Test 2');
                }
            }
            if(listRecLoanWare != null && listRecLoanWare.size() > 0){
                for(Loan_Warehouse__c objLoanWh : listRecLoanWare){
                    System.debug(objLoanWh);
                    objLoanWh.Active__c = true;
                    objLoanWh.Changed_Time__c = (Test.isRunningTest()?Date.Today():(new loan.GlobalLoanUtilFacade()).getCurrentSystemDate());
                    objLoanWh.Previous_Warehouse__c = prevId.get(objLoanWh.Application__c);
                    objLoanWh.CL_Contract__c = objLoanWh.Application__r.CL_Contract__c;
                    objLoanWh.Name = objLoanWh.Loan_Warehouse_Number__c;
                    if(objLoanWh.Application__r.CL_Contract__c != null){
                        loan__Loan_Account__c obj = new loan__Loan_Account__c(id=objLoanWh.Application__r.CL_Contract__c);
                        obj.Warehouse__c = objLoanWh.Warehouse__c;
                        System.debug('Test 3');
                    }
                        System.debug('====objLoanWh.CL_Contract__c====='+objLoanWh.CL_Contract__c);
                    if(objLoanWh.CL_Contract__c != NULL){
                        System.debug('====objLoanWh.Balance_Outstanding__c===='+objLoanWh.Balance_Outstanding__c);
                        System.debug('====objLoanWh.Application__r.CL_Contract__r.loan__Loan_Balance__c======'+objLoanWh.Application__r.CL_Contract__r.loan__Loan_Balance__c);
                        System.debug('=====objLoanWh.Application__r.CL_Contract__r.loan__Interest_Accrued_Not_Due__c===='+objLoanWh.Application__r.CL_Contract__r.loan__Interest_Accrued_Not_Due__c);
                        
                        objLoanWh.Balance_Outstanding__c =( (objLoanWh.Application__r.CL_Contract__r.loan__Loan_Balance__c != NULL && objLoanWh.Application__r.CL_Contract__r.loan__Loan_Status__c != 'Approved') ? (objLoanWh.Application__r.CL_Contract__r.loan__Loan_Balance__c) : (objLoanWh.Application__r.CL_Contract__r.loan__Loan_Amount__c) )+ objLoanWh.Application__r.CL_Contract__r.loan__Interest_Accrued_Not_Due__c;
                        
                    }
                    newRecords.add(objLoanWh);
                    appId.add(objLoanWh.Application__c);
                    loanWarehouseIds.add(objLoanWh.Id);
                    System.debug('Test 4');
                }
            }
            if(newRecords != null && newRecords.size() > 0){
                System.debug('Test 5');
                update newRecords;
            }
            if(loanList != null && loanList.size() > 0){
                System.debug('Test 6');
                update loanList;
            }
            changeActive(appId,loanWarehouseIds);
            }
            catch(Exception e){
                insert new clcommon__Batch_Process_Log__c(clcommon__Message__c = 'LoanWarehouseChangeHelper :'+e.getStackTraceString()+':Error::'+e.getMessage(), clcommon__Timestamp__c = 
                                                      System.Now(),clcommon__Log_Level__c = 'ERROR'); 
                Database.rollback(sp);
                System.debug(e.getMessage());
                
            }
        }
}