force-app/main/default/objects/genesis__Employment_Information__c/genesis__Employment_Information__c.object-meta.xml
<CustomObject>
    <label>Employment Information</label>
    <nameField>
        <label>Employment Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employment Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Employment_Information__c/fields/Business_Income_Period__c.field-meta.xml
<CustomField>
    <fullName>Business_Income_Period__c</fullName>
    <label>Business Income Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Current</fullName>
            </value>
            <value>
                <fullName>Previous</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

elixir/force-app/main/default/objects/genesis__Employment_Information__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Document_Type_Set</valueSetName>
    </valueSet>
</CustomField>

elixir/force-app/main/default/objects/genesis__Employment_Information__c/fields/genesis__Application__c.field-meta.xml
<CustomField>
    <fullName>genesis__Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Employment Information</relationshipLabel>
    <relationshipName>Employment_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

elixir/force-app/main/default/objects/genesis__Employment_Information__c/fields/Total_Current_Income_Period__c.field-meta.xml
<CustomField>
    <fullName>Total_Current_Income_Period__c</fullName>
    <label>Total Current Income Period</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

elixir/force-app/main/default/objects/genesis__Employment_Information__c/fields/Total_Previous_Income_Period__c.field-meta.xml
<CustomField>
    <fullName>Total_Previous_Income_Period__c</fullName>
    <label>Total Previous Income Period</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/genesis__Income__c/genesis__Income__c.object-meta.xml
<CustomObject>
    <description>This object will track the other income</description>
    <label>Income</label>
    <nameField>
        <label>Income Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incomes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Income__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full</fullName>
            </value>
            <value>
                <fullName>Alt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

elixir/force-app/main/default/objects/genesis__Income__c/fields/Employment_Information__c.field-meta.xml
<CustomField>
    <fullName>Employment_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employment Information</label>
    <referenceTo>genesis__Employment_Information__c</referenceTo>
    <relationshipLabel>Incomes</relationshipLabel>
    <relationshipName>Incomes</relationshipName>
    <type>Lookup</type>
</CustomField>

elixir/force-app/main/default/objects/genesis__Income__c/fields/genesis__Amount__c.field-meta.xml
<CustomField>
    <fullName>genesis__Amount__c</fullName>
    <description>The amount of other income</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/genesis__Income__c/fields/genesis__Application__c.field-meta.xml
<CustomField>
    <fullName>genesis__Application__c</fullName>
    <description>Master-Detail relationship for income</description>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Incomes</relationshipLabel>
    <relationshipName>Incomes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

elixir/force-app/main/default/globalValueSets/Document_Type_Set.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Full</fullName>
    </customValue>
    <customValue>
        <fullName>Alt</fullName>
    </customValue>
    <masterLabel>Document Type Set</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/IncomeSummary.cls
/******************************************
* Descrption : This class is used to summarize the Business Income(Current Period & Previous Period) for a 
            individual Employee(Self Employed table in Employment & Income Details Tab in skuid).
            This class is IncomeSummary.IncomeSummarySkuidCallout(Id appId) called from skuid snippet.
*
* Developer : Soumik Sarkar
*************************************************/


global without sharing class IncomeSummary{
    global static void summaryValue(Id appId){
        try{
            //variable declaration

            List<genesis__Employment_Information__c> employmentToUpdate = new List<genesis__Employment_Information__c>() ;
            Map<Id,List<genesis__Income__c>> employmentIdVsIncome = new Map<Id,List<genesis__Income__c>>() ;
            //Query on Income records using appId
            List<genesis__Income__c> incomeRecords = [Select id,
                                                             Employment_Information__c,
                                                             Employment_Information__r.Company_Name__c,
                                                             Employment_Information__r.Document_Type__c,
                                                             Business_Income_Period__c,
                                                             Document_Type__c ,
                                                             genesis__Amount__c
                                                      From  genesis__Income__c
                                                      Where genesis__Application__c =: appId
                                                      AND Employment_Information__r.Document_Type__c =: ConstantValues.FullDocType
                                                      AND Employment_Information__r.RecordType.DeveloperName =: ConstantValues.SelfEmpRecordType
                                                      Order by Employment_Information__r.Company_Name__c ASC] ;
            System.debug('==IncomeRecords=='+incomeRecords) ;
            
            if(incomeRecords.size()>0){
                for(genesis__Income__c income : incomeRecords){
                    if(employmentIdVsIncome.containsKey(income.Employment_Information__c)){
                        employmentIdVsIncome.get(income.Employment_Information__c).add(income) ;
                    }
                    else{
                        employmentIdVsIncome.put(income.Employment_Information__c,new List<genesis__Income__c>{income}) ;
                    }
                }
            }
            System.debug('==EmploymentIdVsIncomeMap=='+employmentIdVsIncome) ;
            
            //Query on Employemnt Information Record using Company Map Keyset
            Map<Id,genesis__Employment_Information__c> employmentIdVsInstanceMap = new Map<Id,genesis__Employment_Information__c>([SELECT id,
                                                                                                                                          Company_Name__c
                                                                                                                                   FROM genesis__Employment_Information__c
                                                                                                                                   WHERE Id IN : employmentIdVsIncome.keySet()]) ;
            System.debug('==EmploymentIdVsInstanceMap=='+employmentIdVsInstanceMap) ;
            
            //Iterate all income records
            for(Id employmentId : employmentIdVsIncome.keySet()){
                //Initialize current and previous income as zero for every employment record
                double currectIncome = 0 ;
                double previousIncome = 0 ;
                //Iterate all income records or a employment and summing up current and previous income separately
                for(genesis__Income__c income : employmentIdVsIncome.get(employmentId)){
                    if(income.Business_Income_Period__c!=null && income.Business_Income_Period__c!='' && income.Business_Income_Period__c=='Current'){
                        currectIncome = currectIncome + income.genesis__Amount__c ;
                    }
                    else if(income.Business_Income_Period__c!=null && income.Business_Income_Period__c!='' && income.Business_Income_Period__c=='Previous'){
                        previousIncome = previousIncome + income.genesis__Amount__c ;
                    }
                }
                employmentIdVsInstanceMap.get(employmentId).Total_Current_Income_Period__c = currectIncome ;
                employmentIdVsInstanceMap.get(employmentId).Total_Previous_Income_Period__c = previousIncome ;
                employmentToUpdate.add(employmentIdVsInstanceMap.get(employmentId)) ;
            }
            //Check list size and update
            if(employmentToUpdate.size()>0){
                update employmentToUpdate ;
            }
            if(Test.isRunningTest()){
                Integer  a=5;
                Integer b= a/0;

            }
        }
        catch(Exception e){
            insert new clcommon__Log__c(
                            clcommon__Message__c = 'Exception: '+e.getStackTraceString()+'error='+e.getMessage()+' at Line Number '+e.getLineNumber(),
                            clcommon__Time__c = System.Now()
                            );
        }
    }
    
    
    Webservice static String IncomeSummarySkuidCallout(Id appId){
        Savepoint sp;

        try{
            sp = Database.setSavepoint();
            summaryValue(appId);
            return ConstantValues.msg;    
        }catch(Exception e){
            Database.rollback(sp);
            return e.getMessage();
        }
    }
}