force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Applications__c/fields/Check_Status_Change__c.field-meta.xml
<CustomField>
    <fullName>Check_Status_Change__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Check Status  Change</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Status__c.field-meta.xml
<CustomField>
    <fullName>genesis__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>App Received</fullName>
                <default>true</default>
                <label>App Received</label>
            </value>
            <value>
                <fullName>App Processed</fullName>
            </value>
            <value>
                <fullName>Conditional Assessed</fullName>
            </value>
            <value>
                <fullName>Conditionally Approved</fullName>
            </value>
            <value>
                <fullName>Conditional Accepted</fullName>
            </value>
            <value>
                <fullName>Assessment in Progress</fullName>
            </value>
            <value>
                <fullName>Recommended</fullName>
            </value>
            <value>
                <fullName>Formally Approved</fullName>
            </value>
            <value>
                <fullName>Solicitor Instructed</fullName>
            </value>
            <value>
                <fullName>LOO Issued</fullName>
            </value>
            <value>
                <fullName>LOO Accepted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Approved - Converted to Contract</fullName>
            </value>
            <value>
                <fullName>Loan Settled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/Solicitor_Status__c.field-meta.xml
<CustomField>
    <fullName>Solicitor_Status__c</fullName>
    <description>RJohnston 23/5/22 - https://wingategroup.atlassian.net/jira/software/c/projects/AMS/boards/8?modal=detail&amp;selectedIssue=AMS-1237
For recording where the settlement process is with the solicitor</description>
    <label>Solicitor Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Instructions Received</fullName>
            </value>
            <value>
                <fullName>Matter On Hold</fullName>
            </value>
            <value>
                <fullName>File in Doc Prep QA</fullName>
            </value>
            <value>
                <fullName>Docs Sent</fullName>
            </value>
            <value>
                <fullName>Docs Returned</fullName>
            </value>
            <value>
                <fullName>Outstanding Requirements</fullName>
            </value>
            <value>
                <fullName>Docs Verified</fullName>
            </value>
            <value>
                <fullName>File in Settlement QA</fullName>
            </value>
            <value>
                <fullName>Ready to Book</fullName>
            </value>
            <value>
                <fullName>Settlement Booked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NextGenBCMCallout.cls
/****************************************************************************************************
Company: Cloudkaptan Consultancy Services Pvt. Ltd.
Author: Ariz Mazhary
Description : This class the callout class for sending BCM to NextGen.
Development Date : 09/05/2022
Last Modified Date : 18/05/2022
Devloper's comment : Some part of the codes are hardcoded and not been put in Constant Classes - since
                    they are referenced only here and its a one time use.
****************************************************************************************************/

global with sharing class NextGenBCMCallout {
    public static void searchByAppId(Id appId){
        Map<String, Object> queryIdMap = new Map<String, Object>();
    	Map<String, Object> requestParamMap = new Map<String, Object>();
        try{
            StaticResource nextGenBCMRequest = [SELECT Body
                                            FROM StaticResource 
                                            WHERE Name = 'NextGenBCMRequestBody'
                                            LIMIT 1];
            List<genesis__Applications__c> applicationList=[SELECT id,
                                                                Solicitor_Status__c,
                                                                genesis__Status__c,
                                                                Check_Status_Change__c 
                                                                FROM genesis__Applications__c 
                                                                WHERE id=:appId];

            String uniqueId=getUUID();
            queryIdMap.put('appId', appId);
            requestParamMap.put(
                'nextGenXMLRequestBody',
                nextGenBCMRequest.Body.toString()
            );
            requestParamMap.put(
                'messageBatch',
                'MessageBatch-'+uniqueId
            );
            requestParamMap.put(
                'message',
                'Message-'+uniqueId
            );
            if(applicationList.size()>0){
                if(applicationList[0].Check_Status_Change__c==true 
                    && (applicationList[0].Solicitor_Status__c==ConstantValues.READY_TO_BOOK 
                    || applicationList[0].Solicitor_Status__c==ConstantValues.SETTLEMENT_BOOKED)){
                    requestParamMap.put(
                        'appStatus',
                        applicationList[0].Solicitor_Status__c
                    );
                }else{
                    requestParamMap.put(
                        'appStatus',
                        applicationList[0].genesis__Status__c
                    );
                }
            }
            
            intframework.AbstractIntegrationService baseintegrationService = intframework.IntegrationServiceFactory.getBaseIntegrationService();
            intframework.BaseIntegrationResponse responseObject;

            // Calling the adapter class, by specifying integraiton family and api type in the base integration service
            responseObject = (intframework.BaseIntegrationResponse) baseintegrationService.runSynchronousIntegrationService(
                'NextGen BCM',
                'NextGen BCM API',
                queryIdMap,
                requestParamMap
            );

        } catch(Exception exe){
            GenericUtility.insertLog(
                'NextGenBCMCallout',
                exe
            );
        }      
                
    }

    public static String getUUID()
    {
        Blob b = Crypto.GenerateAESKey(128);
        String h = EncodingUtil.ConvertTohex(b);
        String guid;
        if(h.length()>=20){
            guid= h.SubString(0,8)+ '-' + h.SubString(8,12) + '-' + 
                    h.SubString(12,16) + '-' + h.SubString(16,20) + '-' + h.substring(20);
        }
        return guid;
    }

    @InvocableMethod(
    label='call seachByAppId callout Method'
    description='Call seachByAppId callout'
    )
    public static void nextGenBCMCallout(List<Id> appIdList){
        try{
            for(Id appId:appIdList){
                searchByAppId(appId);
            }
        }catch(Exception exe){
            GenericUtility.insertLog(
                'NextGenBCMCallout',
                exe
            );
        }
        
    }
}