force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Status__c.field-meta.xml
<CustomField>
    <fullName>genesis__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>App Received</fullName>
                <default>true</default>
                <label>App Received</label>
            </value>
            <value>
                <fullName>App Processed</fullName>
            </value>
            <value>
                <fullName>Conditional Assessed</fullName>
            </value>
            <value>
                <fullName>Conditionally Approved</fullName>
            </value>
            <value>
                <fullName>Conditional Accepted</fullName>
            </value>
            <value>
                <fullName>Assessment in Progress</fullName>
            </value>
            <value>
                <fullName>Recommended</fullName>
            </value>
            <value>
                <fullName>Formally Approved</fullName>
            </value>
            <value>
                <fullName>Solicitor Instructed</fullName>
            </value>
            <value>
                <fullName>LOO Issued</fullName>
            </value>
            <value>
                <fullName>LOO Accepted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Approved - Converted to Contract</fullName>
            </value>
            <value>
                <fullName>Loan Settled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DocumentCategoryCreationBatch.cls
/**************************************************************************
Company : CloudKaptan Consultancy Services Pvt. Ltd.
Developer : Rameswari Barman
Development Date : 23/04/2021
Last Modified By : Rameswari Barman
Last Modified Date : 23/04/2021
Description : This class is used to make Document categories 
by assigning applications in small chunks so that governer limits are not met
***************************************************************************/
global class DocumentCategoryCreationBatch implements Database.Batchable<sObject> {
    global Database.QueryLocator start(Database.BatchableContext bc) {
      DateTime lastDocCreatedDate = Date.newInstance(Integer.valueOf(Label.DocumentCreationLastDate.split('-').get(2)),Integer.valueOf(Label.DocumentCreationLastDate.split('-').get(1)),Integer.valueOf(Label.DocumentCreationLastDate.split('-').get(0)));
      List <String> validStatusList = System.label.DocumentCreationStatus.split(',');
      if(Test.isRunningTest() == true){
        return Database.getQueryLocator(
          [
            SELECT Id
            FROM genesis__Applications__c
            WHERE genesis__Status__c IN: validStatusList
          ]
        );
      }
      else{
        return Database.getQueryLocator(
          [
            SELECT Id
            FROM genesis__Applications__c
            WHERE CreatedDate  <: lastDocCreatedDate
            AND genesis__Status__c IN: validStatusList
          ]
        );
      }
    }
    global void execute(Database.BatchableContext bc, List<genesis__Applications__c> scope) {
      try{
        if (scope != null && !scope.isEmpty()) {
          CreateDocumentCategories.createLoanLevelDocFolders(scope);
          CreateDocumentCategories.createReviewDocFolders(scope);
          CreateDocumentCategories.createSecurityDocFolders(scope);
          CreateDocumentCategories.createpartyDocFolders(scope);
          CreateDocumentCategories.createIndividualEmpPartyDocFolders(scope);
          CreateDocumentCategories.createIndentityDocFolders(scope);
          CreateDocumentCategories.createIndividualEmploymentSubFolders(scope);
          CreateDocumentCategories.createNonIndividualEmpIncomeDocFolders(scope);
          CreateDocumentCategories.createHouseholdPartyDocFolders(scope);
        }
      }
      catch(Exception ex){
        GenericUtility.insertLog('DocumentCategoryCreationBatch', ex);
      }
    }
    global void finish(Database.BatchableContext bc) {
    }
  }