force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Applications__c/fields/Actual_Security_Value__c.field-meta.xml
<CustomField>
    <fullName>Actual_Security_Value__c</fullName>
    <label>Actual Security Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <customHelpPage>loan__CLContractHelp</customHelpPage>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Account__c/fields/Actual_Security_Value__c.field-meta.xml
<CustomField>
    <fullName>Actual_Security_Value__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Actual Security Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Elixir_Prod/force-app/main/default/objects/loan__Loan_Account__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>CL Contracts</relationshipLabel>
    <relationshipName>CL_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Current_Loan_Balance_Excluding_Deposit__c.field-meta.xml
<CustomField>
    <fullName>Current_Loan_Balance_Excluding_Deposit__c</fullName>
    <formula>loan__Loan_Balance__c- Deposit_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Current Loan Balance Excluding Deposit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Current_Total_of_Discharged_Securities__c.field-meta.xml
<CustomField>
    <fullName>Current_Total_of_Discharged_Securities__c</fullName>
    <label>Current Total # of Discharged Securities</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Current_Total_of_Securities__c.field-meta.xml
<CustomField>
    <fullName>Current_Total_of_Securities__c</fullName>
    <label>Current Total # of Securities</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

elixir/force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Approval_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Approval_Date__c</fullName>
    <inlineHelpText>The date on which the loan is approved.</inlineHelpText>
    <label>Approval Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Loan_Status__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Status__c</fullName>
    <inlineHelpText>Status of the Account expected values are :
Pending Approval
Active - Good Standing
Active - Bad Standing
Active - Matured
Approved
Canceled
Closed - Obligations met
Closed- Written Off
Closed - Refinanced
Partial Application
Closed - Premature</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active - Bad Standing</fullName>
            </value>
            <value>
                <fullName>Active - Good Standing</fullName>
            </value>
            <value>
                <fullName>Active - Marked for Closure</fullName>
            </value>
            <value>
                <fullName>Active - Matured</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Closed - Obligations met</fullName>
            </value>
            <value>
                <fullName>Closed - Premature</fullName>
            </value>
            <value>
                <fullName>Closed - Refinanced</fullName>
            </value>
            <value>
                <fullName>Closed- Written Off</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>Partial Application</fullName>
                <default>true</default>
                <label>Partial Application</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Premature Closure Initiated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/MIP_LVR__c.field-meta.xml
<CustomField>
    <fullName>MIP_LVR__c</fullName>
    <label>MIP LVR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Original_Total_of_Securities__c.field-meta.xml
<CustomField>
    <fullName>Original_Total_of_Securities__c</fullName>
    <label>Original Total # of Securities</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Risk_LVR__c.field-meta.xml
<CustomField>
    <fullName>Risk_LVR__c</fullName>
    <label>Risk LVR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/LoanCollateralGenerationBatch.cls
/****************************************************************************************************
Company: Cloudkaptan Consultancy Services Pvt. Ltd.
Author: Ariz Mazhary
Description : This class create Loan Collateral Records for existing Cl Contract.
Development Date : 14/02/2022
Last Modified Date : 24/02/2022
****************************************************************************************************/

public class LoanCollateralGenerationBatch implements DataBase.StateFul,DataBase.Batchable<sObject> {
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([SELECT id,
                                                Current_Loan_Balance_Excluding_Deposit__c,
                                                loan__Payment_Mode__c,
                                                loan__Loan_Purpose__c,
                                                loan__Approval_Date__c,
                                                Original_Total_of_Securities__c,
                                                Actual_Security_Value__c,
                                                Current_Total_of_Securities__c,
                                                Current_Total_of_Discharged_Securities__c,
                                                Risk_LVR__c,
                                                MIP_LVR__c,
                                                Application__c,
                                                Application__r.id
                                            FROM loan__Loan_Account__c 
                                            WHERE loan__Loan_Status__c !=: ConstantValues.CLOSED_OBLIGATIONS_MET ]);
    }
    public void execute(Database.BatchableContext bc, List<loan__Loan_Account__c> objLoanList) {
        try{
            ConvertToContract.collateralValues(objLoanList[0].Application__r.id,objLoanList[0].id);
            ConvertToContract.updateClContract(objLoanList);
            if(test.isRunningTest()){
                Integer a = 4/0;
            }
        }catch(Exception exe){
            GenericUtility.insertBatchProcessLog('LoanCollateralGenerationBatch',exe);
        }
    }
	public void finish(Database.BatchableContext bc){
    }
}