force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Applications__c/fields/Repayment_Type__c.field-meta.xml
<CustomField>
    <fullName>Repayment_Type__c</fullName>
    <label>Repayment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Principal and Interest</fullName>
            </value>
            <value>
                <fullName>Interest Only reverting to Principal and Interest</fullName>
            </value>
            <value>
                <fullName>Interest Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <customHelpPage>loan__CLContractHelp</customHelpPage>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Account__c/fields/Calculated_Upcoming_Repayment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Calculated_Upcoming_Repayment_Amount__c</fullName>
    <formula>IF( !ISBLANK(New_Interest_Rate__c) &amp;&amp; !ISBLANK( New_Interest_Rate_Effective_Date__c) &amp;&amp; ISPICKVAL(Repayment_Type__c , &apos;Principal and Interest&apos;),((New_Interest_Rate__c /12)*((1+( New_Interest_Rate__c /12))^ Remaining_Loan_Term__c ))/((1+(New_Interest_Rate__c/12))^ Remaining_Loan_Term__c -1)* loan__Loan_Balance__c,0.0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Calculated Upcoming Repayment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/First_Repayment_Date__c.field-meta.xml
<CustomField>
    <fullName>First_Repayment_Date__c</fullName>
    <label>First Repayment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/First_Repayment_Date_After_IR_Change__c.field-meta.xml
<CustomField>
    <fullName>First_Repayment_Date_After_IR_Change__c</fullName>
    <label>First Repayment Date After IR Change</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Flat_Repayment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Flat_Repayment_Amount__c</fullName>
    <label>Flat Repayment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Interest_Rate_Change_Notification_Date__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate_Change_Notification_Date__c</fullName>
    <label>Interest Rate Change Notification Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Delinquent_Amount__c.field-meta.xml
<CustomField>
    <fullName>loan__Delinquent_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Total Unpaid bills/invoices amount on this account.</inlineHelpText>
    <label>Delinquent Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Due_Day__c.field-meta.xml
<CustomField>
    <fullName>loan__Due_Day__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Due Day for the loan account.</description>
    <inlineHelpText>The day on which the loan payment is due.</inlineHelpText>
    <label>Current Due Day</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Frequency_of_Loan_Payment__c.field-meta.xml
<CustomField>
    <fullName>loan__Frequency_of_Loan_Payment__c</fullName>
    <inlineHelpText>This decides the Payment Frequency, below are the supported ones:
Daily
Weekly
Bi-weekly
Semi-Monthly
Monthly
Bi-Monthly
Quarterly
Semi-Annual
Annual
Single-Payment</inlineHelpText>
    <label>Payment Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Bi-weekly</fullName>
            </value>
            <value>
                <fullName>Semi-Monthly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
                <default>true</default>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Semi-Annual</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Single-Payment</fullName>
            </value>
            <value>
                <fullName>Semi-Monthly-PD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

elixir/force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>loan__Interest_Rate__c</fullName>
    <description>Interest Rate</description>
    <inlineHelpText>Rate of Interest for the loan.</inlineHelpText>
    <label>Current Interest Rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Invalid_Data__c.field-meta.xml
<CustomField>
    <fullName>loan__Invalid_Data__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If system identify any data issues with this lending account, the reasons will be displayed on the top of lending account and this flag will be checked.
Once the issues are fixed, this flag will be unchecked by system.
User should not modify this flag.</inlineHelpText>
    <label>Invalid Data</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Loan Amount</description>
    <inlineHelpText>This is the financed amount on the contract which will be disbursed to the customer.</inlineHelpText>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Loan_Status__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Status__c</fullName>
    <inlineHelpText>Status of the Account expected values are :
Pending Approval
Active - Good Standing
Active - Bad Standing
Active - Matured
Approved
Canceled
Closed - Obligations met
Closed- Written Off
Closed - Refinanced
Partial Application
Closed - Premature</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active - Bad Standing</fullName>
            </value>
            <value>
                <fullName>Active - Good Standing</fullName>
            </value>
            <value>
                <fullName>Active - Marked for Closure</fullName>
            </value>
            <value>
                <fullName>Active - Matured</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Closed - Obligations met</fullName>
            </value>
            <value>
                <fullName>Closed - Premature</fullName>
            </value>
            <value>
                <fullName>Closed - Refinanced</fullName>
            </value>
            <value>
                <fullName>Closed- Written Off</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>Partial Application</fullName>
                <default>true</default>
                <label>Partial Application</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Premature Closure Initiated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Pmt_Amt_Cur__c.field-meta.xml
<CustomField>
    <fullName>loan__Pmt_Amt_Cur__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Current Payment Amount</description>
    <inlineHelpText>This is the current installment amount that needs to be paid.</inlineHelpText>
    <label>Current Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

elixir/force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Uncleared_Repayment_Amount__c.field-meta.xml
<CustomField>
    <fullName>loan__Uncleared_Repayment_Amount__c</fullName>
    <description>The repaid amount, which has not yet been supervised.</description>
    <inlineHelpText>The reapaid amount, which has not yet been supervised.</inlineHelpText>
    <label>Uncleared Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/New_Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>New_Interest_Rate__c</fullName>
    <label>New Interest Rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/New_Interest_Rate_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>New_Interest_Rate_Effective_Date__c</fullName>
    <label>New Interest Rate Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Remaining_IO_Period__c.field-meta.xml
<CustomField>
    <fullName>Remaining_IO_Period__c</fullName>
    <label>Remaining IO Period</label>
    <summaryFilterItems>
        <field>loan__Repayment_Schedule__c.loan__Is_Archived__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>loan__Repayment_Schedule__c.loan__Due_Principal__c</field>
        <operation>equals</operation>
        <value>0</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>loan__Repayment_Schedule__c.loan__Is_Billed__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryForeignKey>loan__Repayment_Schedule__c.loan__Loan_Account__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Remaining_Loan_Term__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Loan_Term__c</fullName>
    <formula>MONTH(loan__Maturity_Date_Current__c) + 12 - MONTH($User.loan__Current_Branch_s_System_Date__c)+12*(YEAR(loan__Maturity_Date_Current__c)-YEAR($User.loan__Current_Branch_s_System_Date__c)-1)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remaining Loan Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Remaining_Term_from_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Term_from_Schedule__c</fullName>
    <label>Remaining Term from Schedule</label>
    <summaryFilterItems>
        <field>loan__Repayment_Schedule__c.loan__Is_Billed__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>loan__Repayment_Schedule__c.loan__Is_Archived__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryForeignKey>loan__Repayment_Schedule__c.loan__Loan_Account__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Repayment_Type__c.field-meta.xml
<CustomField>
    <fullName>Repayment_Type__c</fullName>
    <label>Repayment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Principal and Interest</fullName>
            </value>
            <value>
                <fullName>Interest Only reverting to Principal and Interest</fullName>
            </value>
            <value>
                <fullName>Interest Only</fullName>
            </value>
            <value>
                <fullName>Prepaid Interest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Scheduled_Balance_As_at_IR_change_date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Balance_As_at_IR_change_date__c</fullName>
    <label>Scheduled Balance As at IR change date</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Second_Repayment_Date__c.field-meta.xml
<CustomField>
    <fullName>Second_Repayment_Date__c</fullName>
    <label>Second Repayment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Second_Repayment_Date_After_IR_Change__c.field-meta.xml
<CustomField>
    <fullName>Second_Repayment_Date_After_IR_Change__c</fullName>
    <label>Second Repayment Date After IR Change</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/InterestRateChangeBatchTest.cls
/**********************************************************************************************************************************************************
Company : CloudKaptan Consultancy Services Pvt. Ltd.
Developer : Sayak Mukhopadhyay
Development Date : 26/05/2022
Last Modified By : Sayak Mukhopadhyay
Last Modified Date : 27/05/2022
Description : This is the test class for InterestRateChangeBatch and InterestRateChangeHandler
 
***********************************************************************************************************************************************************/


@isTest(SeeAllData = false)
public class InterestRateChangeBatchTest{
    @TestSetup
    static void initialize(){
        Date currentSystemDate = Date.Today();
          //Inserting Account 
        Account objAccount = GenericUtilityTestHelper.insertDummyAccount();
        System.AssertNotEquals(
            objAccount.Id,
            null,
            'Account inserted successfully.'
        );
        // Inserting Application
        genesis__applications__c objApplication = GenericUtilityTestHelper.returnApplication(objAccount.id);
        System.AssertNotEquals(
            objApplication.Id,
            null,
            'Application inserted successfully.'
        );
        //Inserting Contract
        loan__Loan_Account__c objContract = GenericUtilityTestHelper.returnLoanAccount();
        objContract.New_Interest_Rate__c = 5;
        objContract.New_Interest_Rate_Effective_Date__c = currentSystemDate;
        objContract.loan__Interest_Type__c = 'Fixed';
        objContract.loan__Invalid_Data__c  = false;
        objContract.loan__Loan_Status__c = 'Active - Good Standing';
        objContract.loan__Uncleared_Repayment_Amount__c = 0;
        objContract.loan__Floating_Rate_Index__c = null;
        objContract.First_Repayment_Date_After_IR_Change__c = currentSystemDate + 23;
        objContract.First_Repayment_Date__c = date.today();
        objContract.Second_Repayment_Date__c=date.newInstance(2022, 8, 7);
        objContract.Interest_Rate_Change_Notification_Date__c = currentSystemDate + 1;
        objContract.Second_Repayment_Date_After_IR_Change__c = currentSystemDate + 46;
        objContract.loan__Interest_Rate__c = 3;
        objContract.Repayment_Type__c='Principal and Interest';
        objContract.loan__Pmt_Amt_Cur__c=3000;
        objContract.loan__Due_Day__c = (currentSystemDate + 23).day();
        update objContract;
        System.AssertNotEquals(
            objContract.Id,
            null,
            'Contract inserted successfully.'
        );

        //Inserting Payment
        loan__Payment_Mode__c objPaymentMode=GenericUtilityTestHelper.getPaymentMode();
        List<loan__Payment_Mode__c> objPaymentModeList=[SELECT id FROM loan__Payment_Mode__c WHERE Name='Direct Debit'];
        System.assertEquals(
            objPaymentModeList.size(), 
            1, 
            'Payment Mode Inserted'
        );

        //Inserting APS
        loan__Automated_Payment_Setup__c objAPS=GenericUtilityTestHelper.returnAPS(objContract.id,objPaymentMode.id);
        objAPS.Created_after_reschedule__c=true;
        objAPS.loan__Amount_Type__c='FIXED AMOUNT';
        update objAPS;
        List<loan__Automated_Payment_Setup__c> objAPSList=[SELECT id FROM loan__Automated_Payment_Setup__c WHERE Created_after_reschedule__c=true AND loan__Amount_Type__c='FIXED AMOUNT'];
        System.assertEquals(
            objAPSList.size(), 
            1, 
            'Payment Mode Inserted'
        );
    }
    @isTest
    static void InterestRateChangeBatchTestMethodeOne(){
        test.startTest();
        List<loan__Loan_Account__c>objContractList = [SELECT id,
                                               Name,
                                               New_Interest_Rate__c,
                                               New_Interest_Rate_Effective_Date__c,
                                               loan__Next_Installment_Date__c,
                                               Calculated_Upcoming_Repayment_Amount__c,
                                               loan__Interest_Rate__c,
                                               Repayment_Type__c ,
                                               Remaining_Loan_Term__c,
                                               Remaining_Term_from_Schedule__c,
                                               Remaining_IO_Period__c,
                                               loan__Due_Day__c,
                                               loan__Frequency_of_Loan_Payment__c,
                                               Interest_Rate_Change_Notification_Date__c,
                                               First_Repayment_Date_After_IR_Change__c,
                                               Second_Repayment_Date_After_IR_Change__c,
                                               loan__Pmt_Amt_Cur__c,
                                               loan__Uncleared_Repayment_Amount__c,
                                               loan__Loan_Status__c,
                                               loan__Delinquent_Amount__c
                                        FROM loan__Loan_Account__c];                  
        InterestRateChangeBatch obj = new InterestRateChangeBatch();
        String sch = '0 0 23 * * ?';
        system.schedule('Test Check', sch, obj );
        test.stopTest();
    }
    @isTest
    static void InterestRateChangeBatchTestMethodeTwo(){
        test.startTest();
        List<loan__Loan_Account__c>objContractList = [SELECT id,
                                               Name,
                                               New_Interest_Rate__c,
                                               New_Interest_Rate_Effective_Date__c,
                                               loan__Next_Installment_Date__c,
                                               Calculated_Upcoming_Repayment_Amount__c,
                                               loan__Interest_Rate__c,
                                               Repayment_Type__c ,
                                               Remaining_Loan_Term__c,
                                               Remaining_Term_from_Schedule__c,
                                               Remaining_IO_Period__c,
                                               loan__Due_Day__c,
                                               loan__Frequency_of_Loan_Payment__c,
                                               Interest_Rate_Change_Notification_Date__c,
                                               First_Repayment_Date_After_IR_Change__c,
                                               Second_Repayment_Date_After_IR_Change__c,
                                               loan__Pmt_Amt_Cur__c,
                                               loan__Uncleared_Repayment_Amount__c,
                                               loan__Loan_Status__c,
                                               loan__Delinquent_Amount__c
                                        FROM loan__Loan_Account__c];
        if(objContractList.size()>0){
            objContractList[0].First_Repayment_Date_After_IR_Change__c = Date.Today() + 1;
            objContractList[0].Interest_Rate_Change_Notification_Date__c = Date.Today() + 5;
            objContractList[0].Second_Repayment_Date_After_IR_Change__c = Date.Today() + 30;
            objContractList[0].loan__Due_Day__c = (Date.Today() + 1).day();
        }
        Database.update(objContractList,false);
        Date firstRepaymentDateAfterIrChange = Date.Today() + 1;
        List<loan__Loan_Account__c> objLoanAccountList = [SELECT id,
                                        First_Repayment_Date_After_IR_Change__c,
                                        Interest_Rate_Change_Notification_Date__c,
                                        New_Interest_Rate_Effective_Date__c,
                                        Second_Repayment_Date_After_IR_Change__c,
                                        loan__Due_Day__c
                                        FROM loan__Loan_Account__c
                                        WHERE First_Repayment_Date_After_IR_Change__c =: firstRepaymentDateAfterIrChange];
        if(objLoanAccountList.size()>0){
            InterestRateChangeBatch obj = new InterestRateChangeBatch();
            String sch = '0 0 23 * * ?';
            system.schedule('Test Check', sch, obj );
        }
        test.stopTest();
    }
    @isTest
    static void InterestRateChangeBatchTestMethodeThree(){
        test.startTest();
        List<loan__Loan_Account__c>objContractList = [SELECT id,
                                               Name,
                                               New_Interest_Rate__c,
                                               New_Interest_Rate_Effective_Date__c,
                                               loan__Next_Installment_Date__c,
                                               Calculated_Upcoming_Repayment_Amount__c,
                                               loan__Interest_Rate__c,
                                               Repayment_Type__c ,
                                               Remaining_Loan_Term__c,
                                               Remaining_Term_from_Schedule__c,
                                               Remaining_IO_Period__c,
                                               loan__Due_Day__c,
                                               loan__Frequency_of_Loan_Payment__c,
                                               Interest_Rate_Change_Notification_Date__c,
                                               First_Repayment_Date_After_IR_Change__c,
                                               Second_Repayment_Date_After_IR_Change__c,
                                               loan__Pmt_Amt_Cur__c,
                                               loan__Uncleared_Repayment_Amount__c,
                                               loan__Loan_Status__c,
                                               loan__Delinquent_Amount__c
                                        FROM loan__Loan_Account__c];
        if(objContractList.size()>0){
            objContractList[0].First_Repayment_Date_After_IR_Change__c = Date.Today() + 1;
            objContractList[0].Interest_Rate_Change_Notification_Date__c = Date.Today() + 5;
            objContractList[0].Second_Repayment_Date_After_IR_Change__c = Date.Today() + 30;
            objContractList[0].loan__Due_Day__c = ((Date.Today() + 1).day())+1;
        }
        Database.update(objContractList,false);
        Date firstRepaymentDateAfterIrChange = Date.Today() + 1;
        List<loan__Loan_Account__c> objLoanAccountList = [SELECT id,
                                        First_Repayment_Date_After_IR_Change__c,
                                        Interest_Rate_Change_Notification_Date__c,
                                        New_Interest_Rate_Effective_Date__c,
                                        Second_Repayment_Date_After_IR_Change__c,
                                        loan__Due_Day__c
                                        FROM loan__Loan_Account__c
                                        WHERE First_Repayment_Date_After_IR_Change__c =: firstRepaymentDateAfterIrChange];
        if(objLoanAccountList.size()>0){
            InterestRateChangeBatch obj = new InterestRateChangeBatch();
            String sch = '0 0 23 * * ?';
            system.schedule('Test Check', sch, obj );
        }
        test.stopTest();
    }
    @isTest
    static void InterestRateChangeBatchTestMethodeFour(){

        test.startTest();
        
        List<loan__Automated_Payment_Setup__c> objAPSList=[SELECT id FROM loan__Automated_Payment_Setup__c];
        objAPSList[0].loan__Type__c='RECURRING';
        objAPSList[0].loan__Frequency__c='Monthly';
        objAPSList[0].loan__Actual_Date__c=date.today();
        //objAPSList[0].loan__Debit_Date__c=date.newinstance(2022,11,1);
        update objAPSList;
        List<loan__Automated_Payment_Setup__c> objAPSList2=[SELECT id FROM loan__Automated_Payment_Setup__c WHERE loan__Type__c='RECURRING' AND loan__Frequency__c='Monthly'];
        System.assertEquals(
            objAPSList2.size(), 
            1, 
            'APS Inserted'
        );

        List<Id> apsIdList=new List<Id>();
        apsIdList.add(objAPSList[0].id);
        OneTimeAPSCreation.oneTimeAPSCreationPILoan(apsIdList);
        test.stopTest();
    }
    @isTest
    static void InterestRateChangeBatchTestMethodFour(){

        test.startTest();
        List<loan__Loan_Account__c>objContractList = [SELECT id,
                                        Flat_Repayment_Amount__c,
                                        Interest_Rate_Change_Notification_Date__c
                                        FROM loan__Loan_Account__c];
        if(objContractList.size()>0){
            objContractList[0].Flat_Repayment_Amount__c = 3000;
        }
        update objContractList;
        List<loan__Loan_Account__c> objLoanList=[SELECT id 
                                                            FROM loan__Loan_Account__c 
                                                            WHERE Flat_Repayment_Amount__c=3000];
        System.assertEquals(
            objLoanList.size(), 
            1, 
            'Contract Inserted'
        );

        List<loan__Automated_Payment_Setup__c> objAPSList=[SELECT id FROM loan__Automated_Payment_Setup__c];
        objAPSList[0].loan__Type__c='RECURRING';
        objAPSList[0].loan__Frequency__c='Monthly';
        objAPSList[0].loan__Actual_Date__c=date.today();
        update objAPSList;
        List<loan__Automated_Payment_Setup__c> objAPSList2=[SELECT id FROM loan__Automated_Payment_Setup__c WHERE loan__Type__c='RECURRING' AND loan__Frequency__c='Monthly'];
        System.assertEquals(
            objAPSList.size(), 
            1, 
            'APS Inserted'
        );

        List<Id> apsIdList=new List<Id>();
        apsIdList.add(objAPSList[0].id);
        OneTimeAPSCreation.oneTimeAPSCreationPILoan(apsIdList);
        test.stopTest();
    }
    @isTest
    static void InterestRateChangeBatchTestMethodFive(){

        test.startTest();
        List<loan__Loan_Account__c>objContractList = [SELECT id,
                                        Flat_Repayment_Amount__c,
                                        First_Repayment_Date_After_IR_Change__c,
                                        Interest_Rate_Change_Notification_Date__c
                                        FROM loan__Loan_Account__c];
        if(objContractList.size()>0){
            objContractList[0].Flat_Repayment_Amount__c = 3000;
            objContractList[0].First_Repayment_Date_After_IR_Change__c = date.newinstance(2021,8,2);
            objContractList[0].Interest_Rate_Change_Notification_Date__c = date.newinstance(2021,8,10);
        }
        update objContractList;
        List<loan__Loan_Account__c> objLoanList=[SELECT id 
                                                            FROM loan__Loan_Account__c 
                                                            WHERE Flat_Repayment_Amount__c=3000];
        System.assertEquals(
            objLoanList.size(), 
            1, 
            'Contract Inserted'
        );

        List<loan__Automated_Payment_Setup__c> objAPSList=[SELECT id FROM loan__Automated_Payment_Setup__c];
        objAPSList[0].loan__Type__c='RECURRING';
        objAPSList[0].loan__Frequency__c='Monthly';
        objAPSList[0].loan__Actual_Date__c=date.today();
        update objAPSList;
        List<loan__Automated_Payment_Setup__c> objAPSList2=[SELECT id 
                                                            FROM loan__Automated_Payment_Setup__c 
                                                            WHERE loan__Type__c='RECURRING' 
                                                            AND loan__Frequency__c='Monthly'];
        System.assertEquals(
            objAPSList.size(), 
            1, 
            'APS Inserted'
        );

        List<Id> apsIdList=new List<Id>();
        apsIdList.add(objAPSList[0].id);
        OneTimeAPSCreation.oneTimeAPSCreationPILoan(apsIdList);
        test.stopTest();
    }
    @isTest
    static void UpdateFirstSecondPmntDateBatchTest(){
        test.startTest();
        List<loan__Loan_Account__c>objContractList = [SELECT Id,
                                            Name,
                                            First_Repayment_Date_After_IR_Change__c,
                                            Second_Repayment_Date_After_IR_Change__c,
                                            New_Interest_Rate_Effective_Date__c,
                                            New_Interest_Rate__c,
                                            Scheduled_Balance_As_at_IR_change_date__c,
                                            loan__Loan_Amount__c
                                            FROM loan__Loan_Account__c];
        if(objContractList.size()>0){
            UpdateFirstSecondPmntDateBatch obj = new UpdateFirstSecondPmntDateBatch();
            String sch = '0 0 22 * * ?';
            system.schedule('Test Check', sch, obj );
        }
        test.stopTest();
    }
    @isTest
    static void UpdateLastDueDayBatchTest(){
        test.startTest();
        
        List<loan__Loan_Account__c>objContractList = [SELECT Id,
                                                         Name,
                                                         loan__Previous_Installment_Date__c
                                                     FROM loan__Loan_Account__c
                                                     ORDER BY Id];
        if(objContractList.size()>0){
            // Inserting Bills
            loan__Loan_account_Due_Details__c objBill = GenericUtilityTestHelper.returnBill(objContractList[0].id);
            System.AssertNotEquals(
                objBill.Id,
                null,
                'Bill inserted successfully.'
            );
            objContractList[0].loan__Previous_Installment_Date__c = NULL;
            update objContractList;
            objContractList = [SELECT Id,
                                      Name,
                                      loan__Previous_Installment_Date__c
                                    FROM loan__Loan_Account__c
                                    WHERE loan__Previous_Installment_Date__c = NULL];
            System.AssertNotEquals(
                objContractList.size(),
                0,
                'Loan updated successfully.'
            );   
            LastDueDateUpdateBatch obj = new LastDueDateUpdateBatch();
            String sch = '0 0 22 * * ?';
            system.schedule('Test Check', sch, obj );
        }
        test.stopTest();
    }
}