force-app/main/default/objects/Account/fields/Approved__c.field-meta.xml
<CustomField>
    <fullName>Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Approved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Bank_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Name__c</fullName>
    <label>Bank Account Name</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Bank_Account_Name_Change__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Name_Change__c</fullName>
    <label>Bank Account Name Change</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

elixir/force-app/main/default/objects/Account/fields/loan__Active__c.field-meta.xml
<CustomField>
    <fullName>loan__Active__c</fullName>
    <label>Active</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Bank_Account__c/loan__Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <displayFormat>BA-{00000}</displayFormat>
        <label>Bank Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Bank_Account__c/fields/Account_Change__c.field-meta.xml
<CustomField>
    <fullName>Account_Change__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Change</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bank Accounts (Account Change)</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Bank_Account__c/fields/Account_Usage_Change__c.field-meta.xml
<CustomField>
    <fullName>Account_Usage_Change__c</fullName>
    <label>Account Usage Change</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Investor Trust Account</fullName>
            </value>
            <value>
                <fullName>Collections Trust Account</fullName>
            </value>
            <value>
                <fullName>Advance Trust Account</fullName>
            </value>
            <value>
                <fullName>Business Account</fullName>
            </value>
            <value>
                <fullName>Tax Withholding Account</fullName>
            </value>
            <value>
                <fullName>Borrower/Investor Account</fullName>
            </value>
            <value>
                <fullName>Broker Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Bank_Account__c/fields/Bank_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Name__c</fullName>
    <label>Bank Account Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Bank_Account__c/fields/Bank_Account_Name_Change__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Name_Change__c</fullName>
    <label>Bank Account Name Change</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Bank_Account__c/fields/Bank_Account_Number_Change__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Number_Change__c</fullName>
    <label>Bank Account Number Change</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Bank_Account__c/fields/Bank_Name_Change__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name_Change__c</fullName>
    <label>Bank Name Change</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Bank_Account__c/fields/BSB_Number__c.field-meta.xml
<CustomField>
    <fullName>BSB_Number__c</fullName>
    <label>BSB Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Bank_Account__c/fields/BSB_Number_Change__c.field-meta.xml
<CustomField>
    <fullName>BSB_Number_Change__c</fullName>
    <label>BSB Number Change</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Bank_Account__c/fields/Created_After_Conversion__c.field-meta.xml
<CustomField>
    <fullName>Created_After_Conversion__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Created After Conversion</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Bank_Account__c/fields/Field_Update__c.field-meta.xml
<CustomField>
    <fullName>Field_Update__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Field Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Bank_Account__c/fields/loan__Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Bank_Account__c/fields/loan__Account_Usage__c.field-meta.xml
<CustomField>
    <fullName>loan__Account_Usage__c</fullName>
    <label>Account Usage</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Investor Trust Account</fullName>
            </value>
            <value>
                <fullName>Collections Trust Account</fullName>
            </value>
            <value>
                <fullName>Advance Trust Account</fullName>
            </value>
            <value>
                <fullName>Business Account</fullName>
            </value>
            <value>
                <fullName>Tax Withholding Account</fullName>
            </value>
            <value>
                <fullName>Borrower/Investor Account</fullName>
            </value>
            <value>
                <fullName>Broker Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

elixir/force-app/main/default/objects/loan__Bank_Account__c/fields/loan__Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>loan__Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>50</length>
    <maskChar>X</maskChar>
    <maskType>lastFour</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

elixir/force-app/main/default/objects/loan__Bank_Account__c/fields/loan__Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>loan__Bank_Name__c</fullName>
    <label>Bank Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Bank_Account__c/fields/Submit_For_Approval__c.field-meta.xml
<CustomField>
    <fullName>Submit_For_Approval__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Submit For Approval</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <customHelpPage>loan__CLContractHelp</customHelpPage>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Account__c/fields/Bank_Detail_Change__c.field-meta.xml
<CustomField>
    <fullName>Bank_Detail_Change__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bank Detail Change</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Borrower_ACH_Change__c.field-meta.xml
<CustomField>
    <fullName>Borrower_ACH_Change__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Borrower ACH Change</label>
    <referenceTo>loan__Bank_Account__c</referenceTo>
    <relationshipLabel>CL Contracts (Borrower ACH Change)</relationshipLabel>
    <relationshipName>CL_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Please choose a account, which will be associated as a customer on this lending account.
You can create a new account, from the lookup window by clicking on new or select the existing account from the lookup.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Loan_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BankAccountTriggerHelper.cls
/****************************************************************************************************
Description:    This Class is a Helper Class for Bank Account Trigger
Developer:      Sayak Mukhopadhyay
Created Date:   11/03/2022
*****************************************************************************************************/

public class BankAccountTriggerHelper {
    public static void updateChangeField(List<loan__Bank_Account__c> newBankAccountList){
        Savepoint sp = Database.setSavepoint();
        try{
            for(loan__Bank_Account__c eachBankAccount : newBankAccountList) {
                eachBankAccount.Bank_Account_Number_Change__c = eachBankAccount.loan__Bank_Account_Number__c;
                eachBankAccount.Bank_Account_Name_Change__c = eachBankAccount.Bank_Account_Name__c;
                eachBankAccount.Bank_Name_Change__c = eachBankAccount.loan__Bank_Name__c;
                eachBankAccount.Account_Usage_Change__c = eachBankAccount.loan__Account_Usage__c;
                eachBankAccount.Active_Change__c = eachBankAccount.loan__Active__c;
                eachBankAccount.Account_Change__c = eachBankAccount.loan__Account__c;
                eachBankAccount.BSB_Number_Change__c = eachBankAccount.BSB_Number__c;
            }
        }catch(Exception e){
            GenericUtility.insertLog('BankAccountTriggerHelper',e); 
            Database.rollback(sp);
        }
    }
    public static void submitApprovalOnInsert(List<loan__Bank_Account__c> newBankAccountList){
        Savepoint sp = Database.setSavepoint();
        try{
            for(loan__Bank_Account__c eachBankAccount : newBankAccountList){
                if (!eachBankAccount.Created_After_Conversion__c){
                    submitForApproval(eachBankAccount);
                } 
                if(eachBankAccount.Created_After_Conversion__c){
                    submitForApproval(eachBankAccount);
                }
            }
        }catch(Exception e){
            GenericUtility.insertLog('BankAccountTriggerHelper',e);
            Database.rollback(sp);
        }
    }
public static void updateFields(List<loan__Bank_Account__c> newBankAccountList, Map<Id,loan__Bank_Account__c> oldMap){
        Savepoint sp = Database.setSavepoint();
        try{
            List<loan__Loan_Account__c> contractList = new List<loan__Loan_Account__c>();
            List<Id> bankAccountIdList = new List<Id>();
            for(loan__Bank_Account__c eachBankAccount : newBankAccountList){
                bankAccountIdList.add(eachBankAccount.id);
            }
            contractList = [SELECT id,
                                loan__Borrower_ACH__c,
                                Borrower_ACH_Change__c,
                                Bank_Detail_Change__c
                                FROM loan__Loan_Account__c
                                WHERE Borrower_ACH_Change__c in: bankAccountIdList];
            for(loan__Bank_Account__c eachBankAccount : newBankAccountList){
                if(!eachBankAccount.Submit_For_Approval__c && oldMap.get(eachBankAccount.id).Submit_For_Approval__c){
                    if(eachBankAccount.Approved__c) {
                        eachBankAccount.Field_Update__c = true;
                        eachBankAccount.loan__Bank_Account_Number__c = eachBankAccount.Bank_Account_Number_Change__c;
                        eachBankAccount.Bank_Account_Name__c = eachBankAccount.Bank_Account_Name_Change__c;
                        eachBankAccount.loan__Bank_Name__c = eachBankAccount.Bank_Name_Change__c;
                        eachBankAccount.loan__Account_Usage__c = eachBankAccount.Account_Usage_Change__c;
                        eachBankAccount.loan__Active__c = eachBankAccount.Active_Change__c;
                        eachBankAccount.loan__Account__c = eachBankAccount.Account_Change__c;
                        eachBankAccount.BSB_Number__c = eachBankAccount.BSB_Number_Change__c;
                        eachBankAccount.Approved__c = false;
                        eachBankAccount.Field_Update__c = false;
                        if(eachBankAccount.Created_After_Conversion__c){
                            for(loan__Loan_Account__c eachContract : contractList){
                               if(eachContract.Borrower_ACH_Change__c == eachBankAccount.id && eachContract.Borrower_ACH_Change__c != eachContract.loan__Borrower_ACH__c){
                                    eachContract.loan__Borrower_ACH__c = eachContract.Borrower_ACH_Change__c;
                               }
                            }
                        }else{
                            for(loan__Loan_Account__c eachContract : contractList){
                                eachContract.Bank_Detail_Change__c=true;
                            }

                        }
                        Database.update(contractList,false);
                        eachBankAccount.Created_After_Conversion__c = false;
                    } else{
                        eachBankAccount.Bank_Account_Number_Change__c = oldMap.get(eachBankAccount.id).loan__Bank_Account_Number__c;
                        eachBankAccount.Bank_Account_Name_Change__c = oldMap.get(eachBankAccount.id).Bank_Account_Name__c;
                        eachBankAccount.Bank_Name_Change__c = oldMap.get(eachBankAccount.id).loan__Bank_Name__c;
                        eachBankAccount.Account_Usage_Change__c = oldMap.get(eachBankAccount.id).loan__Account_Usage__c;
                        eachBankAccount.Active_Change__c = oldMap.get(eachBankAccount.id).loan__Active__c;
                        eachBankAccount.Account_Change__c = oldMap.get(eachBankAccount.id).loan__Account__c;
                        eachBankAccount.BSB_Number_Change__c = oldMap.get(eachBankAccount.id).BSB_Number__c;
                        String taskComment = 'The Bank Account has been rejected due to incorrect information being entered. Please review, re-enter and submit again for approval as soon as possible.';
                        newTaskOnBankAccount(oldMap.get(eachBankAccount.id),taskComment);
                    }
                }
            }
        }catch(Exception e){
            GenericUtility.insertLog('BankAccountTriggerHelper',e);
            Database.rollback(sp);
        }
    }
    public static void submitApprovalOnUpdate(List<loan__Bank_Account__c> newBankAccountList, Map<Id,loan__Bank_Account__c> oldMap){
        for(loan__Bank_Account__c eachBankAccount : newBankAccountList){
            loan__Bank_Account__c oldBankAccount = oldMap.get(eachBankAccount.Id);
            if(!eachBankAccount.Submit_For_Approval__c && oldBankAccount.Submit_For_Approval__c){
                continue;
            }
            else if((eachBankAccount.Bank_Account_Number_Change__c != oldBankAccount.Bank_Account_Number_Change__c) ||
              (eachBankAccount.Bank_Account_Name_Change__c != oldBankAccount.Bank_Account_Name_Change__c) ||
              (eachBankAccount.Bank_Name_Change__c != oldBankAccount.Bank_Name_Change__c) ||
              (eachBankAccount.Account_Usage_Change__c != oldBankAccount.Account_Usage_Change__c) ||
              (eachBankAccount.Active_Change__c != oldBankAccount.Active_Change__c) ||
              (eachBankAccount.Account_Change__c != oldBankAccount.Account_Change__c) ||
              (eachBankAccount.BSB_Number_Change__c != oldBankAccount.BSB_Number_Change__c)){
                submitForApproval(eachBankAccount);
                  
            }
        }
    }
    public static void submitForApproval(loan__Bank_Account__c bankAccount) {               
        Approval.ProcessSubmitRequest approvalRequest = new Approval.ProcessSubmitRequest();          
        approvalRequest.setComments('Submitting approval request');        
        approvalRequest.setObjectId(bankAccount.id);    
        Approval.ProcessResult result = Approval.process(approvalRequest);        
    }
    public static void newTaskOnBankAccount(loan__Bank_Account__c bankAccount,String comment){
        try{
            Task newTask = new Task();
            newTask.ActivityDate = bankAccount.LastModifiedDate.date();
            newTask.Description__c = ConstantValues.REVIEW_AND_RESUBMIT;
            newTask.Description = comment;
            newTask.OwnerId = bankAccount.LastModifiedById;
            newTask.Priority = ConstantValues.HIGH;
            newTask.Status = ConstantValues.NOT_STARTED;
            newTask.Subject = ConstantValues.INTERNAL_TASK;
            newTask.WhatId = bankAccount.id;
            insert newTask;
        }catch(Exception e){
            GenericUtility.insertLog('BankAccountTriggerHelper',e);
        }
    }
}