force-app/main/default/objects/Account/fields/Bank_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Name__c</fullName>
    <label>Bank Account Name</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

elixir/force-app/main/default/objects/Account/fields/BSB__c.field-meta.xml
<CustomField>
    <fullName>BSB__c</fullName>
    <label>BSB</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

elixir/force-app/main/default/objects/Account/fields/loan__Active__c.field-meta.xml
<CustomField>
    <fullName>loan__Active__c</fullName>
    <label>Active</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Solicitor.recordType-meta.xml
<RecordType>
    <fullName>Solicitor</fullName>
    <active>true</active>
    <label>Solicitor</label>
</RecordType>

force-app/main/default/objects/loan__Automated_Payment_Configuration__c/fields/Name_of_User__c.field-meta.xml
<CustomField>
    <fullName>Name_of_User__c</fullName>
    <label>Name of User</label>
    <length>26</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Automated_Payment_Configuration__c/fields/Remitter_Name__c.field-meta.xml
<CustomField>
    <fullName>Remitter_Name__c</fullName>
    <label>Remitter Name</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Automated_Payment_Configuration__c/fields/User_Financial_Institution_Name__c.field-meta.xml
<CustomField>
    <fullName>User_Financial_Institution_Name__c</fullName>
    <label>User Financial Institution Name</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Automated_Payment_Configuration__c/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <label>User Id</label>
    <length>6</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Bank_Account__c/loan__Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <displayFormat>BA-{00000}</displayFormat>
        <label>Bank Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Bank_Account__c/fields/Bank_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Name__c</fullName>
    <label>Bank Account Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Bank_Account__c/fields/BSB_Number__c.field-meta.xml
<CustomField>
    <fullName>BSB_Number__c</fullName>
    <label>BSB Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Bank_Account__c/fields/loan__Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

elixir/force-app/main/default/objects/loan__Bank_Account__c/fields/loan__Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>loan__Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>50</length>
    <maskChar>X</maskChar>
    <maskType>lastFour</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

elixir/force-app/main/default/objects/loan__Bank_Account__c/fields/loan__Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>loan__Bank_Name__c</fullName>
    <label>Bank Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Bank_Account__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Coborrower__c/loan__Coborrower__c.object-meta.xml
<CustomObject>
    <label>Contract Party</label>
    <nameField>
        <displayFormat>CID-{000000000}</displayFormat>
        <label>Contract Party Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Coborrower__c/fields/loan__Party_Type__c.field-meta.xml
<CustomField>
    <fullName>loan__Party_Type__c</fullName>
    <description>Type of the Contract Party</description>
    <inlineHelpText>Type of the Contract Party</inlineHelpText>
    <label>Party Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Borrower</fullName>
            </value>
            <value>
                <fullName>Beneficiary Owner</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Co-applicant</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Director &amp; Shareholder</fullName>
            </value>
            <value>
                <fullName>Family Corporate Trustee</fullName>
            </value>
            <value>
                <fullName>Family Individual Trustee</fullName>
            </value>
            <value>
                <fullName>Guarantor</fullName>
            </value>
            <value>
                <fullName>Household</fullName>
            </value>
            <value>
                <fullName>Individual Investor</fullName>
            </value>
            <value>
                <fullName>Joint Individual Investor</fullName>
            </value>
            <value>
                <fullName>Joint Investor</fullName>
            </value>
            <value>
                <fullName>Shareholder</fullName>
            </value>
            <value>
                <fullName>SMSF Corporate Trustee</fullName>
            </value>
            <value>
                <fullName>SMSF Individual Trustee</fullName>
            </value>
            <value>
                <fullName>Solicitor</fullName>
            </value>
            <value>
                <fullName>Trustee</fullName>
            </value>
            <value>
                <fullName>Valuer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <customHelpPage>loan__CLContractHelp</customHelpPage>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Please choose a account, which will be associated as a customer on this lending account.
You can create a new account, from the lookup window by clicking on new or select the existing account from the lookup.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Loan_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

elixir/force-app/main/default/objects/loan__Loan_Account__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>CL Contracts</relationshipLabel>
    <relationshipName>CL_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Disbursal_Transaction__c/loan__Loan_Disbursal_Transaction__c.object-meta.xml
<CustomObject>
    <customHelpPage>loan__LoanDisbursalTransactionHelp</customHelpPage>
    <description>This is the final stage where all the documents submitted by a customer are finally checked and the loan is approved.</description>
    <label>Loan Disbursal Transaction</label>
    <nameField>
        <displayFormat>LDTI-{0000000000}</displayFormat>
        <label>Loan Disbursal Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Disbursal Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Disbursal_Transaction__c/fields/loan__Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Bank_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bank Account</label>
    <referenceTo>loan__Bank_Account__c</referenceTo>
    <relationshipLabel>Loan Disbursal Transactions</relationshipLabel>
    <relationshipName>Loan_Disbursal_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Disbursal_Transaction__c/fields/loan__Cleared__c.field-meta.xml
<CustomField>
    <fullName>loan__Cleared__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cleared</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Disbursal_Transaction__c/fields/loan__Disbursed_Amt__c.field-meta.xml
<CustomField>
    <fullName>loan__Disbursed_Amt__c</fullName>
    <description>Disbursal Transaction Amount</description>
    <inlineHelpText>Disbursal Transaction Amount</inlineHelpText>
    <label>Disbursal Transaction Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Disbursal_Transaction__c/fields/loan__Financed_Amount__c.field-meta.xml
<CustomField>
    <fullName>loan__Financed_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Amount to be disbursed to borrower.</inlineHelpText>
    <label>Financed Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Disbursal_Transaction__c/fields/loan__Loan_Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Account__c</fullName>
    <description>Loan Account</description>
    <inlineHelpText>Loan Account</inlineHelpText>
    <label>Loan Account</label>
    <referenceTo>loan__Loan_Account__c</referenceTo>
    <relationshipLabel>Loan Disbursal Transactions</relationshipLabel>
    <relationshipName>Loan_Disbursal_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Disbursal_Transaction__c/fields/loan__Mode_of_Payment__c.field-meta.xml
<CustomField>
    <fullName>loan__Mode_of_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mode of Payment</label>
    <referenceTo>loan__Payment_Mode__c</referenceTo>
    <relationshipLabel>Loan Disbursal Transactions</relationshipLabel>
    <relationshipName>Loan_Disbursal_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Warehouse__c/fields/Bank_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Name__c</fullName>
    <label>Bank Account Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/fields/Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>9</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/fields/BSB_Number__c.field-meta.xml
<CustomField>
    <fullName>BSB_Number__c</fullName>
    <label>BSB Number</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/fields/Institution_Name__c.field-meta.xml
<CustomField>
    <fullName>Institution_Name__c</fullName>
    <label>Institution Name</label>
    <length>16</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LoanDisbursalFilegenTest.cls
@isTest
private class LoanDisbursalFilegenTest{
    @TestSetup
    static Void initialize() {
        loan__Org_Parameters__c checkTrigger = new loan__Org_Parameters__c();
        checkTrigger.loan__Disable_Triggers__c = true;
        insert checkTrigger;
        checkTrigger = loan__Org_Parameters__c.getInstance();
        System.assertEquals(
          checkTrigger.loan__Disable_Triggers__c,
          true,
          'Org Parameter config error'
        );
        
      Account solicitorAccount = GenericUtilityTestHelper.insertDummyAccount();
      solicitorAccount.Bank_Account_Name__c = 'XYZ WWS';
      solicitorAccount.Bank_Account_Number__c = '123456789';
      solicitorAccount.BSB__c = '231723';
      update solicitorAccount;
      List<Account> testAccountList = new List<Account>([SELECT Id FROM Account]);
      System.assertEquals(testAccountList.size(), 1, 'Account insert error');

      Warehouse__c testWarehouse = new Warehouse__c();
      testWarehouse.Institution_Name__c = 'TEST FIN INSTITUTION';
      testWarehouse.Bank_Account_Number__c = '2213412';
      testWarehouse.BSB_Number__c = '562122';
      insert testWarehouse;

      loan__Loan_Account__c testLoanAccount = GenericUtilityTestHelper.returnLoanAccount();
      testLoanAccount.Warehouse__c = testWarehouse.Id;
      update testLoanAccount;
      List<loan__Loan_Account__c> testLoanAccountList = new List<loan__Loan_Account__c>(
        [SELECT Id FROM loan__Loan_Account__c]
      );
      System.assertEquals(
        testLoanAccountList.size(),
        1,
        'CL Contract insert error'
      );

      loan__Coborrower__c contractParty = new loan__Coborrower__c();
      contractParty.loan__Account__c = solicitorAccount.Id;
      contractParty.loan__Loan__c = testLoanAccount.Id;
      contractParty.loan__Party_Type__c = 'Solicitor';
      insert contractParty;

      loan__Payment_Mode__c testPaymentMode = [SELECT Id, Name FROM loan__Payment_Mode__c WHERE Name = 'ACH'];
      System.debug(testPaymentMode);
      System.assert(
        testPaymentMode != null,
        'Payment Mode insert error'
      );
        
      loan__Bank_Account__c testBankAccount = new loan__Bank_Account__c();
      testBankAccount.loan__Account__c = solicitorAccount.Id;
      testBankAccount.loan__Active__c = true;
      testBankAccount.loan__Bank_Account_Number__c = '1234567';
      testBankAccount.loan__Bank_Name__c = 'TEST BANK';
      insert testBankAccount;

      loan__Automated_Payment_Configuration__c apc = new loan__Automated_Payment_Configuration__c();
      apc.loan__Folder_Name__c = 'ACH Documents';
      apc.loan__Payment_Mode__c = testPaymentMode.Id;
      apc.loan__File_Type__c = 'Text';
      apc.loan__Event__c = 'LOAN DISBURSAL';
      apc.loan__Active__c = true;
      apc.loan__Filegen_Class__c = 'LoanPaymentTxnFileGen';
      apc.Name_of_User__c = 'WINGATE GROUP';
      apc.Remitter_Name__c = 'WINGATE GROUP';
      apc.loan__Bank_Account__c = testBankAccount.Id;
      apc.User_Financial_Institution_Name__c = 'NAB';
      apc.User_Id__c = '992810';
      insert apc;
      List<loan__Automated_Payment_Configuration__c> testApcList = new List<loan__Automated_Payment_Configuration__c>(
        [SELECT Id FROM loan__Automated_Payment_Configuration__c]
      );
      System.assertEquals(testApcList.size(), 1, 'APC insert error');

      loan__Loan_Disbursal_Transaction__c ldtObj = new loan__Loan_Disbursal_Transaction__c();
      ldtObj.loan__Disbursed_Amt__c = 123000;
      ldtObj.loan__Mode_of_Payment__c = testPaymentMode.Id;
      ldtObj.loan__Cleared__c = true;
      ldtObj.loan__Loan_Account__c = testLoanAccount.Id;
      ldtObj.loan__Financed_Amount__c = 122000;
      insert ldtObj;

      loan__Disbursal_Txn_Distribution__c ldtDist = new loan__Disbursal_Txn_Distribution__c();
      ldtDist.loan__Name_of_Entity__c = 'Application Fee';
      ldtDist.loan__Distribution_Amount__c = 23;
      ldtDist.loan__Loan_Disbursal_Transaction__c = ldtObj.Id;
      insert ldtDist;
    }
    static testMethod void testWithValidScope() {
        loan__Automated_Payment_Configuration__c apc = [
          SELECT Id
          FROM loan__Automated_Payment_Configuration__c
        ];
        List<loan__Loan_Disbursal_Transaction__c> testLdtList = [SELECT Id FROM loan__Loan_Disbursal_Transaction__c];
        test.startTest();
        loan.TransactionSweepToACHState state = new loan.TransactionSweepToACHState();
        state.o1 = apc;
        LoanDisbursalFilegen obj = new LoanDisbursalFilegen();
        String fileName = obj.getSimpleFileName();
        List<String> ret = obj.getEntries(state, testLdtList);
        System.assertEquals(ret.size(), 1, 'Entry list size wrong');
        string header = obj.getHeader(state, testLdtList);
        string trailor = obj.getTrailer(state, testLdtList);
        test.stopTest();
      }
}