force-app/main/default/objects/Account/fields/Bank_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Name__c</fullName>
    <label>Bank Account Name</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

elixir/force-app/main/default/objects/Account/fields/BSB__c.field-meta.xml
<CustomField>
    <fullName>BSB__c</fullName>
    <label>BSB</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Automated_Payment_Configuration__c/fields/Description_of_funds__c.field-meta.xml
<CustomField>
    <fullName>Description_of_funds__c</fullName>
    <label>Description of funds</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Automated_Payment_Configuration__c/fields/Name_of_User__c.field-meta.xml
<CustomField>
    <fullName>Name_of_User__c</fullName>
    <label>Name of User</label>
    <length>26</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Automated_Payment_Configuration__c/fields/Remitter_Name__c.field-meta.xml
<CustomField>
    <fullName>Remitter_Name__c</fullName>
    <label>Remitter Name</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Automated_Payment_Configuration__c/fields/User_Financial_Institution_Name__c.field-meta.xml
<CustomField>
    <fullName>User_Financial_Institution_Name__c</fullName>
    <label>User Financial Institution Name</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Automated_Payment_Configuration__c/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <label>User Id</label>
    <length>6</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Bank_Account__c/loan__Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <displayFormat>BA-{00000}</displayFormat>
        <label>Bank Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Bank_Account__c/fields/Bank_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Name__c</fullName>
    <label>Bank Account Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Bank_Account__c/fields/BSB_Number__c.field-meta.xml
<CustomField>
    <fullName>BSB_Number__c</fullName>
    <label>BSB Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Bank_Account__c/fields/loan__Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

elixir/force-app/main/default/objects/loan__Bank_Account__c/fields/loan__Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>loan__Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>50</length>
    <maskChar>X</maskChar>
    <maskType>lastFour</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/loan__Bank_Account__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Coborrower__c/loan__Coborrower__c.object-meta.xml
<CustomObject>
    <label>Contract Party</label>
    <nameField>
        <displayFormat>CID-{000000000}</displayFormat>
        <label>Contract Party Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Coborrower__c/fields/loan__Party_Type__c.field-meta.xml
<CustomField>
    <fullName>loan__Party_Type__c</fullName>
    <description>Type of the Contract Party</description>
    <inlineHelpText>Type of the Contract Party</inlineHelpText>
    <label>Party Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Borrower</fullName>
            </value>
            <value>
                <fullName>Beneficiary Owner</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Co-applicant</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Director &amp; Shareholder</fullName>
            </value>
            <value>
                <fullName>Family Corporate Trustee</fullName>
            </value>
            <value>
                <fullName>Family Individual Trustee</fullName>
            </value>
            <value>
                <fullName>Guarantor</fullName>
            </value>
            <value>
                <fullName>Household</fullName>
            </value>
            <value>
                <fullName>Individual Investor</fullName>
            </value>
            <value>
                <fullName>Joint Individual Investor</fullName>
            </value>
            <value>
                <fullName>Joint Investor</fullName>
            </value>
            <value>
                <fullName>Shareholder</fullName>
            </value>
            <value>
                <fullName>SMSF Corporate Trustee</fullName>
            </value>
            <value>
                <fullName>SMSF Individual Trustee</fullName>
            </value>
            <value>
                <fullName>Solicitor</fullName>
            </value>
            <value>
                <fullName>Trustee</fullName>
            </value>
            <value>
                <fullName>Valuer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <customHelpPage>loan__CLContractHelp</customHelpPage>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Please choose a account, which will be associated as a customer on this lending account.
You can create a new account, from the lookup window by clicking on new or select the existing account from the lookup.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Loan_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

elixir/force-app/main/default/objects/loan__Loan_Account__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>CL Contracts</relationshipLabel>
    <relationshipName>CL_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Disbursal_Transaction__c/loan__Loan_Disbursal_Transaction__c.object-meta.xml
<CustomObject>
    <customHelpPage>loan__LoanDisbursalTransactionHelp</customHelpPage>
    <description>This is the final stage where all the documents submitted by a customer are finally checked and the loan is approved.</description>
    <label>Loan Disbursal Transaction</label>
    <nameField>
        <displayFormat>LDTI-{0000000000}</displayFormat>
        <label>Loan Disbursal Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Disbursal Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Disbursal_Transaction__c/fields/loan__Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Bank_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bank Account</label>
    <referenceTo>loan__Bank_Account__c</referenceTo>
    <relationshipLabel>Loan Disbursal Transactions</relationshipLabel>
    <relationshipName>Loan_Disbursal_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Disbursal_Transaction__c/fields/loan__Cleared__c.field-meta.xml
<CustomField>
    <fullName>loan__Cleared__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cleared</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Disbursal_Transaction__c/fields/loan__Disbursed_Amt__c.field-meta.xml
<CustomField>
    <fullName>loan__Disbursed_Amt__c</fullName>
    <description>Disbursal Transaction Amount</description>
    <inlineHelpText>Disbursal Transaction Amount</inlineHelpText>
    <label>Disbursal Transaction Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Disbursal_Transaction__c/fields/loan__Loan_Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Account__c</fullName>
    <description>Loan Account</description>
    <inlineHelpText>Loan Account</inlineHelpText>
    <label>Loan Account</label>
    <referenceTo>loan__Loan_Account__c</referenceTo>
    <relationshipLabel>Loan Disbursal Transactions</relationshipLabel>
    <relationshipName>Loan_Disbursal_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Disbursal_Transaction__c/fields/loan__Mode_of_Payment__c.field-meta.xml
<CustomField>
    <fullName>loan__Mode_of_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mode of Payment</label>
    <referenceTo>loan__Payment_Mode__c</referenceTo>
    <relationshipLabel>Loan Disbursal Transactions</relationshipLabel>
    <relationshipName>Loan_Disbursal_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Disbursal_Transaction__c/fields/loan__Sent_To_ACH_On__c.field-meta.xml
<CustomField>
    <fullName>loan__Sent_To_ACH_On__c</fullName>
    <inlineHelpText>This is the date the transaction was sent to ACH. The lock period for clearing is counted from this date.</inlineHelpText>
    <label>Sent To ACH On</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Disbursal_Transaction__c/fields/ORDE_Financial_Fees_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>ORDE_Financial_Fees_Total_Amount__c</fullName>
    <label>ORDE Financial Fees Total Amount</label>
    <summarizedField>loan__Disbursal_Txn_Distribution__c.loan__Distribution_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>loan__Disbursal_Txn_Distribution__c.Amount_Going_To__c</field>
        <operation>equals</operation>
        <value>Elixir</value>
    </summaryFilterItems>
    <summaryForeignKey>loan__Disbursal_Txn_Distribution__c.loan__Loan_Disbursal_Transaction__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Warehouse__c/fields/Bank_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Name__c</fullName>
    <label>Bank Account Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/fields/Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>9</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/fields/BSB_Number__c.field-meta.xml
<CustomField>
    <fullName>BSB_Number__c</fullName>
    <label>BSB Number</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/fields/Institution_Name__c.field-meta.xml
<CustomField>
    <fullName>Institution_Name__c</fullName>
    <label>Institution Name</label>
    <length>16</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LoanDisbursalFilegen.cls
global with sharing class LoanDisbursalFilegen extends loan.FileGenerator {
    Long sumOfAmt = 0;
  Decimal tempAmt;
  Integer entryCount = 0;
  Map<Id, loan__Loan_Disbursal_Transaction__c> lptMap = new Map<Id, loan__Loan_Disbursal_Transaction__c>();
  Map<Id, loan__Automated_Payment_Configuration__c> apcMap = new Map<Id, loan__Automated_Payment_Configuration__c>(
    [
      SELECT
        Id,
        loan__Bank_Account__c,
        loan__Bank_Account__r.loan__Bank_Account_Number__c,
        loan__Bank_Account__r.BSB_Number__c,
        Remitter_Name__c,
        User_Financial_Institution_Name__c,
        User_Id__c,
        Name_of_User__c,
        Description_of_funds__c
      FROM loan__Automated_Payment_Configuration__c LIMIT 200
    ]
  );
  Map<Id, loan__Bank_Account__c> bankAccts = new Map<Id, loan__Bank_Account__c>();
  Date currentDate = (!Test.isRunningTest()
    ? (new loan.GlobalLoanUtilFacade()).getCurrentSystemDate()
    : Date.Today());
  DateTime currentDateTime = (DateTime) currentDate;
  String currDate = currentDateTime.format('ddMMyy');

  class BenfDetails {
    String benfAcctName;
    String benfBSBNumber;
    String benfAccNumber;
    String remitterName;
    Integer amtWithholdingTax;
  }
  // Returns a Map of Detail Record with Loan Disbursal Transaction Ids
  private Map<Id, DirectEntryFileRecordGenUtil.DetailRecordData> requeryScope(
    List<SObject> scope
  ) {
    Map<Id, DirectEntryFileRecordGenUtil.DetailRecordData> detailRecordDataLDTMap = new Map<Id, DirectEntryFileRecordGenUtil.DetailRecordData>();
    DirectEntryFileRecordGenUtil.DetailRecordData obj;
    List<loan__Loan_Disbursal_Transaction__c> ldtTxns;
    Map<Id, List<Id>> loanAccountLDTIdMap = new Map<Id, List<Id>>();
    List<Id> clContractIds = new List<Id>();
    Set<Id> ids = new Set<Id>();
    try {
      if(scope == null || scope.isEmpty()){
        throw new CustomException(ConstantValues.ENTRY_SCOPE_EMPTY);
      }
      // Creating a set of Ids of the given scope
      for (SObject s : scope) {
        ids.add(s.Id);
      }
      ldtTxns = new List<loan__Loan_Disbursal_Transaction__c>(
        [
          SELECT Id, Name,
            loan__ACH_Filename__c,
            loan__Cleared__c,
            loan__Mode_of_Payment__c,
            loan__Mode_of_Payment__r.Name,
            loan__Sent_to_ACH__c,
            loan__Sent_To_ACH_On__c,
            loan__Disbursed_Amt__c,
            loan__Loan_Account__c,
            loan__Loan_Account__r.Warehouse__c,
            loan__Loan_Account__r.Warehouse__r.Institution_Name__c,
            loan__Loan_Account__r.Warehouse__r.Bank_Account_Number__c,
            loan__Loan_Account__r.Warehouse__r.BSB_Number__c,
            ORDE_Financial_Fees_Total_Amount__c
          FROM loan__Loan_Disbursal_Transaction__c
          WHERE
            Id IN :ids
            AND loan__Cleared__c = true
            AND loan__Reversed__c = false
            AND loan__Rejected__c = false
        ]
      );
      for(loan__Loan_Disbursal_Transaction__c each : ldtTxns){
        obj = new DirectEntryFileRecordGenUtil.DetailRecordData();
        obj.lodgementRef = each.Name;
        obj.transAmt = ((each.loan__Disbursed_Amt__c - each.ORDE_Financial_Fees_Total_Amount__c) * 100).round();
        obj.benfBSBNumber = each.loan__Loan_Account__r.Warehouse__r.BSB_Number__c;
        obj.benfAccNumber = each.loan__Loan_Account__r.Warehouse__r.Bank_Account_Number__c;
        obj.remitterName = each.loan__Loan_Account__r.Warehouse__r.Institution_Name__c;
        detailRecordDataLDTMap.put(each.Id, obj);
        System.debug(each.loan__Loan_Account__c);
        clContractIds.add(each.loan__Loan_Account__c);
        List<Id> ldtIds = loanAccountLDTIdMap.get(each.loan__Loan_Account__c);
        if(ldtIds == null){
            ldtIds = new List<Id>();
        }
        ldtIds.add(each.Id);
        loanAccountLDTIdMap.put(each.loan__Loan_Account__c, ldtIds);
      }
      List<loan__Coborrower__c> contractPartyList = [SELECT Id, loan__Loan__c, loan__Account__c, loan__Party_Type__c,
      loan__Account__r.Bank_Account_Name__c, loan__Account__r.Bank_Account_Number__c, loan__Account__r.BSB__c
      FROM loan__Coborrower__c WHERE loan__Loan__c IN:clContractIds AND loan__Party_Type__c =:ConstantValues.SOLICITOR_PARTY_TYPE];
      System.debug(contractPartyList);
      for(loan__Coborrower__c each : contractPartyList){
        System.debug(each);
        List<Id> ldtIds = loanAccountLDTIdMap.get(each.loan__Loan__c);
        for(Id eachId : ldtIds){
            obj = detailRecordDataLDTMap.get(eachId);
            obj.payerBSBNumber = each.loan__Account__r.BSB__c;
            obj.payerAcctNumber = each.loan__Account__r.Bank_Account_Number__c;
            obj.payerAcctName = each.loan__Account__r.Bank_Account_Name__c;
            detailRecordDataLDTMap.put(eachId, obj);
        }
      }
    } catch (Exception ex) {
      GenericUtility.insertLog('LoanDisbursalFilegen', ex);
    }
    return detailRecordDataLDTMap;
  }
  global override String getSimpleFileName() {
    return System.label.LDT_file_name + currDate;
  }
  // This method is for processing scopes for ABA file entries
  private String processScope(
    Id ldtId,
    DirectEntryFileRecordGenUtil.DetailRecordData recOneDataObj
  ) {
    String entryVal;
    loan__Loan_Disbursal_Transaction__c ldtObj = new loan__Loan_Disbursal_Transaction__c(Id = ldtId);
    if(String.isBlank(recOneDataObj.payerBSBNumber)){
        addToInvalidScope(ldtObj, ConstantValues.WRONG_BSB_PAYER);
    } else if(String.isBlank(recOneDataObj.payerAcctNumber)){
        addToInvalidScope(ldtObj, ConstantValues.WRONG_ACOUNT_NUMBER_PAYER);
    } else if(recOneDataObj.transAmt == null){
        addToInvalidScope(ldtObj, ConstantValues.TRANSACTION_AMT_NOT_FOUND);
    } else if(recOneDataObj.payerAcctName == null){
        addToInvalidScope(ldtObj, ConstantValues.PAYER_ACCOUNT_NAME_MISSING);
    } else if(recOneDataObj.lodgementRef == null){
        addToInvalidScope(ldtObj, ConstantValues.LODGMENT_REFERENCE_MISSING);
    } else if(recOneDataObj.benfBSBNumber == null){
        addToInvalidScope(ldtObj, ConstantValues.WRONG_BSB_PAYEE);
    } else if(recOneDataObj.benfAccNumber == null){
        addToInvalidScope(ldtObj, ConstantValues.WRONG_ACOUNT_NUMBER_PAYEE);
    } else if(recOneDataObj.remitterName == null){
        addToInvalidScope(ldtObj, ConstantValues.WAREHOUSE_INST_MISSING);
    } else{
        recOneDataObj.indicator = ConstantValues.INDICATOR;
        recOneDataObj.transCode = ConstantValues.TXN_CODE_CREDIT;
        recOneDataObj.amtWithholdingTax = 0;
        addToValidScope(ldtObj);
        entryVal = DirectEntryFileRecordGenUtil.getRecordOne(recOneDataObj);
        addEntry(entryVal);
    }
    return entryVal;
  }

  global override List<String> getEntries(
    loan.TransactionSweepToACHState state,
    List<SObject> scope
  ) {
    Map<Id, DirectEntryFileRecordGenUtil.DetailRecordData> detailRecordDataLDTMap = requeryScope(scope);
    List<String> totalRecords = new List<String>();
    try {
      for (Id eachKey : detailRecordDataLDTMap.keySet()) {
        System.debug(detailRecordDataLDTMap.get(eachKey));
        String entryVal = processScope(eachKey, detailRecordDataLDTMap.get(eachKey));
        if (String.isNotBlank(entryVal)) {
          totalRecords.add(entryVal);
        }
      }
    } catch (Exception ex) {
      GenericUtility.insertLog(
        'LoanDisbursalFilegen',
        ex
      );
    }
    return totalRecords;
  }
  
  global override String getHeader(
    loan.TransactionSweepToACHState state,
    List<SObject> scope
  ) {
    String headerVal;
    try {
      loan__Automated_Payment_Configuration__c apc = (loan__Automated_Payment_Configuration__c) state.o1;
      apc = apcMap.get(apc.Id);

      if (apc == null) {
        GenericUtility.insertLog(
          'LoanDisbursalFilegen',
          new CustomException(ConstantValues.NO_APC_FOUND)
        );
        return headerVal;
      }

      DirectEntryFileRecordGenUtil.DescriptiveRecordData recZeroDataObj = new DirectEntryFileRecordGenUtil.DescriptiveRecordData();
      // No null check for User_Financial_Institution_Name__c, Name_of_User__c, User_Id__c as they are mandatory fields
      recZeroDataObj.financialInstitutionName = apc.User_Financial_Institution_Name__c;
      recZeroDataObj.username = apc.Name_of_User__c;
      recZeroDataObj.userId = apc.User_Id__c;
      recZeroDataObj.description = apc.Description_of_funds__c;
      headerVal = DirectEntryFileRecordGenUtil.getDescriptiveRecord(recZeroDataObj);
    } catch (Exception ex) {
      GenericUtility.insertLog('LoanDisbursalFilegen', ex);
    }
    return headerVal;
  }

  global override String getTrailer(
    loan.TransactionSweepToACHState state,
    List<SObject> scope
  ) {
    String trailerVal;
    try {
      DirectEntryFileRecordGenUtil.RecordSevenData recSevenDataObj = new DirectEntryFileRecordGenUtil.RecordSevenData();
      recSevenDataObj.sumOfAmt = sumOfAmt;
      recSevenDataObj.entryCount = entryCount;
      trailerVal = DirectEntryFileRecordGenUtil.getRecordSeven(recSevenDataObj);
    } catch (Exception ex) {
      GenericUtility.insertLog('LoanDisbursalFilegen', ex);
    }
    return trailerVal;
  }
}  