force-app/main/default/objects/Account/fields/Bank_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Name__c</fullName>
    <label>Bank Account Name</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

elixir/force-app/main/default/objects/Account/fields/BSB__c.field-meta.xml
<CustomField>
    <fullName>BSB__c</fullName>
    <label>BSB</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

elixir/force-app/main/default/objects/Account/fields/loan__Active__c.field-meta.xml
<CustomField>
    <fullName>loan__Active__c</fullName>
    <label>Active</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Status__c.field-meta.xml
<CustomField>
    <fullName>genesis__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>App Received</fullName>
                <default>true</default>
                <label>App Received</label>
            </value>
            <value>
                <fullName>App Processed</fullName>
            </value>
            <value>
                <fullName>Conditional Assessed</fullName>
            </value>
            <value>
                <fullName>Conditionally Approved</fullName>
            </value>
            <value>
                <fullName>Conditional Accepted</fullName>
            </value>
            <value>
                <fullName>Assessment in Progress</fullName>
            </value>
            <value>
                <fullName>Recommended</fullName>
            </value>
            <value>
                <fullName>Formally Approved</fullName>
            </value>
            <value>
                <fullName>Solicitor Instructed</fullName>
            </value>
            <value>
                <fullName>LOO Issued</fullName>
            </value>
            <value>
                <fullName>LOO Accepted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Approved - Converted to Contract</fullName>
            </value>
            <value>
                <fullName>Loan Settled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

elixir/force-app/main/default/objects/genesis__Applications__c/fields/Primary_loan_purpose_list__c.field-meta.xml
<CustomField>
    <fullName>Primary_loan_purpose_list__c</fullName>
    <label>Primary loan purpose list</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Investment</fullName>
            </value>
            <value>
                <fullName>Owner Occupied</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
                <isActive>false</isActive>
                <label>Business</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/Proposed_repayment_method_list__c.field-meta.xml
<CustomField>
    <fullName>Proposed_repayment_method_list__c</fullName>
    <defaultValue>(&quot;Direct Debit&quot;)</defaultValue>
    <label>Proposed repayment method list</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bpay</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Direct Debit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Bank_Account__c/loan__Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <displayFormat>BA-{00000}</displayFormat>
        <label>Bank Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Bank_Account__c/fields/Bank_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Name__c</fullName>
    <label>Bank Account Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Bank_Account__c/fields/BSB_Number__c.field-meta.xml
<CustomField>
    <fullName>BSB_Number__c</fullName>
    <label>BSB Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Bank_Account__c/fields/loan__Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Bank_Account__c/fields/loan__Account_Usage__c.field-meta.xml
<CustomField>
    <fullName>loan__Account_Usage__c</fullName>
    <label>Account Usage</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Investor Trust Account</fullName>
            </value>
            <value>
                <fullName>Collections Trust Account</fullName>
            </value>
            <value>
                <fullName>Advance Trust Account</fullName>
            </value>
            <value>
                <fullName>Business Account</fullName>
            </value>
            <value>
                <fullName>Tax Withholding Account</fullName>
            </value>
            <value>
                <fullName>Borrower/Investor Account</fullName>
            </value>
            <value>
                <fullName>Broker Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

elixir/force-app/main/default/objects/loan__Bank_Account__c/fields/loan__Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>loan__Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>50</length>
    <maskChar>X</maskChar>
    <maskType>lastFour</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

elixir/force-app/main/default/objects/loan__Bank_Account__c/fields/loan__Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>loan__Bank_Name__c</fullName>
    <label>Bank Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <customHelpPage>loan__CLContractHelp</customHelpPage>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Please choose a account, which will be associated as a customer on this lending account.
You can create a new account, from the lookup window by clicking on new or select the existing account from the lookup.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Loan_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Application_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Application_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <inlineHelpText>Application Received Date.</inlineHelpText>
    <label>Application Date</label>
    <type>Date</type>
</CustomField>

elixir/force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Approval_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Approval_Date__c</fullName>
    <inlineHelpText>The date on which the loan is approved.</inlineHelpText>
    <label>Approval Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ConvertToContract.cls
/*********************************************************************************************************
Class Name     : ConvertToContract
Description    : Apex class for converting application to contract throgh conversion mappping
Developer      : Rameswari Barman
Implementation code : genesis__applications__c app = [select id from genesis__applications__c where id = 'XXX'];
                      ConvertToContract.executeFun(app.Id)
**********************************************************************************************************/

global with sharing class ConvertToContract{
    Webservice static String executeFun(Id appId){
        String ret = '';
        //Savepoint is setup over here
        Savepoint sp=Database.setSavepoint();
        try{
            genesis__applications__c app = new genesis__applications__c(id=appId);
            String status = genesis.ConvertApplicationCtrl.convertApplicationToContract(appId);//storing the returned message from product class call
            if(status == System.label.Application_converted_to_Contract_message && Schema.sObjectType.genesis__applications__c.fields.genesis__Status__c.isUpdateable()){
                app.genesis__Status__c = System.label.ApplicationStatusAfterConvertedToContract;
                //updating the status of application
                update app;
                attachValues(appId);
            }
            else{
                Database.rollback(sp);
                if(test.isRunningTest()){
                    Integer a = 4/0;
                }
            }
            ret = status;
        }
        catch(Exception e){
            Database.rollback(sp);
            insert new clcommon__Batch_Process_Log__c(clcommon__Message__c = 'ConvertToContract :'+e.getStackTraceString()+':Error::'+e.getMessage()+' at Line Number '+e.getLineNumber(), clcommon__Timestamp__c = 
                                                  System.Now(),clcommon__Log_Level__c = 'ERROR'); 
            ret = e.getMessage();  
        }
        return ret;
    }
    //This function copies values from application to Contract during conversion
    Webservice static String attachValues(Id appId){
        String ret;
        loan__Bank_Account__c banAcc;
        Savepoint sp=Database.setSavepoint();
        try{
            genesis__Applications__c app = [select id,
                                                Primary_loan_purpose_list__c,
                                                Proposed_repayment_method_list__c,
                                                CL_Contract__c,genesis__Account__c,
                                                genesis__Account__r.Bank_Account_Name__c,
                                                genesis__Account__r.BSB__c,
                                                genesis__Account__r.Bank_Account_Number__c,
                                                CreatedDate
                                            from genesis__Applications__c where Id =: appId];
            if(app.CL_Contract__c != null){
                loan__Loan_Account__c contr = [select id,
                                                    loan__Payment_Mode__c,
                                                    loan__Loan_Purpose__c,
                                                    loan__Approval_Date__c
                                                from loan__Loan_Account__c 
                                                where id =: app.CL_Contract__c];
                //Checking if proposed repayment method list is provided in application or not
                if(app.Proposed_repayment_method_list__c != null){
                    loan__Payment_Mode__c paymentModeId = [select id from loan__Payment_Mode__c where name =: app.Proposed_repayment_method_list__c];
                    contr.loan__Payment_Mode__c = paymentModeId.Id;
                }
                //Checking if loan purpose list is provided in application or not
                if(app.Primary_loan_purpose_list__c != null){
                    loan__Loan_Purpose__c purposeId = [select id from loan__Loan_Purpose__c where name =: app.Primary_loan_purpose_list__c];
                    contr.loan__Loan_Purpose__c = purposeId.Id;
                }
                //Attaching Bank Account
                if(app.genesis__Account__r.Bank_Account_Name__c != null && app.genesis__Account__r.BSB__c != null && app.genesis__Account__r.Bank_Account_Number__c != null){
                    banAcc = new loan__Bank_Account__c();
                    banAcc.loan__Bank_Account_Number__c = app.genesis__Account__r.Bank_Account_Number__c;
                    banAcc.BSB_Number__c = app.genesis__Account__r.BSB__c;
                    banAcc.Bank_Account_Name__c = app.genesis__Account__r.Bank_Account_Name__c;
                    banAcc.loan__Active__c = true;
                    banAcc.loan__Account_Usage__c = System.label.Borrower_Bank_Account_Type;
                    banAcc.loan__Bank_Name__c = app.genesis__Account__r.BSB__c;
                    banAcc.loan__Account__c = app.genesis__Account__c;
                    if(banAcc != null){
                        insert banAcc;
                        contr.loan__Borrower_ACH__c = banAcc.Id;
                    }
                }
                //Change made by Rameswari on 24/12/2020
                //Attaching Application Date and Approval Date
                DateTime appCreationDate = app.CreatedDate;
                contr.loan__Application_Date__c = date.newInstance(appCreationDate.year() ,appCreationDate.month(), appCreationDate.day());
                
                if(contr != null 
                    && (app.Proposed_repayment_method_list__c != null
                    || app.Primary_loan_purpose_list__c != null 
                    || banAcc!=null 
                    || appCreationDate != null)){
                    update contr;
                }
            }
        }
        catch(Exception e){
            Database.rollback(sp);
            insert new clcommon__Batch_Process_Log__c(clcommon__Message__c = 'ConvertToContract :'+e.getStackTraceString()+':Error::'+e.getMessage()+' at Line Number '+e.getLineNumber(), clcommon__Timestamp__c = 
                                                  System.Now(),clcommon__Log_Level__c = 'ERROR'); 
            ret = e.getMessage();  
        }
        return ret;
    }
}