elixir/force-app/main/default/objects/Account/fields/clcommon__Legal_Entity_Type__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Legal_Entity_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Legal Entity Type</label>
    <referenceTo>clcommon__Legal_Entity__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Borrower.recordType-meta.xml
<RecordType>
    <fullName>Borrower</fullName>
    <active>true</active>
    <label>Borrower</label>
</RecordType>

force-app/main/default/objects/clcommon__Party__c/clcommon__Party__c.object-meta.xml
<CustomObject>
    <label>Party</label>
    <nameField>
        <displayFormat>PAR-{00000000}</displayFormat>
        <label>Party Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/clcommon__Party__c/fields/clcommon__Account__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Parties</relationshipLabel>
    <relationshipName>Parties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/clcommon__Type__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Party Type</label>
    <referenceTo>clcommon__Party_Type__c</referenceTo>
    <relationshipLabel>Parties</relationshipLabel>
    <relationshipName>Parties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/genesis__Application__c.field-meta.xml
<CustomField>
    <fullName>genesis__Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Parties</relationshipLabel>
    <relationshipName>Parties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/Party_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Party_Type_Name__c</fullName>
    <formula>clcommon__Type__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Party Type Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

elixir/force-app/main/default/objects/genesis__Applications__c/fields/genesis__Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>genesis__Loan_Amount__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/EquifaxCompanyEnquiryCallout.cls
global class EquifaxCompanyEnquiryCallout{
    WebService static String companyEnquiryRequest(ID partyid, ID applicationid,Boolean enrichment){
        try{
            String json;
            clcommon__Party__c ans = [SELECT ID, clcommon__Account__r.clcommon__Legal_Entity_Type__c , clcommon__Type__c
            FROM clcommon__Party__c
            WHERE ID = :partyid];
            
            genesis__Applications__c res = [SELECT Name, genesis__Loan_Amount__c
            FROM genesis__Applications__c
            WHERE ID = :applicationid];
            Map<String, String> queryIDMap = new Map<String, String>();
            queryIDMap.put(ConstantValues.PARTY_ID, partyid);
            queryIDMap.put(ConstantValues.PARTY_TYPE_ID, ans.clcommon__Type__c);
            queryIDMap.put(ConstantValues.ENTITY_ID, ans.clcommon__Account__r.clcommon__Legal_Entity_Type__c);
            
            queryIDMap.put(ConstantValues.APPLICATION_ID, applicationid);
            List<clcommon__Party__c> partyList = [SELECT Id, genesis__Application__c, Party_Type_Name__c FROM clcommon__Party__c
            WHERE genesis__Application__c = :applicationid AND Party_Type_Name__c IN (:ConstantValues.BORROWER, :ConstantValues.CO_APPLICANT)];
            Map<String, Object> requestParamMap = new Map<String, Object>();
            requestParamMap.put(ConstantValues.ENRICHMENT_REQUIRED, enrichment);
            if(partyList.size() > 1){
                requestParamMap.put(ConstantValues.IS_JOINT, true);
            }else{
                requestParamMap.put(ConstantValues.IS_JOINT, false);
            }
        
            intframework.AbstractIntegrationService baseintegrationService = intframework.IntegrationServiceFactory.getBaseIntegrationService();
            intframework.BaseIntegrationResponse responseObject;
            responseObject = (intframework.BaseIntegrationResponse) baseintegrationService.runSynchronousIntegrationService(
            ConstantValues.EQUIFAX_FAMILY,
            ConstantValues.COMPANY_ENQUIRY_API_TYPE,
            queryIDMap,
            requestParamMap     
            );
            dom.Document docu = new dom.Document();
            docu.load(responseObject.getBody());
            Map<String, Object> responseMap;
            try {
                responseMap = intframework.XmlToJson.parseDocumentToMap(docu);
            } catch (Exception ex) {
                GenericUtility.insertLog(ConstantValues.EQUIFAX_COMPANY_ENQUIRY_CALLOUT, ex);
                return ConstantValues.SOMETHING_WENT_WRONG;
            }
            return EquifaxCompanyEnquiryResponseHelper.parse(json, ans, responseMap);
        } catch(Exception ex){
            return ex.getMessage()+ex.getLineNumber();  
        }
    }
}