elixir/force-app/main/default/objects/Account/fields/clcommon__Legal_Entity_Type__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Legal_Entity_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Legal Entity Type</label>
    <referenceTo>clcommon__Legal_Entity__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

elixir/force-app/main/default/objects/Account/fields/loan__Active__c.field-meta.xml
<CustomField>
    <fullName>loan__Active__c</fullName>
    <label>Active</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Borrower.recordType-meta.xml
<RecordType>
    <fullName>Borrower</fullName>
    <active>true</active>
    <label>Borrower</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Investor.recordType-meta.xml
<RecordType>
    <fullName>Investor</fullName>
    <active>true</active>
    <label>Investor</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Solicitor.recordType-meta.xml
<RecordType>
    <fullName>Solicitor</fullName>
    <active>true</active>
    <label>Solicitor</label>
</RecordType>

force-app/main/default/objects/clcommon__CL_Product__c/clcommon__CL_Product__c.object-meta.xml
<CustomObject>
    <label>CL Product</label>
    <nameField>
        <displayFormat>PRO-{00000000}</displayFormat>
        <label>CL Product Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/clcommon__CL_Product__c/recordTypes/Investor.recordType-meta.xml
<RecordType>
    <fullName>Investor</fullName>
    <active>true</active>
    <label>Investor</label>
</RecordType>

force-app/main/default/objects/clcommon__Party__c/clcommon__Party__c.object-meta.xml
<CustomObject>
    <label>Party</label>
    <nameField>
        <displayFormat>PAR-{00000000}</displayFormat>
        <label>Party Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/clcommon__Party__c/fields/clcommon__Account__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Parties</relationshipLabel>
    <relationshipName>Parties</relationshipName>
    <type>Lookup</type>
</CustomField>

elixir/force-app/main/default/objects/clcommon__Party__c/fields/clcommon__Party_Type__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Party_Type__c</fullName>
    <label>Party Type(Deprecated)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DEALER</fullName>
            </value>
            <value>
                <fullName>BORROWER</fullName>
            </value>
            <value>
                <fullName>CO-BORROWER</fullName>
            </value>
            <value>
                <fullName>GUARANTOR</fullName>
            </value>
            <value>
                <fullName>ENTITY</fullName>
            </value>
            <value>
                <fullName>REVIEWER</fullName>
            </value>
            <value>
                <fullName>APPRAISER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/clcommon__Type__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Party Type</label>
    <referenceTo>clcommon__Party_Type__c</referenceTo>
    <relationshipLabel>Parties</relationshipLabel>
    <relationshipName>Parties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/genesis__Application__c.field-meta.xml
<CustomField>
    <fullName>genesis__Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Parties</relationshipLabel>
    <relationshipName>Parties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

elixir/force-app/main/default/objects/genesis__Applications__c/fields/genesis__Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>genesis__Interest_Rate__c</fullName>
    <label>Interest Rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

elixir/force-app/main/default/objects/genesis__Applications__c/fields/genesis__Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>genesis__Loan_Amount__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Payment_Frequency__c.field-meta.xml
<CustomField>
    <fullName>genesis__Payment_Frequency__c</fullName>
    <label>Payment Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>genesis__Product_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>WEEKLY</fullName>
            </value>
            <value>
                <fullName>BI-WEEKLY</fullName>
            </value>
            <value>
                <fullName>MONTHLY</fullName>
                <default>true</default>
                <label>MONTHLY</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Status__c.field-meta.xml
<CustomField>
    <fullName>genesis__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>App Received</fullName>
                <default>true</default>
                <label>App Received</label>
            </value>
            <value>
                <fullName>App Processed</fullName>
            </value>
            <value>
                <fullName>Conditional Assessed</fullName>
            </value>
            <value>
                <fullName>Conditionally Approved</fullName>
            </value>
            <value>
                <fullName>Conditional Accepted</fullName>
            </value>
            <value>
                <fullName>Assessment in Progress</fullName>
            </value>
            <value>
                <fullName>Recommended</fullName>
            </value>
            <value>
                <fullName>Formally Approved</fullName>
            </value>
            <value>
                <fullName>Solicitor Instructed</fullName>
            </value>
            <value>
                <fullName>LOO Issued</fullName>
            </value>
            <value>
                <fullName>LOO Accepted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Approved - Converted to Contract</fullName>
            </value>
            <value>
                <fullName>Loan Settled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

elixir/force-app/main/default/objects/genesis__Applications__c/fields/genesis__Term__c.field-meta.xml
<CustomField>
    <fullName>genesis__Term__c</fullName>
    <label>Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/recordTypes/Investor.recordType-meta.xml
<RecordType>
    <fullName>Investor</fullName>
    <active>true</active>
    <description>Investor Application Flow</description>
    <label>Investor</label>
</RecordType>

force-app/main/default/objects/loan__Bank_Account__c/loan__Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <displayFormat>BA-{00000}</displayFormat>
        <label>Bank Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Bank_Account__c/fields/loan__Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Bank_Account__c/fields/loan__Account_Type__c.field-meta.xml
<CustomField>
    <fullName>loan__Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Saving</fullName>
            </value>
            <value>
                <fullName>Checking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Bank_Account__c/fields/loan__Account_Usage__c.field-meta.xml
<CustomField>
    <fullName>loan__Account_Usage__c</fullName>
    <label>Account Usage</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Investor Trust Account</fullName>
            </value>
            <value>
                <fullName>Collections Trust Account</fullName>
            </value>
            <value>
                <fullName>Advance Trust Account</fullName>
            </value>
            <value>
                <fullName>Business Account</fullName>
            </value>
            <value>
                <fullName>Tax Withholding Account</fullName>
            </value>
            <value>
                <fullName>Borrower/Investor Account</fullName>
            </value>
            <value>
                <fullName>Broker Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

elixir/force-app/main/default/objects/loan__Bank_Account__c/fields/loan__Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>loan__Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>50</length>
    <maskChar>X</maskChar>
    <maskType>lastFour</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

elixir/force-app/main/default/objects/loan__Bank_Account__c/fields/loan__Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>loan__Bank_Name__c</fullName>
    <label>Bank Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LoanApplicationConvertTest.cls
/************************************************************************
Description: Test class for LoanApplicationConvert
Developer: Rameswari Barman
**************************************************************************/
@isTest
public class LoanApplicationConvertTest{
    public static testmethod void test1(){
    
        //Inserting legal entity
        clcommon__Legal_Entity__c legEntity = new clcommon__Legal_Entity__c(Name = 'Individual');
        insert legEntity;
        System.assertEquals(legEntity.Name,'Individual');
            
        //Inserting Account
        Account acc = new Account(name = 'Test account',clcommon__Legal_Entity_Type__c = legEntity.id);
        insert acc;
        System.assertEquals(acc.name,'Test account');
        
        
        //Test data using the Loan Product
        loan.TestHelper.createSeedDataForTesting();
        loan__Currency__c curr = loan.TestHelper.createCurrency();
        
        //Create a dummy MF_Account
        loan__MF_Account__c dummyAccount = loan.TestHelper.createMFAccount('XXXAccountForTest','10000 - ASSETS');
        loan__MF_Account__c dummyIncAccount = loan.TestHelper.createMFAccount('XXXIncAccountForTest','30000 - INCOME');
        
        //Create a Fee Set
        loan__Fee__c dummyFee = loan.TestHelper.createFee(curr,dummyIncAccount ,dummyAccount);                                   
        loan__Fee_Set__c dummyFeeSet = loan.TestHelper.createFeeSet();
        loan__Fee_Junction__c dummyFeeJunction = loan.TestHelper.createFeeJunction(dummyFee,dummyFeeSet);
        
        loan__Office_Name__c dummyOffice = loan.TestHelper.createOffice();
        
        //Create a dummy Loan Product
        loan__Loan_Product__c dummyLP = loan.TestHelper.createLoanProduct(dummyOffice,
                                        dummyAccount, 
                                        curr, 
                                        dummyFeeSet);
                                        
        upsert dummyLP;
        
        
        //inserting CL product 
        clcommon__CL_Product__c clp= new clcommon__CL_Product__c(clcommon__Product_Name__c='Interest Only', loan__Lending_Product__c=dummyLP.Id);
        insert clp;                                
        System.assertEquals(clp.clcommon__Product_Name__c,'Interest Only');
        
        //Inserting Applications
        genesis__applications__c app = new genesis__applications__c(genesis__Status__c='Approved',
                                                                    genesis__Fees_Amount__c=10,
                                                                    genesis__account__c = acc.id,
                                                                    genesis__Term__c=12,
                                                                    genesis__Interest_Rate__c=10,
                                                                    genesis__Payment_Frequency__c=ConstantValues.MONTHLY,
                                                                    genesis__Loan_Amount__c=10000,
                                                                    genesis__CL_Product__c=clp.id);
        insert app;
        System.assertEquals(app.genesis__Status__c,'Approved');
        
        //Inserting borrower bank account
        loan__Bank_Account__c borrBank= new loan__Bank_Account__c();
        borrBank.loan__Account__c=acc.Id;
        borrBank.loan__Account_Type__c='Saving';
        borrBank.loan__Account_Usage__c='Borrower/Investor Account';
        borrBank.loan__Bank_Account_Number__c='21432534543';
        borrBank.loan__Active__c=true;
        borrBank.loan__Bank_Name__c ='SBI';
        insert borrBank;
        System.assertEquals(borrBank.loan__Bank_Name__c,'SBI');
        
        //Inserting Borrower Party
        list< clcommon__Party_Type__c > partyTypes= new list<clcommon__Party_Type__c>();
        partyTypes.add(new clcommon__Party_Type__c(Name='BORROWER'));
        partyTypes.add(new clcommon__Party_Type__c(Name='Solicitor'));
        insert partyTypes;
        System.assertEquals(partyTypes.size(),2);
        
        //Inserting borrower Party
        clcommon__Party__c borrParty= new clcommon__Party__c(clcommon__Account__c=acc.Id, genesis__Application__c=app.Id,clcommon__Type__c=[select id from clcommon__Party_Type__c Where Name='BORROWER'].Id);
        insert borrParty;
        System.assertEquals(borrParty.clcommon__Account__c,acc.Id);
        
        //inserting Solicitor Account
        Account solicitorAcc= new Account();
        solicitorAcc.name = 'Test account';
        solicitorAcc.clcommon__Legal_Entity_Type__c = legEntity.id;
        insert solicitorAcc;
        System.assertEquals(solicitorAcc.name,'Test account');
        
        //Inserting solicitor Acc
        loan__Bank_Account__c soliBank= new loan__Bank_Account__c();
        soliBank.loan__Account__c=solicitorAcc.Id;
        soliBank.loan__Account_Type__c='Saving';
        soliBank.loan__Account_Usage__c='Borrower/Investor Account';
        soliBank.loan__Bank_Account_Number__c='21432534543';
        soliBank.loan__Active__c=true;
        soliBank.loan__Bank_Name__c ='SBI';
        insert soliBank;
        System.assertEquals(soliBank.loan__Bank_Name__c,'SBI');
        
        //Inserting borrower Party
        clcommon__Party__c solicitorParty= new clcommon__Party__c(clcommon__Account__c=solicitorAcc.Id, genesis__Application__c=app.Id,clcommon__Type__c=[select id from clcommon__Party_Type__c Where Name='Solicitor'].Id);
        insert solicitorParty;
        System.assertEquals(solicitorParty.clcommon__Account__c,solicitorAcc.Id);
        
        Test.startTest();
            String st=LoanApplicationConvert.convertLoanApplicationCtrl(app.Id);
            System.assert(st!=null);
        Test.stopTest();    
                
    }
    
    //Test Method 2
    public static testmethod void test2(){
        
        //Inserting legal entity
        clcommon__Legal_Entity__c legEntity = new clcommon__Legal_Entity__c(Name = 'Individual');
        insert legEntity;
        System.assertEquals(legEntity.Name,'Individual');
            
        //Inserting Account
        Account acc = new Account(name = 'Test account',clcommon__Legal_Entity_Type__c = legEntity.id);
        insert acc;
        System.assertEquals(acc.name,'Test account');
        
        //Test data using the Loan Product
        loan.TestHelper.createSeedDataForTesting();
        loan__Currency__c curr = loan.TestHelper.createCurrency();
        
        //Create a dummy MF_Account
        loan__MF_Account__c dummyAccount = loan.TestHelper.createMFAccount('XXXAccountForTest','10000 - ASSETS');
        loan__MF_Account__c dummyIncAccount = loan.TestHelper.createMFAccount('XXXIncAccountForTest','30000 - INCOME');
        
        //Create a Fee Set
        loan__Fee__c dummyFee = loan.TestHelper.createFee(curr,dummyIncAccount ,dummyAccount);                                   
        loan__Fee_Set__c dummyFeeSet = loan.TestHelper.createFeeSet();
        loan__Fee_Junction__c dummyFeeJunction = loan.TestHelper.createFeeJunction(dummyFee,dummyFeeSet);
        
        loan__Office_Name__c dummyOffice = loan.TestHelper.createOffice();
        
        //Create a dummy Loan Product
        loan__Loan_Product__c dummyLP = loan.TestHelper.createLoanProduct(dummyOffice,
                                        dummyAccount, 
                                        curr, 
                                        dummyFeeSet);
                                        
        upsert dummyLP;
        
        
        //inserting CL product 
        clcommon__CL_Product__c clp= new clcommon__CL_Product__c(clcommon__Product_Name__c='Interest Only', loan__Lending_Product__c=dummyLP.Id);
        insert clp;                                
        System.assertEquals(clp.clcommon__Product_Name__c,'Interest Only');
        
        //Inserting Applications
        genesis__applications__c app = new genesis__applications__c(genesis__Status__c=ConstantValues.Approved,
                                                                    genesis__Fees_Amount__c=10,
                                                                    genesis__account__c = acc.id,
                                                                    genesis__Term__c=12,
                                                                    genesis__Interest_Rate__c=10,
                                                                    genesis__Payment_Frequency__c=ConstantValues.MONTHLY,
                                                                    genesis__Loan_Amount__c=10000,
                                                                    genesis__CL_Product__c=clp.id);
        insert app;
        System.assertEquals(app.genesis__Status__c,'Approved');
        
        insert new clcommon__Repayment_Plan__c(genesis__Application__c =app.Id, 
                                               clcommon__Frequency__c='Monthly',
                                               clcommon__Payment_Type__c='Interest Only',
                                               clcommon__Number_Of_Payments__c=1,
                                               clcommon__Payment_Start_Date__c=Date.today());
        
        //Inserting borrower bank account
        loan__Bank_Account__c borrBank= new loan__Bank_Account__c();
        borrBank.loan__Account__c=acc.Id;
        borrBank.loan__Account_Type__c='Saving';
        borrBank.loan__Account_Usage__c='Borrower/Investor Account';
        borrBank.loan__Bank_Account_Number__c='21432534543';
        borrBank.loan__Active__c=true;
        borrBank.loan__Bank_Name__c ='SBI';
        insert borrBank;
        System.assertEquals(borrBank.loan__Bank_Name__c,'SBI');
        
        //Inserting Borrower Party
        list< clcommon__Party_Type__c > partyTypes= new list<clcommon__Party_Type__c>();
        partyTypes.add(new clcommon__Party_Type__c(Name='BORROWER'));
        partyTypes.add(new clcommon__Party_Type__c(Name='Solicitor'));
        insert partyTypes;
        System.assertEquals(partyTypes.size(),2);
        
        //Inserting borrower Party
        clcommon__Party__c borrParty= new clcommon__Party__c(clcommon__Account__c=acc.Id, genesis__Application__c=app.Id,clcommon__Type__c=[select id from clcommon__Party_Type__c Where Name='BORROWER'].Id);
        insert borrParty;
        System.assertEquals(borrParty.clcommon__Account__c,acc.Id);
        
        //inserting Solicitor Account
        Account solicitorAcc= new Account();
        solicitorAcc.name = 'Test account';
        solicitorAcc.clcommon__Legal_Entity_Type__c = legEntity.id;
        insert solicitorAcc;
        System.assertEquals(solicitorAcc.name,'Test account');
        
        //Inserting solicitor Acc
        loan__Bank_Account__c soliBank= new loan__Bank_Account__c();
        soliBank.loan__Account__c=solicitorAcc.Id;
        soliBank.loan__Account_Type__c='Saving';
        soliBank.loan__Account_Usage__c='Borrower/Investor Account';
        soliBank.loan__Bank_Account_Number__c='21432534543';
        soliBank.loan__Active__c=true;
        soliBank.loan__Bank_Name__c ='SBI';
        insert soliBank;
        System.assertEquals(soliBank.loan__Bank_Name__c,'SBI');
        
        //Inserting borrower Party
        clcommon__Party__c solicitorParty= new clcommon__Party__c(clcommon__Account__c=solicitorAcc.Id, genesis__Application__c=app.Id,clcommon__Type__c=[select id from clcommon__Party_Type__c Where Name='Solicitor'].Id);
        insert solicitorParty;
        System.assertEquals(solicitorParty.clcommon__Account__c,solicitorAcc.Id);
        
        Test.startTest();
            String st=LoanApplicationConvert.convertLoanApplicationCtrl(app.Id);
            System.assert(st!=null);
        Test.stopTest();    
                
    }
    
}