elixir/force-app/main/default/objects/Account/fields/clcommon__Legal_Entity_Type__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Legal_Entity_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Legal Entity Type</label>
    <referenceTo>clcommon__Legal_Entity__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Borrower.recordType-meta.xml
<RecordType>
    <fullName>Borrower</fullName>
    <active>true</active>
    <label>Borrower</label>
</RecordType>

force-app/main/default/objects/clcommon__Party__c/clcommon__Party__c.object-meta.xml
<CustomObject>
    <label>Party</label>
    <nameField>
        <displayFormat>PAR-{00000000}</displayFormat>
        <label>Party Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

elixir/force-app/main/default/objects/clcommon__Party__c/fields/clcommon__Party_Type__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Party_Type__c</fullName>
    <label>Party Type(Deprecated)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DEALER</fullName>
            </value>
            <value>
                <fullName>BORROWER</fullName>
            </value>
            <value>
                <fullName>CO-BORROWER</fullName>
            </value>
            <value>
                <fullName>GUARANTOR</fullName>
            </value>
            <value>
                <fullName>ENTITY</fullName>
            </value>
            <value>
                <fullName>REVIEWER</fullName>
            </value>
            <value>
                <fullName>APPRAISER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/clcommon__Type__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Party Type</label>
    <referenceTo>clcommon__Party_Type__c</referenceTo>
    <relationshipLabel>Parties</relationshipLabel>
    <relationshipName>Parties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/Living_Expense_Used_for_Servicing_Purpos__c.field-meta.xml
<CustomField>
    <fullName>Living_Expense_Used_for_Servicing_Purpos__c</fullName>
    <label>Living Expense Used for Servicing Purpos</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Applications__c/fields/Monthly_Living_Expenses_Used__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Living_Expenses_Used__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Monthly Living Expenses Used</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DataMigrationBatchTest.cls
/****************************************************************************************************
Company              : Cloudkaptan Consultancy Services Pvt. Ltd. 
Class Name           : DataMigrationBatchTest 
Created Date         : 24/08/2022 
Developed By         : Sayak Mukhopadhyay 
Description          : This is Test class for DataMigrationBatch Class
****************************************************************************************************/
@isTest(SeeAllData = false)
public class DataMigrationBatchTest {
    @TestSetup
    static void initialize() {
        //Inserting Individual Legal Entity
        clcommon__Legal_Entity__c objLegEntity = GenericUtilityTestHelper.returnLegalEntity();
        System.AssertNotEquals(
            objLegEntity.Id,
            null,
            'Legal Entity inserted successfully.'
        );

        // Inserting Borrower Party Type
        clcommon__Party_Type__c objBorrowerPartyType = GenericUtilityTestHelper.returnBorrowerPartyType();
        System.AssertNotEquals(
            objBorrowerPartyType.Id,
            null,
            'Party Type inserted successfully.'
        );

        // Inserting Account for Individual
        Account objAccount = GenericUtilityTestHelper.insertDummyAccount();
        System.AssertNotEquals(
            objAccount.Id,
            null,
            'Account inserted successfully.'
        );
        objAccount.clcommon__Legal_Entity_Type__c = objLegEntity.id; 
        update objAccount;
        System.assertEquals(objAccount.clcommon__Legal_Entity_Type__c, objLegEntity.id, 'Account updated successfully!');

        // Inserting Application
        genesis__applications__c objApplication = GenericUtilityTestHelper.returnApplication(objAccount.id);
        System.AssertNotEquals(
            objApplication.Id,
            null,
            'Application inserted successfully.'
        );
        objApplication.Monthly_Living_Expenses_Used__c = 0.0;
        update objApplication;
        System.assertEquals(objApplication.Monthly_Living_Expenses_Used__c, 0.0, 'Application updated successfully!');

        // Inserting Individual Party 
        clcommon__Party__c objParty = GenericUtilityTestHelper.returnParty(objApplication.id,objAccount.id);
        System.AssertNotEquals(
            objParty.Id,
            null,
            'Party inserted successfully.'
        );
        objParty.clcommon__Type__c = objBorrowerPartyType.id; 
        objParty.Living_Expense_Used_for_Servicing_Purpos__c = 230.0;
        update objParty;
        System.assertEquals(objParty.Living_Expense_Used_for_Servicing_Purpos__c, 230.0, 'Party updated successfully!');
    }
    @isTest
    static void DataMigrationBatchTestMethodeOne() {
        List<genesis__applications__c> objApplicationList = [SELECT id,
                                                                Monthly_Living_Expenses_Used__c
                                                                FROM genesis__applications__c];
        System.assertEquals(objApplicationList.size() > 0, true, 'Application found successfully!');   
        DataMigrationBatch obj = new DataMigrationBatch();
        database.executebatch(obj,1);
        System.assertEquals(objApplicationList[0].Monthly_Living_Expenses_Used__c, 0.0, 'Application updated successfully!');
    }
}