elixir/force-app/main/default/objects/Account/fields/clcommon__Legal_Entity_Type__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Legal_Entity_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Legal Entity Type</label>
    <referenceTo>clcommon__Legal_Entity__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Borrower.recordType-meta.xml
<RecordType>
    <fullName>Borrower</fullName>
    <active>true</active>
    <label>Borrower</label>
</RecordType>

force-app/main/default/objects/clcommon__Party__c/clcommon__Party__c.object-meta.xml
<CustomObject>
    <label>Party</label>
    <nameField>
        <displayFormat>PAR-{00000000}</displayFormat>
        <label>Party Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

elixir/force-app/main/default/objects/clcommon__Party__c/fields/clcommon__Party_Type__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Party_Type__c</fullName>
    <label>Party Type(Deprecated)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DEALER</fullName>
            </value>
            <value>
                <fullName>BORROWER</fullName>
            </value>
            <value>
                <fullName>CO-BORROWER</fullName>
            </value>
            <value>
                <fullName>GUARANTOR</fullName>
            </value>
            <value>
                <fullName>ENTITY</fullName>
            </value>
            <value>
                <fullName>REVIEWER</fullName>
            </value>
            <value>
                <fullName>APPRAISER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/clcommon__Type__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Party Type</label>
    <referenceTo>clcommon__Party_Type__c</referenceTo>
    <relationshipLabel>Parties</relationshipLabel>
    <relationshipName>Parties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/Diff_Of_Asset_and_Liability__c.field-meta.xml
<CustomField>
    <fullName>Diff_Of_Asset_and_Liability__c</fullName>
    <label>Diff Of Asset and Liability</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

elixir/force-app/main/default/objects/clcommon__Party__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full</fullName>
            </value>
            <value>
                <fullName>Alt</fullName>
            </value>
            <value>
                <fullName>Lease</fullName>
                <isActive>false</isActive>
                <label>Lease</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/genesis__Application__c.field-meta.xml
<CustomField>
    <fullName>genesis__Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Parties</relationshipLabel>
    <relationshipName>Parties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/Legal_Entity_Type__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Type__c</fullName>
    <formula>clcommon__Account__r.clcommon__Legal_Entity_Type__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Legal Entity Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/Override_Amount__c.field-meta.xml
<CustomField>
    <fullName>Override_Amount__c</fullName>
    <label>Override Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/Party_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Party_Type_Name__c</fullName>
    <formula>clcommon__Type__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Party Type Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/Total_Current_Income_Period__c.field-meta.xml
<CustomField>
    <fullName>Total_Current_Income_Period__c</fullName>
    <label>Total Current Income Period</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/Total_Self_Employed_Income__c.field-meta.xml
<CustomField>
    <fullName>Total_Self_Employed_Income__c</fullName>
    <label>Total Self Employed Income</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Applications__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full Doc</fullName>
            </value>
            <value>
                <fullName>Alt Doc</fullName>
            </value>
            <value>
                <fullName>Lease Doc</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/Months_Self_Employed__c.field-meta.xml
<CustomField>
    <fullName>Months_Self_Employed__c</fullName>
    <label>Months Self Employed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

elixir/force-app/main/default/objects/genesis__Applications__c/fields/Override_Amount__c.field-meta.xml
<CustomField>
    <fullName>Override_Amount__c</fullName>
    <label>Override Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/Total_Current_Income_Period__c.field-meta.xml
<CustomField>
    <fullName>Total_Current_Income_Period__c</fullName>
    <inlineHelpText>If income has varied substantially (+/- 20% as a guide) over the last two years, commentary is required.
Max increase in year on year is capped at 120% of previous year. Where the income has decreased year on year, the second year’s income is to be used</inlineHelpText>
    <label>Total Current Income Period</label>
    <summarizedField>genesis__Income__c.genesis__Amount__c</summarizedField>
    <summaryFilterItems>
        <field>genesis__Income__c.Business_Income_Period__c</field>
        <operation>equals</operation>
        <value>Current</value>
    </summaryFilterItems>
    <summaryForeignKey>genesis__Income__c.genesis__Application__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/Total_Self_Employed_Full_Doc_Income__c.field-meta.xml
<CustomField>
    <fullName>Total_Self_Employed_Full_Doc_Income__c</fullName>
    <label>Total Self Employed Full Doc Income</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/Total_Self_Employed_Income__c.field-meta.xml
<CustomField>
    <fullName>Total_Self_Employed_Income__c</fullName>
    <label>Total Self Employed Income</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/genesis__Asset_Information__c/genesis__Asset_Information__c.object-meta.xml
<CustomObject>
    <description>This object will store the asset information for individual</description>
    <label>Asset Information</label>
    <nameField>
        <label>Asset Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Elixir_Prod/force-app/main/default/objects/genesis__Asset_Information__c/fields/genesis__Market_Value__c.field-meta.xml
<CustomField>
    <fullName>genesis__Market_Value__c</fullName>
    <description>Market value of asset</description>
    <label>Market Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

elixir/force-app/main/default/objects/genesis__Asset_Information__c/fields/genesis__Original_Amount__c.field-meta.xml
<CustomField>
    <fullName>genesis__Original_Amount__c</fullName>
    <description>Original amount of asset</description>
    <label>Original Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Elixir_Prod/force-app/main/default/objects/genesis__Asset_Information__c/fields/Party__c.field-meta.xml
<CustomField>
    <fullName>Party__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Party</label>
    <referenceTo>clcommon__Party__c</referenceTo>
    <relationshipLabel>Assets Information</relationshipLabel>
    <relationshipName>Assets_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Employment_Information__c/genesis__Employment_Information__c.object-meta.xml
<CustomObject>
    <label>Employment Information</label>
    <nameField>
        <label>Employment Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employment Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

elixir/force-app/main/default/objects/genesis__Employment_Information__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Document_Type_Set</valueSetName>
    </valueSet>
</CustomField>

elixir/force-app/main/default/objects/genesis__Employment_Information__c/fields/Months_Self_Employed__c.field-meta.xml
<CustomField>
    <fullName>Months_Self_Employed__c</fullName>
    <label>Months Self Employed</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/genesis__Employment_Information__c/fields/Override_Amount__c.field-meta.xml
<CustomField>
    <fullName>Override_Amount__c</fullName>
    <label>Override Amount</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

elixir/force-app/main/default/objects/genesis__Employment_Information__c/fields/Party__c.field-meta.xml
<CustomField>
    <fullName>Party__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Party</label>
    <referenceTo>clcommon__Party__c</referenceTo>
    <relationshipLabel>Employment Information</relationshipLabel>
    <relationshipName>Employment_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

elixir/force-app/main/default/objects/genesis__Employment_Information__c/fields/Total_Current_Income_Period__c.field-meta.xml
<CustomField>
    <fullName>Total_Current_Income_Period__c</fullName>
    <label>Total Current Income Period</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/genesis__Income__c/genesis__Income__c.object-meta.xml
<CustomObject>
    <description>This object will track the other income</description>
    <label>Income</label>
    <nameField>
        <label>Income Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incomes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Income__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full</fullName>
            </value>
            <value>
                <fullName>Alt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

elixir/force-app/main/default/objects/genesis__Income__c/fields/Employment_Information__c.field-meta.xml
<CustomField>
    <fullName>Employment_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employment Information</label>
    <referenceTo>genesis__Employment_Information__c</referenceTo>
    <relationshipLabel>Incomes</relationshipLabel>
    <relationshipName>Incomes</relationshipName>
    <type>Lookup</type>
</CustomField>

elixir/force-app/main/default/objects/genesis__Income__c/fields/genesis__Amount__c.field-meta.xml
<CustomField>
    <fullName>genesis__Amount__c</fullName>
    <description>The amount of other income</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Elixir_Prod/force-app/main/default/objects/genesis__Income__c/fields/Party__c.field-meta.xml
<CustomField>
    <fullName>Party__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Party</label>
    <referenceTo>clcommon__Party__c</referenceTo>
    <relationshipLabel>Incomes</relationshipLabel>
    <relationshipName>Incomes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Liability__c/genesis__Liability__c.object-meta.xml
<CustomObject>
    <description>This object will store the liabilities information for individual.</description>
    <label>Liability</label>
    <nameField>
        <label>Liability Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Liabilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Liability__c/fields/genesis__Original_Amount__c.field-meta.xml
<CustomField>
    <fullName>genesis__Original_Amount__c</fullName>
    <description>Principle amount</description>
    <label>Original Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

elixir/force-app/main/default/objects/genesis__Liability__c/fields/Party__c.field-meta.xml
<CustomField>
    <fullName>Party__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Party</label>
    <referenceTo>clcommon__Party__c</referenceTo>
    <relationshipLabel>Liabilities</relationshipLabel>
    <relationshipName>Liabilities</relationshipName>
    <type>Lookup</type>
</CustomField>

elixir/force-app/main/default/globalValueSets/Document_Type_Set.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Full</fullName>
    </customValue>
    <customValue>
        <fullName>Alt</fullName>
    </customValue>
    <masterLabel>Document Type Set</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/UpdateEmpOnAppTest.cls
/****************************************************************************************************
Company              : Cloudkaptan Consultancy Services Pvt. Ltd. 
Class Name           : UpdateEmploymentTypeOnApplication 
Created Date         : 13/07/2022 
Developed By         : Sayak Mukhopadhyay 
Description          : This is Test class of UpdateEmploymentTypeOnApplication,UpdateEmpTypeBatch,
                        UpdateTotalIncomesOnParty
****************************************************************************************************/
@isTest(SeeAllData = false)
public class UpdateEmpOnAppTest {
    @TestSetup
    static void initialize(){
        //Inserting Individual Legal Entity
        clcommon__Legal_Entity__c objLegEntity = GenericUtilityTestHelper.returnLegalEntity();
        System.AssertNotEquals(
            objLegEntity.Id,
            null,
            'Legal Entity inserted successfully.'
        );
        //Inserting Joint Legal Entity
        clcommon__Legal_Entity__c objJointLegEntity = GenericUtilityTestHelper.returnJointLegalEntity();
        System.AssertNotEquals(
            objJointLegEntity.Id,
            null,
            'Legal Entity inserted successfully.'
        );
        // Inserting Borrower Party Type
        clcommon__Party_Type__c objBorrowerPartyType = GenericUtilityTestHelper.returnBorrowerPartyType();
        System.AssertNotEquals(
            objBorrowerPartyType.Id,
            null,
            'Party Type inserted successfully.'
        );
        // Inserting Borrower Party Type
        clcommon__Party_Type__c objHouseholdPartyType = GenericUtilityTestHelper.returnHouseholdPartyType();
        System.AssertNotEquals(
            objHouseholdPartyType.Id,
            null,
            'Party Type inserted successfully.'
        );
        // Inserting Account for Individual
        Account objAccount = GenericUtilityTestHelper.insertDummyAccount();
        objAccount.clcommon__Legal_Entity_Type__c = objLegEntity.id; // Individual
        update objAccount;
        System.AssertNotEquals(
            objAccount.Id,
            null,
            'Account inserted successfully.'
        );
        // Inserting Account For Household 
        Account objHouseholdAccount = GenericUtilityTestHelper.insertDummyAccount();
        objHouseholdAccount.clcommon__Legal_Entity_Type__c = objJointLegEntity.id;
        objHouseholdAccount.Name = 'Elixir & Financial';
        update objHouseholdAccount;
        System.AssertNotEquals(
            objHouseholdAccount.Id,
            null,
            'Account inserted successfully.'
        );
        // Inserting Application
        genesis__applications__c objApplication = GenericUtilityTestHelper.returnApplication(objAccount.id);
        objApplication.Total_Self_Employed_Income__c = 0;
        objApplication.Total_Self_Employed_Full_Doc_Income__c = 0;
        objApplication.Months_Self_Employed__c = 0;
        update objApplication;
        System.AssertNotEquals(
            objApplication.Id,
            null,
            'Application inserted successfully.'
        );
        // Inserting Individual Party 
        clcommon__Party__c objParty = GenericUtilityTestHelper.returnParty(objApplication.id,objAccount.id);
        //objParty.clcommon__Type__c = 'a2V2N000000IHVk'; // Borrower
        objParty.clcommon__Type__c = objBorrowerPartyType.id; // Borrower
        update objParty;
        System.AssertNotEquals(
            objParty.Id,
            null,
            'Party inserted successfully.'
        );
        // Inserting Household Party 
        clcommon__Party__c objHouseholdParty = GenericUtilityTestHelper.returnParty(objApplication.id,objHouseholdAccount.id);
        //objHouseholdParty.clcommon__Type__c = 'a2V2N000000IHWU'; // Household
        objHouseholdParty.clcommon__Type__c = objHouseholdPartyType.id;
        //objHouseholdParty.Diff_Of_Asset_and_Liability__c = 500;
        update objHouseholdParty;
        System.AssertNotEquals(
            objHouseholdParty.Id,
            null,
            'Party inserted successfully.'
        );
        // Inserting Employment Information
        genesis__Employment_Information__c objEmpInfo = GenericUtilityTestHelper.returnEmploymentInformation(objApplication.id);
        objEmpInfo.Override_Amount__c = '10';
        objEmpInfo.Months_Self_Employed__c = 0;
        objEmpInfo.Document_Type__c = 'Full';
        objEmpInfo.Party__c = objParty.id;
        objEmpInfo.Total_Current_Income_Period__c = 200;
        update objEmpInfo;
        System.AssertNotEquals(
            objEmpInfo.Id,
            null,
            'Employment Information inserted successfully.'
        );
        // Inserting Income
        genesis__Income__c objIncome = GenericUtilityTestHelper.returnEmploymentInformation(objApplication.id,objEmpInfo.id);
        objIncome.genesis__Amount__c = 0;
        objIncome.Document_Type__c = ConstantValues.ALT;
        objIncome.Party__c = objParty.id;
        update objIncome;
        System.AssertNotEquals(
            objIncome.Id,
            null,
            'Income inserted successfully.'
        );
        // Inserting Liability
        genesis__Liability__c objLiability = GenericUtilityTestHelper.returnLiability(objApplication.id);
        objLiability.genesis__Original_Amount__c = 200;
        update objLiability;
        System.AssertNotEquals(
            objLiability.Id,
            null,
            'Liability inserted successfully.'
        );
        // Inserting Asset
        genesis__Asset_Information__c objAssetInfo = GenericUtilityTestHelper.returnAssetInformation(objApplication.id);
        objAssetInfo.genesis__Market_Value__c = 300;
        update objAssetInfo;
        System.AssertNotEquals(
            objAssetInfo.Id,
            null,
            'Liability inserted successfully.'
        );
    }
    @isTest
    static void UpdateEmpTestMethodOne(){
        test.startTest();
        List<genesis__applications__c> objApplicationList = [SELECT id
                                                                FROM genesis__applications__c];
        List<genesis__Employment_Information__c> objEmpInfoList = [SELECT id,Party__c,Party__r.Party_Type_Name__c,Party__r.Legal_Entity_Type__c,Document_Type__c FROM genesis__Employment_Information__c WHERE genesis__Application__c in :objApplicationList];                                                       
        UpdateEmploymentTypeOnApplication.updateEmploymentTypeWS(objApplicationList[0].id);
    }
    @isTest
    static void UpdateEmpTestMethodTwo(){
        test.startTest();
        List<genesis__Employment_Information__c> objEmpInfoList = [SELECT id,Document_Type__c,Override_Amount__c,Income_for_servicing_purposes__c FROM genesis__Employment_Information__c];
        if(objEmpInfoList.size()>0){
            objEmpInfoList[0].Document_Type__c = ConstantValues.ALT;
            objEmpInfoList[0].Override_Amount__c = null;
            objEmpInfoList[0].Total_Current_Income_Period__c = 10;
            objEmpInfoList[0].Total_Previous_Income_Period__c = 9;
            update objEmpInfoList[0];
        }
        List<genesis__applications__c> objApplicationList = [SELECT id
                                                                FROM genesis__applications__c];                                                       
        if(objApplicationList.size()>0){
            List <clcommon__Party__c> partyList = [Select Id from clcommon__Party__c where genesis__Application__c =: objApplicationList[0].Id];
            System.assert(partyList.size() > 0, 'Party found successfully!');
            List <genesis__Income__c> incomeList = [SELECT id,
                                                        genesis__Amount__c,
                                                        genesis__Application__r.id,
                                                        genesis__Frequency__c
                                                        FROM genesis__Income__c
                                                        WHERE genesis__Application__c =: objApplicationList[0].Id];
            System.assertEquals(incomeList.size() > 0, true, 'Incomes inserted successfully!');  
            incomeList[0].PAYG_Income__c = true;
            incomeList[0].genesis__Frequency__c = ConstantValues.weekly;
            incomeList[0].genesis__Amount__c = 100;
            update incomeList;
            incomeList = [SELECT id,
                              genesis__Amount__c,
                              genesis__Application__r.id,
                              genesis__Frequency__c
                          FROM genesis__Income__c
                          WHERE genesis__Application__c =: objApplicationList[0].Id
                          AND PAYG_Income__c = TRUE];
            System.assertEquals(incomeList.size() > 0, true, 'Incomes updated successfully!');                                           
            UpdateEmploymentTypeOnApplication.updateEmploymentTypeWS(objApplicationList[0].id);
            UpdateTotalIncomesOnParty.updateIncomesWS(partyList[0].Id);
            UpdateEmpTypeBatch obj = new UpdateEmpTypeBatch(); 
            database.executebatch(obj,1);
        }
    }
    @isTest
    static void UpdateEmpTestMethodThree(){
        test.startTest();
        List<genesis__Employment_Information__c> objEmpInfoList = [SELECT id,Document_Type__c,Override_Amount__c,Income_for_servicing_purposes__c FROM genesis__Employment_Information__c];
        if(objEmpInfoList.size()>0){
            objEmpInfoList[0].Document_Type__c = 'Alt';
            objEmpInfoList[0].Override_Amount__c = null;
            objEmpInfoList[0].Total_Current_Income_Period__c = 10;
            objEmpInfoList[0].Total_Previous_Income_Period__c = 9;
            update objEmpInfoList[0];
        }
        List<genesis__applications__c> objApplicationList = [SELECT id
                                                                FROM genesis__applications__c];                                                       
        if(objApplicationList.size()>0){
            List <clcommon__Party__c> partyList = [Select Id from clcommon__Party__c where genesis__Application__c =: objApplicationList[0].Id];
            System.assert(partyList.size() > 0, 'Party found successfully!');
            List <genesis__Income__c> incomeList = [SELECT id,
                                                        genesis__Amount__c,
                                                        genesis__Application__r.id,
                                                        genesis__Frequency__c
                                                        FROM genesis__Income__c
                                                        WHERE genesis__Application__c =: objApplicationList[0].Id];
            System.assertEquals(incomeList.size() > 0, true, 'Incomes inserted successfully!');  
            incomeList[0].PAYG_Income__c = true;
            incomeList[0].genesis__Frequency__c = ConstantValues.FORTNIGHTLY;
            incomeList[0].genesis__Amount__c = 100;
            update incomeList;
            UpdateEmploymentTypeOnApplication.updateEmploymentTypeWS(objApplicationList[0].id);
            incomeList = [SELECT id,
                              genesis__Amount__c,
                              genesis__Application__r.id,
                              genesis__Frequency__c
                          FROM genesis__Income__c
                          WHERE genesis__Application__c =: objApplicationList[0].Id
                          AND PAYG_Income__c = TRUE];
            System.assertEquals(incomeList.size() > 0, true, 'Incomes updated successfully!');                                           
            UpdateEmpTypeBatch obj = new UpdateEmpTypeBatch(); 
            database.executebatch(obj,1);
        }
    }
    @isTest
    static void UpdateEmpTestMethodFour(){
        test.startTest();
        List<genesis__Employment_Information__c> objEmpInfoList = [SELECT id,Document_Type__c,Override_Amount__c,Income_for_servicing_purposes__c FROM genesis__Employment_Information__c];
        if(objEmpInfoList.size()>0){
            objEmpInfoList[0].Document_Type__c = 'Alt';
            objEmpInfoList[0].Override_Amount__c = null;
            objEmpInfoList[0].Total_Current_Income_Period__c = 10;
            objEmpInfoList[0].Total_Previous_Income_Period__c = 9;
            update objEmpInfoList[0];
        }
        List<genesis__applications__c> objApplicationList = [SELECT id
                                                                FROM genesis__applications__c];                                                       
        if(objApplicationList.size()>0){
            List <clcommon__Party__c> partyList = [Select Id from clcommon__Party__c where genesis__Application__c =: objApplicationList[0].Id];
            System.assert(partyList.size() > 0, 'Party found successfully!');
            List <genesis__Income__c> incomeList = [SELECT id,
                                                        genesis__Amount__c,
                                                        genesis__Application__r.id,
                                                        genesis__Frequency__c
                                                        FROM genesis__Income__c
                                                        WHERE genesis__Application__c =: objApplicationList[0].Id];
            System.assertEquals(incomeList.size() > 0, true, 'Incomes inserted successfully!');  
            incomeList[0].PAYG_Income__c = true;
            incomeList[0].genesis__Frequency__c = ConstantValues.YEARLY;
            incomeList[0].genesis__Amount__c = 100;
            update incomeList;
            incomeList = [SELECT id,
                              genesis__Amount__c,
                              genesis__Application__r.id,
                              genesis__Frequency__c
                          FROM genesis__Income__c
                          WHERE genesis__Application__c =: objApplicationList[0].Id
                          AND PAYG_Income__c = TRUE];
            System.assertEquals(incomeList.size() > 0, true, 'Incomes updated successfully!');                                           
            UpdateEmploymentTypeOnApplication.updateEmploymentTypeWS(objApplicationList[0].id);
            UpdateEmpTypeBatch obj = new UpdateEmpTypeBatch(); 
            database.executebatch(obj,1);
        }
    }
    @isTest
    static void UpdateEmpTestMethodFive(){
        test.startTest();
        List<genesis__Employment_Information__c> objEmpInfoList = [SELECT id,Document_Type__c,Override_Amount__c,Income_for_servicing_purposes__c FROM genesis__Employment_Information__c];
        if(objEmpInfoList.size()>0){
            objEmpInfoList[0].Document_Type__c = 'Alt';
            objEmpInfoList[0].Override_Amount__c = null;
            objEmpInfoList[0].Total_Current_Income_Period__c = 10;
            objEmpInfoList[0].Total_Previous_Income_Period__c = 9;
            update objEmpInfoList[0];
        }
        List<genesis__applications__c> objApplicationList = [SELECT id
                                                                FROM genesis__applications__c];                                                       
        if(objApplicationList.size()>0){
            List <clcommon__Party__c> partyList = [Select Id from clcommon__Party__c where genesis__Application__c =: objApplicationList[0].Id];
            System.assert(partyList.size() > 0, 'Party found successfully!');
            List <genesis__Income__c> incomeList = [SELECT id,
                                                        genesis__Amount__c,
                                                        genesis__Application__r.id,
                                                        genesis__Frequency__c
                                                        FROM genesis__Income__c
                                                        WHERE genesis__Application__c =: objApplicationList[0].Id];
            System.assertEquals(incomeList.size() > 0, true, 'Incomes inserted successfully!');  
            incomeList[0].PAYG_Income__c = true;
            incomeList[0].genesis__Frequency__c = ConstantValues.monthly;
            incomeList[0].genesis__Amount__c = 100;
            update incomeList;
            incomeList = [SELECT id,
                              genesis__Amount__c,
                              genesis__Application__r.id,
                              genesis__Frequency__c
                          FROM genesis__Income__c
                          WHERE genesis__Application__c =: objApplicationList[0].Id
                          AND PAYG_Income__c = TRUE];
            UpdateEmploymentTypeOnApplication.updateEmploymentTypeWS(objApplicationList[0].id);
            System.assertEquals(incomeList.size() > 0, true, 'Incomes updated successfully!');                                           
            UpdateEmpTypeBatch obj = new UpdateEmpTypeBatch(); 
            database.executebatch(obj,1);
        }
    }
    @isTest
    static void UpdateEmpTestMethodSix(){
        test.startTest();
        List<genesis__Employment_Information__c> objEmpInfoList = [SELECT id,Document_Type__c,Override_Amount__c,Income_for_servicing_purposes__c FROM genesis__Employment_Information__c];
        if(objEmpInfoList.size()>0){
            objEmpInfoList[0].Document_Type__c = 'Alt';
            objEmpInfoList[0].Override_Amount__c = null;
            objEmpInfoList[0].Total_Current_Income_Period__c = 10;
            objEmpInfoList[0].Total_Previous_Income_Period__c = 9;
            update objEmpInfoList[0];
        }
        List<genesis__applications__c> objApplicationList = [SELECT id
                                                                FROM genesis__applications__c];                                                       
        if(objApplicationList.size()>0){
            List <clcommon__Party__c> partyList = [Select Id from clcommon__Party__c where genesis__Application__c =: objApplicationList[0].Id];
            System.assert(partyList.size() > 0, 'Party found successfully!');
            List <genesis__Income__c> incomeList = [SELECT id,
                                                        genesis__Amount__c,
                                                        Unemployed_Income__c,
                                                        genesis__Application__r.id,
                                                        genesis__Frequency__c
                                                        FROM genesis__Income__c
                                                        WHERE genesis__Application__c =: objApplicationList[0].Id];
            System.assertEquals(incomeList.size() > 0, true, 'Incomes inserted successfully!');  
            incomeList[0].Employment_Information__c = null;
            incomeList[0].Unemployed_Income__c = true;
            incomeList[0].genesis__Frequency__c = ConstantValues.monthly;
            incomeList[0].genesis__Amount__c = 100;
            update incomeList;
            incomeList = [SELECT id,
                              genesis__Amount__c,
                              genesis__Application__r.id,
                              genesis__Frequency__c
                          FROM genesis__Income__c
                          WHERE genesis__Application__c =: objApplicationList[0].Id
                          AND Unemployed_Income__c = TRUE];
            System.assertEquals(incomeList.size() > 0, true, 'Incomes updated successfully!');                                           
            UpdateTotalIncomesOnParty.updateIncomesWS(partyList[0].Id);
            CustomerCallBatch obj = new CustomerCallBatch(); 
            database.executebatch(obj,1);
        }
    }
    @isTest
    static void UpdateEmpTestMethodSeven(){
        test.startTest();
        List<genesis__Employment_Information__c> objEmpInfoList = [SELECT id,Document_Type__c,Override_Amount__c,Income_for_servicing_purposes__c FROM genesis__Employment_Information__c];
        if(objEmpInfoList.size()>0){
            objEmpInfoList[0].Document_Type__c = 'Alt';
            objEmpInfoList[0].Override_Amount__c = null;
            objEmpInfoList[0].Total_Current_Income_Period__c = 10;
            objEmpInfoList[0].Total_Previous_Income_Period__c = 9;
            update objEmpInfoList[0];
        }
        List<genesis__applications__c> objApplicationList = [SELECT id
                                                                FROM genesis__applications__c];                                                       
        if(objApplicationList.size()>0){
            List <clcommon__Party__c> partyList = [Select Id from clcommon__Party__c where genesis__Application__c =: objApplicationList[0].Id];
            System.assert(partyList.size() > 0, 'Party found successfully!');
            List <genesis__Income__c> incomeList = [SELECT id,
                                                        genesis__Amount__c,
                                                        Other_Income__c,
                                                        genesis__Application__r.id,
                                                        genesis__Frequency__c
                                                        FROM genesis__Income__c
                                                        WHERE genesis__Application__c =: objApplicationList[0].Id];
            System.assertEquals(incomeList.size() > 0, true, 'Incomes inserted successfully!');  
            incomeList[0].Employment_Information__c = null;
            incomeList[0].Other_Income__c = true;
            incomeList[0].genesis__Frequency__c = ConstantValues.monthly;
            incomeList[0].genesis__Amount__c = 100;
            update incomeList;
            incomeList = [SELECT id,
                              genesis__Amount__c,
                              genesis__Application__r.id,
                              genesis__Frequency__c
                          FROM genesis__Income__c
                          WHERE genesis__Application__c =: objApplicationList[0].Id
                          AND Other_Income__c = TRUE];
            System.assertEquals(incomeList.size() > 0, true, 'Incomes updated successfully!');                                           
            UpdateTotalIncomesOnParty.updateIncomesWS(partyList[0].Id);
            CustomerCallBatch obj = new CustomerCallBatch(); 
            database.executebatch(obj,1);
        }
    }
    @isTest
    static void UpdateEmpTestMethodEight(){
        test.startTest();
        List<genesis__applications__c> objApplicationList = [SELECT id
                                                                FROM genesis__applications__c];                                                       
        if(objApplicationList.size()>0){
            CustomerCallBatch obj = new CustomerCallBatch(); 
            database.executebatch(obj,1);
        }
    }
}