elixir/force-app/main/default/objects/Account/fields/clcommon__Legal_Entity_Type__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Legal_Entity_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Legal Entity Type</label>
    <referenceTo>clcommon__Legal_Entity__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

elixir/force-app/main/default/objects/Account/fields/Last_Approved_Application_ID__c.field-meta.xml
<CustomField>
    <fullName>Last_Approved_Application_ID__c</fullName>
    <label>Last Approved Application ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

elixir/force-app/main/default/objects/Elixir_Before_Or_On_Settlement_Fees__c/Elixir_Before_Or_On_Settlement_Fees__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Elixir Before Or On Settlement Fees</label>
</CustomObject>

elixir/force-app/main/default/objects/Elixir_Before_Or_On_Settlement_Fees__c/fields/Fee_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Fee_Field_API_Name__c</fullName>
    <label>Fee Field API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

elixir/force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

elixir/force-app/main/default/objects/genesis__Applications__c/fields/Application_Fee__c.field-meta.xml
<CustomField>
    <fullName>Application_Fee__c</fullName>
    <label>Application Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

elixir/force-app/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <customHelpPage>loan__CLContractHelp</customHelpPage>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Elixir_Prod/force-app/main/default/objects/loan__Loan_Account__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>CL Contracts</relationshipLabel>
    <relationshipName>CL_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Please choose a account, which will be associated as a customer on this lending account.
You can create a new account, from the lookup window by clicking on new or select the existing account from the lookup.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Loan_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

elixir/force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Frequency_of_Loan_Payment__c.field-meta.xml
<CustomField>
    <fullName>loan__Frequency_of_Loan_Payment__c</fullName>
    <inlineHelpText>This decides the Payment Frequency, below are the supported ones:
Daily
Weekly
Bi-weekly
Semi-Monthly
Monthly
Bi-Monthly
Quarterly
Semi-Annual
Annual
Single-Payment</inlineHelpText>
    <label>Payment Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Bi-weekly</fullName>
            </value>
            <value>
                <fullName>Semi-Monthly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
                <default>true</default>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Semi-Annual</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Single-Payment</fullName>
            </value>
            <value>
                <fullName>Semi-Monthly-PD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

elixir/force-app/main/default/classes/PrepaidFeeCalculatorClassTest.cls
/************************************************************************
Description: Test class for PrepaidFeeCalculatorClass
Developer: Rameswari Barman
**************************************************************************/
@isTest
public class PrepaidFeeCalculatorClassTest{
    public static testmethod void test1(){
        //Disabling triggers
        insert new genesis__Org_Parameters__c(genesis__Disable_Triggers__c=true);
        System.assert(genesis__Org_Parameters__c.getInstance()!=null);
        
        //Fee structure
        list<Elixir_Before_Or_On_Settlement_Fees__c> feeSetup= new list<Elixir_Before_Or_On_Settlement_Fees__c>();
        feeSetup.add(new Elixir_Before_Or_On_Settlement_Fees__c(Name='Application Fee', Distribution_Type__c='Pre-Paid Fee', Fee_Field_API_Name__c='Application_Fee__c'));
        insert feeSetup;
        System.assert(Elixir_Before_Or_On_Settlement_Fees__c.getAll().size()==1);
        
        //Inserting legal entity
        clcommon__Legal_Entity__c legEntity = new clcommon__Legal_Entity__c(Name = 'Individual');
        insert legEntity;
        System.assertEquals(legEntity.name,'Individual');
            
        //Inserting Account
        Account acc = new Account(name = 'Rameswari Barman',clcommon__Legal_Entity_Type__c = legEntity.id);
        insert acc;
        
        //Inserting Applications
        genesis__applications__c app = new genesis__applications__c(genesis__Fees_Amount__c=10,genesis__account__c = acc.id);
        insert app;
        System.assertEquals(app.genesis__Fees_Amount__c,10);
        
        acc.last_Approved_Application_ID__c = app.Id;
        update acc;
        
        loan__Loan_Account__c  loanAcc=ElixirTestHelper.returnLoanAccount();
        loanAcc.loan__Account__c=acc.Id;
        loanAcc.loan__Frequency_of_Loan_Payment__c='Weekly';
        loanAcc.Application__c = app.Id;
        upsert loanAcc;
        System.assertEquals(loanAcc.loan__Account__c,acc.Id);

        Test.startTest();
        PrepaidFeeCalculatorClass feeClsObj= new PrepaidFeeCalculatorClass();
        Decimal fee1=feeClsObj.computeFee(new loan__Fee__c(Name='Application Fee'),loanAcc);
        Test.stopTest();            
    }
    public static testmethod void test2(){
        //Disabling triggers
        insert new genesis__Org_Parameters__c(genesis__Disable_Triggers__c=true);
        System.assert(genesis__Org_Parameters__c.getInstance()!=null);
        
        //Fee structure
        list<Elixir_Before_Or_On_Settlement_Fees__c> feeSetup= new list<Elixir_Before_Or_On_Settlement_Fees__c>();
        feeSetup.add(new Elixir_Before_Or_On_Settlement_Fees__c(Name='Application Fee', Distribution_Type__c='Pre-Paid Fee', Fee_Field_API_Name__c='Application_Fee__c'));
        insert feeSetup;
        System.assert(Elixir_Before_Or_On_Settlement_Fees__c.getAll().size()==1);
        
        //Inserting legal entity
        clcommon__Legal_Entity__c legEntity = new clcommon__Legal_Entity__c(Name = 'Individual');
        insert legEntity;
        System.assertEquals(legEntity.Name,'Individual');
            
        //Inserting Account
        Account acc = new Account(name = 'Rameswari Barman',clcommon__Legal_Entity_Type__c = legEntity.id);
        insert acc;
        System.assertEquals(acc.name,'Rameswari Barman');
        
        //Inserting Applications
        genesis__applications__c app = new genesis__applications__c(genesis__Fees_Amount__c=10,genesis__account__c = acc.id);
        insert app;
        System.assertEquals(app.genesis__Fees_Amount__c,10);
        
        acc.last_Approved_Application_ID__c = app.Id;
        update acc;

        loan__Loan_Account__c  loanAcc=ElixirTestHelper.returnLoanAccount();
        loanAcc.loan__Account__c=acc.Id;
        loanAcc.loan__Frequency_of_Loan_Payment__c='Weekly';
        loanAcc.Application__c = app.Id;
        upsert loanAcc;
        System.assertEquals(loanAcc.loan__Account__c,acc.Id);

        Test.startTest();
        PrepaidFeeCalculatorClass feeClsObj= new PrepaidFeeCalculatorClass();
        Decimal fee1=feeClsObj.computeFee(new loan__Fee__c(Name='A'),loanAcc);
        Test.stopTest();            
    }
}