elixir/force-app/main/default/objects/Account/fields/clcommon__Legal_Entity_Type__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Legal_Entity_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Legal Entity Type</label>
    <referenceTo>clcommon__Legal_Entity__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Borrower.recordType-meta.xml
<RecordType>
    <fullName>Borrower</fullName>
    <active>true</active>
    <label>Borrower</label>
</RecordType>

force-app/main/default/objects/clcommon__Party__c/clcommon__Party__c.object-meta.xml
<CustomObject>
    <label>Party</label>
    <nameField>
        <displayFormat>PAR-{00000000}</displayFormat>
        <label>Party Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

elixir/force-app/main/default/objects/clcommon__Party__c/fields/Allow_Direct_Marketing__c.field-meta.xml
<CustomField>
    <fullName>Allow_Direct_Marketing__c</fullName>
    <label>Allow Direct Marketing</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>YesNo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/clcommon__Contact__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Parties</relationshipLabel>
    <relationshipName>Parties</relationshipName>
    <type>Lookup</type>
</CustomField>

elixir/force-app/main/default/objects/clcommon__Party__c/fields/clcommon__Party_Type__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Party_Type__c</fullName>
    <label>Party Type(Deprecated)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DEALER</fullName>
            </value>
            <value>
                <fullName>BORROWER</fullName>
            </value>
            <value>
                <fullName>CO-BORROWER</fullName>
            </value>
            <value>
                <fullName>GUARANTOR</fullName>
            </value>
            <value>
                <fullName>ENTITY</fullName>
            </value>
            <value>
                <fullName>REVIEWER</fullName>
            </value>
            <value>
                <fullName>APPRAISER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/clcommon__Party__c/fields/clcommon__Type__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Party Type</label>
    <referenceTo>clcommon__Party_Type__c</referenceTo>
    <relationshipLabel>Parties</relationshipLabel>
    <relationshipName>Parties</relationshipName>
    <type>Lookup</type>
</CustomField>

elixir/force-app/main/default/objects/clcommon__Party__c/fields/Director__c.field-meta.xml
<CustomField>
    <fullName>Director__c</fullName>
    <label>Director</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

elixir/force-app/main/default/objects/clcommon__Party__c/fields/First_Home_Buyer__c.field-meta.xml
<CustomField>
    <fullName>First_Home_Buyer__c</fullName>
    <label>First Home Buyer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>YesNo</valueSetName>
    </valueSet>
</CustomField>

elixir/force-app/main/default/objects/Contact/fields/clcommon__Legal_Entity_Type__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Legal_Entity_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Legal Entity Type</label>
    <referenceTo>clcommon__Legal_Entity__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Credit_Account__c/Credit_Account__c.object-meta.xml
<CustomObject>
    <label>Credit Account</label>
    <nameField>
        <displayFormat>CA-{0000}</displayFormat>
        <label>Consumer Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Credit_Enquiry__c/Credit_Enquiry__c.object-meta.xml
<CustomObject>
    <label>Credit Enquiry</label>
    <nameField>
        <displayFormat>CEN-{0000}</displayFormat>
        <label>Credit Enquiry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Enquiries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Current_Directorship__c/Current_Directorship__c.object-meta.xml
<CustomObject>
    <label>Current Directorship</label>
    <nameField>
        <displayFormat>DIR-{0000}</displayFormat>
        <label>Directorship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Current Directorships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Director__c/Director__c.object-meta.xml
<CustomObject>
    <label>Director</label>
    <nameField>
        <displayFormat>DA-{00000}</displayFormat>
        <label>Director Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Directors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Applications__c/fields/Allow_Direct_Marketing__c.field-meta.xml
<CustomField>
    <fullName>Allow_Direct_Marketing__c</fullName>
    <label>Allow Direct Marketing</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/First_Home_Buyer__c.field-meta.xml
<CustomField>
    <fullName>First_Home_Buyer__c</fullName>
    <label>First Home Buyer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>YesNo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Default__c/Payment_Default__c.object-meta.xml
<CustomObject>
    <label>Payment Default</label>
    <nameField>
        <displayFormat>PD-{0000}</displayFormat>
        <label>Payment Defaults Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Defaults</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Default__c/fields/Credit_Account__c.field-meta.xml
<CustomField>
    <fullName>Credit_Account__c</fullName>
    <label>Credit Account</label>
    <referenceTo>Credit_Account__c</referenceTo>
    <relationshipLabel>Payment Defaults</relationshipLabel>
    <relationshipName>Payment_Defaults</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/LinkPartyCreditReportTest.cls
/****************************************************************************************************
Company: Cloudkaptan Consultancy Services Pvt. Ltd.
Author: Ariz Mazhary
Description : This class give coverage to LinkPartyCreditReport class
Development Date : 26/07/2021
Last Modified Date : 30/07/2021
****************************************************************************************************/

@isTest(SeeAllData=false)
public class LinkPartyCreditReportTest {
	@TestSetup
    static void initialize(){

        //Inserting legal entity
        clcommon__Legal_Entity__c legEntity = GenericUtilityTestHelper.returnLegalEntity();
        System.AssertNotEquals(
            legEntity.Id,
            null,
            ' Legal Entity inserted successfully.'
        );
        
        //Inserting Account
        Account testAccount = GenericUtilityTestHelper.insertDummyAccount();
        testAccount.clcommon__Legal_Entity_Type__c=legEntity.Id;
        update testAccount;
        List<Account> testAccountList=[SELECT id 
                                        FROM Account 
                                        WHERE clcommon__Legal_Entity_Type__r.Name=:ConstantValues.indType 
                                        LIMIT 1];
        System.AssertNotEquals(
        testAccount.Id,
        null,
        ' Account inserted successfully.'
        );
        
        //Insert Contact
        Contact testContact=GenericUtilityTestHelper.insertDummyContact(
            testAccount
        );
        System.AssertNotEquals(
        testContact.Id,
        null,
        ' Contact inserted successfully.'
        );

        //Insert Application
        genesis__Applications__c testApplication = GenericUtilityTestHelper.returnApplication(
            testAccount.Id
        );
        testApplication.Allow_Direct_Marketing__c=ConstantValues.NO_TAG;
        testApplication.First_Home_Buyer__c=ConstantValues.NO_TAG;
        update testApplication;
        List<genesis__Applications__c> applicationList=[SELECT id 
                                                        FROM genesis__Applications__c 
                                                        WHERE Allow_Direct_Marketing__c=:ConstantValues.NO_TAG
                                                        LIMIT 1 ];
        System.assertEquals(
            applicationList.size(), 
            1, 
            'Application Inserted Successfully'
        );
        clcommon__Party_Type__c partyType =GenericUtilityTestHelper.insertPartyType(ConstantValues.BORROWER);
        System.AssertNotEquals(
            partyType.Id,
            null,
            ' Party Type inserted successfully.'
        );

        clcommon__Party_Type__c partyType1 =GenericUtilityTestHelper.insertPartyType('Co-Applicant');
        System.AssertNotEquals(
            partyType.Id,
            null,
            ' Party Type inserted successfully.'
        );

        //Insert Party
        clcommon__Party__c testParty=GenericUtilityTestHelper.returnParty(
            testApplication.id,
            testAccount.Id
        );
        testParty.clcommon__Contact__c=testContact.Id;
        testParty.clcommon__Type__c=partyType.Id ;
        update testParty;
        List<clcommon__Party__c> partyList=[SELECT id 
                                                        FROM clcommon__Party__c 
                                                        WHERE id=:testParty.Id
                                                        LIMIT 1 ];
        System.assertEquals(
            partyList.size(), 
            1, 
            'Party Inserted Successfully'
        );

        //Insert Party
        clcommon__Party__c testParty1=GenericUtilityTestHelper.returnParty(
            testApplication.id,
            testAccount.Id
        );
        testParty1.clcommon__Contact__c=testContact.Id;
        testParty1.First_Home_Buyer__c=ConstantValues.YES_TAG;
        testParty1.clcommon__Type__c=partyType1.Id ;
        update testParty1;
        List<clcommon__Party__c> partyList1=[SELECT id 
                                                        FROM clcommon__Party__c 
                                                        WHERE id=:testParty1.Id
                                                        LIMIT 1 ];
        System.assertEquals(
            partyList1.size(), 
            1, 
            'Party Inserted Successfully'
        );
        //Insert Credit Account
        Credit_Account__c testCreditAccount=GenericUtilityTestHelper.createCreditAccount(
            testParty1.id
        );
        System.AssertNotEquals(
            testCreditAccount.id,
            null,
            'Credit Account Inserted Successfully'
        );
        //Insert Payment Default
        Payment_Default__c testPaymentDefault=GenericUtilityTestHelper.createPaymentDefaults(
            testParty1.id,
            testCreditAccount.id
        );
        System.AssertNotEquals(
            testPaymentDefault.id,
            null,
            'payment Default Inserted Successfully'
        );
        //Insert Director
        Director__c testdirector=GenericUtilityTestHelper.returnDirector(
            testParty1.id
        );
        System.AssertNotEquals(
            testdirector.id,
            null,
            'Director Inserted Successfully'
        );
        //Insert Directorship
        Current_Directorship__c testdirectorship=GenericUtilityTestHelper.returnDirectorship(
            testParty1.id
        );
        System.AssertNotEquals(
            testdirectorship.id,
            null,
            'Directorship Inserted Successfully'
        );
        //Insert Credit Enquiry
        Credit_Enquiry__c testCreditEnquiry=GenericUtilityTestHelper.returnCreditEnquiry(
            testParty1.id
        );
        System.AssertNotEquals(
            testCreditEnquiry.id,
            null,
            'Credit Enquiry Inserted Successfully'
        );
	}
 @isTest
    static void partyTest(){
        List<clcommon__Party__c> testParty1=[SELECT id 
                                                FROM clcommon__Party__c 
                                                WHERE clcommon__Type__r.Name=:ConstantValues.BORROWER
                                                LIMIT 1];
        List<clcommon__Party__c> testParty2=[SELECT id 
                                                FROM clcommon__Party__c 
                                                WHERE clcommon__Type__r.Name='Co-Applicant'
                                                LIMIT 1];
        test.startTest();
        //UpdateCreditReport obj = new UpdateCreditReport(); 
        LinkPartyCreditReport.linkCreditReport(testParty1[0].id,testParty2[0].id); 
        test.stopTest();
        
    }  
}