elixir/force-app/main/default/objects/Account/fields/Last_Approved_Application_ID__c.field-meta.xml
<CustomField>
    <fullName>Last_Approved_Application_ID__c</fullName>
    <label>Last Approved Application ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

elixir/force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

elixir/force-app/main/default/objects/genesis__Applications__c/fields/Fixed_Rate_Term__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Rate_Term__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Fixed Rate Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Elixir_Prod/force-app/main/default/objects/genesis__Applications__c/fields/genesis__Days_Convention__c.field-meta.xml
<CustomField>
    <fullName>genesis__Days_Convention__c</fullName>
    <label>Days Convention</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>genesis__Product_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>30/360</fullName>
            </value>
            <value>
                <fullName>365/365</fullName>
                <default>true</default>
                <label>365/365</label>
            </value>
            <value>
                <fullName>ACTUAL/ACTUAL</fullName>
            </value>
            <value>
                <fullName>ACTUAL/360</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Interest_Only_Period__c.field-meta.xml
<CustomField>
    <fullName>genesis__Interest_Only_Period__c</fullName>
    <label>Interest Only Period</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

elixir/force-app/main/default/objects/genesis__Applications__c/fields/genesis__Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>genesis__Interest_Rate__c</fullName>
    <label>Interest Rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

elixir/force-app/main/default/objects/genesis__Applications__c/fields/genesis__Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>genesis__Loan_Amount__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

elixir/force-app/main/default/objects/genesis__Applications__c/fields/genesis__Payment_Frequency__c.field-meta.xml
<CustomField>
    <fullName>genesis__Payment_Frequency__c</fullName>
    <label>Payment Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>genesis__Product_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>MONTHLY</fullName>
                <default>true</default>
                <label>MONTHLY</label>
            </value>
            <value>
                <fullName>WEEKLY</fullName>
            </value>
            <value>
                <fullName>BI-WEEKLY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

elixir/force-app/main/default/objects/genesis__Applications__c/fields/genesis__Status__c.field-meta.xml
<CustomField>
    <fullName>genesis__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>App Received</fullName>
                <default>true</default>
                <label>App Received</label>
            </value>
            <value>
                <fullName>App Processed</fullName>
            </value>
            <value>
                <fullName>Indicative Accepted</fullName>
            </value>
            <value>
                <fullName>Val Ordered</fullName>
            </value>
            <value>
                <fullName>Val Received</fullName>
            </value>
            <value>
                <fullName>Recommended</fullName>
            </value>
            <value>
                <fullName>LOO Issued</fullName>
            </value>
            <value>
                <fullName>LOO Accepted</fullName>
            </value>
            <value>
                <fullName>Loan Settled</fullName>
            </value>
            <value>
                <fullName>APPROVED</fullName>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>APPROVED - CONVERTED TO CONTRACT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

elixir/force-app/main/default/objects/genesis__Applications__c/fields/genesis__Term__c.field-meta.xml
<CustomField>
    <fullName>genesis__Term__c</fullName>
    <label>Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/LMI_provider_list__c.field-meta.xml
<CustomField>
    <fullName>LMI_provider_list__c</fullName>
    <label>LMI provider list</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>QBE</fullName>
            </value>
            <value>
                <fullName>Genworth</fullName>
            </value>
            <value>
                <fullName>Self</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Elixir_Prod/force-app/main/default/objects/genesis__Applications__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Application</label>
    <referenceTo>peer__Loan_Application__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

Elixir_Prod/force-app/main/default/objects/genesis__Applications__c/fields/NCCP_status_list__c.field-meta.xml
<CustomField>
    <fullName>NCCP_status_list__c</fullName>
    <label>NCCP status list</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Regulated</fullName>
            </value>
            <value>
                <fullName>Unregulated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

elixir/force-app/main/default/objects/genesis__Applications__c/fields/Repayment_Type__c.field-meta.xml
<CustomField>
    <fullName>Repayment_Type__c</fullName>
    <label>Repayment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Principal and Interest</fullName>
            </value>
            <value>
                <fullName>Interest Only reverting to Principal and Interest</fullName>
            </value>
            <value>
                <fullName>Interest Only</fullName>
            </value>
            <value>
                <fullName>Prepaid Interest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

elixir/force-app/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <customHelpPage>loan__CLContractHelp</customHelpPage>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Elixir_Prod/force-app/main/default/objects/loan__Loan_Account__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>CL Contracts</relationshipLabel>
    <relationshipName>CL_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

elixir/force-app/main/default/objects/loan__Loan_Account__c/fields/Fixed_Rate_Term__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Rate_Term__c</fullName>
    <label>Fixed Rate Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

elixir/force-app/main/default/objects/loan__Loan_Account__c/fields/LMI_provider_list__c.field-meta.xml
<CustomField>
    <fullName>LMI_provider_list__c</fullName>
    <label>LMI provider list</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>QBE</fullName>
            </value>
            <value>
                <fullName>Genworth</fullName>
            </value>
            <value>
                <fullName>Self</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Loan_Status__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Status__c</fullName>
    <inlineHelpText>Status of the Account expected values are :
Pending Approval
Active - Good Standing
Active - Bad Standing
Active - Matured
Approved
Canceled
Closed - Obligations met
Closed- Written Off
Closed - Refinanced
Partial Application
Closed - Premature</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active - Bad Standing</fullName>
            </value>
            <value>
                <fullName>Active - Good Standing</fullName>
            </value>
            <value>
                <fullName>Active - Marked for Closure</fullName>
            </value>
            <value>
                <fullName>Active - Matured</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Closed - Obligations met</fullName>
            </value>
            <value>
                <fullName>Closed - Premature</fullName>
            </value>
            <value>
                <fullName>Closed - Refinanced</fullName>
            </value>
            <value>
                <fullName>Closed- Written Off</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>Partial Application</fullName>
                <default>true</default>
                <label>Partial Application</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Premature Closure Initiated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Application</label>
    <referenceTo>peer__Loan_Application__c</referenceTo>
    <relationshipLabel>CL Contracts</relationshipLabel>
    <relationshipName>CL_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

elixir/force-app/main/default/objects/loan__Loan_Account__c/fields/NCCP_status_list__c.field-meta.xml
<CustomField>
    <fullName>NCCP_status_list__c</fullName>
    <label>NCCP status list</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Regulated</fullName>
            </value>
            <value>
                <fullName>Unregulated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

elixir/force-app/main/default/objects/loan__Loan_Account__c/fields/Repayment_Type__c.field-meta.xml
<CustomField>
    <fullName>Repayment_Type__c</fullName>
    <label>Repayment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Principal and Interest</fullName>
            </value>
            <value>
                <fullName>Interest Only reverting to Principal and Interest</fullName>
            </value>
            <value>
                <fullName>Interest Only</fullName>
            </value>
            <value>
                <fullName>Prepaid Interest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

elixir/force-app/main/default/classes/LoanApplicationConvert.cls
/********************************************************************************
    * Description: Loan Application Convert Class to convert app to loan app and contract
    * Developer: Rameswari Barman
    * Creation Date : 8/08/2019
    * Implementation code : genesis__Applications__c app = [SELECT    id,
                                                Name,
                                                genesis__Balloon_Payment__c,
                                                genesis__Account__c,
                                                genesis__Interest_Rate__c,
                                                genesis__Term__c,
                                                genesis__Payment_Frequency__c,
                                                genesis__Expected_First_Payment_Date__c,
                                                genesis__Expected_Start_Date__c,
                                                genesis__CL_Purpose__r.loan__Lending_Purpose__c,
                                                genesis__CL_Product__r.loan__Lending_Product__c,
                                                genesis__CL_Product__c,
                                                genesis__CL_Product__r.clcommon__Product_Name__c,
                                                genesis__CL_Product__r.loan__Lending_Product__r.id,
                                                genesis__Status__c,
                                                Loan_Application__c,
                                                genesis__Loan_Amount__c,
                                                genesis__Days_Convention__c,
                                                genesis__Interest_Only_Period__c,
                                                Fixed_Rate_Term__c
                                                FROM genesis__Applications__c where id = 'XXXXXX'];
    String st=LoanApplicationConvert.convertLoanApplicationCtrl(app.Id);
********************************************************************************/


global class LoanApplicationConvert{
    private static List< peer__Loan_Application__c> loanApplicationList;
    private static Date currentSystemDate;
    public static String returnString;
    
    //Creates marketplace  loan application and cl contract in partial stage 
    //and attaches with the created loan app
    public static String convertLoanApplication(genesis__Applications__c genApp){
        currentSystemDate = (Test.isRunningTest()?Date.Today():(new loan.GlobalLoanUtilFacade()).getCurrentSystemDate());
        SavePoint sp = Database.setSavePoint();
        Date firstPaymentDate;
        loan__loan_account__c loanAcc = new loan__loan_account__c(); 
        peer__Loan_Application__c loanApplication;
        Account acc; 
        loanApplicationList = new List<peer__Loan_Application__c>();
        try{
            if(genApp != NULL){
                firstPaymentDate = genApp.genesis__Expected_First_Payment_Date__c;
                acc = [SELECT id,Last_Approved_Application_ID__c FROM Account WHERE id =: genApp.genesis__Account__c]; 
                acc.Last_Approved_Application_ID__c = genApp.Id;
                if(acc != null && Schema.sObjectType.Account.fields.Last_Approved_Application_ID__c.isUpdateable()){
                    update acc;
                }
                if(acc != null){
                    peer.LoanApplicationBuilder loanApplication1 = new peer.LoanApplicationBuilder(acc,
                                                                                                genApp.genesis__Loan_Amount__c,
                                                                                                genApp.genesis__Term__c,
                                                                                                genApp.genesis__Interest_Rate__c,
                                                                                                genApp.genesis__CL_Purpose__r.loan__Lending_Purpose__c);
                                                                                                
                    //Set Disbursal Date
                    loanApplication1.setExpectedDisbursalDate(currentSystemDate);
                    
                    //set first payment date
                    loanApplication1.setFirstInstallmentDate(firstPaymentDate); 
                    
                    loanApplication1.setPaymentFrequency(genApp.genesis__Payment_Frequency__c);
                    
                    //Set lending product using cl product
                    loanApplication1.setLoanProductId(genApp.genesis__CL_Product__r.loan__Lending_Product__c);
                    
                    //Generate Schedule
                    loanApplication1.setCreateSchedule(False);
                    
                    //Set Interest only period if applicable
                    if(genApp.genesis__Interest_Only_Period__c != null){
                        loanApplication1.setInterestOnlyPeriod(genApp.genesis__Interest_Only_Period__c);
                    }
                    //Set ballon payment if applicable
                    if(genApp.genesis__Balloon_Payment__c != null){
                        loanApplication1.setBalloonAmount(genApp.genesis__Balloon_Payment__c);
                    }
                    loanApplication = loanApplication1.build();
                    //Set Loan Application 
                    if(loanApplication != NULL){  
                        //Displays created loan appliaction id on genesis application  
                        genApp.Loan_Application__c = loanApplication.Id;
                        genApp.genesis__Status__c = System.label.ApplicationStatusAfterCLContractConverted;
                        
                        //loanApplication.Application__c = genApp.Id;   
                        loanApplication.peer__Stage__c = System.label.InFunding;   
                        
                        //Added for updation
                        //loanApplicationList.add(loanApplication);
                        
                        //query loan Account
                        loanAcc = [SELECT ID,
                                    loan__Loan_Status__c,
                                    Loan_Application__c,
                                    Fixed_Rate_Term__c,
                                    Application__c
                                    FROM loan__loan_account__c
                                WHERE ID =: loanApplication.peer__Loan__c];
                        //Map data from Application to CL contract
                        loanAcc.Loan_Application__c = loanApplication.Id;
                        loanAcc.loan__Loan_Status__c = ConstantValues.APPROVED;
                        loanAcc.Application__c=genApp.Id;
                        loanAcc.Fixed_Rate_Term__c  = genApp.Fixed_Rate_Term__c;
                        //===========
                        loanAcc.Repayment_Type__c = genApp.Repayment_Type__c;
                        loanAcc.LMI_provider_list__c = genApp.LMI_provider_list__c;
                        loanAcc.NCCP_status_list__c = genApp.NCCP_status_list__c;
                        
                        //==========
                    }
                }
                else{
                    returnString = System.label.AccountNotFound;
                }
                if(loanApplication != null){
                    update loanApplication;
                    if(genApp != null){//updates the status and loan application field of application record
                        update genApp;
                    }
                    if(loanAcc != null){
                        update loanAcc;
                    }
                    returnString = System.label.ApplicationToCLContractSuccessStatus;
                }
            }
            else{
                returnString = System.label.ApplicantNotFoundErrorMsg;
            }
        }
        catch(Exception e){
            Database.rollback(sp);
            insert new clcommon__Batch_Process_Log__c(clcommon__Message__c = 'LoanApplicationConvert :'+e.getStackTraceString()+':Error::'+e.getMessage()+' at Line Number '+e.getLineNumber(), clcommon__Timestamp__c = 
                                                  System.Now(),clcommon__Log_Level__c = 'ERROR'); 
            returnString = e.getMessage();  
        }
    return returnString;
    }
    webservice static String convertLoanApplicationCtrl(Id appId) {
        genesis__Applications__c  genApp =[SELECT id,
                                        Name,
                                        genesis__Balloon_Payment__c,
                                        genesis__Account__c,
                                        genesis__Interest_Rate__c,
                                        genesis__Term__c,
                                        genesis__Payment_Frequency__c,
                                        genesis__Expected_First_Payment_Date__c,
                                        genesis__Expected_Start_Date__c,
                                        genesis__CL_Purpose__r.loan__Lending_Purpose__c,
                                        genesis__CL_Product__r.loan__Lending_Product__c,
                                        genesis__CL_Product__c,
                                        genesis__CL_Product__r.clcommon__Product_Name__c,
                                        genesis__CL_Product__r.loan__Lending_Product__r.id,
                                        genesis__Status__c,
                                        Loan_Application__c,
                                        genesis__Loan_Amount__c,
                                        genesis__Days_Convention__c,
                                        genesis__Interest_Only_Period__c,
                                        Fixed_Rate_Term__c,
                                        Repayment_Type__c,
                                        LMI_provider_list__c,
                                        NCCP_status_list__c
                                FROM genesis__Applications__c where id = :appId];                                
        if(genApp.genesis__Term__c==null){
            return ConstantValues.TERM_VALIDATION_MSG;
        }
        if(genApp.Loan_Application__c!=null){
            return ConstantValues.APP_ALREADY_CONVERTED_MSG;
        }
        if(genApp.genesis__Interest_Rate__c == null || genApp.genesis__Interest_Rate__c <0){
            return ConstantValues.INTEREST_RATE_VALIDATION_MSG;
        }
        if(genApp.genesis__Payment_Frequency__c==null){
            return ConstantValues.PAYMENT_FREQUENCY_VALIDATION_MSG;
        }
        if(genApp.genesis__Loan_Amount__c==null || genApp.genesis__Loan_Amount__c==0){
            return ConstantValues.LOAN_AMT_VALIDATION_MSG;
        }
        String result = convertLoanApplication(genApp); 
        return result;
    }
}