elixir/force-app/main/default/objects/Account/fields/Last_Approved_Application_ID__c.field-meta.xml
<CustomField>
    <fullName>Last_Approved_Application_ID__c</fullName>
    <label>Last Approved Application ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

elixir/force-app/main/default/objects/Elixir_Before_Or_On_Settlement_Fees__c/Elixir_Before_Or_On_Settlement_Fees__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Elixir Before Or On Settlement Fees</label>
</CustomObject>

elixir/force-app/main/default/objects/Elixir_Before_Or_On_Settlement_Fees__c/fields/Fee_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Fee_Field_API_Name__c</fullName>
    <label>Fee Field API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

elixir/force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Elixir_Prod/force-app/main/default/objects/genesis__Applications__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Application</label>
    <referenceTo>peer__Loan_Application__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

elixir/force-app/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <customHelpPage>loan__CLContractHelp</customHelpPage>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Elixir_Prod/force-app/main/default/objects/loan__Loan_Account__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>CL Contracts</relationshipLabel>
    <relationshipName>CL_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Please choose a account, which will be associated as a customer on this lending account.
You can create a new account, from the lookup window by clicking on new or select the existing account from the lookup.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Loan_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

elixir/force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Frequency_of_Loan_Payment__c.field-meta.xml
<CustomField>
    <fullName>loan__Frequency_of_Loan_Payment__c</fullName>
    <inlineHelpText>This decides the Payment Frequency, below are the supported ones:
Daily
Weekly
Bi-weekly
Semi-Monthly
Monthly
Bi-Monthly
Quarterly
Semi-Annual
Annual
Single-Payment</inlineHelpText>
    <label>Payment Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Bi-weekly</fullName>
            </value>
            <value>
                <fullName>Semi-Monthly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
                <default>true</default>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Semi-Annual</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Single-Payment</fullName>
            </value>
            <value>
                <fullName>Semi-Monthly-PD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Application</label>
    <referenceTo>peer__Loan_Application__c</referenceTo>
    <relationshipLabel>CL Contracts</relationshipLabel>
    <relationshipName>CL_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

elixir/force-app/main/default/classes/PrepaidFeeCalculatorClass.cls
/********************************************************************************
Name : PrepaidFeeCalculatorClass
Purpose : Custom Fee calculator class which returns the pre-paid fees amount.
            and also the value of the periodic fee
Developer : Rameswari Barman
*********************************************************************************/
public without sharing class PrepaidFeeCalculatorClass implements loan.CustomFeeCalculator{
    public Decimal computeFee(loan__Fee__c fee, loan__Loan_Account__c loan){
        try{
            //Decimal amt = 0;
            loan__Loan_Account__c lacc = [Select id,
                                                 loan__Account__c,
                                                 loan__Frequency_of_Loan_Payment__c,
                                                 Application__c,
                                                 Loan_Application__c,
                                                 loan__Account__r.last_Approved_Application_ID__c
                                          From loan__Loan_Account__c 
                                          Where id =: loan.id];
            //---------------------------------------------------------------------------------
            if(lacc != null && lacc.loan__Account__r.last_Approved_Application_ID__c != null){
                lacc.Application__c = lacc.loan__Account__r.last_Approved_Application_ID__c;
                update lacc;
            }
            
            //--------------------------------------------------------------------------------                              
            //       code to dynamically get all the fields                               
            //--------------------------------------------------------------------------------
            Schema.DescribeSObjectResult r = genesis__Applications__c.sObjectType.getDescribe();
            List<String>apiNames =  new list<String>();
            for(string apiName : r.fields.getMap().keySet()){
               apiNames.add(apiName);
            }
            
            //---------------------------------------------------------------------------------
            //   Creating Query using the Fields
            //---------------------------------------------------------------------------------
            String query='Select '+String.join(apiNames,',')+' From genesis__Applications__c Where id=\''+lacc.Application__c+'\'';
            genesis__Applications__c genApp=Database.query(query);
            
            //---------------------------------------------------------------------------------
            //    Custom settings list to get all fees and its fields mapping from APP fields
            //---------------------------------------------------------------------------------
            map<String,Elixir_Before_Or_On_Settlement_Fees__c> feeSetFieldMap= Elixir_Before_Or_On_Settlement_Fees__c.getAll();
            
            //---------------------------------------------------------------------------------
            //        Get Field API name from custom settings and its current value 
            //---------------------------------------------------------------------------------
            if(feeSetFieldMap.get(fee.Name)!=null && feeSetFieldMap.get(fee.Name).Fee_Field_API_Name__c!=null){
                if(genApp.get(feeSetFieldMap.get(fee.Name).Fee_Field_API_Name__c)!=null && genApp.get(feeSetFieldMap.get(fee.Name).Fee_Field_API_Name__c)!=0){
                    return (Decimal)genApp.get(feeSetFieldMap.get(fee.Name).Fee_Field_API_Name__c);
                }else {
                    return 0;
                }
            }else {
                return 0;
            }
        }catch(Exception e){
            return 0;//throw e;
        }
    }
}