elixir/force-app/main/default/objects/Account/fields/loan__Active__c.field-meta.xml
<CustomField>
    <fullName>loan__Active__c</fullName>
    <label>Active</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Disable_Custom_Triggers__c/Disable_Custom_Triggers__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Disable Custom Triggers</label>
</CustomObject>

Elixir_Prod/force-app/main/default/objects/Disable_Custom_Triggers__c/fields/LoanWarehouseTrigger__c.field-meta.xml
<CustomField>
    <fullName>LoanWarehouseTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LoanWarehouseTrigger</label>
    <type>Checkbox</type>
</CustomField>

elixir/force-app/main/default/objects/Elixir_Before_Or_On_Settlement_Fees__c/Elixir_Before_Or_On_Settlement_Fees__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Elixir Before Or On Settlement Fees</label>
</CustomObject>

elixir/force-app/main/default/objects/Elixir_Before_Or_On_Settlement_Fees__c/fields/Fee_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Fee_Field_API_Name__c</fullName>
    <label>Fee Field API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

elixir/force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

elixir/force-app/main/default/objects/genesis__Applications__c/fields/Application_Fee__c.field-meta.xml
<CustomField>
    <fullName>Application_Fee__c</fullName>
    <label>Application Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

elixir/force-app/main/default/objects/genesis__Applications__c/fields/Drawdown_Prepaid_Interest__c.field-meta.xml
<CustomField>
    <fullName>Drawdown_Prepaid_Interest__c</fullName>
    <label>Drawdown Prepaid Interest</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Interest_Only_Period__c.field-meta.xml
<CustomField>
    <fullName>genesis__Interest_Only_Period__c</fullName>
    <label>Interest Only Period</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

elixir/force-app/main/default/objects/genesis__Applications__c/fields/genesis__Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>genesis__Interest_Rate__c</fullName>
    <label>Interest Rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

elixir/force-app/main/default/objects/genesis__Applications__c/fields/genesis__Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>genesis__Loan_Amount__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

elixir/force-app/main/default/objects/genesis__Applications__c/fields/genesis__Payment_Frequency__c.field-meta.xml
<CustomField>
    <fullName>genesis__Payment_Frequency__c</fullName>
    <label>Payment Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>genesis__Product_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>MONTHLY</fullName>
                <default>true</default>
                <label>MONTHLY</label>
            </value>
            <value>
                <fullName>WEEKLY</fullName>
            </value>
            <value>
                <fullName>BI-WEEKLY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Product_Type__c.field-meta.xml
<CustomField>
    <fullName>genesis__Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>LEASE</fullName>
            </value>
            <value>
                <fullName>LOAN</fullName>
                <default>true</default>
                <label>LOAN</label>
            </value>
            <value>
                <fullName>LINE OF CREDIT</fullName>
            </value>
            <value>
                <fullName>PACKAGE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

elixir/force-app/main/default/objects/genesis__Applications__c/fields/genesis__Term__c.field-meta.xml
<CustomField>
    <fullName>genesis__Term__c</fullName>
    <label>Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

elixir/force-app/main/default/objects/loan__Bank_Account__c/loan__Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <displayFormat>BA-{00000}</displayFormat>
        <label>Bank Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

elixir/force-app/main/default/objects/loan__Bank_Account__c/fields/loan__Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Bank_Account__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

elixir/force-app/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <customHelpPage>loan__CLContractHelp</customHelpPage>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Elixir_Prod/force-app/main/default/objects/loan__Loan_Account__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>CL Contracts</relationshipLabel>
    <relationshipName>CL_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

elixir/force-app/main/default/objects/loan__Loan_Account__c/fields/APS_Created__c.field-meta.xml
<CustomField>
    <fullName>APS_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <label>APS Created</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Please choose a account, which will be associated as a customer on this lending account.
You can create a new account, from the lookup window by clicking on new or select the existing account from the lookup.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Loan_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

elixir/force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Frequency_of_Loan_Payment__c.field-meta.xml
<CustomField>
    <fullName>loan__Frequency_of_Loan_Payment__c</fullName>
    <inlineHelpText>This decides the Payment Frequency, below are the supported ones:
Daily
Weekly
Bi-weekly
Semi-Monthly
Monthly
Bi-Monthly
Quarterly
Semi-Annual
Annual
Single-Payment</inlineHelpText>
    <label>Payment Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Bi-weekly</fullName>
            </value>
            <value>
                <fullName>Semi-Monthly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
                <default>true</default>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Semi-Annual</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Single-Payment</fullName>
            </value>
            <value>
                <fullName>Semi-Monthly-PD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

elixir/force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>loan__Interest_Rate__c</fullName>
    <description>Interest Rate</description>
    <inlineHelpText>Rate of Interest for the loan.</inlineHelpText>
    <label>Current Interest Rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Loan Amount</description>
    <inlineHelpText>This is the financed amount on the contract which will be disbursed to the customer.</inlineHelpText>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Loan_Status__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Status__c</fullName>
    <inlineHelpText>Status of the Account expected values are :
Pending Approval
Active - Good Standing
Active - Bad Standing
Active - Matured
Approved
Canceled
Closed - Obligations met
Closed- Written Off
Closed - Refinanced
Partial Application
Closed - Premature</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active - Bad Standing</fullName>
            </value>
            <value>
                <fullName>Active - Good Standing</fullName>
            </value>
            <value>
                <fullName>Active - Marked for Closure</fullName>
            </value>
            <value>
                <fullName>Active - Matured</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Closed - Obligations met</fullName>
            </value>
            <value>
                <fullName>Closed - Premature</fullName>
            </value>
            <value>
                <fullName>Closed - Refinanced</fullName>
            </value>
            <value>
                <fullName>Closed- Written Off</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>Partial Application</fullName>
                <default>true</default>
                <label>Partial Application</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Premature Closure Initiated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Number_of_Installments__c.field-meta.xml
<CustomField>
    <fullName>loan__Number_of_Installments__c</fullName>
    <description>Contractual Term Of the Loan Account</description>
    <inlineHelpText>Contractual term of the contract.</inlineHelpText>
    <label>Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

elixir/force-app/main/default/objects/loan__Loan_Account__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>CL Contracts</relationshipLabel>
    <relationshipName>CL_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

elixir/force-app/main/default/objects/Loan_Warehouse__c/Loan_Warehouse__c.object-meta.xml
<CustomObject>
    <label>Loan Warehouse</label>
    <nameField>
        <label>Loan Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Warehouse</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

elixir/force-app/main/default/objects/Loan_Warehouse__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Loan Warehouse</relationshipLabel>
    <relationshipName>Loan_Warehouse</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

elixir/force-app/main/default/objects/Loan_Warehouse__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Loan Warehouse</relationshipLabel>
    <relationshipName>Loan_Warehouse</relationshipName>
    <type>Lookup</type>
</CustomField>

elixir/force-app/main/default/classes/DepositTriggerTest.cls
/************************************************************************
Class Name : DepositTriggerTest
Developer : Deep Bhattacharjee
Description : Test class For DepositTrigger and DepositUpdateHelper
************************************************************************/

@isTest
public with sharing class DepositTriggerTest {
    static testMethod void test(){
        Elixir_Before_Or_On_Settlement_Fees__c fee = new Elixir_Before_Or_On_Settlement_Fees__c();
        fee.name = 'Application Fee';
        fee.Distribution_Type__c = 'Pre-Paid Fee';
        fee.Fee_Field_API_Name__c = 'Application_Fee__c';
        insert fee;
        System.assertEquals(fee.name,'Application Fee');
        
        //Inserting Legal Entity
        clcommon__Legal_Entity__c legEntity = ElixirTestHelper.returnLegalEntity();
        insert legEntity;
        System.assertEquals(legEntity.Name,'Individual');
        
        //Inserting Account
        Account acc = ElixirTestHelper.returnBorrowerAccount(legEntity.Id);
        insert acc;
        System.assertEquals(acc.name,'Rameswari Barman');
        
        //Inserting Application
        genesis__applications__c app = ElixirTestHelper.returnApplication(acc.Id);
        app.genesis__Payment_Frequency__c = 'Monthly';
        app.Drawdown_Prepaid_Interest__c = 1000;
        insert app;
        System.assertEquals(app.genesis__account__c,acc.Id);
        
        //Inserting Warehouse
        Warehouse__c ware = ElixirTestHelper.returnWarehouse();
        insert ware;
        System.assertEquals(ware.name,'Warehouse 1');
        
        
        Loan_Warehouse__c loanWarehouse1 = ElixirTestHelper.returnLoanWarehouse(ware.Id,app.Id);
        loanWarehouse1.Active__c = true;
        insert loanWarehouse1;
        System.assertEquals(loanWarehouse1.Warehouse__c,ware.Id);
        
        //Inserting LoanWarehouse
        Loan_Warehouse__c loanWarehouse = ElixirTestHelper.returnLoanWarehouse(ware.Id,app.Id);
        insert loanWarehouse;
        System.assertEquals(loanWarehouse.Warehouse__c,ware.Id);
        
        //Inserting Custom Setting
        Disable_Custom_Triggers__c dis = Disable_Custom_Triggers__c.getOrgDefaults();
        dis.LoanWarehouseTrigger__c = false;
        insert dis;
        System.assertEquals(dis.LoanWarehouseTrigger__c,false);
        
        //Inserting Conversion Mapping
        genesis__Conversion_Mapping_Header__c conHead = new genesis__Conversion_Mapping_Header__c();
        conHead.genesis__Product_Type__c = 'LOAN';
        insert conHead;
        System.assertEquals(conHead.genesis__Product_Type__c,'LOAN');
        
        genesis__Conversion_Mapping__c conMap1 = ElixirTestHelper.returnConversionMapping(conHead.Id,'genesis__Applications__c','genesis__Loan_Amount__c','loan__Loan_Account__c','loan__Loan_Amount__c');
        genesis__Conversion_Mapping__c conMap2 = ElixirTestHelper.returnConversionMapping(conHead.Id,'genesis__Applications__c','genesis__Interest_Only_Period__c','loan__Loan_Account__c','loan__Interest_Only_Period__c');
        genesis__Conversion_Mapping__c conMap3 = ElixirTestHelper.returnConversionMapping(conHead.Id,'genesis__Applications__c','genesis__Payment_Frequency__c','loan__Loan_Account__c','loan__Frequency_of_Loan_Payment__c');
        genesis__Conversion_Mapping__c conMap4 = ElixirTestHelper.returnConversionMapping(conHead.Id,'genesis__Applications__c','genesis__Interest_Rate__c','loan__Loan_Account__c','loan__Interest_Rate__c');
        genesis__Conversion_Mapping__c conMap5 = ElixirTestHelper.returnConversionMapping(conHead.Id,'genesis__Applications__c','genesis__Term__c','loan__Loan_Account__c','loan__Number_of_Installments__c');
        List<genesis__Conversion_Mapping__c> conMapList = new List<genesis__Conversion_Mapping__c>();
        conMapList.add(conMap1);
        conMapList.add(conMap2);
        conMapList.add(conMap3);
        conMapList.add(conMap4);
        insert conMapList;
        //System.assertEquals(conMap1.size(),4);
        
        loan__Loan_Account__c loanC = ElixirTestHelper.returnLoanAccount();
        loanC.loan__Account__c = acc.Id;
        loanC.loan__Loan_Amount__c = 1000;
        loanC.loan__Frequency_of_Loan_Payment__c = ConstantValues.MONTHLY;
        loanC.Loan__Loan_Status__c = loan.LoanConstants.LOAN_STATUSACTIVE_BAD_STANDING;
        loanC.Application__c = app.id;
        loanC.APS_Created__c = false;
        loanC.loan__Account__c = acc.Id;
        loanC.loan__Last_Installment_Date__c = Date.today();
        loanC.loan__Next_Installment_Date__c = Date.today();
        loanC.loan__Principal_Remaining__c = 100;
        update loanC;
        System.assertEquals(loanC.loan__Next_Installment_Date__c,Date.today());

        loan__Payment_Mode__c pmt = new loan__Payment_Mode__c();
        pmt.name = 'ACH';
        insert pmt;
        System.assertEquals(pmt.name,'ACH');

        loan__Bank_Account__c bank = new loan__Bank_Account__c();
        bank.loan__Account__c = acc.Id;
        bank.loan__Active__c = True;
        bank.loan__Bank_Account_Number__c = '123456';
        bank.loan__Bank_Name__c = 'ABCD';
        insert bank;
        System.assertEquals(bank.loan__Active__c,True);

        loanC.loan__Loan_Status__c = 'Approved';
        update loanC;
        loan__Fee__c feeAmt = new loan__Fee__c(name = 'Application Fee', loan__Amount__c = 400,loan__Time_of_charge__c='Pre-Paid Fees');
        insert feeAmt;
        System.assertEquals(feeAmt.name,'Application Fee');
        
        loan__Fee__c feeAmtNext = new loan__Fee__c(name = 'Drawdown Prepaid Interest', loan__Amount__c = 400,loan__Time_of_charge__c='Other');
        insert feeAmtNext;
        System.assertEquals(feeAmtNext.name,'Drawdown Prepaid Interest');
        
        loan__Contract_Pre_Paid_Fee__c conFee = new loan__Contract_Pre_Paid_Fee__c(loan__Amount__c = 400,loan__Contract__c = loanC.Id,loan__Fee_Type__c = feeAmt.Id);
        insert conFee;
        System.assertEquals(conFee.loan__Amount__c,400);

        clcommon__Deposit__c dep = new clcommon__Deposit__c();
        dep.loan__Loan_Account__c = loanC.id;
        dep.clcommon__Current_Deposit_Rate__c =10;
        dep.clcommon__Deposit_Amount__c = 4000;
        dep.clcommon__Deposit_Rate__c = 10;
        insert dep;
        System.assertEquals(dep.clcommon__Current_Deposit_Rate__c,10);

        test.startTest();
        ConvertToContract.executeFun(app.Id);
        app.CL_Contract__c = loanC.Id;
        update app;
        WarehouseFunding.executeFun(loanC.Id,ware.Id);
        //clcommon__Deposit__c dep = [SELECT id,name,clcommon__Current_Deposit_Amount__c,loan__Loan_Account__c FROM clcommon__Deposit__c WHERE loan__Loan_Account__c = :loanC.Id LIMIT 1];
        dep.clcommon__Current_Deposit_Amount__c =2000;
        update dep;
        DepositWithdrawal.withdrawAmt(loanC.Id);
        PageReference pageRef = Page.loan__tabbedLoanAccount;
        pageRef.getParameters().put('LoanId', loanC.id);
        Test.setCurrentPage(pageRef);
        RedrawController controller = new RedrawController();
        controller.acct = loanC;
        controller.redrawAmount = '200'; 
        controller.message = 'Sample Message';
        controller.doRedraw();
        test.stopTest();
    }
    static testMethod void test1(){
        Elixir_Before_Or_On_Settlement_Fees__c fee = new Elixir_Before_Or_On_Settlement_Fees__c();
        fee.name = 'Application Fee';
        fee.Distribution_Type__c = 'Pre-Paid Fee';
        fee.Fee_Field_API_Name__c = 'Application_Fee__c';
        insert fee;
        System.assertEquals(fee.name,'Application Fee');
        
        //Inserting Legal Entity
        clcommon__Legal_Entity__c legEntity = ElixirTestHelper.returnLegalEntity();
        insert legEntity;
        System.assertEquals(legEntity.Name,'Individual');
        
        //Inserting Account
        Account acc = ElixirTestHelper.returnBorrowerAccount(legEntity.Id);
        insert acc;
        System.assertEquals(acc.name,'Rameswari Barman');
        
        //Inserting Application
        genesis__applications__c app = ElixirTestHelper.returnApplication(acc.Id);
        app.genesis__Payment_Frequency__c = 'Monthly';
        app.Drawdown_Prepaid_Interest__c = 1000;
        insert app;
        System.assertEquals(app.genesis__account__c,acc.Id);
        
        //Inserting Warehouse
        Warehouse__c ware = ElixirTestHelper.returnWarehouse();
        insert ware;
        System.assertEquals(ware.name,'Warehouse 1');
        
        
        Loan_Warehouse__c loanWarehouse1 = ElixirTestHelper.returnLoanWarehouse(ware.Id,app.Id);
        loanWarehouse1.Active__c = true;
        insert loanWarehouse1;
        System.assertEquals(loanWarehouse1.Warehouse__c,ware.Id);
        
        //Inserting LoanWarehouse
        Loan_Warehouse__c loanWarehouse = ElixirTestHelper.returnLoanWarehouse(ware.Id,app.Id);
        insert loanWarehouse;
        System.assertEquals(loanWarehouse.Warehouse__c,ware.Id);
        
        //Inserting Custom Setting
        Disable_Custom_Triggers__c dis = Disable_Custom_Triggers__c.getOrgDefaults();
        dis.LoanWarehouseTrigger__c = false;
        insert dis;
        System.assertEquals(dis.LoanWarehouseTrigger__c,false);
        
        //Inserting Conversion Mapping
        genesis__Conversion_Mapping_Header__c conHead = new genesis__Conversion_Mapping_Header__c();
        conHead.genesis__Product_Type__c = 'LOAN';
        insert conHead;
        System.assertEquals(conHead.genesis__Product_Type__c,'LOAN');
        
        genesis__Conversion_Mapping__c conMap1 = ElixirTestHelper.returnConversionMapping(conHead.Id,'genesis__Applications__c','genesis__Loan_Amount__c','loan__Loan_Account__c','loan__Loan_Amount__c');
        genesis__Conversion_Mapping__c conMap2 = ElixirTestHelper.returnConversionMapping(conHead.Id,'genesis__Applications__c','genesis__Interest_Only_Period__c','loan__Loan_Account__c','loan__Interest_Only_Period__c');
        genesis__Conversion_Mapping__c conMap3 = ElixirTestHelper.returnConversionMapping(conHead.Id,'genesis__Applications__c','genesis__Payment_Frequency__c','loan__Loan_Account__c','loan__Frequency_of_Loan_Payment__c');
        genesis__Conversion_Mapping__c conMap4 = ElixirTestHelper.returnConversionMapping(conHead.Id,'genesis__Applications__c','genesis__Interest_Rate__c','loan__Loan_Account__c','loan__Interest_Rate__c');
        genesis__Conversion_Mapping__c conMap5 = ElixirTestHelper.returnConversionMapping(conHead.Id,'genesis__Applications__c','genesis__Term__c','loan__Loan_Account__c','loan__Number_of_Installments__c');
        List<genesis__Conversion_Mapping__c> conMapList = new List<genesis__Conversion_Mapping__c>();
        conMapList.add(conMap1);
        conMapList.add(conMap2);
        conMapList.add(conMap3);
        conMapList.add(conMap4);
        insert conMapList;
        //System.assertEquals(conMap1.size(),4);
        
        loan__Loan_Account__c loanC = ElixirTestHelper.returnLoanAccount();
        loanC.loan__Account__c = acc.Id;
        loanC.loan__Loan_Amount__c = 1000;
        loanC.loan__Frequency_of_Loan_Payment__c = ConstantValues.MONTHLY;
        loanC.Loan__Loan_Status__c = loan.LoanConstants.LOAN_STATUSACTIVE_BAD_STANDING;
        loanC.Application__c = app.id;
        loanC.APS_Created__c = false;
        loanC.loan__Account__c = acc.Id;
        loanC.loan__Last_Installment_Date__c = Date.today();
        loanC.loan__Next_Installment_Date__c = Date.today();
        loanC.loan__Principal_Remaining__c = 100;
        update loanC;
        System.assertEquals(loanC.loan__Next_Installment_Date__c,Date.today());

        loan__Payment_Mode__c pmt = new loan__Payment_Mode__c();
        pmt.name = 'ACH';
        insert pmt;
        System.assertEquals(pmt.name,'ACH');

        loan__Bank_Account__c bank = new loan__Bank_Account__c();
        bank.loan__Account__c = acc.Id;
        bank.loan__Active__c = True;
        bank.loan__Bank_Account_Number__c = '123456';
        bank.loan__Bank_Name__c = 'ABCD';
        insert bank;
        System.assertEquals(bank.loan__Active__c,True);

        loanC.loan__Loan_Status__c = 'Approved';
        update loanC;
        loan__Fee__c feeAmt = new loan__Fee__c(name = 'Application Fee', loan__Amount__c = 400,loan__Time_of_charge__c='Pre-Paid Fees');
        insert feeAmt;
        System.assertEquals(feeAmt.name,'Application Fee');
        
        loan__Fee__c feeAmtNext = new loan__Fee__c(name = 'Drawdown Prepaid Interest', loan__Amount__c = 400,loan__Time_of_charge__c='Other');
        insert feeAmtNext;
        System.assertEquals(feeAmtNext.name,'Drawdown Prepaid Interest');
        
        loan__Contract_Pre_Paid_Fee__c conFee = new loan__Contract_Pre_Paid_Fee__c(loan__Amount__c = 400,loan__Contract__c = loanC.Id,loan__Fee_Type__c = feeAmt.Id);
        insert conFee;
        System.assertEquals(conFee.loan__Amount__c,400);

        clcommon__Deposit__c dep = new clcommon__Deposit__c();
        dep.loan__Loan_Account__c = loanC.id;
        dep.clcommon__Current_Deposit_Rate__c =10;
        dep.clcommon__Deposit_Amount__c = 4000;
        dep.clcommon__Deposit_Rate__c = 10;
        insert dep;
        System.assertEquals(dep.clcommon__Current_Deposit_Rate__c,10);

        test.startTest();
        ConvertToContract.executeFun(app.Id);
        app.CL_Contract__c = loanC.Id;
        update app;
        WarehouseFunding.executeFun(loanC.Id,ware.Id);
        //clcommon__Deposit__c dep = [SELECT id,name,clcommon__Current_Deposit_Amount__c,loan__Loan_Account__c FROM clcommon__Deposit__c WHERE loan__Loan_Account__c = :loanC.Id LIMIT 1];
        dep.clcommon__Current_Deposit_Amount__c =2000;
        update dep;
        DepositWithdrawal.withdrawAmt(loanC.Id);
        PageReference pageRef = Page.loan__tabbedLoanAccount;
        pageRef.getParameters().put('LoanId', loanC.id);
        Test.setCurrentPage(pageRef);
        RedrawController controller = new RedrawController();
        controller.acct = loanC;
        controller.redrawAmount = '-200'; 
        controller.message = 'Sample Message';
        controller.doRedraw();
        controller.cancel();
        test.stopTest();
    }
    static testMethod void test2(){
        Elixir_Before_Or_On_Settlement_Fees__c fee = new Elixir_Before_Or_On_Settlement_Fees__c();
        fee.name = 'Application Fee';
        fee.Distribution_Type__c = 'Pre-Paid Fee';
        fee.Fee_Field_API_Name__c = 'Application_Fee__c';
        insert fee;
        System.assertEquals(fee.name,'Application Fee');
        
        //Inserting Legal Entity
        clcommon__Legal_Entity__c legEntity = ElixirTestHelper.returnLegalEntity();
        insert legEntity;
        System.assertEquals(legEntity.Name,'Individual');
        
        //Inserting Account
        Account acc = ElixirTestHelper.returnBorrowerAccount(legEntity.Id);
        insert acc;
        System.assertEquals(acc.name,'Rameswari Barman');
        
        //Inserting Application
        genesis__applications__c app = ElixirTestHelper.returnApplication(acc.Id);
        app.genesis__Payment_Frequency__c = 'Monthly';
        app.Drawdown_Prepaid_Interest__c = 1000;
        insert app;
        System.assertEquals(app.genesis__account__c,acc.Id);
        
        //Inserting Warehouse
        Warehouse__c ware = ElixirTestHelper.returnWarehouse();
        insert ware;
        System.assertEquals(ware.name,'Warehouse 1');
        
        
        Loan_Warehouse__c loanWarehouse1 = ElixirTestHelper.returnLoanWarehouse(ware.Id,app.Id);
        loanWarehouse1.Active__c = true;
        insert loanWarehouse1;
        System.assertEquals(loanWarehouse1.Warehouse__c,ware.Id);
        
        //Inserting LoanWarehouse
        Loan_Warehouse__c loanWarehouse = ElixirTestHelper.returnLoanWarehouse(ware.Id,app.Id);
        insert loanWarehouse;
        System.assertEquals(loanWarehouse.Warehouse__c,ware.Id);
        
        //Inserting Custom Setting
        Disable_Custom_Triggers__c dis = Disable_Custom_Triggers__c.getOrgDefaults();
        dis.LoanWarehouseTrigger__c = false;
        insert dis;
        System.assertEquals(dis.LoanWarehouseTrigger__c,false);
        
        //Inserting Conversion Mapping
        genesis__Conversion_Mapping_Header__c conHead = new genesis__Conversion_Mapping_Header__c();
        conHead.genesis__Product_Type__c = 'LOAN';
        insert conHead;
        System.assertEquals(conHead.genesis__Product_Type__c,'LOAN');
        
        genesis__Conversion_Mapping__c conMap1 = ElixirTestHelper.returnConversionMapping(conHead.Id,'genesis__Applications__c','genesis__Loan_Amount__c','loan__Loan_Account__c','loan__Loan_Amount__c');
        genesis__Conversion_Mapping__c conMap2 = ElixirTestHelper.returnConversionMapping(conHead.Id,'genesis__Applications__c','genesis__Interest_Only_Period__c','loan__Loan_Account__c','loan__Interest_Only_Period__c');
        genesis__Conversion_Mapping__c conMap3 = ElixirTestHelper.returnConversionMapping(conHead.Id,'genesis__Applications__c','genesis__Payment_Frequency__c','loan__Loan_Account__c','loan__Frequency_of_Loan_Payment__c');
        genesis__Conversion_Mapping__c conMap4 = ElixirTestHelper.returnConversionMapping(conHead.Id,'genesis__Applications__c','genesis__Interest_Rate__c','loan__Loan_Account__c','loan__Interest_Rate__c');
        genesis__Conversion_Mapping__c conMap5 = ElixirTestHelper.returnConversionMapping(conHead.Id,'genesis__Applications__c','genesis__Term__c','loan__Loan_Account__c','loan__Number_of_Installments__c');
        List<genesis__Conversion_Mapping__c> conMapList = new List<genesis__Conversion_Mapping__c>();
        conMapList.add(conMap1);
        conMapList.add(conMap2);
        conMapList.add(conMap3);
        conMapList.add(conMap4);
        insert conMapList;
        //System.assertEquals(conMap1.size(),4);
        
        loan__Loan_Account__c loanC = ElixirTestHelper.returnLoanAccount();
        loanC.loan__Account__c = acc.Id;
        loanC.loan__Loan_Amount__c = 1000;
        loanC.loan__Frequency_of_Loan_Payment__c = ConstantValues.MONTHLY;
        loanC.Loan__Loan_Status__c = loan.LoanConstants.LOAN_STATUSACTIVE_BAD_STANDING;
        loanC.Application__c = app.id;
        loanC.APS_Created__c = false;
        loanC.loan__Account__c = acc.Id;
        loanC.loan__Last_Installment_Date__c = Date.today();
        loanC.loan__Next_Installment_Date__c = Date.today();
        loanC.loan__Principal_Remaining__c = 100;
        update loanC;
        System.assertEquals(loanC.loan__Next_Installment_Date__c,Date.today());

        loan__Payment_Mode__c pmt = new loan__Payment_Mode__c();
        pmt.name = 'ACH';
        insert pmt;
        System.assertEquals(pmt.name,'ACH');

        loan__Bank_Account__c bank = new loan__Bank_Account__c();
        bank.loan__Account__c = acc.Id;
        bank.loan__Active__c = True;
        bank.loan__Bank_Account_Number__c = '123456';
        bank.loan__Bank_Name__c = 'ABCD';
        insert bank;
        System.assertEquals(bank.loan__Active__c,True);

        loanC.loan__Loan_Status__c = 'Approved';
        update loanC;
        loan__Fee__c feeAmt = new loan__Fee__c(name = 'Application Fee', loan__Amount__c = 400,loan__Time_of_charge__c='Pre-Paid Fees');
        insert feeAmt;
        System.assertEquals(feeAmt.name,'Application Fee');
        
        loan__Fee__c feeAmtNext = new loan__Fee__c(name = 'Drawdown Prepaid Interest', loan__Amount__c = 400,loan__Time_of_charge__c='Other');
        insert feeAmtNext;
        System.assertEquals(feeAmtNext.name,'Drawdown Prepaid Interest');
        
        loan__Contract_Pre_Paid_Fee__c conFee = new loan__Contract_Pre_Paid_Fee__c(loan__Amount__c = 400,loan__Contract__c = loanC.Id,loan__Fee_Type__c = feeAmt.Id);
        insert conFee;
        System.assertEquals(conFee.loan__Amount__c,400);

        clcommon__Deposit__c dep = new clcommon__Deposit__c();
        dep.loan__Loan_Account__c = loanC.id;
        dep.clcommon__Current_Deposit_Rate__c =10;
        dep.clcommon__Deposit_Amount__c = 4000;
        dep.clcommon__Deposit_Rate__c = 10;
        insert dep;
        System.assertEquals(dep.clcommon__Current_Deposit_Rate__c,10);

        test.startTest();
        ConvertToContract.executeFun(app.Id);
        app.CL_Contract__c = loanC.Id;
        update app;
        WarehouseFunding.executeFun(loanC.Id,ware.Id);
        //clcommon__Deposit__c dep = [SELECT id,name,clcommon__Current_Deposit_Amount__c,loan__Loan_Account__c FROM clcommon__Deposit__c WHERE loan__Loan_Account__c = :loanC.Id LIMIT 1];
        dep.clcommon__Current_Deposit_Amount__c =2000;
        update dep;
        DepositWithdrawal.withdrawAmt(loanC.Id);
        PageReference pageRef = Page.loan__tabbedLoanAccount;
        pageRef.getParameters().put('LoanId', loanC.id);
        Test.setCurrentPage(pageRef);
        RedrawController controller = new RedrawController();
        controller.acct = loanC;
        controller.message = 'Sample Message';
        controller.doRedraw();
        test.stopTest();
    }
}