elixir/force-app/main/default/objects/Account/fields/loan__Active__c.field-meta.xml
<CustomField>
    <fullName>loan__Active__c</fullName>
    <label>Active</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Borrower.recordType-meta.xml
<RecordType>
    <fullName>Borrower</fullName>
    <active>true</active>
    <label>Borrower</label>
</RecordType>

force-app/main/default/objects/loan__Coborrower__c/loan__Coborrower__c.object-meta.xml
<CustomObject>
    <label>Contract Party</label>
    <nameField>
        <displayFormat>CID-{000000000}</displayFormat>
        <label>Contract Party Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Coborrower__c/fields/loan__Party_Type__c.field-meta.xml
<CustomField>
    <fullName>loan__Party_Type__c</fullName>
    <description>Type of the Contract Party</description>
    <inlineHelpText>Type of the Contract Party</inlineHelpText>
    <label>Party Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Borrower</fullName>
            </value>
            <value>
                <fullName>Beneficiary Owner</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Co-applicant</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Director &amp; Shareholder</fullName>
            </value>
            <value>
                <fullName>Family Corporate Trustee</fullName>
            </value>
            <value>
                <fullName>Family Individual Trustee</fullName>
            </value>
            <value>
                <fullName>Guarantor</fullName>
            </value>
            <value>
                <fullName>Household</fullName>
            </value>
            <value>
                <fullName>Individual Investor</fullName>
            </value>
            <value>
                <fullName>Joint Individual Investor</fullName>
            </value>
            <value>
                <fullName>Joint Investor</fullName>
            </value>
            <value>
                <fullName>Shareholder</fullName>
            </value>
            <value>
                <fullName>SMSF Corporate Trustee</fullName>
            </value>
            <value>
                <fullName>SMSF Individual Trustee</fullName>
            </value>
            <value>
                <fullName>Solicitor</fullName>
            </value>
            <value>
                <fullName>Trustee</fullName>
            </value>
            <value>
                <fullName>Valuer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <customHelpPage>loan__CLContractHelp</customHelpPage>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Account__c/fields/Current_Loan_Balance_Excluding_Deposit__c.field-meta.xml
<CustomField>
    <fullName>Current_Loan_Balance_Excluding_Deposit__c</fullName>
    <formula>loan__Loan_Balance__c- Deposit_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Current Loan Balance Excluding Deposit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Please choose a account, which will be associated as a customer on this lending account.
You can create a new account, from the lookup window by clicking on new or select the existing account from the lookup.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Loan_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Delinquent_Amount__c.field-meta.xml
<CustomField>
    <fullName>loan__Delinquent_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Total Unpaid bills/invoices amount on this account.</inlineHelpText>
    <label>Delinquent Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

elixir/force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Disbursal_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Disbursal_Date__c</fullName>
    <description>Contract Date on the Loan account, this will be updated at the time of funding with the Expected Disbursal Date.</description>
    <inlineHelpText>Contract date on the loan. This will be updated at the time of funding with the expected disbursal date.</inlineHelpText>
    <label>Contract Date</label>
    <type>Date</type>
</CustomField>

elixir/force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>loan__Interest_Rate__c</fullName>
    <description>Interest Rate</description>
    <inlineHelpText>Rate of Interest for the loan.</inlineHelpText>
    <label>Current Interest Rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Loan Amount</description>
    <inlineHelpText>This is the financed amount on the contract which will be disbursed to the customer.</inlineHelpText>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Loan_Status__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Status__c</fullName>
    <inlineHelpText>Status of the Account expected values are :
Pending Approval
Active - Good Standing
Active - Bad Standing
Active - Matured
Approved
Canceled
Closed - Obligations met
Closed- Written Off
Closed - Refinanced
Partial Application
Closed - Premature</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active - Bad Standing</fullName>
            </value>
            <value>
                <fullName>Active - Good Standing</fullName>
            </value>
            <value>
                <fullName>Active - Marked for Closure</fullName>
            </value>
            <value>
                <fullName>Active - Matured</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Closed - Obligations met</fullName>
            </value>
            <value>
                <fullName>Closed - Premature</fullName>
            </value>
            <value>
                <fullName>Closed - Refinanced</fullName>
            </value>
            <value>
                <fullName>Closed- Written Off</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>Partial Application</fullName>
                <default>true</default>
                <label>Partial Application</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Premature Closure Initiated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

elixir/force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Maturity_Date_Current__c.field-meta.xml
<CustomField>
    <fullName>loan__Maturity_Date_Current__c</fullName>
    <inlineHelpText>This is the date on which the the loan matures</inlineHelpText>
    <label>Current Maturity Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Pmt_Amt_Cur__c.field-meta.xml
<CustomField>
    <fullName>loan__Pmt_Amt_Cur__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Current Payment Amount</description>
    <inlineHelpText>This is the current installment amount that needs to be paid.</inlineHelpText>
    <label>Current Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Remaining_IO_Period__c.field-meta.xml
<CustomField>
    <fullName>Remaining_IO_Period__c</fullName>
    <label>Remaining IO Period</label>
    <summaryFilterItems>
        <field>loan__Repayment_Schedule__c.loan__Is_Archived__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>loan__Repayment_Schedule__c.loan__Due_Principal__c</field>
        <operation>equals</operation>
        <value>0</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>loan__Repayment_Schedule__c.loan__Is_Billed__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryForeignKey>loan__Repayment_Schedule__c.loan__Loan_Account__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Restrict_Redraw__c.field-meta.xml
<CustomField>
    <fullName>Restrict_Redraw__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Restrict Redraw</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Payment_Transaction__c/loan__Loan_Payment_Transaction__c.object-meta.xml
<CustomObject>
    <customHelpPage>loan__LoanPaymentTransactionHelp</customHelpPage>
    <description>Loan Payment Transaction</description>
    <label>Loan Payment Transaction</label>
    <nameField>
        <displayFormat>LPT-{000000000}</displayFormat>
        <label>Loan Payment Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Payment Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Payment_Transaction__c/fields/loan__Automated_Payment_Setup__c.field-meta.xml
<CustomField>
    <fullName>loan__Automated_Payment_Setup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Automated Payment Setup</label>
    <referenceTo>loan__Automated_Payment_Setup__c</referenceTo>
    <relationshipLabel>Loan Payment Transactions</relationshipLabel>
    <relationshipName>Loan_Payment_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Payment_Transaction__c/fields/loan__Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>loan__Payment_Type__c</fullName>
    <description>This field is used to determine the reason for which payment is created.Reason can be to settle the loan, sell the loan or waive the interest.</description>
    <inlineHelpText>This field is used to determine the reason for which payment is created.Reason can be to settle the loan, sell the loan or waive the interest.</inlineHelpText>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Waived</fullName>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Regular</fullName>
                <default>true</default>
                <label>Regular</label>
            </value>
            <value>
                <fullName>Rebate</fullName>
            </value>
            <value>
                <fullName>Closure-Tolerance</fullName>
            </value>
            <value>
                <fullName>Principal Adjustment - Sub</fullName>
            </value>
            <value>
                <fullName>Excess</fullName>
            </value>
            <value>
                <fullName>Write-Off Recovery</fullName>
            </value>
            <value>
                <fullName>Refinance</fullName>
            </value>
            <value>
                <fullName>Deposit Payment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Loan_Payment_Transaction__c/fields/loan__Receipt_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Receipt_Date__c</fullName>
    <defaultValue>$User.loan__Current_Branch_s_System_Date__c</defaultValue>
    <description>Receipt Date</description>
    <inlineHelpText>Receipt Date</inlineHelpText>
    <label>Receipt Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Payment_Transaction__c/fields/loan__Rejected__c.field-meta.xml
<CustomField>
    <fullName>loan__Rejected__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Rejected</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CustomerPortalControllerTest.cls
/**
 * Created by Ethan Sargent on 8/07/2021.
 */

@IsTest
private class CustomerPortalControllerTest
{
    private static String authorisedUsername = 'argo-ordeportalauthorised@test.com';
    private static String unauthorisedUsername = 'argo-ordeportalunauthorised@test.com';
    private static String delegatedUsername = 'argo-ordeportaldelegated@test.com';

    private static User authorisedUser;
    private static User unAuthorisedUser;
    private static User delegatedUser;
    private static User getAuthorisedUser()
    {
        if (authorisedUser != null) return authorisedUser;
        return authorisedUser = [SELECT Id, AccountId, ContactId FROM User WHERE Username = :authorisedUsername];
    }
    private static User getUnauthorisedUser()
    {
        if (unAuthorisedUser != null) return unAuthorisedUser;
        return unAuthorisedUser = [SELECT Id, AccountId, ContactId FROM User WHERE Username = :unauthorisedUsername];
    }
    private static User getDelegatedUser()
    {
        if (delegatedUser != null) return delegatedUser;
        return delegatedUser = [SELECT Id, AccountId, ContactId FROM User WHERE Username = :delegatedUsername];
    }

    @TestSetup
    static void setup()
    {
        loan__Org_Parameters__c checkTrigger = new loan__Org_Parameters__c();
        checkTrigger.loan__Disable_Triggers__c = true;
        insert checkTrigger;
        RecordType personAccountType = [SELECT Id FROM RecordType WHERE IsPersonType = TRUE AND IsActive = TRUE];
        Account authorisedAccount = new Account(FirstName = 'Authorised', LastName = 'Person Account', RecordTypeId = personAccountType.Id);
        Account unauthorisedAccount = new Account(FirstName = 'Unauthorised', LastName = 'PersonAccount', RecordTypeId = personAccountType.Id);
        Account delegatedAuthAccount = new Account(FirstName = 'Delegated', LastName = 'PersonAccount', RecordTypeId = personAccountType.Id);
        insert new List<Account> {authorisedAccount, unauthorisedAccount, delegatedAuthAccount};
        Map<Id, Account> personAccountsForContactIds = new Map<Id, Account>([SELECT Id, PersonContactId FROM Account]);
        authorisedAccount = personAccountsForContactIds.get(authorisedAccount.Id);
        unauthorisedAccount = personAccountsForContactIds.get(unauthorisedAccount.Id);
        delegatedAuthAccount = personAccountsForContactIds.get(delegatedAuthAccount.Id);
        AccountContactRelation delegatedAuthRelation = new AccountContactRelation(Roles = 'Director', AccountId = authorisedAccount.Id, ContactId = delegatedAuthAccount.PersonContactId);
        insert delegatedAuthRelation;

        loan__Loan_Account__c loanAccount = (loan__Loan_Account__c) JSON.deserialize('{"Name": "LAI-00000675", "Current_Loan_Balance_Excluding_Deposit__c": 0.00, "loan__Delinquent_Amount__c": 0.00, "loan__Loan_Status__c": "Closed - Obligations met", "loan__Loan_Amount__c": 300000.00, "loan__Disbursal_Date__c": "2020-05-26", "loan__Maturity_Date_Current__c": "2021-05-26", "loan__Interest_Rate__c": 4.5000, "loan__Next_Installment_Date__c": "2020-08-26", "loan__Pmt_Amt_Cur__c": 25618.42, "Remaining_IO_Period__c": 0, "Restrict_Redraw__c": false, "loan__Loan_Status__c": "Active - Good Standing"}', loan__Loan_Account__c.class);
        loanAccount.loan__Account__c = authorisedAccount.Id;
        loanAccount.loan__Disbursal_Date__c = Date.today();
        insert loanAccount;
        loan__Coborrower__c coborrower = new loan__Coborrower__c(loan__Loan__c = loanAccount.Id, loan__Account__c = authorisedAccount.Id, loan__Party_Type__c = 'Borrower');
        insert coborrower;

        loan__Loan_Payment_Transaction__c uncleared = new loan__Loan_Payment_Transaction__c(
                loan__Cleared__c = false,
                loan__Reversed__c = false,
                loan__Rejected__c = false,
                loan__Loan_Account__c = loanAccount.Id,
                loan__Transaction_Date__c = Date.today(),
                loan__Transaction_Amount__c = 100,
                loan__Receipt_Date__c = Date.today()
        );
        loan__Loan_Payment_Transaction__c dishonoured = new loan__Loan_Payment_Transaction__c(
                loan__Cleared__c = false,
                loan__Reversed__c = false,
                loan__Rejected__c = true,
                loan__Loan_Account__c = loanAccount.Id,
                loan__Transaction_Date__c = Date.today(),
                loan__Transaction_Amount__c = 100,
                loan__Receipt_Date__c = Date.today()
        );
        loan__Loan_Payment_Transaction__c paymentTransaction = new loan__Loan_Payment_Transaction__c(
                loan__Payment_Type__c = 'Regular',
                loan__Loan_Account__c = loanAccount.Id,
                loan__Transaction_Date__c = Date.today(),
                loan__Transaction_Amount__c = 100,
                loan__Receipt_Date__c = Date.today()
        );
        insert paymentTransaction;
        loan__Loan_Transaction_Summary__c historyTransaction = new loan__Loan_Transaction_Summary__c(
                loan__Loan_Account__c = loanAccount.Id,
                loan__Consolidated_Loan_Balance__c = 0,
                loan__Transaction_Amount__c = 100,
                loan__Transaction_Date__c = Date.today(),
                loan__Loan_Payment_Txn__c = paymentTransaction.Id
        );
        insert new List<SObject> {uncleared, dishonoured, historyTransaction};

        loan__Automated_Payment_Setup__c paymentSetup = new loan__Automated_Payment_Setup__c();
        paymentSetup.loan__Transaction_Amount__c = 10000;
        paymentSetup.loan__Debit_Date__c = Date.today().addDays(1);
        paymentSetup.loan__Active__c = true;
        paymentSetup.loan__CL_Contract__c = loanAccount.Id;
        paymentSetup.loan__Type__c = 'RECURRING';
        paymentSetup.loan__Amount_Type__c = 'FIXED AMOUNT';
        paymentSetup.loan__Actual_Date__c = paymentSetup.loan__Debit_Date__c;
        paymentSetup.loan__Frequency__c = 'MONTHLY';
        insert paymentSetup;


        Profile p = [SELECT Id FROM Profile WHERE Name = 'Orde Customer Community Plus User'];
        User authorisedUser = new User(Alias = 'test', Email = 'argo-ordeportal@test.com',
                EmailEncodingKey = 'UTF-8', LastName = 'Testing', LanguageLocaleKey = 'en_US',
                LocaleSidKey = 'en_US', ProfileId = p.Id,
                TimeZoneSidKey = 'Australia/Sydney', Username = authorisedUsername, ContactId = authorisedAccount.PersonContactId);
        User unauthorisedUser = new User(Alias = 'testuac', Email = 'argo-ordeportal@test.com',
                EmailEncodingKey = 'UTF-8', LastName = 'TestingUnauthorised', LanguageLocaleKey = 'en_US',
                LocaleSidKey = 'en_US', ProfileId = p.Id,
                TimeZoneSidKey = 'Australia/Sydney', Username = unauthorisedUsername, ContactId = unauthorisedAccount.PersonContactId);
        User delegatedAccountAccessUser = new User(Alias = 'testdac', Email = 'argo-ordeportal@test.com',
                EmailEncodingKey = 'UTF-8', LastName = 'TestingDelegated', LanguageLocaleKey = 'en_US',
                LocaleSidKey = 'en_US', ProfileId = p.Id,
                TimeZoneSidKey = 'Australia/Sydney', Username = delegatedUsername, ContactId = delegatedAuthAccount.PersonContactId);

        insert new List<User> {authorisedUser, unauthorisedUser, delegatedAccountAccessUser};

    }

    @IsTest
    static void testGetLoanAccountAuthorised()
    {
        // Arrange
        User u = getAuthorisedUser();
        CustomerPortalController.LoanAccountRequestDto req = new CustomerPortalController.LoanAccountRequestDto();
        req.loanAccountId = [SELECT Id FROM loan__Loan_Account__c LIMIT 1].Id;
        // Act
        CustomerPortalController.LoanAccountDto result;
        Test.startTest();
        System.runAs(u)
        {
            result = CustomerPortalController.getLoanAccountDetails(req);
        }
        Test.stopTest();
        // Assert
        System.assertNotEquals(null, result);
        System.assertNotEquals(0, result.fields.keySet().size());
        System.assertEquals(req.loanAccountId, result.recordId);
    }

    @IsTest
    static void testGetLoanAccountUnauthorised()
    {
        // Arrange
        User u = getUnauthorisedUser();
        CustomerPortalController.LoanAccountRequestDto req = new CustomerPortalController.LoanAccountRequestDto();
        req.loanAccountId = [SELECT Id FROM loan__Loan_Account__c LIMIT 1].Id;
        // Act
        CustomerPortalController.LoanAccountDto result;
        Test.startTest();
        System.runAs(u)
        {
            result = CustomerPortalController.getLoanAccountDetails(req);
        }
        Test.stopTest();
        // Assert
        System.assertEquals(0, result.fields.keySet().size());
        System.assertEquals(null, result.recordId);
    }


    @IsTest
    static void testGetTransactionHistoryAuthorised()
    {
        // Arrange
        User u = getAuthorisedUser();
        CustomerPortalController.TransactionHistoryRequestDto req = new CustomerPortalController.TransactionHistoryRequestDto();
        req.loanAccountId = [SELECT Id FROM loan__Loan_Account__c LIMIT 1].Id;
        // Act
        CustomerPortalController.TransactionHistoryResponseDto result;
        Test.startTest();
        System.runAs(u)
        {
            result = CustomerPortalController.getTransactionHistory(req);
        }
        Test.stopTest();
        // Assert
        System.assertNotEquals(null, result);
        System.assertEquals(1, result.transactionHistory.size());
        System.assertEquals(2, result.unclearedPayments.size());
        System.assertEquals(1, result.dishonouredPayments.size());
    }

    @IsTest
    static void testGetTransactionHistoryUnauthorised()
    {
        // Arrange
        User u = getUnauthorisedUser();
        CustomerPortalController.TransactionHistoryRequestDto req = new CustomerPortalController.TransactionHistoryRequestDto();
        req.loanAccountId = [SELECT Id FROM loan__Loan_Account__c LIMIT 1].Id;
        // Act
        CustomerPortalController.TransactionHistoryResponseDto result;
        Test.startTest();
        System.runAs(u)
        {
            result = CustomerPortalController.getTransactionHistory(req);
        }
        Test.stopTest();
        // Assert
        System.assertNotEquals(null, result);
        System.assertEquals(0, result.transactionHistory.size());
        System.assertEquals(0, result.unclearedPayments.size());
        System.assertEquals(0, result.dishonouredPayments.size());
    }

    @IsTest
    static void testGetAccountsWithDelegated()
    {
        User u = getDelegatedUser();

        // Act
        List<CustomerPortalController.AccountSwitcherDto> result;
        Test.startTest();
        System.runAs(u)
        {
            result = CustomerPortalController.getAccounts();
        }
        Test.stopTest();
        // Assert
        System.assertNotEquals(null, result);
        System.assertEquals(1, result.size());

    }

    @IsTest
    static void testGetAccountsNotDelegated()
    {
        User u = getAuthorisedUser();

        // Act
        List<CustomerPortalController.AccountSwitcherDto> result;
        Test.startTest();
        System.runAs(u)
        {
            result = CustomerPortalController.getAccounts();
        }
        Test.stopTest();
        // Assert
        System.assertNotEquals(null, result);
        System.assertEquals(1, result.size());

    }

    @IsTest
    static void testGetLoansAuthorised()
    {
        User u = getAuthorisedUser();
        CustomerPortalController.LoanSwitcherRequestDto requestDto = new CustomerPortalController.LoanSwitcherRequestDto();
        // Act
        List<CustomerPortalController.LoanSwitcherDto> result;
        Test.startTest();
        System.runAs(u)
        {
            result = CustomerPortalController.getLoans(requestDto);
        }
        Test.stopTest();
        // Assert
        System.assertNotEquals(null, result);
        System.assertEquals(1, result.size());

    }

    @IsTest
    static void testGetLoansDelegated()
    {
        User u = getDelegatedUser();
        User authorisedUser = getAuthorisedUser();
        CustomerPortalController.LoanSwitcherRequestDto requestDto = new CustomerPortalController.LoanSwitcherRequestDto();
        requestDto.requestedAccountId = authorisedUser.AccountId;
        // Act
        List<CustomerPortalController.LoanSwitcherDto> result;
        Test.startTest();
        System.runAs(u)
        {
            result = CustomerPortalController.getLoans(requestDto);
        }
        Test.stopTest();
        // Assert
        System.assertNotEquals(null, result);
        System.assertEquals(1, result.size());

    }

    @IsTest
    static void testGetLoansUnauthorised()
    {
        User u = getUnauthorisedUser();
        User authorisedUser = getAuthorisedUser();
        CustomerPortalController.LoanSwitcherRequestDto requestDto = new CustomerPortalController.LoanSwitcherRequestDto();
        requestDto.requestedAccountId = authorisedUser.AccountId;
        // Act
        List<CustomerPortalController.LoanSwitcherDto> result;
        Test.startTest();
        System.runAs(u)
        {
            result = CustomerPortalController.getLoans(requestDto);
        }
        Test.stopTest();
        // Assert
        System.assertNotEquals(null, result);
        System.assertEquals(0, result.size());

    }


    @IsTest
    static void testGetDirectDebitInformationAuthorised()
    {
        User u = getAuthorisedUser();
        CustomerPortalController.LoanAccountRequestDto requestDto = new CustomerPortalController.LoanAccountRequestDto();
        requestDto.loanAccountId = [SELECT Id FROM loan__Loan_Account__c].Id;
        // Act
        List<CustomerPortalController.TabulatedDetailsResponseDto> result;
        Test.startTest();
        System.runAs(u)
        {
            result = CustomerPortalController.getDirectDebitInformation(requestDto);
        }
        Test.stopTest();
        // Assert
        System.assertNotEquals(null, result);
        System.assertEquals(1, result.size());

    }


    @IsTest
    static void testGetDirectDebitInformationUnauthorised()
    {
        User u = getUnauthorisedUser();
        User authorisedUser = getAuthorisedUser();
        CustomerPortalController.LoanSwitcherRequestDto requestDto = new CustomerPortalController.LoanSwitcherRequestDto();
        requestDto.requestedAccountId = authorisedUser.AccountId;
        // Act
        List<CustomerPortalController.LoanSwitcherDto> result;
        Test.startTest();
        System.runAs(u)
        {
            result = CustomerPortalController.getLoans(requestDto);
        }
        Test.stopTest();
        // Assert
        System.assertNotEquals(null, result);
        System.assertEquals(0, result.size());

    }

    @IsTest
    static void testGetStatementInformationAuthorised()
    {
        User u = getAuthorisedUser();
        CustomerPortalController.LoanAccountRequestDto requestDto = new CustomerPortalController.LoanAccountRequestDto();
        requestDto.loanAccountId = [SELECT Id FROM loan__Loan_Account__c].Id;
        Attachment attachment = new Attachment();
        attachment.Name = 'Half Yearly Statement Jun 2021';
        attachment.Body = Blob.valueOf('Test Data');
        attachment.ParentId = requestDto.loanAccountId;
        insert attachment;

        ContentVersion cv = new ContentVersion();
        cv.ContentLocation = 'S';
        cv.Title = 'Half Yearly Statement Jun 2021';
        cv.PathOnClient = 'Test ContentVersion';
        cv.VersionData = Blob.valueOf('testData');
        cv.SharingPrivacy = 'N';
        insert cv;

        ContentDocumentLink cdl = new ContentDocumentLink();
        cdl.ContentDocumentId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :cv.Id].ContentDocumentId;

        cdl.LinkedEntityId = requestDto.loanAccountId;
        cdl.ShareType = 'V';
        cdl.Visibility = 'AllUsers';
        insert cdl;
        System.assertNotEquals(null, cdl.Id);

        // Act
        List<CustomerPortalController.TabulatedDetailsResponseDto> result;
        Test.startTest();
        System.runAs(u)
        {
            result = CustomerPortalController.getStatementDetails(requestDto);
        }
        Test.stopTest();
        // Assert
        System.assertNotEquals(null, result);
        System.assertEquals(1, result.size());

    }

    @IsTest
    static void testGetStatementInformationUnauthorised()
    {
        User u = getUnauthorisedUser();
        CustomerPortalController.LoanAccountRequestDto requestDto = new CustomerPortalController.LoanAccountRequestDto();
        requestDto.loanAccountId = [SELECT Id FROM loan__Loan_Account__c].Id;
        Attachment attachment = new Attachment();
        attachment.Name = 'Half Yearly Statement Jun 2021';
        attachment.Body = Blob.valueOf('Test Data');
        attachment.ParentId = requestDto.loanAccountId;
        insert attachment;

        ContentVersion cv = new ContentVersion();
        cv.ContentLocation = 'S';
        cv.Title = 'Half Yearly Statement Jun 2021';
        cv.PathOnClient = 'Test ContentVersion';
        cv.VersionData = Blob.valueOf('testData');
        insert cv;

        ContentDocumentLink cdl = new ContentDocumentLink();
        cdl.ContentDocumentId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :cv.Id].ContentDocumentId;

        cdl.LinkedEntityId = requestDto.loanAccountId;
        cdl.ShareType = 'V';
        cdl.Visibility = 'AllUsers';
        insert cdl;
        System.assertNotEquals(null, cdl.Id);

        // Act
        List<CustomerPortalController.TabulatedDetailsResponseDto> result;
        Test.startTest();
        System.runAs(u)
        {
            result = CustomerPortalController.getStatementDetails(requestDto);
        }
        Test.stopTest();
        // Assert
        System.assertNotEquals(null, result);
        System.assertEquals(0, result.size());

    }

//    @IsTest
//    static void testGetStatementFileAuthorised()
//    {
//        User u = getAuthorisedUser();
//        CustomerPortalController.StatementDownloadRequestDto requestDto = new CustomerPortalController.StatementDownloadRequestDto();
//        requestDto.loanAccountId = [SELECT Id FROM loan__Loan_Account__c].Id;
//        ContentVersion cv = new ContentVersion();
//        cv.ContentLocation = 'S';
//        cv.Title = 'Test ContentVersion';
//        cv.PathOnClient = 'Test ContentVersion';
//        cv.VersionData = Blob.valueOf('testData');
//        insert cv;
//
//        ContentDocumentLink cdl = new ContentDocumentLink();
//        cdl.ContentDocumentId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :cv.Id].ContentDocumentId;
//
//        cdl.LinkedEntityId = requestDto.loanAccountId;
//        cdl.ShareType = 'V';
//        cdl.Visibility = 'AllUsers';
//        insert cdl;
//        System.assertNotEquals(null, cdl.Id);
//
//        requestDto.statementId = cdl.Id;
//        // Act
//        List<String> results;
//        Test.startTest();
//        System.runAs(u)
//        {
//            results = CustomerPortalController.getStatementFile(requestDto);
//        }
//        Test.stopTest();
//        // Assert
//        System.assertNotEquals(0, results.size());
//        System.assertEquals('Half Yearly Statement Jun 2021', results[0]);
//        System.assertEquals(EncodingUtil.base64Encode(Blob.valueOf('Test Data')), results[1]);
//    }
//
//    @IsTest
//    static void testGetStatementFileUnauthorised()
//    {
//        User u = getUnauthorisedUser();
//        CustomerPortalController.StatementDownloadRequestDto requestDto = new CustomerPortalController.StatementDownloadRequestDto();
//        requestDto.loanAccountId = [SELECT Id FROM loan__Loan_Account__c].Id;
//        Attachment attachment = new Attachment();
//        attachment.Name = 'Half Yearly Statement Jun 2021';
//        attachment.Body = Blob.valueOf('Test Data');
//        attachment.ParentId = requestDto.loanAccountId;
//        insert attachment;
//
//        requestDto.statementId = attachment.Id;
//        // Act
//        List<String> results;
//        Test.startTest();
//        System.runAs(u)
//        {
//            results = CustomerPortalController.getStatementFile(requestDto);
//        }
//        Test.stopTest();
//        // Assert
//        System.assertEquals(null, results[0]);
//        System.assertEquals(null, results[1]);
//    }

    @IsTest
    static void testGetPortalUserInfo()
    {
        User u = getAuthorisedUser();
        // Act
        CustomerPortalController.UserDetailsDto result;
        Test.startTest();
        System.runAs(u)
        {
            result = CustomerPortalController.getPortalUserInfo();
        }
        Test.stopTest();
        // Assert
        System.assertNotEquals(null, result);
        System.assertNotEquals(null, result);
    }

    @IsTest
    static void testUpdatePortalUserInfo()
    {
        User u = getAuthorisedUser();
        // Act
        CustomerPortalController.UserDetailsDto request;
        System.runAs(u)
        {
            request = CustomerPortalController.getPortalUserInfo();
        }
        request.phone = '99998888';
        Boolean result = false;
        Test.startTest();
        System.runAs(u)
        {
            result = CustomerPortalController.updatePortalUserInfo(request);
        }
        Test.stopTest();
        // Assert
        System.assertEquals(true, result);
    }


    @IsTest
    static void testException()
    {
        CustomerPortalException.test();
    }

    @IsTest
    static void testDirectDebitDto()
    {
        PortalManageDirectDebitRequestDto requestDto = new PortalManageDirectDebitRequestDto();
        requestDto.recordId = 'test';
        requestDto.loanAccountId = 'test';
        requestDto.isDelete = false;
        requestDto.directDebitType = 'test';
        requestDto.amountType = 'test';
        requestDto.debitDate = Date.today();
        requestDto.transactionAmount = 1;
        requestDto.frequency = 'test';

    }

}