elixir/force-app/main/default/objects/Account/fields/loan__Active__c.field-meta.xml
<CustomField>
    <fullName>loan__Active__c</fullName>
    <label>Active</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

elixir/force-app/main/default/objects/Account/fields/loan__Borrower__c.field-meta.xml
<CustomField>
    <fullName>loan__Borrower__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Borrower</label>
    <type>Checkbox</type>
</CustomField>

elixir/force-app/main/default/objects/Contact/fields/loan__Payment_Mode__c.field-meta.xml
<CustomField>
    <fullName>loan__Payment_Mode__c</fullName>
    <description>Payment mode, used to disburse payments back to broker.</description>
    <inlineHelpText>Payment mode, used to disburse payments back to broker.</inlineHelpText>
    <label>Payment Mode</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACH</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Check</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Bank_Account__c/loan__Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <displayFormat>BA-{00000}</displayFormat>
        <label>Bank Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Bank_Account__c/fields/BSB_Number__c.field-meta.xml
<CustomField>
    <fullName>BSB_Number__c</fullName>
    <label>BSB Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Bank_Account__c/fields/loan__Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

elixir/force-app/main/default/objects/loan__Bank_Account__c/fields/loan__Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>loan__Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>50</length>
    <maskChar>X</maskChar>
    <maskType>lastFour</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

elixir/force-app/main/default/objects/loan__Bank_Account__c/fields/loan__Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>loan__Bank_Name__c</fullName>
    <label>Bank Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

elixir/force-app/main/default/objects/loan__Bank_Account__c/fields/loan__Contact__c.field-meta.xml
<CustomField>
    <fullName>loan__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <customHelpPage>loan__CLContractHelp</customHelpPage>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Please choose a account, which will be associated as a customer on this lending account.
You can create a new account, from the lookup window by clicking on new or select the existing account from the lookup.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Loan_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

elixir/force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Contact__c.field-meta.xml
<CustomField>
    <fullName>loan__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Please choose a contact, which will be associated as a customer on this lending account.
You can create a new contact, from the lookup window by clicking on new or select the existing contact from the lookup.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Loan_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

elixir/force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Disbursal_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Disbursal_Date__c</fullName>
    <description>Contract Date on the Loan account, this will be updated at the time of funding with the Expected Disbursal Date.</description>
    <inlineHelpText>Contract date on the loan. This will be updated at the time of funding with the expected disbursal date.</inlineHelpText>
    <label>Contract Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Loan Amount</description>
    <inlineHelpText>This is the financed amount on the contract which will be disbursed to the customer.</inlineHelpText>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Loan_Status__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Status__c</fullName>
    <inlineHelpText>Status of the Account expected values are :
Pending Approval
Active - Good Standing
Active - Bad Standing
Active - Matured
Approved
Canceled
Closed - Obligations met
Closed- Written Off
Closed - Refinanced
Partial Application
Closed - Premature</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active - Bad Standing</fullName>
            </value>
            <value>
                <fullName>Active - Good Standing</fullName>
            </value>
            <value>
                <fullName>Active - Marked for Closure</fullName>
            </value>
            <value>
                <fullName>Active - Matured</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Closed - Obligations met</fullName>
            </value>
            <value>
                <fullName>Closed - Premature</fullName>
            </value>
            <value>
                <fullName>Closed - Refinanced</fullName>
            </value>
            <value>
                <fullName>Closed- Written Off</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>Partial Application</fullName>
                <default>true</default>
                <label>Partial Application</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Premature Closure Initiated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Total_Amount_Disbursed__c.field-meta.xml
<CustomField>
    <fullName>loan__Total_Amount_Disbursed__c</fullName>
    <defaultValue>0</defaultValue>
    <description>This is the total amount disbursed including any additional costs.</description>
    <inlineHelpText>This is the total amount disbursed including any additional costs.</inlineHelpText>
    <label>Total Amount Disbursed</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Disbursal_Transaction__c/loan__Loan_Disbursal_Transaction__c.object-meta.xml
<CustomObject>
    <customHelpPage>loan__LoanDisbursalTransactionHelp</customHelpPage>
    <description>This is the final stage where all the documents submitted by a customer are finally checked and the loan is approved.</description>
    <label>Loan Disbursal Transaction</label>
    <nameField>
        <displayFormat>LDTI-{0000000000}</displayFormat>
        <label>Loan Disbursal Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Disbursal Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Disbursal_Transaction__c/fields/loan__Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Bank_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bank Account</label>
    <referenceTo>loan__Bank_Account__c</referenceTo>
    <relationshipLabel>Loan Disbursal Transactions</relationshipLabel>
    <relationshipName>Loan_Disbursal_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Disbursal_Transaction__c/fields/loan__Cleared__c.field-meta.xml
<CustomField>
    <fullName>loan__Cleared__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cleared</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Disbursal_Transaction__c/fields/loan__Disbursal_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Disbursal_Date__c</fullName>
    <defaultValue>$User.loan__Current_Branch_s_System_Date__c</defaultValue>
    <description>By default, this is the date specified in the proposed disbursal date in the account details. If the date is modified during loan disbursal, the repayment schedule is regenerated accordingly.</description>
    <inlineHelpText>By default, this is the date specified in the proposed disbursal date in the account details. If the date is modified during loan disbursal, the repayment schedule is regenerated accordingly.</inlineHelpText>
    <label>Disbursal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Disbursal_Transaction__c/fields/loan__Loan_Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Account__c</fullName>
    <description>Loan Account</description>
    <inlineHelpText>Loan Account</inlineHelpText>
    <label>Loan Account</label>
    <referenceTo>loan__Loan_Account__c</referenceTo>
    <relationshipLabel>Loan Disbursal Transactions</relationshipLabel>
    <relationshipName>Loan_Disbursal_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Disbursal_Transaction__c/fields/loan__Mode_of_Payment__c.field-meta.xml
<CustomField>
    <fullName>loan__Mode_of_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mode of Payment</label>
    <referenceTo>loan__Payment_Mode__c</referenceTo>
    <relationshipLabel>Loan Disbursal Transactions</relationshipLabel>
    <relationshipName>Loan_Disbursal_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Payment_Transaction__c/loan__Loan_Payment_Transaction__c.object-meta.xml
<CustomObject>
    <customHelpPage>loan__LoanPaymentTransactionHelp</customHelpPage>
    <description>Loan Payment Transaction</description>
    <label>Loan Payment Transaction</label>
    <nameField>
        <displayFormat>LPT-{000000000}</displayFormat>
        <label>Loan Payment Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Payment Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Payment_Transaction__c/fields/loan__Payment_Mode__c.field-meta.xml
<CustomField>
    <fullName>loan__Payment_Mode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Mode</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>loan__Payment_Mode__c.Name</field>
            <operation>notEqual</operation>
            <value>Internal Transfer</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>loan__Payment_Mode__c</referenceTo>
    <relationshipLabel>Loan Payment Transactions</relationshipLabel>
    <relationshipName>Loan_Payment_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Payment_Transaction__c/fields/loan__Sent_to_ACH__c.field-meta.xml
<CustomField>
    <fullName>loan__Sent_to_ACH__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sent to ACH</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Repayment_Transaction_Adjustment__c/loan__Repayment_Transaction_Adjustment__c.object-meta.xml
<CustomObject>
    <description>Repayment Transaction Adjustment Object</description>
    <label>Repayment Transaction Reversal</label>
    <nameField>
        <displayFormat>RTA-{0000000000}</displayFormat>
        <label>Repayment Transaction Adjustment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Transaction Reversal</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Repayment_Transaction_Adjustment__c/fields/loan__Loan_Payment_Transaction__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Payment_Transaction__c</fullName>
    <description>Loan Payment Transaction</description>
    <inlineHelpText>Loan Payment Transaction</inlineHelpText>
    <label>Loan Payment Transaction</label>
    <referenceTo>loan__Loan_Payment_Transaction__c</referenceTo>
    <relationshipName>Repayment_Transaction_Adjustment</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/loan__Repayment_Transaction_Adjustment__c/fields/loan__Payment_Mode__c.field-meta.xml
<CustomField>
    <fullName>loan__Payment_Mode__c</fullName>
    <formula>loan__Loan_Payment_Transaction__r.loan__Payment_Mode__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payment_Mode</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LoanPaymentReturnFileHandlerTest.cls
/****************************************************************************************************/
/* Description          : This test class mostly covers the LoanPaymentReturnFileHandler class. */
/* Testing Scenario 1   : (testWithValidData) This test method will test with 1 reversable LPT,
1 LPT with multiple Txns exception, 1 LPT with already reversed exception and 6 LPTs with Txn not
found exception. Total 9 LPTs to cover every return cause. */
/* Testing Scenario 2   : (testWithValidData) This test method will test how the class will handle
 if invalid a file is provided. */
/****************************************************************************************************/

@isTest
public class LoanPaymentReturnFileHandlerTest {
  @TestSetup
  static void initialize() {
    loan__Org_Parameters__c checkTrigger = new loan__Org_Parameters__c();
    checkTrigger.loan__Disable_Triggers__c = true;
    insert checkTrigger;
    Account testAccount = new Account();
    testAccount.loan__Active__c = 'Yes';
    testAccount.loan__Borrower__c = true;
    testAccount.Name = 'Test';
    testAccount.BillingPostalcode = '1234';
    testAccount.BillingCity = 'TestCity';
    insert testAccount;
    Contact testContact = new Contact();
    testContact.AccountId = testAccount.id;
    testContact.LastName = 'Test';
    insert testContact;
    loan__Bank_Account__c testPayeebankAccount = new loan__Bank_Account__c();
    testPayeebankAccount.loan__Bank_Name__c = 'PayeeBank';
    testPayeebankAccount.BSB_Number__c = '324089';
    testPayeebankAccount.loan__Bank_Account_Number__c = '234567700';
    testPayeebankAccount.loan__Account__c = testAccount.Id;
    testPayeebankAccount.loan__Active__c = true;
    insert testPayeebankAccount;
    loan__Bank_Account__c testPayerbankAccount = new loan__Bank_Account__c();
    testPayerbankAccount.loan__Bank_Name__c = 'PayerBank';
    testPayerbankAccount.BSB_Number__c = '453009';
    testPayerbankAccount.loan__Bank_Account_Number__c = '770065432';
    testPayerbankAccount.loan__Account__c = testAccount.Id;
    testPayerbankAccount.loan__Active__c = true;
    insert testPayerbankAccount;
    loan__Payment_Mode__c testDDPaymentMode = new loan__Payment_Mode__c();
    testDDPaymentMode.Name = 'Direct Debit';
    insert testDDPaymentMode;
    loan__Loan_Account__c testLoanAccount = new loan__Loan_Account__c();
    testLoanAccount.loan__Account__c = testAccount.Id;
    testLoanAccount.loan__Contact__c = testContact.Id;
    testLoanAccount.loan__Loan_Amount__c = 500000;
    testLoanAccount.loan__Disbursed_Amount__c = 500000;
    //testLoanAccount.loan__Total_Amount_Disbursed__c = 500000;
    testLoanAccount.loan__Loan_Status__c = 'Approved';
    testLoanAccount.loan__Borrower_ACH__c = testPayerbankAccount.Id;
    insert testLoanAccount;
    loan__Loan_Disbursal_Transaction__c testLdt = new loan__Loan_Disbursal_Transaction__c();
    testLdt.loan__Loan_Account__c = testLoanAccount.Id;
    testLdt.loan__Disbursal_Date__c = Date.newInstance(2019, 6, 10);
    testLdt.loan__Mode_of_Payment__c = testDDPaymentMode.Id;
    testLdt.loan__Cleared__c = true;
    insert testLdt;
    testLoanAccount.loan__Disbursal_Date__c = Date.newInstance(2019, 6, 10);
    update testLoanAccount;
    loan__Loan_Payment_Transaction__c testLpt = new loan__Loan_Payment_Transaction__c();
    testLpt.loan__Loan_Account__c = testLoanAccount.Id;
    testLpt.loan__Sent_to_ACH__c = false;
    testLpt.loan__Payment_Type__c = 'Regular';
    testLpt.loan__Transaction_Date__c = Date.newInstance(2019, 6, 10);
    testLpt.loan__Payment_Mode__c = testDDPaymentMode.id;
    testLpt.loan__Transaction_Amount__c = 5000;
    testLpt.loan__Cleared__c = true;
    testLpt.loan__Reversed__c = false;
    testLpt.loan__Rejected__c = false;
    insert testLpt;
    loan__Loan_Payment_Transaction__c testLpt2 = new loan__Loan_Payment_Transaction__c();
    testLpt2.loan__Loan_Account__c = testLoanAccount.Id;
    testLpt2.loan__Sent_to_ACH__c = false;
    testLpt2.loan__Payment_Type__c = 'Regular';
    testLpt2.loan__Transaction_Date__c = Date.newInstance(2019, 6, 10);
    testLpt2.loan__Payment_Mode__c = testDDPaymentMode.id;
    testLpt2.loan__Transaction_Amount__c = 5000;
    testLpt2.loan__Cleared__c = true;
    testLpt2.loan__Reversed__c = true;
    testLpt2.loan__Rejected__c = false;
    insert testLpt2;
    testLoanAccount.loan__Last_Transaction_Id__c = (String) testLpt.Id;
    update testLoanAccount;
    testLoanAccount = new loan__Loan_Account__c();
    testLoanAccount.loan__Account__c = testAccount.Id;
    testLoanAccount.loan__Contact__c = testContact.Id;
    testLoanAccount.loan__Loan_Amount__c = 500000;
    testLoanAccount.loan__Disbursed_Amount__c = 500000;
    //testLoanAccount.loan__Total_Amount_Disbursed__c = 500000;
    testLoanAccount.loan__Loan_Status__c = 'Approved';
    testLoanAccount.loan__Borrower_ACH__c = testPayerbankAccount.Id;
    insert testLoanAccount;
    testLdt = new loan__Loan_Disbursal_Transaction__c();
    testLdt.loan__Loan_Account__c = testLoanAccount.Id;
    testLdt.loan__Disbursal_Date__c = Date.newInstance(2019, 6, 10);
    testLdt.loan__Mode_of_Payment__c = testDDPaymentMode.Id;
    testLdt.loan__Cleared__c = true;
    insert testLdt;
    testLoanAccount.loan__Disbursal_Date__c = Date.newInstance(2019, 6, 10);
    update testLoanAccount;
    testLpt = new loan__Loan_Payment_Transaction__c();
    testLpt.loan__Loan_Account__c = testLoanAccount.Id;
    testLpt.loan__Sent_to_ACH__c = false;
    testLpt.loan__Payment_Type__c = 'Regular';
    testLpt.loan__Transaction_Date__c = Date.newInstance(2019, 6, 10);
    testLpt.loan__Payment_Mode__c = testDDPaymentMode.id;
    testLpt.loan__Transaction_Amount__c = 5000;
    testLpt.loan__Cleared__c = true;
    testLpt.loan__Reversed__c = false;
    testLpt.loan__Rejected__c = false;
    insert testLpt;
  }
  @isTest
  static void testWithValidData() {
    List<loan__Loan_Payment_Transaction__c> lptList = new List<loan__Loan_Payment_Transaction__c>(
      [
        SELECT Id, Name
        FROM loan__Loan_Payment_Transaction__c
        WHERE loan__Reversed__c = false
      ]
    );
    System.assertEquals(lptList.size(), 2, 'Non reversed LPT not inserted');
    String record =
      '2756-2341234567897130000500000xxxxxx                          ' +
      lptList[0].Name +
      '     123-456123456789AJAX CRACKERS   00000000';
    record +=
      '\n2756-2341234567898130000500000xxxxxx                          ' +
      lptList[1].Name +
      '     123-456123456789AJAX CRACKERS   00000000';
    lptList = new List<loan__Loan_Payment_Transaction__c>(
      [
        SELECT Id, Name
        FROM loan__Loan_Payment_Transaction__c
        WHERE loan__Reversed__c = true
      ]
    );
    System.assertEquals(lptList.size(), 1, 'Reversed LPT not inserted');
    record +=
      '\n2756-2341234567899130000500000xxxxxx                          ' +
      lptList[0].Name +
      '     123-456123456789AJAX CRACKERS   00000000';
    List<StaticResource> sr = new List<StaticResource>(
      [
        SELECT Id, Name, Body
        FROM StaticResource
        WHERE Name = 'deReturnSampleReport'
        LIMIT 1
      ]
    );
    System.assertEquals(sr.size(), 1, 'Static Resource not found');
    String val = sr[0].Body.toString();
    List<String> records = val.split('\n');
    records.add(1, record);
    val = String.join(records, '\n');
    Test.startTest();
    LoanPaymentReturnFileHandler fileHandlerObj = new LoanPaymentReturnFileHandler();
    fileHandlerObj.parse(val);
    Test.stopTest();
    List<loan__Repayment_Transaction_Adjustment__c> reversalRecords = new List<loan__Repayment_Transaction_Adjustment__c>(
      [SELECT Id FROM loan__Repayment_Transaction_Adjustment__c]
    );
    System.assertEquals(
      reversalRecords.size(),
      1,
      'LPT reversal record not inserted'
    );
    String likeQuery = ConstantValues.TXN_REV_ERR + '%';
    List<peer__Bank_Recon_Exception__c> exceptionList;
    exceptionList = new List<peer__Bank_Recon_Exception__c>(
      [
        SELECT Id, peer__Recon_Message__c, peer__Reference_Number__c
        FROM peer__Bank_Recon_Exception__c
        WHERE peer__Recon_Message__c LIKE :likeQuery
      ]
    );
    System.assertEquals(
      exceptionList.size(),
      1,
      'Multiple Txn exception count from Return Report mismatched with the actual'
    );
    exceptionList = new List<peer__Bank_Recon_Exception__c>(
      [
        SELECT Id, peer__Recon_Message__c, peer__Reference_Number__c
        FROM peer__Bank_Recon_Exception__c
        WHERE peer__Recon_Message__c = :ConstantValues.ALREADY_REV
      ]
    );
    System.assertEquals(
      exceptionList.size(),
      1,
      'Already reversed Txn exception count from Return Report mismatched with the actual'
    );
    exceptionList = new List<peer__Bank_Recon_Exception__c>(
      [
        SELECT Id, peer__Recon_Message__c, peer__Reconciliation_Message__c
        FROM peer__Bank_Recon_Exception__c
        WHERE peer__Recon_Message__c = :ConstantValues.TXN_NOT_FOUND
      ]
    );
    System.assertEquals(
      exceptionList.size(),
      6,
      'Invalid Txn exception count from Return Report mismatched with the actual'
    );
  }
  @isTest
  static void testWithInvalidFileData() {
    String val = '';
    Test.startTest();
    LoanPaymentReturnFileHandler fileHandlerObj = new LoanPaymentReturnFileHandler();
    try {
      fileHandlerObj.parse(val);
    } catch (Exception ex) {
      System.debug(ex.getMessage());
    }
    Test.stopTest();
  }
}