force-app/main/default/objects/Linked_Loan__c/Linked_Loan__c.object-meta.xml
<CustomObject>
    <label>Linked Loan</label>
    <nameField>
        <displayFormat>LLJunction-{0000}</displayFormat>
        <label>Linked Loan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Linked Loans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Linked_Loan__c/fields/Current_Loan_Balance_Excluding_Deposit__c.field-meta.xml
<CustomField>
    <fullName>Current_Loan_Balance_Excluding_Deposit__c</fullName>
    <formula>Linked_Loan__r.Current_Loan_Balance_Excluding_Deposit__c</formula>
    <label>Current Loan Balance Excluding Deposit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Linked_Loan__c/fields/Current_Loan_Record__c.field-meta.xml
<CustomField>
    <fullName>Current_Loan_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Loan Record</label>
    <referenceTo>loan__Loan_Account__c</referenceTo>
    <relationshipLabel>Linked Loans</relationshipLabel>
    <relationshipName>Current_Loans_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Linked_Loan__c/fields/Linked_Loan__c.field-meta.xml
<CustomField>
    <fullName>Linked_Loan__c</fullName>
    <label>Linked Loan</label>
    <referenceTo>loan__Loan_Account__c</referenceTo>
    <relationshipLabel>Linked Loans (Linked Loan)</relationshipLabel>
    <relationshipName>Linked_Loans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Linked_Loan__c/fields/Linked_Loan_Status__c.field-meta.xml
<CustomField>
    <fullName>Linked_Loan_Status__c</fullName>
    <formula>TEXT( Linked_Loan__r.loan__Loan_Status__c )</formula>
    <label>Linked Loan Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <customHelpPage>loan__CLContractHelp</customHelpPage>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Account__c/fields/Current_Loan_Balance_Excluding_Deposit__c.field-meta.xml
<CustomField>
    <fullName>Current_Loan_Balance_Excluding_Deposit__c</fullName>
    <formula>loan__Loan_Balance__c- Deposit_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Current Loan Balance Excluding Deposit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Financier_Linked_Loans__c.field-meta.xml
<CustomField>
    <fullName>Financier_Linked_Loans__c</fullName>
    <label>Financier Linked Loans</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Linked_Loans__c.field-meta.xml
<CustomField>
    <fullName>Linked_Loans__c</fullName>
    <label>Linked Loans</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Total_Sum_of_Financier_Exposure__c.field-meta.xml
<CustomField>
    <fullName>Total_Sum_of_Financier_Exposure__c</fullName>
    <label>Total Sum of Financier Exposure</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Total_Sum_Of_Linked_Loans__c.field-meta.xml
<CustomField>
    <fullName>Total_Sum_Of_Linked_Loans__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Sum Of Linked Loans</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

elixir/force-app/main/default/objects/loan__Loan_Account__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>CL Contracts</relationshipLabel>
    <relationshipName>CL_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/LinkedLoanRelatedLoanController.cls
/****************************************************************************************************
Company: Cloudkaptan Consultancy Services Pvt. Ltd.
Author: Ariz Mazhary
Description : This is the controller class of linkedLoansPage.This class shows detail of Linked Loans 
			related to Loan and delete the linked loan when Del button is clicked.
Development Date : 6/05/2021
Last Modified Date : 19/05/2021
****************************************************************************************************/
public with sharing class LinkedLoanRelatedLoanController {

    public loan__Loan_Account__c acct {get;set;}
    public String linkedLoanId {get; set;}
    
    public LinkedLoanRelatedLoanController(ApexPages.StandardController stdController){
        acct = [SELECT id,
                      Name 
                  FROM loan__Loan_Account__c 
                  WHERE id = :ApexPages.currentPage().getParameters().get(ConstantValues.LOAN_ID)];
    }
    //This method returns the Linked Loan Details related to CL Contract.
    public List<Linked_Loan__c> getLinkedLoanList(){
        List<Linked_Loan__c> linkedLoanList =[SELECT id,
                                                    Linked_Loan__c,
                                                    Current_Loan_Record__c,
                                                    Current_Loan_Record__r.Name,
                                                    Linked_Loan__r.Name,
                                                    Current_Loan_Balance_Excluding_Deposit__c,
                                                    Linked_Loan_Status__c,
                                                    Linked_Loan__r.Warehouse__c 
                                                FROM Linked_Loan__c 
                                                WHERE Current_Loan_Record__c=:acct.id];
        return linkedLoanList;
    }

    //This method delete the selected Linked Loan 
    public PageReference deleteLinkedLoan(){
        try{
        List<Id> loanIdList=new List<Id>();
        List<Linked_Loan__c> linkedLoan1List=new List<Linked_Loan__c>();
        List<Linked_Loan__c> linkedLoan2List=new List<Linked_Loan__c>();
        if(linkedLoanId!=null){
            linkedLoan1List = [SELECT id,
                                Linked_Loan__c,
                                Linked_Loan__r.Name,
                                Current_Loan_Balance_Excluding_Deposit__c,
                                Current_Loan_Record__r.Name,
                                Current_Loan_Record__c
                            FROM Linked_Loan__c 
                            WHERE id =: linkedLoanId LIMIT 1];
        }
        if(linkedLoan1List.size()>0){                               
            linkedLoan2List = [SELECT id,
                                Linked_Loan__c,
                                Linked_Loan__r.Name,
                                Current_Loan_Balance_Excluding_Deposit__c,
                                Current_Loan_Record__r.Name,
                                Current_Loan_Record__c
                            FROM Linked_Loan__c 
                            WHERE Linked_Loan__c =: linkedLoan1List[0].Current_Loan_Record__c 
                            AND Current_Loan_Record__c =:linkedLoan1List[0].Linked_Loan__c LIMIT 1];   
        }
        
        loanIdList.add(linkedLoan1List[0].Current_Loan_Record__c);
        loanIdList.add(linkedLoan1List[0].Linked_Loan__c);
        if(linkedLoan1List.size()>0){
            database.delete(linkedLoan1List,false);
        }
        if(linkedLoan2List.size()>0){
            database.delete(linkedLoan2List,false);
        }

        updateLoanAccount(loanIdList);

        PageReference tempPage = ApexPages.currentPage();            
        tempPage.setRedirect(true);
        return tempPage;

        }catch(Exception exe){
            insert new clcommon__Log__c(
                clcommon__Message__c = 'LinkedLoanRelatedLoanController :Exception: '+exe.getStackTraceString()+'error='+exe.getMessage()+' at Line Number '+exe.getLineNumber(),
                clcommon__Time__c = System.Now());
            return null;
        }
        
    }
    //This method add the Linked Loans Name on Linked Loans field and update Total sum of Linked Loan on the CL Contract.
    public static void updateLoanAccount(List<Id> loanIdList){

        try{
            List<loan__Loan_Account__c> loanList=new List<loan__Loan_Account__c>();
            List<Linked_Loan__c> linkedLoanList1=new List<Linked_Loan__c>();
            List<String> loanNameList=new List<String>();
            List<String> loanFinancierList=new List<String>();
            if(loanIdList.size()>0){
                loanList=[SELECT Name,
                                Total_Sum_Of_Linked_Loans__c,
                                Current_Loan_Balance_Excluding_Deposit__c,
                                Linked_Loans__c,
                                Financier_Linked_Loans__c,
                                Warehouse__c,
                                Total_Sum_of_Financier_Exposure__c 
                            FROM loan__Loan_Account__c 
                            WHERE id in: loanIdList ];
                linkedLoanList1 =[SELECT id,
                                        Linked_Loan__r.id,
                                        Linked_Loan__r.Name,
                                        Current_Loan_Record__r.Name,
                                        Current_Loan_Record__c,
                                        Current_Loan_Balance_Excluding_Deposit__c,
                                        Linked_Loan__r.Warehouse__c  
                                    FROM Linked_Loan__c 
                                    WHERE Current_Loan_Record__c IN: loanIdList
                                    ORDER BY Linked_Loan__r.Name ASC];
            }
            
            for(loan__Loan_Account__c loan1: loanList){
                loan1.Linked_Loans__c=null;
                loan1.Total_Sum_Of_Linked_Loans__c=0;
                loan1.Financier_Linked_Loans__c=null;
                loan1.Total_Sum_of_Financier_Exposure__c=0;
                for(Linked_Loan__c linkedLoan : linkedLoanList1){
                    if((loan1.id==linkedLoan.Current_Loan_Record__c)){
                        if(loan1.Total_Sum_Of_Linked_Loans__c==0 && linkedLoan.Current_Loan_Balance_Excluding_Deposit__c!=null){
                            loan1.Total_Sum_Of_Linked_Loans__c=loan1.Current_Loan_Balance_Excluding_Deposit__c;
                        }
                        if(loan1.Total_Sum_Of_Linked_Loans__c!=null && linkedLoan.Current_Loan_Balance_Excluding_Deposit__c!=null){
                            loan1.Total_Sum_Of_Linked_Loans__c = loan1.Total_Sum_Of_Linked_Loans__c
                                                                +linkedLoan.Current_Loan_Balance_Excluding_Deposit__c;
                        }
                        if(loan1.Linked_Loans__c==null){
                            loan1.Linked_Loans__c=loan1.Name;
                        }
                        if(loan1.Linked_Loans__c!=null && linkedLoan.Linked_Loan__r.Name!=null){
                            loan1.Linked_Loans__c = loan1.Linked_Loans__c
                                                +ConstantValues.SEMICOLON+linkedLoan.Linked_Loan__r.Name;
                        }
                        if(loan1.Financier_Linked_Loans__c==null){
                            loan1.Financier_Linked_Loans__c=loan1.Name;
                        }
                        if(loan1.Financier_Linked_Loans__c != null && linkedLoan.Linked_Loan__r.Name!=null 
                            && linkedLoan.Linked_Loan__r.Warehouse__c==loan1.Warehouse__c){
                            loan1.Financier_Linked_Loans__c = loan1.Financier_Linked_Loans__c
                                + ConstantValues.SEMICOLON+linkedLoan.Linked_Loan__r.Name;
                        }
                        if(loan1.Total_Sum_of_Financier_Exposure__c==0 && loan1.Current_Loan_Balance_Excluding_Deposit__c!=null){
                            loan1.Total_Sum_of_Financier_Exposure__c=loan1.Current_Loan_Balance_Excluding_Deposit__c;
                        }
                        if(loan1.Total_Sum_of_Financier_Exposure__c!=null && linkedLoan.Current_Loan_Balance_Excluding_Deposit__c!=null
                            && linkedLoan.Linked_Loan__r.Warehouse__c==loan1.Warehouse__c){
                            loan1.Total_Sum_of_Financier_Exposure__c = loan1.Total_Sum_of_Financier_Exposure__c
                                                                +linkedLoan.Current_Loan_Balance_Excluding_Deposit__c;
                        }
                    }
                    
                }
                //Sort the Linked Loans in Ascending order 
                if(loan1.Linked_Loans__c!=null){
                    loanNameList=loan1.Linked_Loans__c.split(';');
                    loanNameList.sort();
                    loan1.Linked_Loans__c=null;
                    for(String loanName:loanNameList){
                        if(loan1.Linked_Loans__c==null){
                            loan1.Linked_Loans__c = loanName;
                        }else{
                            loan1.Linked_Loans__c = loan1.Linked_Loans__c
                                            +ConstantValues.SEMICOLON+loanName;
                        }
                    }
                }
                //Sort the Financier Linked Loans in Ascending Order.
                if(loan1.Financier_Linked_Loans__c!=null){
                    loanFinancierList=loan1.Financier_Linked_Loans__c.split(';');
                    loanFinancierList.sort();
                    loan1.Financier_Linked_Loans__c=null;
                    for(String loanFinancier:loanFinancierList){
                        if(loan1.Financier_Linked_Loans__c==null){
                            loan1.Financier_Linked_Loans__c = loanFinancier;
                        }else{
                            loan1.Financier_Linked_Loans__c = loan1.Financier_Linked_Loans__c
                                            +ConstantValues.SEMICOLON+loanFinancier;
                        }
                    }
                }
            }
            
            if(loanList.size()>0){
                database.update(loanList,false);
            }
        }catch(Exception exe){
            insert new clcommon__Log__c(
                clcommon__Message__c = 'LinkedLoanRelatedLoanController :Exception: '+exe.getStackTraceString()
                                        +'error='+exe.getMessage()+' at Line Number '+exe.getLineNumber(),
                clcommon__Time__c = System.Now());
        }
    }

}