force-app/main/default/objects/Linked_Loan__c/Linked_Loan__c.object-meta.xml
<CustomObject>
    <label>Linked Loan</label>
    <nameField>
        <displayFormat>LLJunction-{0000}</displayFormat>
        <label>Linked Loan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Linked Loans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Linked_Loan__c/fields/Current_Loan_Balance_Excluding_Deposit__c.field-meta.xml
<CustomField>
    <fullName>Current_Loan_Balance_Excluding_Deposit__c</fullName>
    <formula>Linked_Loan__r.Current_Loan_Balance_Excluding_Deposit__c</formula>
    <label>Current Loan Balance Excluding Deposit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Linked_Loan__c/fields/Current_Loan_Record__c.field-meta.xml
<CustomField>
    <fullName>Current_Loan_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Loan Record</label>
    <referenceTo>loan__Loan_Account__c</referenceTo>
    <relationshipLabel>Linked Loans</relationshipLabel>
    <relationshipName>Current_Loans_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Linked_Loan__c/fields/Linked_Loan__c.field-meta.xml
<CustomField>
    <fullName>Linked_Loan__c</fullName>
    <label>Linked Loan</label>
    <referenceTo>loan__Loan_Account__c</referenceTo>
    <relationshipLabel>Linked Loans (Linked Loan)</relationshipLabel>
    <relationshipName>Linked_Loans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Linked_Loan__c/fields/Linked_Loan_Status__c.field-meta.xml
<CustomField>
    <fullName>Linked_Loan_Status__c</fullName>
    <formula>TEXT( Linked_Loan__r.loan__Loan_Status__c )</formula>
    <label>Linked Loan Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <customHelpPage>loan__CLContractHelp</customHelpPage>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Account__c/fields/Current_Loan_Balance_Excluding_Deposit__c.field-meta.xml
<CustomField>
    <fullName>Current_Loan_Balance_Excluding_Deposit__c</fullName>
    <formula>loan__Loan_Balance__c- Deposit_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Current Loan Balance Excluding Deposit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Linked_Loans__c.field-meta.xml
<CustomField>
    <fullName>Linked_Loans__c</fullName>
    <label>Linked Loans</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Total_Amount_Borrowed__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Borrowed__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Sum Of Linked Loans</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/LinkedLoanDetails.cls
/****************************************************************************************************
Company: Cloudkaptan Consultancy Services Pvt. Ltd.
Author: Ariz Mazhary
Description : This is the controller class of linkedLoan1sPage.This class the detail of Linked Loans
                    and delete the linked loan.
Development Date : 
Last Modified Date : 
****************************************************************************************************/
public with sharing class LinkedLoanDetails {

    public loan__Loan_Account__c acct {get;set;}
    public class MyException extends Exception {}
    public String llId {get; set;}
    public List<Linked_Loan__c> linkedLoanList { get; set; }
    public LinkedLoanDetails(ApexPages.StandardController stdController){
        acct = [SELECT id,
                      name 
                  FROM loan__Loan_Account__c 
                  WHERE id = :ApexPages.currentPage().getParameters().get('id')];

        linkedLoanList =[SELECT id,
                               Linked_Loan__c,
                               Current_Loan_Record__c,
                               Current_Loan_Record__r.Name,
                               Linked_Loan__r.Name,
                               Current_Loan_Balance_Excluding_Deposit__c,
                               Linked_Loan_Status__c 
                         FROM Linked_Loan__c 
                         WHERE Current_Loan_Record__c=: ApexPages.currentPage().getParameters().get('id') ];       
    }
    //Delete the Linked Loan and add the Linked Loans Name on the CL Contract field Linked Loans.
    public PageReference deleteRecord(){
        try{
        Linked_Loan__c linkedLoan1 = [SELECT id,
                                           Linked_Loan__c,
                                           Linked_Loan__r.Name,
                                           Current_Loan_Balance_Excluding_Deposit__c,
                                           Current_Loan_Record__r.Name,
                                           Current_Loan_Record__c
                                       FROM Linked_Loan__c 
                                       WHERE id =: llId limit 1];
                                        
        Linked_Loan__c linkedLoan2 = [SELECT id,
                                           Linked_Loan__c,
                                           Linked_Loan__r.Name,
                                           Current_Loan_Balance_Excluding_Deposit__c,
                                           Current_Loan_Record__r.Name,
                                           Current_Loan_Record__c
                                       FROM Linked_Loan__c 
                                       WHERE Linked_Loan__c =: linkedLoan1.Current_Loan_Record__c 
                                       AND Current_Loan_Record__c =:linkedLoan1.Linked_Loan__c limit 1];   
                                       
        
        if(linkedLoan1 != null){
            delete linkedLoan1;
        }
        if(linkedLoan2 != null){
            delete linkedLoan2;
        }

        List<Linked_Loan__c> linkedLoanList1 =[SELECT id,
                                                    Linked_Loan__r.id,
                                                    Linked_Loan__r.Name,
                                                    Current_Loan_Record__r.Name,
                                                    Current_Loan_Record__c,
                                                    Current_Loan_Balance_Excluding_Deposit__c 
                                                FROM Linked_Loan__c 
                                                WHERE Current_Loan_Record__c=: linkedLoan1.Current_Loan_Record__c
                                                OR Current_Loan_Record__c=: linkedLoan2.Current_Loan_Record__c 
                                                ORDER BY Linked_Loan__r.Name ASC];

        List<Id> loanIdList=new List<Id>();
        loanIdList.add(ApexPages.currentPage().getParameters().get('id'));
        loanIdList.add(linkedLoan1.Linked_Loan__c);
        
        List<loan__Loan_Account__c> loanList1=[SELECT Name,
                                            Total_Amount_Borrowed__c,
                                            Current_Loan_Balance_Excluding_Deposit__c,
                                            Linked_Loans__c 
                                        FROM loan__Loan_Account__c 
                                        WHERE id in: loanIdList ];
        
        for(loan__Loan_Account__c loan1: loanList1){
            List<String> LoanList=new List<String>();
            LoanList.add(loan1.Name); 
            
            loan1.Total_Amount_Borrowed__c=loan1.Current_Loan_Balance_Excluding_Deposit__c;
            for(Linked_Loan__c lla : linkedLoanList1){
                if((loan1.id==lla.Current_Loan_Record__c)){
                    if(loan1.Total_Amount_Borrowed__c==null){
                        loan1.Total_Amount_Borrowed__c=lla.Current_Loan_Balance_Excluding_Deposit__c;
                    }else{
                        loan1.Total_Amount_Borrowed__c=loan1.Total_Amount_Borrowed__c+lla.Current_Loan_Balance_Excluding_Deposit__c;
                    }
                    if(!LoanList.contains(lla.Linked_Loan__r.Name)){
                        LoanList.add(lla.Linked_Loan__r.Name);
                    }
                }
                
            }
            LoanList.sort();
            Loan1.Linked_Loans__c=null;
            Integer check=0;
            for(String loan2:LoanList){
                if(Loan1.Linked_Loans__c==null){
                    Loan1.Linked_Loans__c=loan2;
                }else{
                    loan1.Linked_Loans__c=loan1.Linked_Loans__c+';'+loan2;
                }
                check=check+1;
            }
            if(check==1){
                loan1.Linked_Loans__c=null;
                loan1.Total_Amount_Borrowed__c=0;
            }    
                
        }

        if(loanList1.size()>0){
            database.update(loanList1,false);
        }

        PageReference tempPage = ApexPages.currentPage();            
        tempPage.setRedirect(true);
        return tempPage;
        }catch(Exception e){
            insert new clcommon__Log__c(
                clcommon__Message__c = 'linkedLoan1Details :Exception: '+e.getStackTraceString()+'error='+e.getMessage()+' at Line Number '+e.getLineNumber(),
                clcommon__Time__c = System.Now());
            return null;
        }
        
    }

}