force-app/main/default/objects/Linked_Loan__c/Linked_Loan__c.object-meta.xml
<CustomObject>
    <label>Linked Loan</label>
    <nameField>
        <displayFormat>LLJunction-{0000}</displayFormat>
        <label>Linked Loan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Linked Loans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Linked_Loan__c/fields/Current_Loan_Balance_Excluding_Deposit__c.field-meta.xml
<CustomField>
    <fullName>Current_Loan_Balance_Excluding_Deposit__c</fullName>
    <formula>Linked_Loan__r.Current_Loan_Balance_Excluding_Deposit__c</formula>
    <label>Current Loan Balance Excluding Deposit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Linked_Loan__c/fields/Current_Loan_Record__c.field-meta.xml
<CustomField>
    <fullName>Current_Loan_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Loan Record</label>
    <referenceTo>loan__Loan_Account__c</referenceTo>
    <relationshipLabel>Linked Loans</relationshipLabel>
    <relationshipName>Current_Loans_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Linked_Loan__c/fields/Linked_Loan__c.field-meta.xml
<CustomField>
    <fullName>Linked_Loan__c</fullName>
    <label>Linked Loan</label>
    <referenceTo>loan__Loan_Account__c</referenceTo>
    <relationshipLabel>Linked Loans (Linked Loan)</relationshipLabel>
    <relationshipName>Linked_Loans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <customHelpPage>loan__CLContractHelp</customHelpPage>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Account__c/fields/Current_Loan_Balance_Excluding_Deposit__c.field-meta.xml
<CustomField>
    <fullName>Current_Loan_Balance_Excluding_Deposit__c</fullName>
    <formula>loan__Loan_Balance__c- Deposit_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Current Loan Balance Excluding Deposit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Financier_Linked_Loans__c.field-meta.xml
<CustomField>
    <fullName>Financier_Linked_Loans__c</fullName>
    <label>Financier Linked Loans</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Linked_Loans__c.field-meta.xml
<CustomField>
    <fullName>Linked_Loans__c</fullName>
    <label>Linked Loans</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Loan_Status__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Status__c</fullName>
    <inlineHelpText>Status of the Account expected values are :
Pending Approval
Active - Good Standing
Active - Bad Standing
Active - Matured
Approved
Canceled
Closed - Obligations met
Closed- Written Off
Closed - Refinanced
Partial Application
Closed - Premature</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active - Bad Standing</fullName>
            </value>
            <value>
                <fullName>Active - Good Standing</fullName>
            </value>
            <value>
                <fullName>Active - Marked for Closure</fullName>
            </value>
            <value>
                <fullName>Active - Matured</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Closed - Obligations met</fullName>
            </value>
            <value>
                <fullName>Closed - Premature</fullName>
            </value>
            <value>
                <fullName>Closed - Refinanced</fullName>
            </value>
            <value>
                <fullName>Closed- Written Off</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>Partial Application</fullName>
                <default>true</default>
                <label>Partial Application</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Premature Closure Initiated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Total_Sum_of_Financier_Exposure__c.field-meta.xml
<CustomField>
    <fullName>Total_Sum_of_Financier_Exposure__c</fullName>
    <label>Total Sum of Financier Exposure</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Total_Sum_Of_Linked_Loans__c.field-meta.xml
<CustomField>
    <fullName>Total_Sum_Of_Linked_Loans__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Sum Of Linked Loans</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

elixir/force-app/main/default/objects/loan__Loan_Account__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>CL Contracts</relationshipLabel>
    <relationshipName>CL_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TotalSumOfLinkedLoanUpdateBatch.cls
/****************************************************************************************************
Company: Cloudkaptan Consultancy Services Pvt. Ltd.
Author: Ariz Mazhary
Description : This class updates the Total Sum of Linked Loan in CL Contract whenever this batch job runs.
Development Date : 19/05/2021
Last Modified Date : 20/05/2021
****************************************************************************************************/

public class TotalSumOfLinkedLoanUpdateBatch implements DataBase.StateFul,DataBase.Batchable<sObject>,Schedulable {
    //Query all Cl Contract  
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([SELECT id,
                                               Name,
                                               Linked_Loans__c,
                                               Current_Loan_Balance_Excluding_Deposit__c,
                                               Total_Sum_Of_Linked_Loans__c,
                                               Total_Sum_of_Financier_Exposure__c,
                                               Warehouse__c,
                                               loan__Loan_Status__c,
                                               Financier_Linked_Loans__c
                                           FROM loan__Loan_Account__c
                                           WHERE Current_Loan_Balance_Excluding_Deposit__c!= null]);
    }
    //This method updates Total Sum of Linked Loan in CL Contract.
    public void execute(Database.BatchableContext bc, List<loan__Loan_Account__c> objLoanList) {
        try{
            List<Linked_Loan__c> objLinkedLoanList = new List<Linked_Loan__c>();
            List<String> loanFinancierList=new List<String>();
            List<String> loanNameList=new List<String>();

            if(objLoanList.size()>0){
                objLinkedLoanList =[SELECT id,
                                       Linked_Loan__r.Name,
                                       Current_Loan_Record__c,
                                       Current_Loan_Balance_Excluding_Deposit__c,
                                       Linked_Loan__r.Warehouse__c,
                                       Linked_Loan__r.Id 
                                   FROM Linked_Loan__c 
                                   WHERE Current_Loan_Record__c IN: objLoanList
                                   AND Current_Loan_Balance_Excluding_Deposit__c!=null];
                List<Id> loanId=new List<Id>();
                List<String> loanStatusList=System.label.loanStatus.split(',');
                for(loan__Loan_Account__c loanAccount:objLoanList){
                    if(loanStatusList.contains(loanAccount.loan__Loan_Status__c)){
                        loanId.add(loanAccount.id);
                    }
                }
                if(loanId.size()>0){
                    deleteLinkage(loanId);
                }
            
                for(loan__Loan_Account__c loanAccount:objLoanList){
                    loanAccount.Total_Sum_Of_Linked_Loans__c=0;
                    loanAccount.Total_Sum_of_Financier_Exposure__c=0;
                    loanAccount.Financier_Linked_Loans__c=null;
                    loanAccount.Linked_Loans__c=null;
                    if(!loanStatusList.contains(loanAccount.loan__Loan_Status__c)){
                        for(Linked_Loan__c linkedLoan : objLinkedLoanList){
                            if(linkedLoan.Current_Loan_Record__c==loanAccount.id  && !loanId.contains(linkedLoan.Linked_Loan__r.Id)){
                                if(loanAccount.Total_Sum_Of_Linked_Loans__c==0){
                                    loanAccount.Total_Sum_Of_Linked_Loans__c=loanAccount.Current_Loan_Balance_Excluding_Deposit__c;
                                }
                                if(loanAccount.Total_Sum_Of_Linked_Loans__c!=NULL){
                                    loanAccount.Total_Sum_Of_Linked_Loans__c = loanAccount.Total_Sum_Of_Linked_Loans__c 
                                                                                + linkedLoan.Current_Loan_Balance_Excluding_Deposit__c;
                                }
                                if(loanAccount.Linked_Loans__c==null){
                                    loanAccount.Linked_Loans__c=loanAccount.Name;
                                }
                                if(loanAccount.Linked_Loans__c!=null && linkedLoan.Linked_Loan__r.Name!=null){
                                    loanAccount.Linked_Loans__c = loanAccount.Linked_Loans__c
                                                        +ConstantValues.SEMICOLON+linkedLoan.Linked_Loan__r.Name;
                                }
                                if(loanAccount.Total_Sum_of_Financier_Exposure__c==0 && loanAccount.Current_Loan_Balance_Excluding_Deposit__c!=null){
                                    loanAccount.Total_Sum_of_Financier_Exposure__c=loanAccount.Current_Loan_Balance_Excluding_Deposit__c;
                                }
                                if(loanAccount.Total_Sum_of_Financier_Exposure__c!=null && linkedLoan.Current_Loan_Balance_Excluding_Deposit__c!=null
                                    && linkedLoan.Linked_Loan__r.Warehouse__c==loanAccount.Warehouse__c){
                                    loanAccount.Total_Sum_of_Financier_Exposure__c = loanAccount.Total_Sum_of_Financier_Exposure__c
                                                                        +linkedLoan.Current_Loan_Balance_Excluding_Deposit__c;
                                }
                                if(loanAccount.Financier_Linked_Loans__c==null){
                                    loanAccount.Financier_Linked_Loans__c=loanAccount.Name;
                                }
                                if(loanAccount.Financier_Linked_Loans__c != null && linkedLoan.Linked_Loan__r.Name!=null 
                                    && linkedLoan.Linked_Loan__r.Warehouse__c==loanAccount.Warehouse__c){
                                    loanAccount.Financier_Linked_Loans__c = loanAccount.Financier_Linked_Loans__c
                                        + ConstantValues.SEMICOLON+linkedLoan.Linked_Loan__r.Name;
                                }
                            }
                        }
                        //Sort the Linked Loans in Ascending order 
                        if(loanAccount.Linked_Loans__c!=null){
                            loanNameList=loanAccount.Linked_Loans__c.split(';');
                            loanNameList.sort();
                            loanAccount.Linked_Loans__c=null;
                            for(String loanName:loanNameList){
                                if(loanAccount.Linked_Loans__c==null){
                                    loanAccount.Linked_Loans__c = loanName;
                                }else{
                                    loanAccount.Linked_Loans__c = loanAccount.Linked_Loans__c
                                                    +ConstantValues.SEMICOLON+loanName;
                                }
                            }
                        }
                        //Sort the Financier Linked Loans in Ascending Order.
                        if(loanAccount.Financier_Linked_Loans__c!=null){
                            loanFinancierList=loanAccount.Financier_Linked_Loans__c.split(';');
                            loanFinancierList.sort();
                            loanAccount.Financier_Linked_Loans__c=null;
                            for(String loanFinancier:loanFinancierList){
                                if(loanAccount.Financier_Linked_Loans__c==null){
                                    loanAccount.Financier_Linked_Loans__c = loanFinancier;
                                }else{
                                    loanAccount.Financier_Linked_Loans__c = loanAccount.Financier_Linked_Loans__c
                                                    +ConstantValues.SEMICOLON+loanFinancier;
                                }
                            }
                        }
                    }
                }
            }
            if(objLoanList.size()>0){
                Database.update(objLoanList,false);
            }
        }catch(Exception exe){
            insert new clcommon__Batch_Process_Log__c(
                clcommon__Message__c = 'TotalSumOfLinkedLoanUpdateBatch :Exception: '+exe.getStackTraceString()
                                        +'error='+exe.getMessage()+' at Line Number '+exe.getLineNumber(),
                clcommon__Timestamp__c = System.Now());
        }
    }
    public static void deleteLinkage(List<Id> loanId){
        List<Linked_Loan__c> linkedLoan=new List<Linked_Loan__c>();
        linkedLoan=[SELECT id,
                        Linked_Loan__c,
                        Current_Loan_Record__c 
                    FROM Linked_Loan__c 
                    WHERE Linked_Loan__c=:loanId 
                    OR Current_Loan_Record__c=:loanId];
        if(linkedLoan.size()>0){
            Database.delete(linkedLoan,false);
        }
    }
    public void execute(SchedulableContext sc) {
        TotalSumOfLinkedLoanUpdateBatch obj = new TotalSumOfLinkedLoanUpdateBatch();
        Integer size = Integer.valueof(System.label.TotalSumOfLinkedLoanUpdateBatch_Size);  
        database.executebatch(obj,size);
    }
    public void finish(Database.BatchableContext bc){
    }

}