force-app/main/default/objects/Linked_Loan__c/Linked_Loan__c.object-meta.xml
<CustomObject>
    <label>Linked Loan</label>
    <nameField>
        <displayFormat>LLJunction-{0000}</displayFormat>
        <label>Linked Loan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Linked Loans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Linked_Loan__c/fields/Current_Loan_Balance_Excluding_Deposit__c.field-meta.xml
<CustomField>
    <fullName>Current_Loan_Balance_Excluding_Deposit__c</fullName>
    <formula>Linked_Loan__r.Current_Loan_Balance_Excluding_Deposit__c</formula>
    <label>Current Loan Balance Excluding Deposit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Linked_Loan__c/fields/Current_Loan_Record__c.field-meta.xml
<CustomField>
    <fullName>Current_Loan_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Loan Record</label>
    <referenceTo>loan__Loan_Account__c</referenceTo>
    <relationshipLabel>Linked Loans</relationshipLabel>
    <relationshipName>Current_Loans_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Linked_Loan__c/fields/Linked_Loan__c.field-meta.xml
<CustomField>
    <fullName>Linked_Loan__c</fullName>
    <label>Linked Loan</label>
    <referenceTo>loan__Loan_Account__c</referenceTo>
    <relationshipLabel>Linked Loans (Linked Loan)</relationshipLabel>
    <relationshipName>Linked_Loans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <customHelpPage>loan__CLContractHelp</customHelpPage>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Account__c/fields/Current_Loan_Balance_Excluding_Deposit__c.field-meta.xml
<CustomField>
    <fullName>Current_Loan_Balance_Excluding_Deposit__c</fullName>
    <formula>loan__Loan_Balance__c- Deposit_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Current Loan Balance Excluding Deposit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Linked_Loans__c.field-meta.xml
<CustomField>
    <fullName>Linked_Loans__c</fullName>
    <label>Linked Loans</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Total_Amount_Borrowed__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Borrowed__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Sum Of Linked Loans</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/UpdateSumOfLinkedLoanBatch.cls
/****************************************************************************************************
Company: Cloudkaptan Consultancy Services Pvt. Ltd.
Author: Ariz Mazhary
Description : This class updates the Total Sum of Linked Loan in Contract whenever this batch job runs.
Development Date : 19/05/2021
Last Modified Date : 20/05/2021
****************************************************************************************************/

public class UpdateSumOfLinkedLoanBatch implements DataBase.StateFul,DataBase.Batchable<sObject>,Schedulable { 
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([SELECT id,
                                                Name,
                                                Linked_Loans__c,
                                                Current_Loan_Balance_Excluding_Deposit__c,
                                                Total_Amount_Borrowed__c 
                                            FROM loan__Loan_Account__c ]);
    }
    public void execute(Database.BatchableContext bc, List<loan__Loan_Account__c> scope) {
        try{
            List<Linked_Loan__c> linkedLoanList = new List<Linked_Loan__c>();
            if(scope.size()>0){
                linkedLoanList =[SELECT id,
                                        Linked_Loan__r.Name,
                                        Current_Loan_Record__c,
                                        Current_Loan_Balance_Excluding_Deposit__c 
                                    FROM Linked_Loan__c 
                                    WHERE Current_Loan_Record__c IN: scope];
            
                for(loan__Loan_Account__c loan1:scope){
                    if(linkedLoanList.size()>0){
                        loan1.Total_Amount_Borrowed__c=loan1.Current_Loan_Balance_Excluding_Deposit__c;
                        for(Linked_Loan__c lla : linkedLoanList){
                            if(lla.Current_Loan_Record__c==loan1.id){
                                if(loan1.Total_Amount_Borrowed__c==NULL){
                                    loan1.Total_Amount_Borrowed__c=lla.Current_Loan_Balance_Excluding_Deposit__c;
                                }else{
                                    loan1.Total_Amount_Borrowed__c=loan1.Total_Amount_Borrowed__c + lla.Current_Loan_Balance_Excluding_Deposit__c;
                                }
                            }
                        }
                    }
                }
            }
            if(scope.size()>0){
                Database.update(scope,false);
            }
        }catch(Exception exe){
            insert new clcommon__Log__c(
                clcommon__Message__c = 'UpdateSumOfLinkedLoanBatch :Exception: '+exe.getStackTraceString()+'error='+exe.getMessage()+' at Line Number '+exe.getLineNumber(),
                clcommon__Time__c = System.Now());
        }
    }
    public void execute(SchedulableContext sc) {
        UpdateSumOfLinkedLoanBatch usl = new UpdateSumOfLinkedLoanBatch();
        Integer size = 10000;  
        database.executebatch(usl,size);
    }
    public void finish(Database.BatchableContext bc){
    }
}