force-app/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <customHelpPage>loan__CLContractHelp</customHelpPage>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Account__c/fields/Current_Loan_Balance_Excluding_Deposit__c.field-meta.xml
<CustomField>
    <fullName>Current_Loan_Balance_Excluding_Deposit__c</fullName>
    <formula>loan__Loan_Balance__c- Deposit_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Current Loan Balance Excluding Deposit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Please choose a account, which will be associated as a customer on this lending account.
You can create a new account, from the lookup window by clicking on new or select the existing account from the lookup.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Loan_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Delinquent_Amount__c.field-meta.xml
<CustomField>
    <fullName>loan__Delinquent_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Total Unpaid bills/invoices amount on this account.</inlineHelpText>
    <label>Delinquent Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

elixir/force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Disbursal_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Disbursal_Date__c</fullName>
    <description>Contract Date on the Loan account, this will be updated at the time of funding with the Expected Disbursal Date.</description>
    <inlineHelpText>Contract date on the loan. This will be updated at the time of funding with the expected disbursal date.</inlineHelpText>
    <label>Contract Date</label>
    <type>Date</type>
</CustomField>

elixir/force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>loan__Interest_Rate__c</fullName>
    <description>Interest Rate</description>
    <inlineHelpText>Rate of Interest for the loan.</inlineHelpText>
    <label>Current Interest Rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Loan Amount</description>
    <inlineHelpText>This is the financed amount on the contract which will be disbursed to the customer.</inlineHelpText>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Loan_Status__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Status__c</fullName>
    <inlineHelpText>Status of the Account expected values are :
Pending Approval
Active - Good Standing
Active - Bad Standing
Active - Matured
Approved
Canceled
Closed - Obligations met
Closed- Written Off
Closed - Refinanced
Partial Application
Closed - Premature</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active - Bad Standing</fullName>
            </value>
            <value>
                <fullName>Active - Good Standing</fullName>
            </value>
            <value>
                <fullName>Active - Marked for Closure</fullName>
            </value>
            <value>
                <fullName>Active - Matured</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Closed - Obligations met</fullName>
            </value>
            <value>
                <fullName>Closed - Premature</fullName>
            </value>
            <value>
                <fullName>Closed - Refinanced</fullName>
            </value>
            <value>
                <fullName>Closed- Written Off</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>Partial Application</fullName>
                <default>true</default>
                <label>Partial Application</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Premature Closure Initiated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

elixir/force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Maturity_Date_Current__c.field-meta.xml
<CustomField>
    <fullName>loan__Maturity_Date_Current__c</fullName>
    <inlineHelpText>This is the date on which the the loan matures</inlineHelpText>
    <label>Current Maturity Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Pmt_Amt_Cur__c.field-meta.xml
<CustomField>
    <fullName>loan__Pmt_Amt_Cur__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Current Payment Amount</description>
    <inlineHelpText>This is the current installment amount that needs to be paid.</inlineHelpText>
    <label>Current Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Remaining_IO_Period__c.field-meta.xml
<CustomField>
    <fullName>Remaining_IO_Period__c</fullName>
    <label>Remaining IO Period</label>
    <summaryFilterItems>
        <field>loan__Repayment_Schedule__c.loan__Is_Archived__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>loan__Repayment_Schedule__c.loan__Due_Principal__c</field>
        <operation>equals</operation>
        <value>0</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>loan__Repayment_Schedule__c.loan__Is_Billed__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryForeignKey>loan__Repayment_Schedule__c.loan__Loan_Account__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Restrict_Redraw__c.field-meta.xml
<CustomField>
    <fullName>Restrict_Redraw__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Restrict Redraw</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Redraw_Request__c/Redraw_Request__c.object-meta.xml
<CustomObject>
    <label>Redraw Request</label>
    <nameField>
        <displayFormat>RDR-{000000}</displayFormat>
        <label>Redraw Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Redraw Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/ContentVersionTriggerTest.cls
/**
 * Created by Ethan Sargent on 30/08/2021.
 */

@IsTest
private class ContentVersionTriggerTest
{

    @TestSetup
    static void setup()
    {
        loan__Org_Parameters__c checkTrigger = new loan__Org_Parameters__c();
        checkTrigger.loan__Disable_Triggers__c = true;
        insert checkTrigger;
        RecordType personAccountType = [SELECT Id FROM RecordType WHERE IsPersonType = TRUE AND IsActive = TRUE];
        Account authorisedAccount = new Account(FirstName = 'Authorised', LastName = 'Person Account', RecordTypeId = personAccountType.Id);
        insert authorisedAccount;
        Map<Id, Account> personAccountsForContactIds = new Map<Id, Account>([SELECT Id, PersonContactId FROM Account]);
        authorisedAccount = personAccountsForContactIds.get(authorisedAccount.Id);

        loan__Loan_Account__c loanAccount = (loan__Loan_Account__c) JSON.deserialize('{"Name": "LAI-00000675", "Current_Loan_Balance_Excluding_Deposit__c": 0.00, "loan__Delinquent_Amount__c": 0.00, "loan__Loan_Status__c": "Closed - Obligations met", "loan__Loan_Amount__c": 300000.00, "loan__Disbursal_Date__c": "2020-05-26", "loan__Maturity_Date_Current__c": "2021-05-26", "loan__Interest_Rate__c": 4.5000, "loan__Next_Installment_Date__c": "2020-08-26", "loan__Pmt_Amt_Cur__c": 25618.42, "Remaining_IO_Period__c": 0, "Restrict_Redraw__c": false, "loan__Loan_Status__c": "Active - Good Standing"}', loan__Loan_Account__c.class);
        loanAccount.loan__Account__c = authorisedAccount.Id;
        loanAccount.loan__Disbursal_Date__c = Date.today();
        insert loanAccount;
    }

    @IsTest
    static void testCreateRedrawRequestAndLinkDocument()
    {
        // Arrange
        ContentVersion cv = new ContentVersion();
        cv.ContentLocation = 'S';
        cv.Title = 'Test ContentVersion';
        cv.PathOnClient = 'Test ContentVersion';
        cv.VersionData = Blob.valueOf('testData');
        cv.Loan_Account_fileupload__c = [SELECT Id FROM loan__Loan_Account__c].Id;


        // Act
        Test.startTest();
        insert cv;
        Test.stopTest();
        Id contentDocumentId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :cv.Id].ContentDocumentId;
        // Assert
        System.assertEquals(3, [SELECT Id FROM ContentDocumentLink WHERE ContentDocumentId = :contentDocumentId].size());
        System.assertEquals(1, [SELECT Id FROM Redraw_Request__c].size());
        System.assertEquals(1, [SELECT Id FROM ContentDocumentLink WHERE LinkedEntityId IN (SELECT Id FROM loan__Loan_Account__c)].size());
    }

    @IsTest
    static void testInsertNormalDocument()
    {
        // Arrange
        ContentVersion cv = new ContentVersion();
        cv.ContentLocation = 'S';
        cv.Title = 'Test ContentVersion';
        cv.PathOnClient = 'Test ContentVersion';
        cv.VersionData = Blob.valueOf('testData');

        // Act
        Test.startTest();
        insert cv;
        Test.stopTest();
        Id contentDocumentId = [SELECT ContentDocumentId FROM ContentVersion].ContentDocumentId;
        // Assert
        System.assertEquals(1, [SELECT Id FROM ContentDocumentLink WHERE ContentDocumentId = :contentDocumentId].size());
        System.assertEquals(0, [SELECT Id FROM Redraw_Request__c].size());
    }
}