force-app/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <customHelpPage>loan__CLContractHelp</customHelpPage>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Account__c/fields/Calculated_Upcoming_Repayment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Calculated_Upcoming_Repayment_Amount__c</fullName>
    <formula>IF( !ISBLANK(New_Interest_Rate__c) &amp;&amp; !ISBLANK( New_Interest_Rate_Effective_Date__c) &amp;&amp; ISPICKVAL(Repayment_Type__c , &apos;Principal and Interest&apos;),((New_Interest_Rate__c /12)*((1+( New_Interest_Rate__c /12))^ Remaining_Loan_Term__c ))/((1+(New_Interest_Rate__c/12))^ Remaining_Loan_Term__c -1)* loan__Loan_Balance__c,0.0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Calculated Upcoming Repayment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/First_Repayment_Date_After_IR_Change__c.field-meta.xml
<CustomField>
    <fullName>First_Repayment_Date_After_IR_Change__c</fullName>
    <label>First Repayment Date After IR Change</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Please choose a account, which will be associated as a customer on this lending account.
You can create a new account, from the lookup window by clicking on new or select the existing account from the lookup.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Loan_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

elixir/force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>loan__Interest_Rate__c</fullName>
    <description>Interest Rate</description>
    <inlineHelpText>Rate of Interest for the loan.</inlineHelpText>
    <label>Current Interest Rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Loan Amount</description>
    <inlineHelpText>This is the financed amount on the contract which will be disbursed to the customer.</inlineHelpText>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/New_Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>New_Interest_Rate__c</fullName>
    <label>New Interest Rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/New_Interest_Rate_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>New_Interest_Rate_Effective_Date__c</fullName>
    <label>New Interest Rate Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Remaining_Term_from_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Term_from_Schedule__c</fullName>
    <label>Remaining Term from Schedule</label>
    <summaryFilterItems>
        <field>loan__Repayment_Schedule__c.loan__Is_Billed__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>loan__Repayment_Schedule__c.loan__Is_Archived__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryForeignKey>loan__Repayment_Schedule__c.loan__Loan_Account__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Scheduled_Balance_As_at_IR_change_date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Balance_As_at_IR_change_date__c</fullName>
    <label>Scheduled Balance As at IR change date</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Second_Repayment_Date_After_IR_Change__c.field-meta.xml
<CustomField>
    <fullName>Second_Repayment_Date_After_IR_Change__c</fullName>
    <label>Second Repayment Date After IR Change</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/LoanAccountTriggerTest.cls
/**
 * Created by caleb on 1/07/2022.
 */

@IsTest
public with sharing class LoanAccountTriggerTest
{
    @IsTest(SeeAllData=true)
    public static void test1()
    {
        /*
        Account personAccount = new Account();
        personAccount.RecordTypeId = Schema.SObjectType.Account
                .getRecordTypeInfosByDeveloperName()
                .get('PersonAccount')
                .getRecordTypeId();
        personAccount.FirstName = 'Test';
        personAccount.LastName = 'Test';
        personAccount.PersonEmail = 't@t.com';
        insert personAccount;

        loan__Loan_Account__c t = new loan__Loan_Account__c();
        t.loan__Loan_Amount__c = 1.0;
        t.New_Interest_Rate__c = 0.0;
        t.First_Repayment_Date_After_IR_Change__c = Date.today();
        t.Second_Repayment_Date_After_IR_Change__c = Date.today();
        t.loan__Account__c = personAccount.Id;
        insert t;

        //Test.startTest();
        loan__Loan_Account__c t2 = new loan__Loan_Account__c();
        t2.New_Interest_Rate_Effective_Date__c = Date.today();
        t2.Id = t.Id;
        update t2;
        //Test.stopTest();
        */
        List<loan__Loan_Account__c> loanAccounts = [
                SELECT Id, Calculated_Upcoming_Repayment_Amount__c, Remaining_Term_from_Schedule__c
                FROM loan__Loan_Account__c
                WHERE Calculated_Upcoming_Repayment_Amount__c != NULL
                AND Remaining_Term_from_Schedule__c != 0
                ORDER BY Id
                LIMIT 10
        ];
        for (loan__Loan_Account__c loanAccount : loanAccounts)
        {
            loanAccount.New_Interest_Rate__c = 6;
            loanAccount.First_Repayment_Date_After_IR_Change__c = Date.today();
            loanAccount.Second_Repayment_Date_After_IR_Change__c = Date.today().addDays(10);
            loanAccount.New_Interest_Rate_Effective_Date__c = Date.today().addDays(20);
            loanAccount.Scheduled_Balance_As_at_IR_change_date__c = 4;
            loanAccount.loan__Interest_Rate__c = 5;
        }
        Test.startTest();
        update loanAccounts;
        Test.stopTest();
    }

    @IsTest(SeeAllData=true)
    public static void test2()
    {
        List<loan__Loan_Account__c> loanAccounts1 = [
                SELECT Id, Calculated_Upcoming_Repayment_Amount__c, Remaining_Term_from_Schedule__c
                FROM loan__Loan_Account__c
                WHERE Calculated_Upcoming_Repayment_Amount__c != NULL
                AND Remaining_Term_from_Schedule__c != 0
                ORDER BY Id
                LIMIT 10
        ];
        for (loan__Loan_Account__c loanAccount : loanAccounts1)
        {
            loanAccount.New_Interest_Rate__c = 6;
            loanAccount.First_Repayment_Date_After_IR_Change__c = Date.today();
            loanAccount.Second_Repayment_Date_After_IR_Change__c = Date.today().addDays(10);
            loanAccount.New_Interest_Rate_Effective_Date__c = Date.today().addDays(20);
            loanAccount.Scheduled_Balance_As_at_IR_change_date__c = 4;
            loanAccount.loan__Interest_Rate__c = 5;
        }
        List<loan__Loan_Account__c> loanAccounts2 = [
                SELECT Id, Calculated_Upcoming_Repayment_Amount__c, Remaining_Term_from_Schedule__c
                FROM loan__Loan_Account__c
                WHERE Calculated_Upcoming_Repayment_Amount__c != NULL
                AND Remaining_Term_from_Schedule__c != 0
                ORDER BY Id
                LIMIT 10
        ];
        for (loan__Loan_Account__c loanAccount : loanAccounts2)
        {
            loanAccount.New_Interest_Rate__c = 6;
            loanAccount.First_Repayment_Date_After_IR_Change__c = Date.today();
            loanAccount.Second_Repayment_Date_After_IR_Change__c = Date.today().addDays(10);
            loanAccount.New_Interest_Rate_Effective_Date__c = Date.today().addDays(20);
            loanAccount.Scheduled_Balance_As_at_IR_change_date__c = 4;
            loanAccount.loan__Interest_Rate__c = 5;
        }
        Test.startTest();
        update loanAccounts1;
        update loanAccounts2;
        Test.stopTest();
    }
}