force-app/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <customHelpPage>loan__CLContractHelp</customHelpPage>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Please choose a account, which will be associated as a customer on this lending account.
You can create a new account, from the lookup window by clicking on new or select the existing account from the lookup.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Loan_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TaskRelatedLoanController.cls
/****************************************************************************************************
Company: Cloudkaptan Consultancy Services Pvt. Ltd.
Author: Ariz Mazhary
Description : This is the controller class of ActivityListPage.This class shows detail of Task 
      related to Loan and delete the Task when Del button is clicked.
Development Date : 04/01/2022
Last Modified Date : 05/01/2022
****************************************************************************************************/
global class TaskRelatedLoanController {
    public List<loan__Loan_Account__c> acctList {get;set;}
    public String taskId {get; set;}
    
    public TaskRelatedLoanController(ApexPages.StandardController stdController){
        acctList = [SELECT id,
                      Name,loan__Account__c 
                  FROM loan__Loan_Account__c 
                  WHERE id = :ApexPages.currentPage().getParameters().get(ConstantValues.LOAN_ID)];
    }
    //This method returns the Task Details related to CL Contract.
    public List<Task> gettaskList(){
        List<Task> taskList=new List<Task>();
        if(acctList.size()>0){
            taskList =[SELECT id,
                            Subject,
                            whoId,
                            ActivityDate,
                            CreatedDate,
                            OwnerId,
                            LastModifiedById,
                            LastModifiedDate,
                            Description__c
                        FROM Task 
                        WHERE whatId=:acctList[0].id
                        ORDER BY LastModifiedDate DESC];
        }
        return taskList;
    }
    //This method delete the selected Task
    public PageReference deleteTask(){
        try{
            List<Task> deleteTaskList=new List<Task>();
            if(taskId!=null){
                deleteTaskList = [SELECT id,
                                        Subject,
                                        whoId,
                                        ActivityDate,
                                        CreatedDate,
                                        OwnerId,
                                        LastModifiedById,
                                        LastModifiedDate
                                    FROM Task 
                                    WHERE id =: taskId LIMIT 1];
            }
            
            if(deleteTaskList.size()>0){
                database.delete(deleteTaskList,false);
            }
            
            PageReference tempPage =  ApexPages.currentPage();          
            tempPage.setRedirect(true);
            return tempPage;

        }catch(Exception exe){
            GenericUtility.insertLog('TaskRelatedLoanController',exe);
            return null;
        }
        
    }
}